In [1]:
import pandas as pd
from scipy.optimize import curve_fit
import seaborn
seaborn.set(style='whitegrid')
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import LogFormatter
%matplotlib qt
# %matplotlib inline
from datetime import datetime, date

C:\Users\etiirine\Anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

## Reading in the data

In [2]:
#read in the data
mid=pd.read_csv("MID s3.tsv", sep="\t", skiprows=lambda x: x <=11,  on_bad_lines="skip")
mid.drop([0,1], inplace=True)
print(mid.describe())
#bring the time data into a new df
time = pd.DataFrame(mid.iloc[:,0::2]) #- get every second column
print(time.describe())
#add elapsed time columns
def elapsed_time(df):
    itr = 0
    counter = len(df.columns)
    masses = [2,4,12,16,18,28,32,40,44]
    for i in df:
        timestamp = pd.to_datetime(df[i], format="%Y/%m/%d %H:%M:%S.%f")
        runtime = (timestamp-timestamp[2]).dt.total_seconds()
        colname = "Elapsed time, mass {}".format(masses[itr]) 
        df.insert(counter, colname, runtime)
        itr += 1
        counter += 1
    return(df)
elapsed_time(time)

       mass 2.0_value  mass 4.0_value  mass 12.0_value  mass 16.0_value  \
count    9.790000e+02    9.790000e+02     9.790000e+02     9.790000e+02
mean     2.675530e-11    1.276886e-12     3.470486e-13     6.665709e-13
std      3.880245e-12    1.860989e-13     7.254319e-14     1.449576e-13
min      2.177250e-11    1.012800e-12     1.975000e-13     4.612000e-13
25%      2.232480e-11    1.068150e-12     2.755000e-13     5.212500e-13
50%      2.745650e-11    1.312400e-12     3.412000e-13     6.370000e-13
75%      3.026930e-11    1.446550e-12     4.184000e-13     8.089000e-13
max      3.635750e-11    1.742600e-12     4.847000e-13     9.584000e-13

       mass 18.0_value  mass 28.0_value  mass 32.0_value  mass 40.0_value  \
count     9.790000e+02     9.790000e+02     9.790000e+02     1.870000e+02
mean      1.212745e-12     2.082592e-12     8.767559e-13     1.294006e-12
std       6.755157e-14     3.583144e-13     5.259320e-13     3.965710e-13
min       1.067200e-12     1.519100e-12     0.000000e+00     1.500000e-15
25%       1.148100e-12     1.644950e-12     7.138500e-13     1.033850e-12
50%       1.225700e-12     2.149900e-12     8.120000e-13     1.445200e-12
75%       1.269300e-12     2.426900e-12     1.428200e-12     1.596900e-12
max       1.354100e-12     2.732500e-12     1.747100e-12     1.731900e-12

       mass 44.0_value
count     6.000000e+00
mean      1.193850e-12
std       4.921414e-13
min       7.384000e-13
25%       7.472000e-13
50%       1.184300e-12
75%       1.624700e-12
max       1.683100e-12
                  mass 2.0_time            mass 4.0_time  \
count                       979                      979
unique                      979                      979
top     2022/11/14 14:44:18.235  2022/11/14 14:44:18.485
freq                          1                        1

                 mass 12.0_time           mass 16.0_time  \
count                       979                      979
unique                      979                      979
top     2022/11/14 14:44:18.735  2022/11/14 14:44:18.985
freq                          1                        1

                 mass 18.0_time           mass 28.0_time  \
count                       979                      979
unique                      979                      979
top     2022/11/14 14:44:19.235  2022/11/14 14:44:19.485
freq                          1                        1

                 mass 32.0_time           mass 40.0_time  \
count                       979                      187
unique                      979                      187
top     2022/11/14 14:44:19.736  2022/11/14 14:44:19.986
freq                          1                        1

                 mass 44.0_time
count                         6
unique                        6
top     2022/11/14 14:44:20.236
freq                          1

,mass 2.0_time,mass 4.0_time,mass 12.0_time,mass 16.0_time,mass 18.0_time,mass 28.0_time,mass 32.0_time,mass 40.0_time,mass 44.0_time,"Elapsed time, mass 2","Elapsed time, mass 4","Elapsed time, mass 12","Elapsed time, mass 16","Elapsed time, mass 18","Elapsed time, mass 28","Elapsed time, mass 32","Elapsed time, mass 40","Elapsed time, mass 44"
2,2022/11/14 14:44:18.235,2022/11/14 14:44:18.485,2022/11/14 14:44:18.735,2022/11/14 14:44:18.985,2022/11/14 14:44:19.235,2022/11/14 14:44:19.485,2022/11/14 14:44:19.736,2022/11/14 14:44:19.986,2022/11/14 14:44:20.236,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
3,2022/11/14 14:44:20.558,2022/11/14 14:44:20.808,2022/11/14 14:44:21.058,2022/11/14 14:44:21.308,2022/11/14 14:44:21.558,2022/11/14 14:44:21.808,2022/11/14 14:44:22.059,2022/11/14 14:44:22.309,2022/11/14 14:44:22.560,2.323,2.323,2.323,2.323,2.323,2.323,2.323,2.323,2.324
4,2022/11/14 14:44:22.881,2022/11/14 14:44:23.131,2022/11/14 14:44:23.382,2022/11/14 14:44:23.632,2022/11/14 14:44:23.882,2022/11/14 14:44:24.132,2022/11/14 14:44:24.382,2022/11/14 14:44:24.632,2022/11/14 14:44:24.883,4.646,4.646,4.647,4.647,4.647,4.647,4.646,4.646,4.647
5,2022/11/14 14:44:25.204,2022/11/14 14:44:25.454,2022/11/14 14:44:25.705,2022/11/14 14:44:25.955,2022/11/14 14:44:26.205,2022/11/14 14:44:26.455,2022/11/14 14:44:26.705,2022/11/14 14:44:27.206,NaN,6.969,6.969,6.970,6.970,6.970,6.970,6.969,7.220,NaN
6,2022/11/14 14:44:27.527,2022/11/14 14:44:27.777,2022/11/14 14:44:28.027,2022/11/14 14:44:28.277,2022/11/14 14:44:28.527,2022/11/14 14:44:28.778,2022/11/14 14:44:29.028,2022/11/14 14:44:29.528,NaN,9.292,9.292,9.292,9.292,9.292,9.293,9.292,9.542,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
976,2022/11/14 15:22:00.352,2022/11/14 15:22:00.602,2022/11/14 15:22:00.852,2022/11/14 15:22:01.102,2022/11/14 15:22:01.352,2022/11/14 15:22:01.603,2022/11/14 15:22:02.353,NaN,NaN,2262.117,2262.117,2262.117,2262.117,2262.117,2262.118,2262.617,NaN,NaN
977,2022/11/14 15:22:02.674,2022/11/14 15:22:02.924,2022/11/14 15:22:03.175,2022/11/14 15:22:03.425,2022/11/14 15:22:03.675,2022/11/14 15:22:03.925,2022/11/14 15:22:04.676,NaN,NaN,2264.439,2264.439,2264.440,2264.440,2264.440,2264.440,2264.940,NaN,NaN
978,2022/11/14 15:22:04.997,2022/11/14 15:22:05.247,2022/11/14 15:22:05.497,2022/11/14 15:22:05.747,2022/11/14 15:22:05.997,2022/11/14 15:22:06.248,2022/11/14 15:22:06.998,NaN,NaN,2266.762,2266.762,2266.762,2266.762,2266.762,2266.763,2267.262,NaN,NaN
979,2022/11/14 15:22:07.319,2022/11/14 15:22:07.569,2022/11/14 15:22:07.820,2022/11/14 15:22:08.070,2022/11/14 15:22:08.320,2022/11/14 15:22:08.570,2022/11/14 15:22:09.321,NaN,NaN,2269.084,2269.084,2269.085,2269.085,2269.085,2269.085,2269.585,NaN,NaN
980,2022/11/14 15:22:09.642,2022/11/14 15:22:09.892,2022/11/14 15:22:10.142,2022/11/14 15:22:10.392,2022/11/14 15:22:10.642,2022/11/14 15:22:10.893,2022/11/14 15:22:11.643,NaN,NaN,2271.407,2271.407,2271.407,2271.407,2271.407,2271.408,2271.907,NaN,NaN

### Position of the EGA

<div>
<img src="20221114_144204.jpg" width="1000"/>
</div>

In [3]:
#reading the Emission current, pressures
vaclog=pd.read_csv("vaclog", sep="\t")
vaclog.head()
#adding an elapsed time column
timestamp=[]
for i in vaclog["Time"]:
    timestamp.append(i)
#making the column into a datetime object
timestamps=pd.to_datetime(vaclog["Time"],format="%d/%m/%Y %H:%M:%S")
runtime=(timestamps-timestamps[0]).dt.total_seconds()    
vaclog.insert(2,"Elapsed time",runtime)
vaclog.drop(index=vaclog.index[0], 
        axis=0, 
        inplace=True)

vaclog.head()

,Live comments,Time,Elapsed time,injection 100mbar,Barion_2,Barion_1,DUAL experiment,DUAL insulation,injection 1mbar,helium,T-platinum,T-CERNOX,I_emission,I_grid
1,NaN,14/11/2022 14:44:08,10.0,-0.063232,1.890000e-09,7.300000e-10,4.996000e-09,1.147000e-06,0.000288,0.0,-100.336,61.504,0.0,NaN
2,NaN,14/11/2022 14:44:17,19.0,-0.063896,1.890000e-09,7.310000e-10,4.996000e-09,9.904000e-07,0.000273,0.0,-100.336,61.504,0.0,NaN
3,NaN,14/11/2022 14:44:26,28.0,-0.063279,1.890000e-09,7.290000e-10,4.996000e-09,8.986000e-07,0.000268,0.0,-100.224,61.504,0.0,NaN
4,NaN,14/11/2022 14:44:35,37.0,-0.066534,1.880000e-09,7.300000e-10,4.996000e-09,8.392000e-07,0.000283,0.0,-100.112,61.504,0.0,NaN
5,NaN,14/11/2022 14:44:45,47.0,-0.062615,1.880000e-09,7.290000e-10,4.996000e-09,8.104000e-07,0.000272,0.0,-100.112,61.504,0.0,NaN

In [4]:
#Reading in the HiVolta measurement file to get the grid current
hv = pd.read_csv("hv log", sep=",")
#hv.drop(columns=["Vmon1","Vmon2","Vmon3","Vmon4","Vmon5","Vmon6","Vmon7","Vmon8","Imon3","Imon4","Imon5","Imon6","Imon7","Imon8","Comments1"], inplace=True)
hv["hv_grid"]=[element * 1e-6 for element in hv["IMon1"]]
hv["em"]=[element * 1e-6 for element in hv["IMon2"]]
hv.drop(hv.columns[hv.columns.str.contains('Unnamed',case = False)],axis = 1, inplace = True)
hv["em"]=abs(hv["em"])
hv["hv_grid"]=abs(hv["hv_grid"])

#adding an elapsed time column
timestamp=[]
for i in hv["Time"]:
    timestamp.append(i)
    
#making the column into a datetime object
timestamps=pd.to_datetime(hv["Time"],format="%H:%M:%S.%f")
runtime=(timestamps-timestamps[0]).dt.total_seconds()    
hv.insert(2,"Elapsed time",runtime)
hv.drop(index=hv.index[0], 
        axis=0, 
        inplace=True)

hv.describe()

,Elapsed time,VMon1,VMon2,VMon3,VMon4,VMon5,VMon6,VMon7,VMon8,IMon1,IMon2,IMon3,IMon4,IMon5,IMon6,IMon7,IMon8,hv_grid,em
count,1738.000000,1738.000000,1738.000000,1738.000000,1738.000000,1738.000000,1738.0,1738.0,1.738000e+03,1738.000000,1738.000000,1738.000000,1738.000000,1738.000000,1738.000000,1738.000000,1738.000000,1.738000e+03,1.738000e+03
mean,1043.601011,102.984810,66.934591,667.739919,667.869471,656.653234,0.0,0.0,4.000000e-02,-0.024110,-1.682124,23.459534,21.670733,4.426051,-0.007074,-0.013819,-0.010010,3.279171e-08,1.687864e-06
std,603.019306,201.433548,47.048233,469.540127,469.513649,473.319960,0.0,0.0,1.943449e-16,0.049727,0.264412,16.639058,16.650765,14.048962,0.002548,0.001087,0.001176,4.447997e-08,2.248506e-07
min,1.767000,0.020000,0.060000,0.000000,0.000000,0.000000,0.0,0.0,4.000000e-02,-0.487000,-4.952700,-0.548400,-2.229400,-21.556000,-0.011700,-0.015800,-0.012200,0.000000e+00,1.143000e-07
25%,522.622250,0.080000,0.080000,0.180000,0.160000,0.000000,0.0,0.0,4.000000e-02,-0.047500,-1.769600,-0.076200,-1.878300,-9.570900,-0.008900,-0.014400,-0.010900,4.100000e-09,1.582000e-06
50%,1043.401000,0.120000,100.060000,1000.000000,1000.120000,1000.100000,0.0,0.0,4.000000e-02,-0.004200,-1.759100,35.166200,33.386100,13.886250,-0.007600,-0.013500,-0.010100,1.450000e-08,1.759100e-06
75%,1565.583500,0.140000,100.080000,1000.040000,1000.140000,1000.140000,0.0,0.0,4.000000e-02,0.000700,-1.582000,35.860225,34.081800,14.581100,-0.004500,-0.013000,-0.009200,4.787500e-08,1.769600e-06
max,2085.022000,499.980000,100.160000,1000.100000,1000.260000,1000.320000,0.0,0.0,4.000000e-02,0.517400,0.919900,35.990000,34.210800,14.707900,-0.002700,-0.012000,-0.007600,5.174000e-07,4.952700e-06

### Data processing

In [5]:
#Filtering background signal

#Find the timestamp where emission was turned on
#print("Result 1:",hv.loc[hv["Comment"]=="emission start"])
x=pd.Timestamp(2022, 11, 10, 17,12, 45)

#then find the time value closest to it in the MID scan file
print("\n","Result 2:",mid.iloc[(pd.to_datetime(mid['mass 2.0_time'],format="%Y/%m/%d %H:%M:%S") - x).abs().argsort(),:])

#average the signal before this timestamp and subtract it from the Em-on part
bck=np.mean(mid["mass 40.0_value"])
print("\n","Result 3:",bck)

#apply background correction to the rest of the mass spectrum
mid["mass 2, corr"]=mid["mass 2.0_value"]-bck
print("Res 1:",mid["mass 2, corr"].describe())


#From the signal, get the partial pressures 
h2_sens=2.13e-2
p_h2=mid["mass 2, corr"][102:195]/h2_sens
print(p_h2.describe())

#baseline for partial pressure delta
base_h2=mid["mass 2, corr"][0:102]/h2_sens
base_h2.describe()

 Result 2:                mass 2.0_time  mass 2.0_value            mass 4.0_time  \
2    2022/11/14 14:44:18.235    2.380210e-11  2022/11/14 14:44:18.485
3    2022/11/14 14:44:20.558    2.318340e-11  2022/11/14 14:44:20.808
4    2022/11/14 14:44:22.881    2.317210e-11  2022/11/14 14:44:23.131
5    2022/11/14 14:44:25.204    2.313340e-11  2022/11/14 14:44:25.454
6    2022/11/14 14:44:27.527    2.290820e-11  2022/11/14 14:44:27.777
..                       ...             ...                      ...
976  2022/11/14 15:22:00.352    2.199390e-11  2022/11/14 15:22:00.602
977  2022/11/14 15:22:02.674    2.192350e-11  2022/11/14 15:22:02.924
978  2022/11/14 15:22:04.997    2.215030e-11  2022/11/14 15:22:05.247
979  2022/11/14 15:22:07.319    2.202670e-11  2022/11/14 15:22:07.569
980  2022/11/14 15:22:09.642    2.189830e-11  2022/11/14 15:22:09.892

     mass 4.0_value           mass 12.0_time  mass 12.0_value  \
2      1.131400e-12  2022/11/14 14:44:18.735     2.875000e-13
3      1.078700e-12  2022/11/14 14:44:21.058     2.891000e-13
4      1.101400e-12  2022/11/14 14:44:23.382     2.742000e-13
5      1.120500e-12  2022/11/14 14:44:25.705     2.830000e-13
6      1.078400e-12  2022/11/14 14:44:28.027     2.718000e-13
..              ...                      ...              ...
976    1.048000e-12  2022/11/14 15:22:00.852     2.433000e-13
977    1.030400e-12  2022/11/14 15:22:03.175     2.522000e-13
978    1.040900e-12  2022/11/14 15:22:05.497     2.788000e-13
979    1.049300e-12  2022/11/14 15:22:07.820     2.668000e-13
980    1.046200e-12  2022/11/14 15:22:10.142     2.662000e-13

              mass 16.0_time  mass 16.0_value           mass 18.0_time  \
2    2022/11/14 14:44:18.985     5.342000e-13  2022/11/14 14:44:19.235
3    2022/11/14 14:44:21.308     5.614000e-13  2022/11/14 14:44:21.558
4    2022/11/14 14:44:23.632     5.520000e-13  2022/11/14 14:44:23.882
5    2022/11/14 14:44:25.955     4.968000e-13  2022/11/14 14:44:26.205
6    2022/11/14 14:44:28.277     4.762000e-13  2022/11/14 14:44:28.527
..                       ...              ...                      ...
976  2022/11/14 15:22:01.102     5.150000e-13  2022/11/14 15:22:01.352
977  2022/11/14 15:22:03.425     5.034000e-13  2022/11/14 15:22:03.675
978  2022/11/14 15:22:05.747     5.266000e-13  2022/11/14 15:22:05.997
979  2022/11/14 15:22:08.070     5.537000e-13  2022/11/14 15:22:08.320
980  2022/11/14 15:22:10.392     5.117000e-13  2022/11/14 15:22:10.642

     mass 18.0_value           mass 28.0_time  mass 28.0_value  \
2       1.207200e-12  2022/11/14 14:44:19.485     1.709700e-12
3       1.185900e-12  2022/11/14 14:44:21.808     1.662100e-12
4       1.181400e-12  2022/11/14 14:44:24.132     1.649700e-12
5       1.180000e-12  2022/11/14 14:44:26.455     1.614900e-12
6       1.155000e-12  2022/11/14 14:44:28.778     1.575100e-12
..               ...                      ...              ...
976     1.159300e-12  2022/11/14 15:22:01.603     1.781600e-12
977     1.134000e-12  2022/11/14 15:22:03.925     1.784600e-12
978     1.136800e-12  2022/11/14 15:22:06.248     1.789800e-12
979     1.104600e-12  2022/11/14 15:22:08.570     1.736800e-12
980     1.129100e-12  2022/11/14 15:22:10.893     1.774400e-12

              mass 32.0_time  mass 32.0_value           mass 40.0_time  \
2    2022/11/14 14:44:19.736     1.085000e-13  2022/11/14 14:44:19.986
3    2022/11/14 14:44:22.059     1.019000e-13  2022/11/14 14:44:22.309
4    2022/11/14 14:44:24.382     1.059000e-13  2022/11/14 14:44:24.632
5    2022/11/14 14:44:26.705     7.230000e-14  2022/11/14 14:44:27.206
6    2022/11/14 14:44:29.028     6.400000e-15  2022/11/14 14:44:29.528
..                       ...              ...                      ...
976  2022/11/14 15:22:02.353     7.886000e-13                      NaN
977  2022/11/14 15:22:04.676     7.677000e-13                      NaN
978  2022/11/14 15:22:06.998     7.547000e-13                      NaN
979  2022/11/14 15:22:09.321     7.912000e-13                      NaN
980  2022/11/14 15:22:11.643     7.719000e-13                      NaN

     mass 40.0_value           mass 44.0_time  mass 44.0_value
2       2.040000e-14  2022/11/14 14:44:20.236     7.508000e-13
3       9.900000e-15  2022/11/14 14:44:22.560     7.460000e-13
4       9.300000e-15  2022/11/14 14:44:24.883     7.384000e-13
5       7.484000e-13                      NaN              NaN
6       7.441000e-13                      NaN              NaN
..               ...                      ...              ...
976              NaN                      NaN              NaN
977              NaN                      NaN              NaN
978              NaN                      NaN              NaN
979              NaN                      NaN              NaN
980              NaN                      NaN              NaN

[979 rows x 18 columns]

 Result 3: 1.2940064171122987e-12
Res 1: count    9.790000e+02
mean     2.546130e-11
std      3.880245e-12
min      2.047849e-11
25%      2.103079e-11
50%      2.616249e-11
75%      2.897529e-11
max      3.506349e-11
Name: mass 2, corr, dtype: float64
count    9.300000e+01
mean     9.794325e-10
std      2.588720e-11
min      9.639293e-10
25%      9.741499e-10
50%      9.771030e-10
75%      9.802814e-10
max      1.222281e-09
Name: mass 2, corr, dtype: float64

count    1.020000e+02
mean     9.939874e-10
std      1.430046e-11
min      9.696335e-10
25%      9.854211e-10
50%      9.909175e-10
75%      1.001675e-09
max      1.056718e-09
Name: mass 2, corr, dtype: float64

In [6]:
#CO

#Find the timestamp where emission was turned on
#print("Result 1:",hv.loc[hv["Comment"]=="emission start"])
x=pd.Timestamp(2022, 11, 10, 17,12, 45)

#then find the time value closest to it in the MID scan file
print("\n","Result 2:",mid.iloc[(pd.to_datetime(mid['mass 28.0_time'],format="%Y/%m/%d %H:%M:%S") - x).abs().argsort(),:])

#average this signal and subtract it from the Em-on part
bck=np.mean(mid["mass 28.0_value"][0:102])
print("\n","Result 3:",bck)

#apply background correction to the rest of the mass spectrum
mid["mass 28, corr"]=mid["mass 28.0_value"][102:]-bck
mid["mass 28, corr"].describe()

#getting the differential spectrum
#first get the timestamp where grid voltage was changed to -500V
print("Location:",hv.loc[hv["Comment"]=="grid repelling"])
y=pd.Timestamp(2022, 11, 10, 17,22, 56)

#then find the time value closest to it in the MID scan file
print("\n","Result 4:",mid.iloc[(pd.to_datetime(mid['mass 28.0_time'],format="%Y/%m/%d %H:%M:%S") - y).abs().argsort(),:])

#subtract grid repelling from grid transparent
#getting the mean signal when grid is repelling
grid2=np.mean(mid["mass 28, corr"][195:])
mid["sample sig, mass 28"]=mid["mass 28, corr"][102:195]-grid2
mid["sample sig, mass 28"].describe()

 Result 2:                mass 2.0_time  mass 2.0_value            mass 4.0_time  \
2    2022/11/14 14:44:18.235    2.380210e-11  2022/11/14 14:44:18.485
3    2022/11/14 14:44:20.558    2.318340e-11  2022/11/14 14:44:20.808
4    2022/11/14 14:44:22.881    2.317210e-11  2022/11/14 14:44:23.131
5    2022/11/14 14:44:25.204    2.313340e-11  2022/11/14 14:44:25.454
6    2022/11/14 14:44:27.527    2.290820e-11  2022/11/14 14:44:27.777
..                       ...             ...                      ...
976  2022/11/14 15:22:00.352    2.199390e-11  2022/11/14 15:22:00.602
977  2022/11/14 15:22:02.674    2.192350e-11  2022/11/14 15:22:02.924
978  2022/11/14 15:22:04.997    2.215030e-11  2022/11/14 15:22:05.247
979  2022/11/14 15:22:07.319    2.202670e-11  2022/11/14 15:22:07.569
980  2022/11/14 15:22:09.642    2.189830e-11  2022/11/14 15:22:09.892

     mass 4.0_value           mass 12.0_time  mass 12.0_value  \
2      1.131400e-12  2022/11/14 14:44:18.735     2.875000e-13
3      1.078700e-12  2022/11/14 14:44:21.058     2.891000e-13
4      1.101400e-12  2022/11/14 14:44:23.382     2.742000e-13
5      1.120500e-12  2022/11/14 14:44:25.705     2.830000e-13
6      1.078400e-12  2022/11/14 14:44:28.027     2.718000e-13
..              ...                      ...              ...
976    1.048000e-12  2022/11/14 15:22:00.852     2.433000e-13
977    1.030400e-12  2022/11/14 15:22:03.175     2.522000e-13
978    1.040900e-12  2022/11/14 15:22:05.497     2.788000e-13
979    1.049300e-12  2022/11/14 15:22:07.820     2.668000e-13
980    1.046200e-12  2022/11/14 15:22:10.142     2.662000e-13

              mass 16.0_time  mass 16.0_value           mass 18.0_time  \
2    2022/11/14 14:44:18.985     5.342000e-13  2022/11/14 14:44:19.235
3    2022/11/14 14:44:21.308     5.614000e-13  2022/11/14 14:44:21.558
4    2022/11/14 14:44:23.632     5.520000e-13  2022/11/14 14:44:23.882
5    2022/11/14 14:44:25.955     4.968000e-13  2022/11/14 14:44:26.205
6    2022/11/14 14:44:28.277     4.762000e-13  2022/11/14 14:44:28.527
..                       ...              ...                      ...
976  2022/11/14 15:22:01.102     5.150000e-13  2022/11/14 15:22:01.352
977  2022/11/14 15:22:03.425     5.034000e-13  2022/11/14 15:22:03.675
978  2022/11/14 15:22:05.747     5.266000e-13  2022/11/14 15:22:05.997
979  2022/11/14 15:22:08.070     5.537000e-13  2022/11/14 15:22:08.320
980  2022/11/14 15:22:10.392     5.117000e-13  2022/11/14 15:22:10.642

     mass 18.0_value           mass 28.0_time  mass 28.0_value  \
2       1.207200e-12  2022/11/14 14:44:19.485     1.709700e-12
3       1.185900e-12  2022/11/14 14:44:21.808     1.662100e-12
4       1.181400e-12  2022/11/14 14:44:24.132     1.649700e-12
5       1.180000e-12  2022/11/14 14:44:26.455     1.614900e-12
6       1.155000e-12  2022/11/14 14:44:28.778     1.575100e-12
..               ...                      ...              ...
976     1.159300e-12  2022/11/14 15:22:01.603     1.781600e-12
977     1.134000e-12  2022/11/14 15:22:03.925     1.784600e-12
978     1.136800e-12  2022/11/14 15:22:06.248     1.789800e-12
979     1.104600e-12  2022/11/14 15:22:08.570     1.736800e-12
980     1.129100e-12  2022/11/14 15:22:10.893     1.774400e-12

              mass 32.0_time  mass 32.0_value           mass 40.0_time  \
2    2022/11/14 14:44:19.736     1.085000e-13  2022/11/14 14:44:19.986
3    2022/11/14 14:44:22.059     1.019000e-13  2022/11/14 14:44:22.309
4    2022/11/14 14:44:24.382     1.059000e-13  2022/11/14 14:44:24.632
5    2022/11/14 14:44:26.705     7.230000e-14  2022/11/14 14:44:27.206
6    2022/11/14 14:44:29.028     6.400000e-15  2022/11/14 14:44:29.528
..                       ...              ...                      ...
976  2022/11/14 15:22:02.353     7.886000e-13                      NaN
977  2022/11/14 15:22:04.676     7.677000e-13                      NaN
978  2022/11/14 15:22:06.998     7.547000e-13                      NaN
979  2022/11/14 15:22:09.321     7.912000e-13                      NaN
980  2022/11/14 15:22:11.643     7.719000e-13                      NaN

     mass 40.0_value           mass 44.0_time  mass 44.0_value  mass 2, corr
2       2.040000e-14  2022/11/14 14:44:20.236     7.508000e-13  2.250809e-11
3       9.900000e-15  2022/11/14 14:44:22.560     7.460000e-13  2.188939e-11
4       9.300000e-15  2022/11/14 14:44:24.883     7.384000e-13  2.187809e-11
5       7.484000e-13                      NaN              NaN  2.183939e-11
6       7.441000e-13                      NaN              NaN  2.161419e-11
..               ...                      ...              ...           ...
976              NaN                      NaN              NaN  2.069989e-11
977              NaN                      NaN              NaN  2.062949e-11
978              NaN                      NaN              NaN  2.085629e-11
979              NaN                      NaN              NaN  2.073269e-11
980              NaN                      NaN              NaN  2.060429e-11

[979 rows x 19 columns]

 Result 3: 1.608368627450981e-12
Location:             Date          Time  Elapsed time   VMon1   VMon2    VMon3  \
1121  14/11/2022  15:09:52.223      1335.611    0.12  100.06  1000.02
1122  14/11/2022  15:09:54.331      1337.719   50.44  100.08  1000.02
1123  14/11/2022  15:09:55.524      1338.912  180.70  100.08  1000.02

        VMon4    VMon5  VMon6  VMon7  ...   IMon2    IMon3    IMon4    IMon5  \
1121  1000.16  1000.16    0.0    0.0  ... -1.6135  35.8955  34.1155  14.6128
1122  1000.16  1000.16    0.0    0.0  ... -1.6144  35.8971  34.1175  14.6144
1123  1000.16  1000.16    0.0    0.0  ... -1.6851  35.9059  34.1246  14.6196

       IMon6   IMon7   IMon8         Comment       hv_grid        em
1121 -0.0044 -0.0128 -0.0114  grid repelling  3.720000e-08  0.000002
1122 -0.0044 -0.0128 -0.0114  grid repelling  4.030000e-07  0.000002
1123 -0.0044 -0.0128 -0.0114  grid repelling  4.845000e-07  0.000002

[3 rows x 22 columns]

 Result 4:                mass 2.0_time  mass 2.0_value            mass 4.0_time  \
2    2022/11/14 14:44:18.235    2.380210e-11  2022/11/14 14:44:18.485
3    2022/11/14 14:44:20.558    2.318340e-11  2022/11/14 14:44:20.808
4    2022/11/14 14:44:22.881    2.317210e-11  2022/11/14 14:44:23.131
5    2022/11/14 14:44:25.204    2.313340e-11  2022/11/14 14:44:25.454
6    2022/11/14 14:44:27.527    2.290820e-11  2022/11/14 14:44:27.777
..                       ...             ...                      ...
976  2022/11/14 15:22:00.352    2.199390e-11  2022/11/14 15:22:00.602
977  2022/11/14 15:22:02.674    2.192350e-11  2022/11/14 15:22:02.924
978  2022/11/14 15:22:04.997    2.215030e-11  2022/11/14 15:22:05.247
979  2022/11/14 15:22:07.319    2.202670e-11  2022/11/14 15:22:07.569
980  2022/11/14 15:22:09.642    2.189830e-11  2022/11/14 15:22:09.892

     mass 4.0_value           mass 12.0_time  mass 12.0_value  \
2      1.131400e-12  2022/11/14 14:44:18.735     2.875000e-13
3      1.078700e-12  2022/11/14 14:44:21.058     2.891000e-13
4      1.101400e-12  2022/11/14 14:44:23.382     2.742000e-13
5      1.120500e-12  2022/11/14 14:44:25.705     2.830000e-13
6      1.078400e-12  2022/11/14 14:44:28.027     2.718000e-13
..              ...                      ...              ...
976    1.048000e-12  2022/11/14 15:22:00.852     2.433000e-13
977    1.030400e-12  2022/11/14 15:22:03.175     2.522000e-13
978    1.040900e-12  2022/11/14 15:22:05.497     2.788000e-13
979    1.049300e-12  2022/11/14 15:22:07.820     2.668000e-13
980    1.046200e-12  2022/11/14 15:22:10.142     2.662000e-13

              mass 16.0_time  mass 16.0_value           mass 18.0_time  \
2    2022/11/14 14:44:18.985     5.342000e-13  2022/11/14 14:44:19.235
3    2022/11/14 14:44:21.308     5.614000e-13  2022/11/14 14:44:21.558
4    2022/11/14 14:44:23.632     5.520000e-13  2022/11/14 14:44:23.882
5    2022/11/14 14:44:25.955     4.968000e-13  2022/11/14 14:44:26.205
6    2022/11/14 14:44:28.277     4.762000e-13  2022/11/14 14:44:28.527
..                       ...              ...                      ...
976  2022/11/14 15:22:01.102     5.150000e-13  2022/11/14 15:22:01.352
977  2022/11/14 15:22:03.425     5.034000e-13  2022/11/14 15:22:03.675
978  2022/11/14 15:22:05.747     5.266000e-13  2022/11/14 15:22:05.997
979  2022/11/14 15:22:08.070     5.537000e-13  2022/11/14 15:22:08.320
980  2022/11/14 15:22:10.392     5.117000e-13  2022/11/14 15:22:10.642

     mass 18.0_value           mass 28.0_time  mass 28.0_value  \
2       1.207200e-12  2022/11/14 14:44:19.485     1.709700e-12
3       1.185900e-12  2022/11/14 14:44:21.808     1.662100e-12
4       1.181400e-12  2022/11/14 14:44:24.132     1.649700e-12
5       1.180000e-12  2022/11/14 14:44:26.455     1.614900e-12
6       1.155000e-12  2022/11/14 14:44:28.778     1.575100e-12
..               ...                      ...              ...
976     1.159300e-12  2022/11/14 15:22:01.603     1.781600e-12
977     1.134000e-12  2022/11/14 15:22:03.925     1.784600e-12
978     1.136800e-12  2022/11/14 15:22:06.248     1.789800e-12
979     1.104600e-12  2022/11/14 15:22:08.570     1.736800e-12
980     1.129100e-12  2022/11/14 15:22:10.893     1.774400e-12

              mass 32.0_time  mass 32.0_value           mass 40.0_time  \
2    2022/11/14 14:44:19.736     1.085000e-13  2022/11/14 14:44:19.986
3    2022/11/14 14:44:22.059     1.019000e-13  2022/11/14 14:44:22.309
4    2022/11/14 14:44:24.382     1.059000e-13  2022/11/14 14:44:24.632
5    2022/11/14 14:44:26.705     7.230000e-14  2022/11/14 14:44:27.206
6    2022/11/14 14:44:29.028     6.400000e-15  2022/11/14 14:44:29.528
..                       ...              ...                      ...
976  2022/11/14 15:22:02.353     7.886000e-13                      NaN
977  2022/11/14 15:22:04.676     7.677000e-13                      NaN
978  2022/11/14 15:22:06.998     7.547000e-13                      NaN
979  2022/11/14 15:22:09.321     7.912000e-13                      NaN
980  2022/11/14 15:22:11.643     7.719000e-13                      NaN

     mass 40.0_value           mass 44.0_time  mass 44.0_value  mass 2, corr  \
2       2.040000e-14  2022/11/14 14:44:20.236     7.508000e-13  2.250809e-11
3       9.900000e-15  2022/11/14 14:44:22.560     7.460000e-13  2.188939e-11
4       9.300000e-15  2022/11/14 14:44:24.883     7.384000e-13  2.187809e-11
5       7.484000e-13                      NaN              NaN  2.183939e-11
6       7.441000e-13                      NaN              NaN  2.161419e-11
..               ...                      ...              ...           ...
976              NaN                      NaN              NaN  2.069989e-11
977              NaN                      NaN              NaN  2.062949e-11
978              NaN                      NaN              NaN  2.085629e-11
979              NaN                      NaN              NaN  2.073269e-11
980              NaN                      NaN              NaN  2.060429e-11

     mass 28, corr
2              NaN
3              NaN
4              NaN
5              NaN
6              NaN
..             ...
976   1.732314e-13
977   1.762314e-13
978   1.814314e-13
979   1.284314e-13
980   1.660314e-13

[979 rows x 20 columns]

count    9.300000e+01
mean    -6.107915e-13
std      2.514509e-14
min     -6.696173e-13
25%     -6.274173e-13
50%     -6.142173e-13
75%     -5.978173e-13
max     -5.414173e-13
Name: sample sig, mass 28, dtype: float64

### Plotting

In [7]:
#Plotting the all the relevant MID spectrums
plt.figure(figsize=(14,8))
plt.plot(time['Elapsed time, mass 2'],mid["mass 2.0_value"],marker=".", markersize=4,label='M2')
plt.plot(time['Elapsed time, mass 4'],mid["mass 4.0_value"],marker=".", markersize=4,label='M4')
plt.plot(time['Elapsed time, mass 12'],mid["mass 12.0_value"],marker=".", markersize=4,label='M14')
plt.plot(time['Elapsed time, mass 16'],mid["mass 16.0_value"],marker=".", markersize=4,label='M16')
plt.plot(time['Elapsed time, mass 18'],mid["mass 18.0_value"],marker=".", markersize=4,label='M18')
plt.plot(time['Elapsed time, mass 28'],mid["mass 28.0_value"],marker=".", markersize=4,label='M28')
plt.plot(time['Elapsed time, mass 32'],mid["mass 32.0_value"],marker=".", markersize=4,label='M32')
plt.plot(time['Elapsed time, mass 40'],mid["mass 40.0_value"],marker=".", markersize=4,label='M40')
plt.plot(time["Elapsed time, mass 44"],mid["mass 44.0_value"],marker=".", markersize=4,label='M44')

plt.xlabel('Elapsed time (s)')
plt.ylabel('Ion current (A)')
plt.legend(title="Mol masses", loc="upper right")
plt.title("MID scan, EGA in @RT, dynamic vacuum")
plt.yscale('log')

In [8]:
#plotting HiVolta log
plt.figure(figsize=(12,6))
plt.plot(hv["Elapsed time"],hv["hv_grid"],marker=".", markersize=4,label='Grid current')
plt.plot(hv["Elapsed time"],hv["em"],marker=".", markersize=4,label='Emission current')
plt.xlabel('Elapsed time (s)')
plt.ylabel('Current (A)')
plt.legend(loc="upper right")
plt.title("HiVolta current recording, EGA in @RT, dynamic vacuum")
plt.yscale('log')

In [9]:
#Plotting BA2, BA1 pressure
plt.figure(figsize=(10,6))
plt.plot(vaclog["Elapsed time"],vaclog["Barion_2"],marker=".", markersize=4,label='Barion 2')
plt.plot(vaclog["Elapsed time"],vaclog["Barion_1"],marker=".", markersize=4,label='Barion 1')

plt.xlabel('Elapsed time (s)')
plt.ylabel('Pressure (mbar)')
plt.legend()
plt.title("Total pressure evolution, EGA in @RT, dynamic vacuum")
ax = plt.gca()
ax.set_yscale('log')
plt.tick_params(axis="y", which='minor')
ax.yaxis.set_minor_formatter(LogFormatter(minor_thresholds=(2,0.5)))
plt.show()

# Primary desorption calculation method
### Elena's formula for the cryo setup
$$
\eta=\frac{C_{H2}\cdot (\Delta p_1 - \Delta p_2)q_e}{k_B\cdot T \cdot I_e}
$$

Where $\Delta p_i=p(t)_i - p(t=0)_i$ and $i=1,2$
In the case of the 4K setup, we know the exact conductance of gasses. The formula above applies well.

In [10]:
#calculation delta_p-s
dp1 = (np.mean(p_h2)-np.mean(base_h2))*100
print(dp1)

#Constants
k_B = 1.38e-23
T = 296
q_e = 1.6e-19
c_h2 = 37.91/1000
s_h2=42/1000
x_h2=1/((1/c_h2)+(1/s_h2))
print(x_h2)
#Emission current
I_em = np.mean(hv["em"].nlargest(30))
print(I_em)
#Conductance for CO in m3/s
c_co=10.13/1000
c_co2 = 8.08/1000

-1.4554927498790037e-09
0.01992516581153798
2.600916666666666e-06

In [11]:
#Desorption yield
eta_h2 = (x_h2*dp1*q_e)/(k_B*T*I_em)
#eta_co = (c_co*(dp1-dp2)*q_e)/(k_B*T*I_em)
print("The desorption yield for H2 [mol/el]:",eta_h2,"\n",)#""The desorption yield for CO2 [mol/el]:",eta_co2)

The desorption yield for H2 [mol/el]: -0.00043675183485515276