In [1]:
import pandas as pd
from scipy.optimize import curve_fit
from scipy.integrate import quad
from sklearn.metrics import r2_score
import seaborn
seaborn.set(style='whitegrid')
import numpy as np
import math
import matplotlib.pyplot as plt
import matplotlib.dates as md
import matplotlib.ticker as tick
from matplotlib.ticker import LogFormatter
%matplotlib qt
# %matplotlib inline
from datetime import datetime, date

C:\Users\etiirine\Anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

## Reading in the data

#### MID

In [2]:
#read in the data
mid = pd.read_csv("MID.tsv", sep="\t", skiprows=lambda x: x <=11,  on_bad_lines="skip")
mid.drop([0,1], inplace=True)
#print(mid.describe())
#bring the time data into a new df:
time = pd.DataFrame(mid.iloc[:,0::2]) #- get every second column
time["mass 2.0_time"] = pd.to_datetime(time["mass 2.0_time"], format="%Y/%m/%d %H:%M:%S.%f").dt.strftime('%d/%m/%Y %H:%M:%S')
time["mass 4.0_time"] = pd.to_datetime(time["mass 4.0_time"], format="%Y/%m/%d %H:%M:%S.%f").dt.strftime('%d/%m/%Y %H:%M:%S')
time["mass 5.5_time"] = pd.to_datetime(time["mass 5.5_time"], format="%Y/%m/%d %H:%M:%S.%f").dt.strftime('%d/%m/%Y %H:%M:%S')
time["mass 12.0_time"] = pd.to_datetime(time["mass 12.0_time"], format="%Y/%m/%d %H:%M:%S.%f").dt.strftime('%d/%m/%Y %H:%M:%S')
time["mass 15.0_time"] = pd.to_datetime(time["mass 15.0_time"], format="%Y/%m/%d %H:%M:%S.%f").dt.strftime('%d/%m/%Y %H:%M:%S')
time["mass 16.0_time"] = pd.to_datetime(time["mass 16.0_time"], format="%Y/%m/%d %H:%M:%S.%f").dt.strftime('%d/%m/%Y %H:%M:%S')
time["mass 18.0_time"] = pd.to_datetime(time["mass 18.0_time"], format="%Y/%m/%d %H:%M:%S.%f").dt.strftime('%d/%m/%Y %H:%M:%S')
time["mass 28.0_time"] = pd.to_datetime(time["mass 28.0_time"], format="%Y/%m/%d %H:%M:%S.%f").dt.strftime('%d/%m/%Y %H:%M:%S')
time["mass 32.0_time"] = pd.to_datetime(time["mass 32.0_time"], format="%Y/%m/%d %H:%M:%S.%f").dt.strftime('%d/%m/%Y %H:%M:%S')
time["mass 40.0_time"] = pd.to_datetime(time["mass 40.0_time"], format="%Y/%m/%d %H:%M:%S.%f").dt.strftime('%d/%m/%Y %H:%M:%S')
time["mass 44.0_time"] = pd.to_datetime(time["mass 44.0_time"], format="%Y/%m/%d %H:%M:%S.%f").dt.strftime('%d/%m/%Y %H:%M:%S')

#add elapsed time columns
def elapsed_time(df):
    itr = 0
    counter = len(df.columns)
    masses = [2,4,5.5,12,15,16,18,28,32,40,44]
    for i in df:
        timestamp = pd.to_datetime(df[i], format="%Y/%m/%d %H:%M:%S.%f")
        runtime = (timestamp-timestamp[2]).dt.total_seconds()
        colname = "Elapsed time, mass {}".format(masses[itr]) 
        df.insert(counter, colname, runtime)
        itr += 1
        counter += 1
    return(df)
#elapsed_time(time)
time
#time["Elapsed time, mass 40"].describe()

,mass 2.0_time,mass 4.0_time,mass 5.5_time,mass 12.0_time,mass 15.0_time,mass 16.0_time,mass 18.0_time,mass 28.0_time,mass 32.0_time,mass 40.0_time,mass 44.0_time
2,13/12/2022 17:34:18,13/12/2022 17:34:18,13/12/2022 17:34:19,13/12/2022 17:34:19,13/12/2022 17:34:19,13/12/2022 17:34:19,13/12/2022 17:34:20,13/12/2022 17:34:20,13/12/2022 17:34:20,13/12/2022 17:34:20,NaN
3,13/12/2022 17:34:25,13/12/2022 17:34:25,13/12/2022 17:34:25,13/12/2022 17:34:25,13/12/2022 17:34:26,13/12/2022 17:34:26,13/12/2022 17:34:26,13/12/2022 17:34:26,13/12/2022 17:34:27,13/12/2022 17:34:27,NaN
4,13/12/2022 17:34:31,13/12/2022 17:34:31,13/12/2022 17:34:31,13/12/2022 17:34:32,13/12/2022 17:34:32,13/12/2022 17:34:32,13/12/2022 17:34:32,13/12/2022 17:34:33,13/12/2022 17:34:33,13/12/2022 17:34:33,NaN
5,13/12/2022 17:34:37,13/12/2022 17:34:37,13/12/2022 17:34:38,13/12/2022 17:34:38,13/12/2022 17:34:38,13/12/2022 17:34:38,13/12/2022 17:34:39,13/12/2022 17:34:39,13/12/2022 17:34:39,13/12/2022 17:34:39,NaN
6,13/12/2022 17:34:44,13/12/2022 17:34:44,13/12/2022 17:34:44,13/12/2022 17:34:44,13/12/2022 17:34:45,13/12/2022 17:34:45,13/12/2022 17:34:45,13/12/2022 17:34:45,13/12/2022 17:34:46,13/12/2022 17:34:46,13/12/2022 17:34:47
...,...,...,...,...,...,...,...,...,...,...,...
341,13/12/2022 18:10:02,13/12/2022 18:10:03,13/12/2022 18:10:03,13/12/2022 18:10:03,13/12/2022 18:10:03,13/12/2022 18:10:04,13/12/2022 18:10:04,13/12/2022 18:10:04,13/12/2022 18:10:04,13/12/2022 18:10:05,NaN
342,13/12/2022 18:10:09,13/12/2022 18:10:09,13/12/2022 18:10:09,13/12/2022 18:10:09,13/12/2022 18:10:10,13/12/2022 18:10:10,13/12/2022 18:10:10,13/12/2022 18:10:10,13/12/2022 18:10:11,13/12/2022 18:10:11,NaN
343,13/12/2022 18:10:15,13/12/2022 18:10:15,13/12/2022 18:10:16,13/12/2022 18:10:16,13/12/2022 18:10:16,13/12/2022 18:10:16,13/12/2022 18:10:17,13/12/2022 18:10:17,13/12/2022 18:10:17,13/12/2022 18:10:17,NaN
344,13/12/2022 18:10:21,13/12/2022 18:10:22,13/12/2022 18:10:22,13/12/2022 18:10:22,13/12/2022 18:10:22,13/12/2022 18:10:23,13/12/2022 18:10:23,13/12/2022 18:10:23,13/12/2022 18:10:23,13/12/2022 18:10:24,NaN
345,13/12/2022 18:10:28,13/12/2022 18:10:28,13/12/2022 18:10:28,13/12/2022 18:10:28,13/12/2022 18:10:29,13/12/2022 18:10:29,13/12/2022 18:10:29,13/12/2022 18:10:29,13/12/2022 18:10:30,13/12/2022 18:10:30,NaN

In [35]:
#print(mid[mid.columns[1::2]])

     mass 2.0_value  mass 4.0_value  mass 5.5_value  mass 12.0_value  \
2      1.921830e-11    9.218000e-13    5.800000e-14     1.746000e-13
3      1.945420e-11    9.547000e-13    5.770000e-14     1.823000e-13
4      1.969180e-11    9.517000e-13    6.270000e-14     1.666000e-13
5      1.985630e-11    9.632000e-13    1.580000e-14     1.768000e-13
6      1.973530e-11    9.713000e-13    1.850000e-14     1.684000e-13
..              ...             ...             ...              ...
341    2.048890e-11    5.732000e-13    1.590000e-14     1.795000e-13
342    2.044700e-11    5.593000e-13    2.030000e-14     1.635000e-13
343    2.045180e-11    5.700000e-13    1.950000e-14     1.567000e-13
344    2.051530e-11    5.495000e-13    1.960000e-14     1.952000e-13
345    2.039380e-11    5.550000e-13    2.290000e-14     2.028000e-13

     mass 15.0_value  mass 16.0_value  mass 18.0_value  mass 28.0_value  \
2       9.400000e-14     4.321000e-13     7.971000e-13     8.514000e-13
3       9.930000e-14     4.348000e-13     7.835000e-13     8.674000e-13
4       1.068000e-13     4.198000e-13     7.963000e-13     8.509000e-13
5       1.148000e-13     4.327000e-13     8.573000e-13     8.645000e-13
6       9.780000e-14     4.730000e-13     7.629000e-13     8.333000e-13
..               ...              ...              ...              ...
341     3.150000e-14     4.137000e-13     9.007000e-13     8.451000e-13
342     2.600000e-14     4.466000e-13     8.688000e-13     8.794000e-13
343     2.700000e-14     4.537000e-13     8.501000e-13     8.661000e-13
344     3.550000e-14     4.359000e-13     8.845000e-13     8.935000e-13
345     3.590000e-14     4.204000e-13     8.759000e-13     8.749000e-13

     mass 32.0_value  mass 40.0_value  mass 44.0_value
2       9.560000e-14     4.130000e-14              NaN
3       1.137000e-13     5.030000e-14              NaN
4       1.027000e-13     6.720000e-14              NaN
5       8.670000e-14     1.490000e-14              NaN
6       2.730000e-14     2.230000e-14     3.762000e-13
..               ...              ...              ...
341     4.200000e-14     2.300000e-14              NaN
342     3.310000e-14     2.680000e-14              NaN
343     3.780000e-14     1.380000e-14              NaN
344     4.130000e-14     1.790000e-14              NaN
345     2.550000e-14     1.710000e-14              NaN

[344 rows x 11 columns]

#### Vaclogger

In [3]:
#reading the Emission current, pressures
vaclog=pd.read_csv("vaclog", sep="\t")
vaclog.head()#### Baseline MID
#adding an elapsed time column
timestamp=[]
for i in vaclog["Time"]:
    timestamp.append(i)
#making the column into a datetime object
timestamps=pd.to_datetime(vaclog["Time"],format="%d/%m/%Y %H:%M:%S")
runtime=(timestamps-timestamps[0]).dt.total_seconds()    
vaclog.insert(2,"Elapsed time",runtime)
# vaclog.drop(index=vaclog.index[0], 
#         axis=0, 
#         inplace=True)

vaclog

,Live comments,Time,Elapsed time,injection 100mbar,Barion_2,Barion_1,DUAL experiment,DUAL insulation,injection 1mbar,helium,T-platinum,T-CERNOX,I_emission,I_grid
0,NaN,13/12/2022 17:31:14,0.0,-0.046295,2.540000e-09,1.640000e-09,4.996000e-09,4.919000e-07,0.35246,197.0,-5.163,4288.086,NaN,NaN
1,NaN,13/12/2022 17:31:21,7.0,-0.047451,2.900000e-09,1.680000e-09,4.996000e-09,4.919000e-07,0.35245,197.0,-5.275,4288.198,NaN,NaN
2,NaN,13/12/2022 17:31:28,14.0,-0.046614,2.900000e-09,1.640000e-09,4.996000e-09,4.919000e-07,0.35244,197.0,-5.050,4286.403,NaN,NaN
3,NaN,13/12/2022 17:31:35,21.0,-0.050953,2.400000e-09,1.860000e-09,4.996000e-09,4.733000e-07,0.35245,196.0,-5.275,4286.739,NaN,NaN
4,NaN,13/12/2022 17:31:42,28.0,-0.046468,1.140000e-09,6.030000e-10,4.996000e-09,4.688000e-07,0.35244,196.0,-5.163,4286.515,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326,NaN,13/12/2022 18:10:16,2342.0,-0.042349,1.010000e-09,4.950000e-10,4.996000e-09,4.577000e-07,0.35240,76.0,-5.163,2780.235,NaN,NaN
327,NaN,13/12/2022 18:10:23,2349.0,-0.042349,1.000000e-09,4.960000e-10,4.996000e-09,4.577000e-07,0.35240,76.0,-5.163,2766.992,NaN,NaN
328,NaN,13/12/2022 18:10:30,2356.0,-0.042054,1.010000e-09,4.960000e-10,4.996000e-09,4.571000e-07,0.35241,76.0,-5.275,2768.451,NaN,NaN
329,NaN,13/12/2022 18:10:37,2363.0,-0.042620,1.000000e-09,4.950000e-10,4.996000e-09,4.577000e-07,0.35242,76.0,-5.163,2759.135,NaN,NaN
330,NaN,13/12/2022 18:10:44,2370.0,-0.042817,1.010000e-09,4.960000e-10,4.996000e-09,4.571000e-07,0.35240,76.0,-5.163,2747.912,NaN,NaN

#### HiVolta log

In [25]:
#Reading in the HiVolta measurement file 
hv = pd.read_csv("hv log", sep=",")
#hv.drop(columns=["Vmon1","Vmon2","Vmon3","Vmon4","Vmon5","Vmon6","Vmon7","Vmon8","Imon3","Imon4","Imon5","Imon6","Imon7","Imon8","Comments1"], inplace=True)
hv["hv_grid"]=[element * 1e-6 for element in hv["IMon1"]]
hv["em"]=[element * 1e-6 for element in hv["IMon2"]]
hv.drop(hv.columns[hv.columns.str.contains('Unnamed',case = False)],axis = 1, inplace = True)
hv["em"]=abs(hv["em"])
hv["hv_grid"]=abs(hv["hv_grid"])

#adding a datetime column
datetime = pd.to_datetime(hv['Date'] + ' ' + hv['Time'],format="%d/%m/%Y %H:%M:%S.%f")
datetime = datetime.dt.strftime('%Y-%m-%d %H:%M:%S')

hv.insert(0,"datetime",datetime)

#adding an elapsed time column
timestamp=[]
for i in hv["Time"]:
    timestamp.append(i)
    
#making the column into a datetime object
timestamps=pd.to_datetime(hv["Time"],format="%H:%M:%S.%f")
runtime=(timestamps-timestamps[0]).dt.total_seconds()    
hv.insert(2,"Elapsed time",runtime)


# hv.drop(index=hv.index[0], 
#         axis=0, 
#         inplace=True)

hv

,datetime,Date,Elapsed time,Time,VMon1,VMon2,VMon3,VMon4,VMon5,VMon6,...,IMon2,IMon3,IMon4,IMon5,IMon6,IMon7,IMon8,Comment,hv_grid,em
0,2022-12-13 17:30:03,13/12/2022,0.000,17:30:03.498,0.06,0.10,0.18,0.18,0.0,0.0,...,0.0062,0.0129,0.0105,0.0167,-0.0142,-0.0258,-0.0100,NaN,1.000000e-10,6.200000e-09
1,2022-12-13 17:30:04,13/12/2022,1.178,17:30:04.676,0.06,0.10,0.18,0.18,0.0,0.0,...,0.0062,0.0129,0.0105,0.0164,-0.0142,-0.0258,-0.0100,NaN,1.000000e-10,6.200000e-09
2,2022-12-13 17:30:05,13/12/2022,2.366,17:30:05.864,0.06,0.10,0.18,0.18,0.0,0.0,...,0.0062,0.0129,0.0105,0.0101,-0.0142,-0.0258,-0.0100,NaN,1.000000e-10,6.200000e-09
3,2022-12-13 17:30:07,13/12/2022,3.548,17:30:07.046,0.06,0.10,0.18,0.18,0.0,0.0,...,0.0062,0.0129,0.0105,0.0171,-0.0142,-0.0258,-0.0100,NaN,1.000000e-10,6.200000e-09
4,2022-12-13 17:31:58,13/12/2022,114.845,17:31:58.343,0.06,0.10,0.14,0.16,0.0,0.0,...,0.0057,0.0165,0.0082,0.0124,-0.0143,-0.0262,-0.0099,NaN,2.000000e-10,5.700000e-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1872,2022-12-13 18:09:37,13/12/2022,2373.930,18:09:37.428,0.08,0.06,0.06,0.14,0.0,0.0,...,-0.0052,-0.0069,-0.0100,-0.0053,-0.0153,-0.0282,-0.0112,NaN,1.000000e-10,5.200000e-09
1873,2022-12-13 18:09:38,13/12/2022,2375.102,18:09:38.600,0.08,0.06,0.06,0.12,0.0,0.0,...,-0.0048,-0.0069,-0.0097,-0.0053,-0.0153,-0.0282,-0.0112,NaN,1.000000e-10,4.800000e-09
1874,2022-12-13 18:09:39,13/12/2022,2376.291,18:09:39.789,0.08,0.06,0.06,0.12,0.0,0.0,...,-0.0048,-0.0069,-0.0097,-0.0058,-0.0153,-0.0282,-0.0112,NaN,0.000000e+00,4.800000e-09
1875,2022-12-13 18:09:40,13/12/2022,2377.471,18:09:40.969,0.08,0.06,0.06,0.12,0.0,0.0,...,-0.0048,-0.0069,-0.0097,-0.0058,-0.0153,-0.0282,-0.0114,NaN,3.000000e-10,4.800000e-09
1876,2022-12-13 18:09:42,13/12/2022,2378.651,18:09:42.149,0.08,0.06,0.06,0.12,0.0,0.0,...,-0.0051,-0.0069,-0.0097,-0.0058,-0.0153,-0.0282,-0.0114,NaN,3.000000e-10,5.100000e-09

### Checking injection pressure linearity

In [5]:
#defining a function for the straight line
def func(x,a,b):
    return a*x + b
#curve fit for the data
y = vaclog["injection 1mbar"].values
x = (vaclog["Elapsed time"]/3600).values
params, cov = curve_fit(func,x,y)
#straight line parameters
a, b = params
print(f"Fitted line: y = {a:.2f}*x+{b:.2f}")

Fitted line: y = -0.00*x+0.35

In [6]:
#checking inj pressure linearity, graph
fig, ax = plt.subplots()
y_fit = func(x,a,b)
ax.plot((vaclog["Elapsed time"]/3600),vaclog["injection 1mbar"],marker=".", markersize=5,label='inj volume pressure')
ax.plot((vaclog["Elapsed time"]/3600),y_fit, "--",color="red", label="Y= -ax + b fit") 
ax.legend(loc="upper right")

ax.set_xlabel('Elapsed time (h)')
ax.set_ylabel('Pressure (mbar)')
ax.set_yscale('linear')
plt.title("S1 Injection pressure evolution 1mbar conductance gauge")

Text(0.5, 1.0, 'S1 Injection pressure evolution 1mbar conductance gauge')

### Data processing

In [7]:
#print vaclog comments
print(pd.unique(vaclog["Live comments"]))

[nan]

In [8]:
#Temperature curve for CERNOX - for temp stability
A=[230.317302,-6170.1513,71837.9529,-477946.76,2.003668910085786e+6,-5.488690193047771e+6,9.830475663897528e+6,-1.111226817786569e+7,7.202477878914065e+6,-2.04194551328507e+6]
#specify fit parameters A, data (Resistance values)
def polyfit(params,data):
    total=[]
    for j in data: 
        exp=0
        for i in range(len(params)):
            exp += (params[i]/(math.log10(j))**i)
        total.append(10**exp)
    return(total)

In [9]:
#Filtering background signal

#Find the timestamp where emission was turned on and off
print("Result 1:",hv.loc[hv["Comment"]=="emission on"])
print("Result 2:", hv.loc[hv["Comment"]=="grid repelling"])
x=pd.Timestamp(2022, 12, 13, 17,38,53)
y=pd.Timestamp(2022, 12, 13, 17, 45, 21)

#then find the time value closest to it in the MID scan file 
print("\n","Result 3:",mid.iloc[(pd.to_datetime(mid['mass 2.0_time'],format="%Y/%m/%d %H:%M:%S") - x).abs().argsort(),:])
print("\n","Result 4:",mid.iloc[(pd.to_datetime(mid['mass 2.0_time'],format="%Y/%m/%d %H:%M:%S") - y).abs().argsort(),:])

#take a mass with a signal known to be in the background
bck=np.mean(mid["mass 40.0_value"])

#apply background correction to the rest of the mass spectrum
mid["mass 2, corr"]=mid["mass 2.0_value"]-bck

 
#From the signal, get the partial pressures 
h2_sens=2.13e-2
p_h2=mid["mass 2, corr"][45:107]/h2_sens
print(p_h2.describe())

#baseline for partial pressure delta
base_h2=mid["mass 2, corr"][0:45]/h2_sens
base_h2.describe()

Result 1:                 datetime        Date  Elapsed time          Time  VMon1  \
339  13/12/2022 17:38:53  13/12/2022       529.855  17:38:53.353   0.08
340  13/12/2022 17:38:54  13/12/2022       531.038  17:38:54.536   0.10
341  13/12/2022 17:38:55  13/12/2022       532.227  17:38:55.725   0.16
342  13/12/2022 17:38:56  13/12/2022       533.471  17:38:56.969   0.08

      VMon2   VMon3   VMon4   VMon5  VMon6  ...   IMon2    IMon3    IMon4  \
339  100.12  999.66  999.66  641.82    0.0  ...  0.3700  26.3643  26.3879
340  100.12  999.66  999.66  771.98    0.0  ...  0.3670  27.7330  27.7084
341  100.12  999.66  999.64  902.14    0.0  ...  0.3773  28.6768  28.6777
342  100.12  999.68  999.70  998.46    0.0  ...  0.4532  29.8831  29.8351

       IMon5   IMon6   IMon7   IMon8      Comment       hv_grid            em
339  26.3281 -0.0149 -0.0271 -0.0114  emission on  6.000000e-10  3.700000e-07
340  27.6982 -0.0149 -0.0271 -0.0114  emission on  2.900000e-09  3.670000e-07
341  28.6241 -0.0149 -0.0271 -0.0114  emission on  7.030000e-08  3.773000e-07
342  29.8594 -0.0149 -0.0271 -0.0114  emission on  5.420000e-08  4.532000e-07

[4 rows x 23 columns]
Result 2:                 datetime        Date  Elapsed time          Time   VMon1  \
660  13/12/2022 17:45:18  13/12/2022       915.135  17:45:18.633  401.32
661  13/12/2022 17:45:19  13/12/2022       916.322  17:45:19.820  498.60
662  13/12/2022 17:45:21  13/12/2022       917.525  17:45:21.023  499.88
663  13/12/2022 17:45:22  13/12/2022       918.711  17:45:22.209  499.88

     VMon2    VMon3    VMon4    VMon5  VMon6  ...   IMon2    IMon3    IMon4  \
660  100.1  1000.02  1000.14  1000.12    0.0  ...  0.0375  31.8527  31.8170
661  100.1  1000.02  1000.14  1000.12    0.0  ...  0.0277  31.8527  31.8172
662  100.1  1000.02  1000.14  1000.12    0.0  ...  0.0200  31.8527  31.8188
663  100.1  1000.02  1000.14  1000.12    0.0  ...  0.0195  31.8527  31.8190

       IMon5   IMon6   IMon7   IMon8         Comment       hv_grid  \
660  31.7556 -0.0141 -0.0277 -0.0114  grid repelling  5.267000e-07
661  31.7556 -0.0142 -0.0277 -0.0114  grid repelling  2.248000e-07
662  31.7557 -0.0142 -0.0277 -0.0114  grid repelling  2.610000e-08
663  31.7558 -0.0142 -0.0277 -0.0114  grid repelling  2.430000e-08

               em
660  3.750000e-08
661  2.770000e-08
662  2.000000e-08
663  1.950000e-08

[4 rows x 23 columns]

 Result 3:                mass 2.0_time  mass 2.0_value            mass 4.0_time  \
45   2022/12/13 17:38:50.683    2.048840e-11  2022/12/13 17:38:50.933
46   2022/12/13 17:38:57.008    2.134950e-11  2022/12/13 17:38:57.258
44   2022/12/13 17:38:44.358    2.052920e-11  2022/12/13 17:38:44.608
47   2022/12/13 17:39:03.333    2.101780e-11  2022/12/13 17:39:03.583
43   2022/12/13 17:38:38.033    2.044220e-11  2022/12/13 17:38:38.283
..                       ...             ...                      ...
341  2022/12/13 18:10:02.883    2.048890e-11  2022/12/13 18:10:03.133
342  2022/12/13 18:10:09.208    2.044700e-11  2022/12/13 18:10:09.458
343  2022/12/13 18:10:15.533    2.045180e-11  2022/12/13 18:10:15.783
344  2022/12/13 18:10:21.858    2.051530e-11  2022/12/13 18:10:22.108
345  2022/12/13 18:10:28.183    2.039380e-11  2022/12/13 18:10:28.433

     mass 4.0_value            mass 5.5_time  mass 5.5_value  \
45     1.011300e-12  2022/12/13 17:38:51.183    1.270000e-14
46     1.055900e-12  2022/12/13 17:38:57.508    1.180000e-14
44     9.961000e-13  2022/12/13 17:38:44.858    1.650000e-14
47     1.016700e-12  2022/12/13 17:39:03.833    1.850000e-14
43     9.752000e-13  2022/12/13 17:38:38.533    1.690000e-14
..              ...                      ...             ...
341    5.732000e-13  2022/12/13 18:10:03.383    1.590000e-14
342    5.593000e-13  2022/12/13 18:10:09.708    2.030000e-14
343    5.700000e-13  2022/12/13 18:10:16.033    1.950000e-14
344    5.495000e-13  2022/12/13 18:10:22.358    1.960000e-14
345    5.550000e-13  2022/12/13 18:10:28.683    2.290000e-14

              mass 12.0_time  mass 12.0_value           mass 15.0_time  \
45   2022/12/13 17:38:51.433     1.764000e-13  2022/12/13 17:38:51.683
46   2022/12/13 17:38:57.758     1.923000e-13  2022/12/13 17:38:58.008
44   2022/12/13 17:38:45.108     1.819000e-13  2022/12/13 17:38:45.358
47   2022/12/13 17:39:04.083     1.865000e-13  2022/12/13 17:39:04.333
43   2022/12/13 17:38:38.783     1.923000e-13  2022/12/13 17:38:39.033
..                       ...              ...                      ...
341  2022/12/13 18:10:03.633     1.795000e-13  2022/12/13 18:10:03.883
342  2022/12/13 18:10:09.958     1.635000e-13  2022/12/13 18:10:10.208
343  2022/12/13 18:10:16.283     1.567000e-13  2022/12/13 18:10:16.533
344  2022/12/13 18:10:22.608     1.952000e-13  2022/12/13 18:10:22.858
345  2022/12/13 18:10:28.933     2.028000e-13  2022/12/13 18:10:29.183

     mass 15.0_value  ...           mass 18.0_time  mass 18.0_value  \
45      3.760000e-14  ...  2022/12/13 17:38:52.184     7.932000e-13
46      2.660000e-14  ...  2022/12/13 17:38:58.509     8.610000e-13
44      3.380000e-14  ...  2022/12/13 17:38:45.859     8.397000e-13
47      2.430000e-14  ...  2022/12/13 17:39:04.834     8.555000e-13
43      2.250000e-14  ...  2022/12/13 17:38:39.534     8.691000e-13
..               ...  ...                      ...              ...
341     3.150000e-14  ...  2022/12/13 18:10:04.384     9.007000e-13
342     2.600000e-14  ...  2022/12/13 18:10:10.709     8.688000e-13
343     2.700000e-14  ...  2022/12/13 18:10:17.034     8.501000e-13
344     3.550000e-14  ...  2022/12/13 18:10:23.359     8.845000e-13
345     3.590000e-14  ...  2022/12/13 18:10:29.684     8.759000e-13

              mass 28.0_time  mass 28.0_value           mass 32.0_time  \
45   2022/12/13 17:38:52.434     8.994000e-13  2022/12/13 17:38:52.685
46   2022/12/13 17:38:58.759     8.376000e-13  2022/12/13 17:38:59.010
44   2022/12/13 17:38:46.110     9.263000e-13  2022/12/13 17:38:46.360
47   2022/12/13 17:39:05.084     8.764000e-13  2022/12/13 17:39:05.335
43   2022/12/13 17:38:39.785     9.406000e-13  2022/12/13 17:38:40.035
..                       ...              ...                      ...
341  2022/12/13 18:10:04.634     8.451000e-13  2022/12/13 18:10:04.885
342  2022/12/13 18:10:10.959     8.794000e-13  2022/12/13 18:10:11.210
343  2022/12/13 18:10:17.284     8.661000e-13  2022/12/13 18:10:17.535
344  2022/12/13 18:10:23.609     8.935000e-13  2022/12/13 18:10:23.860
345  2022/12/13 18:10:29.934     8.749000e-13  2022/12/13 18:10:30.185

     mass 32.0_value           mass 40.0_time  mass 40.0_value mass 44.0_time  \
45      2.320000e-14  2022/12/13 17:38:52.935     1.520000e-14            NaN
46      2.270000e-14  2022/12/13 17:38:59.260     2.440000e-14            NaN
44      2.490000e-14  2022/12/13 17:38:46.610     1.650000e-14            NaN
47      4.290000e-14  2022/12/13 17:39:05.585     1.600000e-14            NaN
43      2.680000e-14  2022/12/13 17:38:40.285     2.090000e-14            NaN
..               ...                      ...              ...            ...
341     4.200000e-14  2022/12/13 18:10:05.135     2.300000e-14            NaN
342     3.310000e-14  2022/12/13 18:10:11.460     2.680000e-14            NaN
343     3.780000e-14  2022/12/13 18:10:17.785     1.380000e-14            NaN
344     4.130000e-14  2022/12/13 18:10:24.110     1.790000e-14            NaN
345     2.550000e-14  2022/12/13 18:10:30.435     1.710000e-14            NaN

     mass 44.0_value
45               NaN
46               NaN
44               NaN
47               NaN
43               NaN
..               ...
341              NaN
342              NaN
343              NaN
344              NaN
345              NaN

[344 rows x 22 columns]

 Result 4:                mass 2.0_time  mass 2.0_value            mass 4.0_time  \
107  2022/12/13 17:45:22.833    1.989550e-11  2022/12/13 17:45:23.083
106  2022/12/13 17:45:16.508    1.989180e-11  2022/12/13 17:45:16.758
108  2022/12/13 17:45:29.158    1.982400e-11  2022/12/13 17:45:29.408
105  2022/12/13 17:45:10.183    2.007340e-11  2022/12/13 17:45:10.433
109  2022/12/13 17:45:35.483    2.001970e-11  2022/12/13 17:45:35.733
..                       ...             ...                      ...
341  2022/12/13 18:10:02.883    2.048890e-11  2022/12/13 18:10:03.133
342  2022/12/13 18:10:09.208    2.044700e-11  2022/12/13 18:10:09.458
343  2022/12/13 18:10:15.533    2.045180e-11  2022/12/13 18:10:15.783
344  2022/12/13 18:10:21.858    2.051530e-11  2022/12/13 18:10:22.108
345  2022/12/13 18:10:28.183    2.039380e-11  2022/12/13 18:10:28.433

     mass 4.0_value            mass 5.5_time  mass 5.5_value  \
107    9.841000e-13  2022/12/13 17:45:23.333    1.730000e-14
106    9.604000e-13  2022/12/13 17:45:17.008    2.140000e-14
108    9.396000e-13  2022/12/13 17:45:29.658    2.030000e-14
105    9.642000e-13  2022/12/13 17:45:10.683    1.820000e-14
109    9.669000e-13  2022/12/13 17:45:35.983    1.540000e-14
..              ...                      ...             ...
341    5.732000e-13  2022/12/13 18:10:03.383    1.590000e-14
342    5.593000e-13  2022/12/13 18:10:09.708    2.030000e-14
343    5.700000e-13  2022/12/13 18:10:16.033    1.950000e-14
344    5.495000e-13  2022/12/13 18:10:22.358    1.960000e-14
345    5.550000e-13  2022/12/13 18:10:28.683    2.290000e-14

              mass 12.0_time  mass 12.0_value           mass 15.0_time  \
107  2022/12/13 17:45:23.583     1.927000e-13  2022/12/13 17:45:23.833
106  2022/12/13 17:45:17.258     1.761000e-13  2022/12/13 17:45:17.508
108  2022/12/13 17:45:29.908     1.816000e-13  2022/12/13 17:45:30.158
105  2022/12/13 17:45:10.933     1.774000e-13  2022/12/13 17:45:11.183
109  2022/12/13 17:45:36.233     1.907000e-13  2022/12/13 17:45:36.483
..                       ...              ...                      ...
341  2022/12/13 18:10:03.633     1.795000e-13  2022/12/13 18:10:03.883
342  2022/12/13 18:10:09.958     1.635000e-13  2022/12/13 18:10:10.208
343  2022/12/13 18:10:16.283     1.567000e-13  2022/12/13 18:10:16.533
344  2022/12/13 18:10:22.608     1.952000e-13  2022/12/13 18:10:22.858
345  2022/12/13 18:10:28.933     2.028000e-13  2022/12/13 18:10:29.183

     mass 15.0_value  ...           mass 18.0_time  mass 18.0_value  \
107     2.820000e-14  ...  2022/12/13 17:45:24.334     8.588000e-13
106     2.860000e-14  ...  2022/12/13 17:45:18.009     8.831000e-13
108     2.500000e-14  ...  2022/12/13 17:45:30.659     7.760000e-13
105     3.710000e-14  ...  2022/12/13 17:45:11.684     8.567000e-13
109     3.310000e-14  ...  2022/12/13 17:45:36.984     8.060000e-13
..               ...  ...                      ...              ...
341     3.150000e-14  ...  2022/12/13 18:10:04.384     9.007000e-13
342     2.600000e-14  ...  2022/12/13 18:10:10.709     8.688000e-13
343     2.700000e-14  ...  2022/12/13 18:10:17.034     8.501000e-13
344     3.550000e-14  ...  2022/12/13 18:10:23.359     8.845000e-13
345     3.590000e-14  ...  2022/12/13 18:10:29.684     8.759000e-13

              mass 28.0_time  mass 28.0_value           mass 32.0_time  \
107  2022/12/13 17:45:24.585     9.113000e-13  2022/12/13 17:45:24.835
106  2022/12/13 17:45:18.260     8.844000e-13  2022/12/13 17:45:18.510
108  2022/12/13 17:45:30.910     7.635000e-13  2022/12/13 17:45:31.160
105  2022/12/13 17:45:11.935     9.184000e-13  2022/12/13 17:45:12.185
109  2022/12/13 17:45:37.235     8.687000e-13  2022/12/13 17:45:37.485
..                       ...              ...                      ...
341  2022/12/13 18:10:04.634     8.451000e-13  2022/12/13 18:10:04.885
342  2022/12/13 18:10:10.959     8.794000e-13  2022/12/13 18:10:11.210
343  2022/12/13 18:10:17.284     8.661000e-13  2022/12/13 18:10:17.535
344  2022/12/13 18:10:23.609     8.935000e-13  2022/12/13 18:10:23.860
345  2022/12/13 18:10:29.934     8.749000e-13  2022/12/13 18:10:30.185

     mass 32.0_value           mass 40.0_time  mass 40.0_value  \
107     3.850000e-14  2022/12/13 17:45:25.085     1.880000e-14
106     2.050000e-14  2022/12/13 17:45:18.760     1.560000e-14
108     1.640000e-14  2022/12/13 17:45:31.410     1.380000e-14
105     3.400000e-14  2022/12/13 17:45:12.435     1.360000e-14
109     1.920000e-14  2022/12/13 17:45:37.735     1.720000e-14
..               ...                      ...              ...
341     4.200000e-14  2022/12/13 18:10:05.135     2.300000e-14
342     3.310000e-14  2022/12/13 18:10:11.460     2.680000e-14
343     3.780000e-14  2022/12/13 18:10:17.785     1.380000e-14
344     4.130000e-14  2022/12/13 18:10:24.110     1.790000e-14
345     2.550000e-14  2022/12/13 18:10:30.435     1.710000e-14

              mass 44.0_time  mass 44.0_value
107                      NaN              NaN
106                      NaN              NaN
108                      NaN              NaN
105                      NaN              NaN
109  2022/12/13 17:45:38.486     1.075000e-13
..                       ...              ...
341                      NaN              NaN
342                      NaN              NaN
343                      NaN              NaN
344                      NaN              NaN
345                      NaN              NaN

[344 rows x 22 columns]
count    6.200000e+01
mean     9.541607e-10
std      1.278598e-11
min      9.297929e-10
25%      9.445770e-10
50%      9.536310e-10
75%      9.621967e-10
max      9.858399e-10
Name: mass 2, corr, dtype: float64

count    4.500000e+01
mean     9.510844e-10
std      1.653616e-11
min      9.013563e-10
25%      9.403188e-10
50%      9.560653e-10
75%      9.605300e-10
max      1.001413e-09
Name: mass 2, corr, dtype: float64

# Primary desorption calculation 
### Elena's formula for the cryo setup
$$
\eta=\frac{C_{H2}\cdot (\Delta p_1 - \Delta p_2)q_e}{k_B\cdot T \cdot I_e}
$$

Where $\Delta p_i=p(t)_i - p(t=0)_i$ and $i=1,2$
In the case of the 4K setup, we know the exact conductance of gasses. The formula above applies well.

Due to the EGA being fully retracted, it is safe to assume that the desorption takes place at approximately room temperature

In [10]:
#calculation delta_p-s
dp1 = (np.mean(p_h2)-np.mean(base_h2))*100
print(dp1)

#Constants
k_B = 1.38e-23
T = 293
print(T)
q_e = 1.6e-19
c_h2 = 37.91/1000
s_h2=42/1000
x_h2=1/((1/c_h2)+(1/s_h2))
print(x_h2)
#Emission current
#ignore the inrush current values
hv["em"].where(hv["em"] <= 1.5e-6, np.nan, inplace=True)

I_em = np.nanmean(hv["em"].nlargest(30))
print(I_em)
#Conductance for CO in m3/s
c_co=10.13/1000
c_co2 = 8.08/1000

3.0762902384438795e-10
293
0.01992516581153798
5.805433333333332e-07

In [11]:
#Desorption yield
eta_h2 = (x_h2*dp1*q_e)/(k_B*T*I_em)
#eta_co = (c_co*(dp1-dp2)*q_e)/(k_B*T*I_em)
print("S1 The desorption yield for H2 [mol/el]:",eta_h2,"\n",)#""The desorption yield for CO2 [mol/el]:",eta_co2)

S1 The desorption yield for H2 [mol/el]: 0.0004177994705124395

### Plotting

In [12]:
#define parameters for plotting
#annotation params
figtext_kwargs = dict(horizontalalignment ="center", 
                      fontsize = 12, color ="green", 
                      style ="italic", wrap = True)
#date params
locator = pd.date_range(min(time["mass 2.0_time"]),max(time["mass 2.0_time"]),freq="15min")
print(locator)
formatter = md.DateFormatter("%H:%M:%S")
print(formatter)
#daterange = pd.date_range("2018-01-01", periods=, freq="M")

DatetimeIndex(['2022-12-13 17:34:18', '2022-12-13 17:49:18',
               '2022-12-13 18:04:18'],
              dtype='datetime64[ns]', freq='15T')
<matplotlib.dates.DateFormatter object at 0x000001EBD655B460>

In [37]:
#Plotting the all the relevant MID spectrums
plt.figure(figsize=(14,8))
ax = plt.gca()
ax = plt.gca()
#xfmt = md.DateFormatter('%Y-%m-%d %H:%M:%S')
#ax.xaxis.set_major_formatter(xfmt)
ax.xaxis.set_major_locator(plt.MaxNLocator(10))

for label in ax.get_xticklabels(which='major'):
    label.set(rotation=30, horizontalalignment='right')
# # Format the date into months & days
# ax.xaxis.set_major_formatter(mdates.DateFormatter('%H/%d')) 
# # Change the tick interval
# plt.gca().xaxis.set_major_locator(mdates.DayLocator(interval=30)) 
# ax.xaxis.set_major_formatter(formatter)


plt.plot(time["mass 2.0_time"],mid["mass 2.0_value"],marker=".", markersize=4,label='M2')
plt.plot(time["mass 4.0_time"],mid["mass 4.0_value"],marker=".", markersize=4,label='M4')
#plt.plot(time["mass 12.0_time"],mid["mass 12.0_value"],marker=".", markersize=4,label='M11')
#plt.plot(time["mass 16.0_time"],mid["mass 16.0_value"],marker=".", markersize=4,label='M16')
#plt.plot(time["mass 18.0_time"],mid["mass 18.0_value"],marker=".", markersize=4,label='M18')
#plt.plot(time["mass 28.0_time"],mid["mass 28.0_value"],marker=".", markersize=4,label='M28')
#plt.plot(time["mass 32.0_time"],mid["mass 32.0_value"],marker=".", markersize=4,label='M32')
#plt.plot(time["mass 40.0_time"],mid["mass 40.0_value"],marker=".", markersize=4,label='M40')
#plt.plot(time["mass 44.0_time"],mid["mass 44.0_value"],marker=".", markersize=4,label='M44')

plt.xlabel('Timestamp')
plt.ylabel('Ion current (A)')
plt.legend(title="Mol masses", loc="upper right")
plt.title("S1 MID scan")
plt.figtext(0.19,0.84, 'No electron activity',**figtext_kwargs)
#plt.figtext(525, 2.9e-11, '\u2193 Initial desorption peak',**figtext_kwargs)
#plt.figtext(1100, 2.6e-11, 'Grid transparent', fontdict = font)
#plt.figtext(1670, 1.5e-11, 'Grid repelling', fontdict = font)
#plt.figtext(2005, 4.46e-11, '\u2193 EGA rotated', fontdict = font)
#plt.figtext(2306, 2.6e-11, 'Grid transparent', fontdict = font)
plt.yscale('log')
# plt.xticks(locator)
# plt.gcf().autofmt_xdate()
plt.show()

In [28]:
#plotting HiVolta log
plt.figure(figsize=(12,6))

plt.plot(hv["datetime"],hv["hv_grid"],marker=".", markersize=4,label='Grid current')
plt.plot(hv["datetime"],hv["em"],marker=".", markersize=4,label='Emission current')
plt.xlabel('Timestamp')
plt.ylabel('Current (A)')
plt.legend(loc="upper right")
plt.title("S1 Current evolution")
ax = plt.gca()
#xfmt = md.DateFormatter('%Y-%m-%d %H:%M:%S')
#ax.xaxis.set_major_formatter(xfmt)
ax.xaxis.set_major_locator(plt.MaxNLocator(10))

for label in ax.get_xticklabels(which='major'):
    label.set(rotation=30, horizontalalignment='right')
    print(label)
plt.yscale('log')
plt.show()

Text(0, 0, '')
Text(0, 0, '')
Text(0, 0, '')
Text(0, 0, '')
Text(0, 0, '')
Text(0, 0, '')
Text(0, 0, '')
Text(0, 0, '')
Text(0, 0, '')
Text(0, 0, '')

In [ ]:
#Plotting BA2, BA1 pressure
plt.figure(figsize=(10,6))
plt.plot(vaclog["Elapsed time"],vaclog["Barion_2"],marker=".", markersize=4,label='Barion 2')
plt.plot(vaclog["Elapsed time"],vaclog["Barion_1"],marker=".", markersize=4,label='Barion 1')

plt.xlabel('Elapsed time (s)')
plt.ylabel('Pressure (mbar)')
plt.legend()
plt.title("S1 Total pressure evolution")
ax = plt.gca()
ax.set_yscale('log')
plt.tick_params(axis="y", which='minor')
plt.grid(visible=None, which='both', axis='both')
plt.show()

In [ ]:
## Plotting the temp evolution
plt.figure()
plt.plot((vaclog["Elapsed time"]),polyfit(A,vaclog["T-CERNOX"]),marker=".", markersize=5,label='T-CERNOX')

plt.xlabel('Elapsed time (s)')
plt.ylabel('Temperature (K)')
plt.legend()
plt.title("S1 Temperature evolution")
plt.yscale('linear')