In [1]:
import pandas as pd
from scipy.optimize import curve_fit
import seaborn
seaborn.set(style='whitegrid')
import numpy as np
import matplotlib.pyplot as plt
import math
from matplotlib.ticker import LogFormatter
%matplotlib qt
# %matplotlib inline
from datetime import datetime, date

C:\Users\etiirine\Anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [2]:
#read in the data
mid = pd.read_csv("MID ega middle pos.tsv", sep="\t", skiprows=lambda x: x <=11,  on_bad_lines="skip")
mid.drop([0,1], inplace=True)
print(mid.describe())
#bring the time data into a new df
time = pd.DataFrame(mid.iloc[:,0::2]) #- get every second column
print(time.describe())
#add elapsed time columns
def elapsed_time(df):
    itr = 0
    counter = len(df.columns)
    masses = [2,4,12,16,18,28,32,40,44]
    for i in df:
        timestamp = pd.to_datetime(df[i], format="%Y/%m/%d %H:%M:%S.%f")
        runtime = (timestamp-timestamp[2]).dt.total_seconds()
        colname = "Elapsed time, mass {}".format(masses[itr]) 
        df.insert(counter, colname, runtime)
        itr += 1
        counter += 1
    return(df)
elapsed_time(time)

       mass 2.0_value  mass 4.0_value  mass 12.0_value  mass 16.0_value  \
count    1.342000e+03    1.342000e+03     1.342000e+03     1.342000e+03
mean     4.673327e-11    1.652835e-12     6.387419e-13     1.216852e-12
std      8.472184e-12    9.141274e-13     1.142658e-13     3.653593e-13
min      2.111490e-11    4.500000e-15     2.477000e-13     4.910000e-13
25%      4.137730e-11    1.026875e-12     5.802250e-13     1.105525e-12
50%      4.625055e-11    2.045950e-12     6.326000e-13     1.200500e-12
75%      5.173925e-11    2.302475e-12     7.035500e-13     1.323600e-12
max      1.074910e-10    5.395300e-12     1.251600e-12     1.061040e-11

       mass 18.0_value  mass 28.0_value  mass 32.0_value  mass 40.0_value  \
count     1.342000e+03     1.342000e+03     1.342000e+03     1.342000e+03
mean      2.471230e-12     4.428383e-12     4.599836e-14     1.006524e-12
std       6.172663e-13     9.175029e-13     9.938932e-15     1.226430e-12
min       1.176400e-12     4.930000e-14     3.700000e-15     0.000000e+00
25%       1.988900e-12     3.805050e-12     4.030000e-14     2.200000e-15
50%       2.505250e-12     4.497650e-12     4.680000e-14     5.600000e-15
75%       2.923125e-12     5.057600e-12     5.230000e-14     2.286000e-12
max       4.809000e-12     9.281700e-12     1.070000e-13     4.174900e-12

       mass 44.0_value
count     7.760000e+02
mean      2.567439e-12
std       6.027874e-13
min       6.998000e-13
25%       2.219175e-12
50%       2.526850e-12
75%       2.893275e-12
max       6.212200e-12
                  mass 2.0_time            mass 4.0_time  \
count                      1342                     1342
unique                     1342                     1342
top     2022/11/25 10:03:04.399  2022/11/25 10:03:04.649
freq                          1                        1

                 mass 12.0_time           mass 16.0_time  \
count                      1342                     1342
unique                     1342                     1342
top     2022/11/25 10:03:04.899  2022/11/25 10:03:05.149
freq                          1                        1

                 mass 18.0_time           mass 28.0_time  \
count                      1342                     1342
unique                     1342                     1342
top     2022/11/25 10:03:05.399  2022/11/25 10:03:05.649
freq                          1                        1

                 mass 32.0_time           mass 40.0_time  \
count                      1342                     1342
unique                     1342                     1342
top     2022/11/25 10:03:05.900  2022/11/25 10:03:06.400
freq                          1                        1

                 mass 44.0_time
count                       776
unique                      776
top     2022/11/25 10:03:08.723
freq                          1

,mass 2.0_time,mass 4.0_time,mass 12.0_time,mass 16.0_time,mass 18.0_time,mass 28.0_time,mass 32.0_time,mass 40.0_time,mass 44.0_time,"Elapsed time, mass 2","Elapsed time, mass 4","Elapsed time, mass 12","Elapsed time, mass 16","Elapsed time, mass 18","Elapsed time, mass 28","Elapsed time, mass 32","Elapsed time, mass 40","Elapsed time, mass 44"
2,2022/11/25 10:03:04.399,2022/11/25 10:03:04.649,2022/11/25 10:03:04.899,2022/11/25 10:03:05.149,2022/11/25 10:03:05.399,2022/11/25 10:03:05.649,2022/11/25 10:03:05.900,2022/11/25 10:03:06.400,NaN,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,NaN
3,2022/11/25 10:03:06.721,2022/11/25 10:03:06.971,2022/11/25 10:03:07.221,2022/11/25 10:03:07.472,2022/11/25 10:03:07.722,2022/11/25 10:03:07.972,2022/11/25 10:03:08.222,2022/11/25 10:03:08.472,2022/11/25 10:03:08.723,2.322,2.322,2.322,2.323,2.323,2.323,2.322,2.072,NaN
4,2022/11/25 10:03:09.044,2022/11/25 10:03:09.294,2022/11/25 10:03:09.544,2022/11/25 10:03:09.794,2022/11/25 10:03:10.044,2022/11/25 10:03:10.295,2022/11/25 10:03:10.545,2022/11/25 10:03:10.795,2022/11/25 10:03:11.045,4.645,4.645,4.645,4.645,4.645,4.646,4.645,4.395,NaN
5,2022/11/25 10:03:11.366,2022/11/25 10:03:11.616,2022/11/25 10:03:11.867,2022/11/25 10:03:12.117,2022/11/25 10:03:12.367,2022/11/25 10:03:12.617,2022/11/25 10:03:12.867,2022/11/25 10:03:13.118,2022/11/25 10:03:13.368,6.967,6.967,6.968,6.968,6.968,6.968,6.967,6.718,NaN
6,2022/11/25 10:03:13.689,2022/11/25 10:03:13.939,2022/11/25 10:03:14.189,2022/11/25 10:03:14.439,2022/11/25 10:03:14.689,2022/11/25 10:03:14.940,2022/11/25 10:03:15.190,2022/11/25 10:03:15.690,NaN,9.290,9.290,9.290,9.290,9.290,9.291,9.290,9.290,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1339,2022/11/25 10:54:56.591,2022/11/25 10:54:56.841,2022/11/25 10:54:57.092,2022/11/25 10:54:57.342,2022/11/25 10:54:57.592,2022/11/25 10:54:57.842,2022/11/25 10:54:58.092,2022/11/25 10:54:58.343,2022/11/25 10:54:58.593,3112.192,3112.192,3112.193,3112.193,3112.193,3112.193,3112.192,3111.943,NaN
1340,2022/11/25 10:54:58.914,2022/11/25 10:54:59.164,2022/11/25 10:54:59.414,2022/11/25 10:54:59.664,2022/11/25 10:54:59.914,2022/11/25 10:55:00.165,2022/11/25 10:55:00.415,2022/11/25 10:55:00.665,2022/11/25 10:55:00.915,3114.515,3114.515,3114.515,3114.515,3114.515,3114.516,3114.515,3114.265,NaN
1341,2022/11/25 10:55:01.236,2022/11/25 10:55:01.486,2022/11/25 10:55:01.737,2022/11/25 10:55:01.987,2022/11/25 10:55:02.237,2022/11/25 10:55:02.487,2022/11/25 10:55:02.737,2022/11/25 10:55:03.238,NaN,3116.837,3116.837,3116.838,3116.838,3116.838,3116.838,3116.837,3116.838,NaN
1342,2022/11/25 10:55:03.559,2022/11/25 10:55:03.809,2022/11/25 10:55:04.059,2022/11/25 10:55:04.309,2022/11/25 10:55:04.559,2022/11/25 10:55:04.810,2022/11/25 10:55:05.060,2022/11/25 10:55:05.560,NaN,3119.160,3119.160,3119.160,3119.160,3119.160,3119.161,3119.160,3119.160,NaN
1343,2022/11/25 10:55:05.881,2022/11/25 10:55:06.131,2022/11/25 10:55:06.382,2022/11/25 10:55:06.632,2022/11/25 10:55:06.882,2022/11/25 10:55:07.132,2022/11/25 10:55:07.382,2022/11/25 10:55:07.633,2022/11/25 10:55:07.883,3121.482,3121.482,3121.483,3121.483,3121.483,3121.483,3121.482,3121.233,NaN

In [3]:
#reading the Emission current, pressures
vaclog=pd.read_csv("vaclog", sep="\t")
vaclog.head()
#adding an elapsed time column
timestamp=[]
for i in vaclog["Time"]:
    timestamp.append(i)
#making the column into a datetime object
timestamps=pd.to_datetime(vaclog["Time"],format="%d/%m/%Y %H:%M:%S")
runtime=(timestamps-timestamps[0]).dt.total_seconds()    
vaclog.insert(2,"Elapsed time",runtime)
vaclog.drop(index=vaclog.index[0], 
        axis=0, 
        inplace=True)

vaclog.head()

,Live comments,Time,Elapsed time,injection 100mbar,Barion_2,Barion_1,DUAL experiment,DUAL insulation,injection 1mbar,helium,T-platinum,T-CERNOX,I_emission,I_grid
1,NaN,25/11/2022 10:02:41,7.0,-0.065079,2.500000e-09,7.630000e-10,4.996000e-09,0.000002,0.000580,0.0,-112.345,54.882,NaN,NaN
2,NaN,25/11/2022 10:02:48,14.0,-0.065967,2.470000e-09,7.490000e-10,4.996000e-09,0.000002,0.000581,0.0,-112.121,54.994,NaN,NaN
3,NaN,25/11/2022 10:02:56,22.0,-0.065055,2.450000e-09,7.520000e-10,4.996000e-09,0.000002,0.000579,0.0,-112.121,55.106,NaN,NaN
4,NaN,25/11/2022 10:03:03,29.0,-0.064906,2.430000e-09,7.490000e-10,4.996000e-09,0.000002,0.000577,0.0,-112.345,55.219,NaN,NaN
5,NaN,25/11/2022 10:03:10,36.0,-0.065944,2.410000e-09,7.450000e-10,4.996000e-09,0.000002,0.000580,0.0,-112.233,55.106,NaN,NaN

In [4]:
#Reading in the HiVolta measurement file to get the grid current
hv = pd.read_csv("hv log", sep=",")
#hv.drop(columns=["Vmon1","Vmon2","Vmon3","Vmon4","Vmon5","Vmon6","Vmon7","Vmon8","Imon3","Imon4","Imon5","Imon6","Imon7","Imon8","Comments1"], inplace=True)
hv["hv_grid"]=[element * 1e-6 for element in hv["IMon1"]]
hv["em"]=[element * 1e-6 for element in hv["IMon2"]]
hv.drop(hv.columns[hv.columns.str.contains('Unnamed',case = False)],axis = 1, inplace = True)
hv["em"]=abs(hv["em"])
hv["hv_grid"]=abs(hv["hv_grid"])

#adding an elapsed time column
timestamp=[]
for i in hv["Time"]:
    timestamp.append(i)
    
#making the column into a datetime object
timestamps=pd.to_datetime(hv["Time"],format="%H:%M:%S.%f")
runtime=(timestamps-timestamps[0]).dt.total_seconds()    
hv.insert(2,"Elapsed time",runtime)
hv.drop(index=hv.index[0], 
        axis=0, 
        inplace=True)

hv.describe()

,Elapsed time,VMon1,VMon2,VMon3,VMon4,VMon5,VMon6,VMon7,VMon8,IMon1,IMon2,IMon3,IMon4,IMon5,IMon6,IMon7,IMon8,hv_grid,em
count,2557.000000,2557.000000,2557.000000,2557.000000,2557.000000,2557.000000,2557.0,2557.0,2557.0,2557.000000,2557.000000,2557.000000,2557.000000,2557.000000,2557.000000,2557.000000,2557.000000,2.557000e+03,2.557000e+03
mean,1599.369464,178.958178,97.058170,966.592499,965.509386,964.688565,0.0,0.0,0.0,-0.046293,0.408382,38.509743,38.519470,38.556124,-0.019194,-0.029878,-0.021183,6.253043e-08,4.083960e-07
std,880.016138,239.047886,17.100193,177.860835,180.818592,182.966031,0.0,0.0,0.0,0.067669,0.351995,7.215886,7.226668,7.238905,0.001281,0.001586,0.001471,5.302312e-08,3.519790e-07
min,68.897000,0.020000,0.080000,0.000000,0.000000,0.000000,0.0,0.0,0.0,-0.514700,-0.006200,-0.067300,-0.057100,-0.030500,-0.024300,-0.032400,-0.023500,0.000000e+00,6.000000e-10
25%,837.580000,0.080000,100.080000,999.820000,999.900000,999.960000,0.0,0.0,0.0,-0.084700,0.023100,39.553100,39.566300,39.607600,-0.019800,-0.031100,-0.022700,1.790000e-08,2.310000e-08
50%,1600.013000,0.100000,100.080000,999.820000,999.920000,999.980000,0.0,0.0,0.0,-0.062400,0.487200,40.047900,40.063000,40.100300,-0.019100,-0.030300,-0.021200,6.290000e-08,4.872000e-07
75%,2361.019000,499.860000,100.080000,999.840000,999.940000,999.980000,0.0,0.0,0.0,0.017400,0.658900,40.402900,40.418100,40.458700,-0.018200,-0.029100,-0.019900,8.480000e-08,6.589000e-07
max,3123.318000,499.900000,100.160000,999.860000,999.960000,1000.000000,0.0,0.0,0.0,0.545800,3.313700,40.788900,40.799300,40.836900,-0.017400,-0.026900,-0.018100,5.458000e-07,3.313700e-06

### Data processing

In [5]:
#Filtering background signal - necessary only when calculating desorption yield

#Find the timestamp where emission was turned on
print("Result 1:",hv.loc[hv["Comment"]=="emission on"])
print("Result 2:",hv.loc[hv["Comment"]=="grid repelling"])

x=pd.Timestamp(2022, 11, 25, 10, 4, 57)
y=pd.Timestamp(2022, 11, 25, 10, 38, 53)

#then find the time value closest to it in the MID scan file
print("\n","Result 4:",mid.iloc[(pd.to_datetime(mid['mass 2.0_time'],format="%Y/%m/%d %H:%M:%S") - x).abs().argsort(),:])
print("\n","Result 5:",mid.iloc[(pd.to_datetime(mid['mass 2.0_time'],format="%Y/%m/%d %H:%M:%S") - y).abs().argsort(),:])

#average the signal before this timestamp and subtract it from the Em-on part
bck=np.mean(mid["mass 40.0_value"])
print("\n","Result 7:",bck)

#apply background correction to the rest of the mass spectrum
mid["mass 2, corr"]=mid["mass 2.0_value"]-bck
#print("Res 5:",mid["mass 2, corr"].describe())

#remove values under noise level from MID spectrum
mid["mass 40.0_value"][mid["mass 40.0_value"] < 1e-14] = np.nan

#From the signal, get the partial pressures 
h2_sens=2.13e-2
p_h2=mid["mass 2, corr"][50:927]/h2_sens

#baseline for partial pressure delta
base_h2=mid["mass 2, corr"][0:50]/h2_sens

Result 1:           Date          Time  Elapsed time  VMon1   VMon2   VMon3   VMon4  \
96  25/11/2022  10:04:57.094       189.729    0.1  100.14  999.50  999.46
97  25/11/2022  10:04:58.294       190.929    0.1  100.12  999.56  999.52
98  25/11/2022  10:04:59.481       192.116    0.1  100.12  999.56  999.52
99  25/11/2022  10:05:00.717       193.352    0.1  100.12  999.58  999.54

     VMon5  VMon6  VMon7  ...   IMon2    IMon3    IMon4    IMon5   IMon6  \
96  999.58    0.0    0.0  ...  1.0347  36.5824  36.5447  36.5901 -0.0223
97  999.58    0.0    0.0  ...  1.0347  36.5747  36.5503  36.5960 -0.0223
98  999.58    0.0    0.0  ...  1.0287  36.5891  36.5723  36.6187 -0.0223
99  999.60    0.0    0.0  ...  1.0204  36.5959  36.5821  36.6289 -0.0223

     IMon7   IMon8      Comment       hv_grid        em
96 -0.0324 -0.0227  emission on  1.279000e-07  0.000001
97 -0.0324 -0.0227  emission on  1.258000e-07  0.000001
98 -0.0324 -0.0227  emission on  1.273000e-07  0.000001
99 -0.0324 -0.0227  emission on  1.274000e-07  0.000001

[4 rows x 22 columns]
Result 2:             Date          Time  Elapsed time   VMon1   VMon2   VMon3   VMon4  \
1803  25/11/2022  10:38:51.352      2223.987  281.12  100.12  999.84  999.94
1804  25/11/2022  10:38:52.536      2225.171  421.32  100.12  999.84  999.94
1805  25/11/2022  10:38:53.727      2226.362  499.18  100.10  999.84  999.94
1806  25/11/2022  10:38:54.919      2227.554  499.38  100.10  999.84  999.94
1807  25/11/2022  10:38:56.109      2228.744  499.56  100.10  999.84  999.94

       VMon5  VMon6  VMon7  ...   IMon2    IMon3    IMon4    IMon5   IMon6  \
1803  999.98    0.0    0.0  ...  0.0745  40.3943  40.3796  40.4144 -0.0193
1804  999.98    0.0    0.0  ...  0.0580  40.3808  40.3790  40.4153 -0.0193
1805  999.98    0.0    0.0  ...  0.0420  40.3727  40.3790  40.4153 -0.0193
1806  999.98    0.0    0.0  ...  0.0345  40.3703  40.3790  40.4153 -0.0193
1807  999.98    0.0    0.0  ...  0.0304  40.3703  40.3786  40.4161 -0.0193

       IMon7   IMon8         Comment       hv_grid            em
1803 -0.0289 -0.0204  grid repelling  5.185000e-07  7.450000e-08
1804 -0.0289 -0.0204  grid repelling  5.403000e-07  5.800000e-08
1805 -0.0289 -0.0204  grid repelling  1.162000e-07  4.200000e-08
1806 -0.0289 -0.0204  grid repelling  4.590000e-08  3.450000e-08
1807 -0.0289 -0.0204  grid repelling  3.340000e-08  3.040000e-08

[5 rows x 22 columns]

 Result 4:                 mass 2.0_time  mass 2.0_value            mass 4.0_time  \
50    2022/11/25 10:04:55.879    4.631990e-11  2022/11/25 10:04:56.129
51    2022/11/25 10:04:58.201    4.630590e-11  2022/11/25 10:04:58.451
49    2022/11/25 10:04:53.556    3.039970e-11  2022/11/25 10:04:53.806
52    2022/11/25 10:05:00.524    4.540190e-11  2022/11/25 10:05:00.774
48    2022/11/25 10:04:51.234    2.247050e-11  2022/11/25 10:04:51.484
...                       ...             ...                      ...
1339  2022/11/25 10:54:56.591    3.414180e-11  2022/11/25 10:54:56.841
1340  2022/11/25 10:54:58.914    3.398860e-11  2022/11/25 10:54:59.164
1341  2022/11/25 10:55:01.236    3.403050e-11  2022/11/25 10:55:01.486
1342  2022/11/25 10:55:03.559    3.374400e-11  2022/11/25 10:55:03.809
1343  2022/11/25 10:55:05.881    3.368490e-11  2022/11/25 10:55:06.131

      mass 4.0_value           mass 12.0_time  mass 12.0_value  \
50      2.255200e-12  2022/11/25 10:04:56.379     5.342000e-13
51      2.263500e-12  2022/11/25 10:04:58.702     5.244000e-13
49      1.463800e-12  2022/11/25 10:04:54.057     3.697000e-13
52      2.206200e-12  2022/11/25 10:05:01.024     5.649000e-13
48      1.076200e-12  2022/11/25 10:04:51.734     2.794000e-13
...              ...                      ...              ...
1339    7.710000e-14  2022/11/25 10:54:57.092     5.696000e-13
1340    8.320000e-14  2022/11/25 10:54:59.414     5.912000e-13
1341    7.650000e-14  2022/11/25 10:55:01.737     5.785000e-13
1342    8.980000e-14  2022/11/25 10:55:04.059     6.013000e-13
1343    8.010000e-14  2022/11/25 10:55:06.382     5.959000e-13

               mass 16.0_time  mass 16.0_value           mass 18.0_time  \
50    2022/11/25 10:04:56.629     1.047300e-12  2022/11/25 10:04:56.879
51    2022/11/25 10:04:58.952     1.057200e-12  2022/11/25 10:04:59.202
49    2022/11/25 10:04:54.307     7.808000e-13  2022/11/25 10:04:54.557
52    2022/11/25 10:05:01.274     9.913000e-13  2022/11/25 10:05:01.524
48    2022/11/25 10:04:51.984     5.912000e-13  2022/11/25 10:04:52.234
...                       ...              ...                      ...
1339  2022/11/25 10:54:57.342     9.928000e-13  2022/11/25 10:54:57.592
1340  2022/11/25 10:54:59.664     9.602000e-13  2022/11/25 10:54:59.914
1341  2022/11/25 10:55:01.987     1.039100e-12  2022/11/25 10:55:02.237
1342  2022/11/25 10:55:04.309     1.022200e-12  2022/11/25 10:55:04.559
1343  2022/11/25 10:55:06.632     1.002200e-12  2022/11/25 10:55:06.882

      mass 18.0_value           mass 28.0_time  mass 28.0_value  \
50       1.312800e-12  2022/11/25 10:04:57.130     3.209100e-12
51       1.371100e-12  2022/11/25 10:04:59.452     3.251600e-12
49       1.294600e-12  2022/11/25 10:04:54.807     2.607000e-12
52       1.379800e-12  2022/11/25 10:05:01.775     3.297100e-12
48       1.231900e-12  2022/11/25 10:04:52.485     1.970000e-12
...               ...                      ...              ...
1339     3.209700e-12  2022/11/25 10:54:57.842     4.371200e-12
1340     3.251900e-12  2022/11/25 10:55:00.165     4.339800e-12
1341     3.207300e-12  2022/11/25 10:55:02.487     4.361600e-12
1342     3.181100e-12  2022/11/25 10:55:04.810     4.310900e-12
1343     3.126200e-12  2022/11/25 10:55:07.132     4.287400e-12

               mass 32.0_time  mass 32.0_value           mass 40.0_time  \
50    2022/11/25 10:04:57.380     2.810000e-14  2022/11/25 10:04:57.630
51    2022/11/25 10:04:59.702     4.110000e-14  2022/11/25 10:05:00.203
49    2022/11/25 10:04:55.057     3.750000e-14  2022/11/25 10:04:55.308
52    2022/11/25 10:05:02.025     3.680000e-14  2022/11/25 10:05:02.525
48    2022/11/25 10:04:52.735     3.270000e-14  2022/11/25 10:04:53.235
...                       ...              ...                      ...
1339  2022/11/25 10:54:58.092     4.190000e-14  2022/11/25 10:54:58.343
1340  2022/11/25 10:55:00.415     5.040000e-14  2022/11/25 10:55:00.665
1341  2022/11/25 10:55:02.737     4.430000e-14  2022/11/25 10:55:03.238
1342  2022/11/25 10:55:05.060     2.980000e-14  2022/11/25 10:55:05.560
1343  2022/11/25 10:55:07.382     3.830000e-14  2022/11/25 10:55:07.633

      mass 40.0_value           mass 44.0_time  mass 44.0_value
50       6.100000e-15  2022/11/25 10:04:57.880     2.179300e-12
51       2.200200e-12                      NaN              NaN
49       3.000000e-16  2022/11/25 10:04:55.558     2.006700e-12
52       2.302900e-12                      NaN              NaN
48       1.094600e-12                      NaN              NaN
...               ...                      ...              ...
1339     1.700000e-15  2022/11/25 10:54:58.593     1.990400e-12
1340     9.000000e-16  2022/11/25 10:55:00.915     1.992400e-12
1341     1.976100e-12                      NaN              NaN
1342     1.935100e-12                      NaN              NaN
1343     7.100000e-15  2022/11/25 10:55:07.883     1.962700e-12

[1342 rows x 18 columns]

 Result 5:                mass 2.0_time  mass 2.0_value            mass 4.0_time  \
927  2022/11/25 10:38:52.716    4.620270e-11  2022/11/25 10:38:52.966
928  2022/11/25 10:38:55.039    4.649190e-11  2022/11/25 10:38:55.289
926  2022/11/25 10:38:50.394    4.672950e-11  2022/11/25 10:38:50.644
929  2022/11/25 10:38:57.361    4.609470e-11  2022/11/25 10:38:57.611
925  2022/11/25 10:38:48.071    5.204210e-11  2022/11/25 10:38:48.321
..                       ...             ...                      ...
6    2022/11/25 10:03:13.689    2.178840e-11  2022/11/25 10:03:13.939
5    2022/11/25 10:03:11.366    2.177490e-11  2022/11/25 10:03:11.616
4    2022/11/25 10:03:09.044    2.186260e-11  2022/11/25 10:03:09.294
3    2022/11/25 10:03:06.721    2.195880e-11  2022/11/25 10:03:06.971
2    2022/11/25 10:03:04.399    2.197440e-11  2022/11/25 10:03:04.649

     mass 4.0_value           mass 12.0_time  mass 12.0_value  \
927    2.239900e-12  2022/11/25 10:38:53.217     6.698000e-13
928    2.236100e-12  2022/11/25 10:38:55.539     6.530000e-13
926    2.264100e-12  2022/11/25 10:38:50.894     6.879000e-13
929    2.253300e-12  2022/11/25 10:38:57.862     6.568000e-13
925    2.497200e-12  2022/11/25 10:38:48.572     7.820000e-13
..              ...                      ...              ...
6      1.032000e-12  2022/11/25 10:03:14.189     2.480000e-13
5      1.045100e-12  2022/11/25 10:03:11.867     3.008000e-13
4      1.072700e-12  2022/11/25 10:03:09.544     2.952000e-13
3      1.093000e-12  2022/11/25 10:03:07.221     2.872000e-13
2      1.022100e-12  2022/11/25 10:03:04.899     2.561000e-13

              mass 16.0_time  mass 16.0_value           mass 18.0_time  \
927  2022/11/25 10:38:53.467     1.189400e-12  2022/11/25 10:38:53.717
928  2022/11/25 10:38:55.789     1.149500e-12  2022/11/25 10:38:56.039
926  2022/11/25 10:38:51.144     1.280200e-12  2022/11/25 10:38:51.394
929  2022/11/25 10:38:58.112     1.189000e-12  2022/11/25 10:38:58.362
925  2022/11/25 10:38:48.822     1.427300e-12  2022/11/25 10:38:49.072
..                       ...              ...                      ...
6    2022/11/25 10:03:14.439     5.205000e-13  2022/11/25 10:03:14.689
5    2022/11/25 10:03:12.117     5.114000e-13  2022/11/25 10:03:12.367
4    2022/11/25 10:03:09.794     5.216000e-13  2022/11/25 10:03:10.044
3    2022/11/25 10:03:07.472     5.499000e-13  2022/11/25 10:03:07.722
2    2022/11/25 10:03:05.149     5.560000e-13  2022/11/25 10:03:05.399

     mass 18.0_value           mass 28.0_time  mass 28.0_value  \
927     2.856500e-12  2022/11/25 10:38:53.967     4.846200e-12
928     2.874900e-12  2022/11/25 10:38:56.290     4.796200e-12
926     2.897500e-12  2022/11/25 10:38:51.645     5.009200e-12
929     2.945700e-12  2022/11/25 10:38:58.612     4.818700e-12
925     2.903200e-12  2022/11/25 10:38:49.322     5.249400e-12
..               ...                      ...              ...
6       1.186600e-12  2022/11/25 10:03:14.940     1.824000e-12
5       1.250000e-12  2022/11/25 10:03:12.617     1.803700e-12
4       1.220900e-12  2022/11/25 10:03:10.295     1.819700e-12
3       1.176400e-12  2022/11/25 10:03:07.972     1.814200e-12
2       1.226800e-12  2022/11/25 10:03:05.649     1.785300e-12

              mass 32.0_time  mass 32.0_value           mass 40.0_time  \
927  2022/11/25 10:38:54.217     4.320000e-14  2022/11/25 10:38:54.468
928  2022/11/25 10:38:56.540     4.550000e-14  2022/11/25 10:38:56.790
926  2022/11/25 10:38:51.895     4.890000e-14  2022/11/25 10:38:52.145
929  2022/11/25 10:38:58.862     4.940000e-14  2022/11/25 10:38:59.363
925  2022/11/25 10:38:49.572     5.330000e-14  2022/11/25 10:38:50.073
..                       ...              ...                      ...
6    2022/11/25 10:03:15.190     2.370000e-14  2022/11/25 10:03:15.690
5    2022/11/25 10:03:12.867     6.930000e-14  2022/11/25 10:03:13.118
4    2022/11/25 10:03:10.545     9.110000e-14  2022/11/25 10:03:10.795
3    2022/11/25 10:03:08.222     1.070000e-13  2022/11/25 10:03:08.472
2    2022/11/25 10:03:05.900     8.090000e-14  2022/11/25 10:03:06.400

     mass 40.0_value           mass 44.0_time  mass 44.0_value
927     3.600000e-15  2022/11/25 10:38:54.718     2.483900e-12
928     5.200000e-15  2022/11/25 10:38:57.040     2.415900e-12
926     1.800000e-15  2022/11/25 10:38:52.395     2.514800e-12
929     2.425200e-12                      NaN              NaN
925     2.796700e-12                      NaN              NaN
..               ...                      ...              ...
6       8.506000e-13                      NaN              NaN
5       1.000000e-16  2022/11/25 10:03:13.368     8.013000e-13
4       1.840000e-14  2022/11/25 10:03:11.045     8.171000e-13
3       1.290000e-14  2022/11/25 10:03:08.723     8.182000e-13
2       8.312000e-13                      NaN              NaN

[1342 rows x 18 columns]

 Result 7: 1.0065239940387484e-12

C:\Users\etiirine\AppData\Local\Temp\ipykernel_4764\456045194.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mid["mass 40.0_value"][mid["mass 40.0_value"] < 1e-14] = np.nan

In [6]:
#Temperature curve for CERNOX - for temp stability
A=[230.317302,-6170.1513,71837.9529,-477946.76,2.003668910085786e+6,-5.488690193047771e+6,9.830475663897528e+6,-1.111226817786569e+7,7.202477878914065e+6,-2.04194551328507e+6]
#specify fit parameters A, data (Resistance values)
def polyfit(params,data):
    total=[]
    for j in data: 
        exp=0
        for i in range(len(params)):
            exp += (params[i]/(math.log10(j))**i)
        total.append(10**exp)
    return(total)

### Plotting

In [7]:
#Plotting the all the relevant MID spectrums
plt.figure(figsize=(14,8))
plt.plot(time['Elapsed time, mass 2'],mid["mass 2.0_value"],marker=".", markersize=4,label='M2')
plt.plot(time['Elapsed time, mass 4'],mid["mass 4.0_value"],marker=".", markersize=4,label='M4')
plt.plot(time['Elapsed time, mass 12'],mid["mass 12.0_value"],marker=".", markersize=4,label='M14')
plt.plot(time['Elapsed time, mass 16'],mid["mass 16.0_value"],marker=".", markersize=4,label='M16')
plt.plot(time['Elapsed time, mass 18'],mid["mass 18.0_value"],marker=".", markersize=4,label='M18')
plt.plot(time['Elapsed time, mass 28'],mid["mass 28.0_value"],marker=".", markersize=4,label='M28')
plt.plot(time['Elapsed time, mass 32'],mid["mass 32.0_value"],marker=".", markersize=4,label='M12')
plt.plot(time['Elapsed time, mass 40'],mid["mass 40.0_value"],marker=".", markersize=4,label='M40')
plt.plot(time["Elapsed time, mass 44"],mid["mass 44.0_value"],marker=".", markersize=4,label='M44')

plt.xlabel('Elapsed time (s)')
plt.ylabel('Ion current (A)')
plt.legend(title="Mol masses", loc="upper right")
plt.title("MID scan, EGA in the middle on a-C @ RT, dynamic vacuum")
font = {'family': 'arial',
        'color':  'green',
        'weight': 'normal',
        'size': 12,
        }
plt.text(-100, 1.4e-11, 'No emission', fontdict = font)
plt.text(250, 7e-11, 'Emission on, inconsistent I_em', fontdict = font)
plt.text(1090, 2.8e-11, 'Grid repelling', fontdict = font)
plt.text(1475, 7e-11, 'Grid transparent, Em. more stable', fontdict = font)
plt.text(2170, 3.5e-11, 'Grid repelling, EGA turned', fontdict = font)
plt.yscale('log')

In [8]:
#plotting HiVolta log
plt.figure(figsize=(12,6))
plt.plot(hv["Elapsed time"],hv["hv_grid"],marker=".", markersize=4,label='Grid current')
plt.plot(hv["Elapsed time"],hv["em"],marker=".", markersize=4,label='Emission current')
plt.xlabel('Elapsed time (s)')
plt.ylabel('Current (A)')
plt.legend(loc="upper right")
plt.title("HiVolta current log, EGA in the middle on a-C @ RT, dynamic vacuum")
font = {'family': 'arial',
        'color':  'green',
        'weight': 'normal',
        'size': 12,
        }
plt.text(230, 3e-6, 'Emission on', fontdict = font)
plt.text(1170, 7e-9, 'Grid repelling', fontdict = font)
plt.text(1600, 1e-6, 'Grid transparent', fontdict = font)
plt.text(2300, 7e-9, 'Grid repelling, EGA turned', fontdict = font)

plt.yscale('log')

In [9]:
#Plotting BA2, BA1 pressure
plt.figure(figsize=(10,6))
plt.plot(vaclog["Elapsed time"],vaclog["Barion_2"],marker=".", markersize=4,label='Barion 2')
plt.plot(vaclog["Elapsed time"],vaclog["Barion_1"],marker=".", markersize=4,label='Barion 1')

plt.xlabel('Elapsed time (s)')
plt.ylabel('Pressure (mbar)')
plt.legend()
plt.title("Total pressure evolution, EGA in the middle on a-C @ RT, dynamic vacuum")
ax = plt.gca()
ax.set_yscale('log')
plt.tick_params(axis="y", which='minor')
plt.show()

# Primary desorption calculation method
### Elena's formula for the cryo setup
$$
\eta=\frac{C_{H2}\cdot (\Delta p_1 - \Delta p_2)q_e}{k_B\cdot T \cdot I_e}
$$

Where $\Delta p_i=p(t)_i - p(t=0)_i$ and $i=1,2$
In the case of the 4K setup, we know the exact conductance of gasses. The formula above applies well.

In [10]:
#calculation delta_p-s
dp1 = (np.mean(p_h2)-np.mean(base_h2))*100
print(dp1)

#Constants
k_B = 1.38e-23
T = np.mean(polyfit(A,vaclog["T-CERNOX"]))
print(T)
q_e = 1.6e-19
c_h2 = 37.91/1000
s_h2=42/1000
x_h2=1/((1/c_h2)+(1/s_h2))
print(x_h2)

#Emission current
#ignore the inrush current values
hv["em"].where(hv["em"] <= 1.2e-6, np.nan, inplace=True)
I_em = np.nanmean(hv["em"].nlargest(100))
print(I_em)

#Conductance for CO in m3/s
c_co=10.13/1000
c_co2 = 8.08/1000

1.0477019896039116e-07
304.42329107720155
0.01992516581153798
1.02597e-06

In [11]:
#Desorption yield
eta_h2 = (x_h2*dp1*q_e)/(k_B*T*I_em)
#eta_co = (c_co*(dp1-dp2)*q_e)/(k_B*T*I_em)
print("The desorption yield for H2 [mol/el]:",eta_h2,"\n",)#""The desorption yield for CO2 [mol/el]:",eta_co2)

The desorption yield for H2 [mol/el]: 0.07749399857011617