In [1]:
import pandas as pd
from scipy.optimize import curve_fit
import seaborn
import math
seaborn.set(style='whitegrid')
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import LogFormatter
%matplotlib qt
# %matplotlib inlineb
from datetime import datetime, date

C:\Users\etiirine\Anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [2]:
#reading the Emission current, pressures
vaclog=pd.read_csv("overnight warmup log", sep="\t")
vaclog.head()
#adding an elapsed time column
timestamp=[]
for i in vaclog["Time"]:
    timestamp.append(i)
#making the column into a datetime object
timestamps=pd.to_datetime(vaclog["Time"],format="%d/%m/%Y %H:%M:%S")
runtime=(timestamps-timestamps[0]).dt.total_seconds()    
vaclog.insert(2,"Elapsed time",runtime)
vaclog.drop(index=vaclog.index[0], 
        axis=0, 
        inplace=True)

vaclog.head()

,Live comments,Time,Elapsed time,injection 100mbar,Barion_2,Barion_1,DUAL experiment,DUAL insulation,injection 1mbar,helium,T-platinum,T-CERNOX,I_emission,I_grid
1,NaN,28/11/2022 18:01:52,8.0,0.57899,0.0,0.0,4.996000e-09,3.452000e-07,0.000841,261.0,-4.826,4272.822,NaN,NaN
2,NaN,28/11/2022 18:01:59,15.0,0.58291,0.0,0.0,4.996000e-09,3.448000e-07,0.000821,261.0,-4.938,4272.822,NaN,NaN
3,NaN,28/11/2022 18:02:06,22.0,0.58195,0.0,0.0,4.996000e-09,3.452000e-07,0.000815,262.0,-4.938,4273.047,NaN,NaN
4,NaN,28/11/2022 18:02:13,29.0,0.57852,0.0,0.0,4.996000e-09,3.452000e-07,0.000820,261.0,-5.050,4273.047,NaN,NaN
5,NaN,28/11/2022 18:02:20,36.0,0.58288,0.0,0.0,4.996000e-09,3.456000e-07,0.000812,261.0,-5.163,4273.047,NaN,NaN

In [3]:
#Temperature curve for CERNOX - for temp stability
A=[230.317302,-6170.1513,71837.9529,-477946.76,2.003668910085786e+6,-5.488690193047771e+6,9.830475663897528e+6,-1.111226817786569e+7,7.202477878914065e+6,-2.04194551328507e+6]
#specify fit parameters A, data (Resistance values)
def polyfit(params,data):
    total=[]
    for j in data: 
        exp=0
        for i in range(len(params)):
            exp += (params[i]/(math.log10(j))**i)
        total.append(10**exp)
    return(total)

In [4]:
#Plotting the temp evolution
plt.figure()
plt.plot((vaclog["Elapsed time"]),polyfit(A,vaclog["T-CERNOX"]),marker=".", markersize=5,label='Overnight warmup')

plt.xlabel('Elapsed time (s)')
plt.ylabel('Temperature (K)')
plt.legend()
plt.title("28.11 cooldown temperatures")
plt.yscale('linear')