In [1]:
import pandas as pd
from scipy.optimize import curve_fit
import seaborn
seaborn.set(style='whitegrid')
import numpy as np
import matplotlib.pyplot as plt
%matplotlib qt
# %matplotlib inline
from datetime import datetime, date

C:\Users\etiirine\Anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
C:\Users\etiirine\Anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [2]:
#read in the data
df= pd.read_csv("N2 injection volume calibration_series 2", sep='\t', index_col=False)
df.drop(columns=["Live comments","I_emission","I_grid","T-platinum","T-CERNOX","helium"], inplace=True)
#df.drop(columns=['Threshold'], inplace=True)
#df.drop(labels=[0,1], axis=0)
df.head()

,Time,injection 100mbar,Barion_2,Barion_1,DUAL experiment,DUAL insulation,injection 1mbar
0,20/10/2022 09:40:11,-0.064045,2.530000e-09,8.500000e-10,4.996000e-09,0.000003,0.000168
1,20/10/2022 09:40:23,-0.059286,2.530000e-09,8.480000e-10,4.996000e-09,0.000003,0.000196
2,20/10/2022 09:40:35,-0.063652,2.530000e-09,8.480000e-10,4.996000e-09,0.000003,0.000195
3,20/10/2022 09:40:46,-0.062492,2.530000e-09,8.480000e-10,4.996000e-09,0.000003,0.000183
4,20/10/2022 09:40:58,-0.061581,2.530000e-09,8.500000e-10,4.996000e-09,0.000003,0.000157

,Time,injection 100mbar,Barion_2,Barion_1,DUAL experiment,DUAL insulation,injection 1mbar
0,20/10/2022 09:40:11,-0.064045,2.530000e-09,8.500000e-10,4.996000e-09,0.000003,0.000168
1,20/10/2022 09:40:23,-0.059286,2.530000e-09,8.480000e-10,4.996000e-09,0.000003,0.000196
2,20/10/2022 09:40:35,-0.063652,2.530000e-09,8.480000e-10,4.996000e-09,0.000003,0.000195
3,20/10/2022 09:40:46,-0.062492,2.530000e-09,8.480000e-10,4.996000e-09,0.000003,0.000183
4,20/10/2022 09:40:58,-0.061581,2.530000e-09,8.500000e-10,4.996000e-09,0.000003,0.000157

In [3]:
#add elapsed time

timestamps=pd.to_datetime(df["Time"],format="%d/%m/%Y %H:%M:%S")
runtime=(timestamps-timestamps[0]).dt.total_seconds()    
df.insert(1,"Elapsed time",runtime)

In [4]:
df.head()

,Time,Elapsed time,injection 100mbar,Barion_2,Barion_1,DUAL experiment,DUAL insulation,injection 1mbar
0,20/10/2022 09:40:11,0.0,-0.064045,2.530000e-09,8.500000e-10,4.996000e-09,0.000003,0.000168
1,20/10/2022 09:40:23,12.0,-0.059286,2.530000e-09,8.480000e-10,4.996000e-09,0.000003,0.000196
2,20/10/2022 09:40:35,24.0,-0.063652,2.530000e-09,8.480000e-10,4.996000e-09,0.000003,0.000195
3,20/10/2022 09:40:46,35.0,-0.062492,2.530000e-09,8.480000e-10,4.996000e-09,0.000003,0.000183
4,20/10/2022 09:40:58,47.0,-0.061581,2.530000e-09,8.500000e-10,4.996000e-09,0.000003,0.000157

,Time,Elapsed time,injection 100mbar,Barion_2,Barion_1,DUAL experiment,DUAL insulation,injection 1mbar
0,20/10/2022 09:40:11,0.0,-0.064045,2.530000e-09,8.500000e-10,4.996000e-09,0.000003,0.000168
1,20/10/2022 09:40:23,12.0,-0.059286,2.530000e-09,8.480000e-10,4.996000e-09,0.000003,0.000196
2,20/10/2022 09:40:35,24.0,-0.063652,2.530000e-09,8.480000e-10,4.996000e-09,0.000003,0.000195
3,20/10/2022 09:40:46,35.0,-0.062492,2.530000e-09,8.480000e-10,4.996000e-09,0.000003,0.000183
4,20/10/2022 09:40:58,47.0,-0.061581,2.530000e-09,8.500000e-10,4.996000e-09,0.000003,0.000157

In [5]:
#Plotting the general pressure evolution for overview
plt.figure()
plt.plot((df["Elapsed time"]/3600),df['Barion_1'],marker=".", markersize=5,label='BA1')
plt.plot((df["Elapsed time"]/3600),df['Barion_2'],marker=".", markersize=5,label='BA2')
plt.plot((df["Elapsed time"]/3600),df['injection 1mbar'],marker=".", markersize=5,label='1.1 F-R')
plt.xlabel('Elapsed time (h)')
plt.ylabel('Pressure (mbar)')
plt.legend()
plt.title("Pressure evolution")
plt.yscale('log')

In [6]:
#Disregarding all unnecesessary data before injection
x=0.269*3600
y=1.913*3600
print("Value of Elapsed time at the first relevant datapoint",x)
#find the index of this value
print(df.iloc[(df['Elapsed time'] - x).abs().argsort(),:])
print("Value of Elapsed time at the last relevant datapoint",x)
#find the index of this value
print(df.iloc[(df['Elapsed time'] - y).abs().argsort(),:])

Value of Elapsed time at the first relevant datapoint 968.4000000000001
                    Time  Elapsed time  injection 100mbar      Barion_2  \
83   20/10/2022 09:56:19         968.0          -0.061679  4.140000e-06
84   20/10/2022 09:56:31         980.0          -0.063798  7.210000e-06
82   20/10/2022 09:56:07         956.0          -0.064415  3.940000e-06
85   20/10/2022 09:56:42         991.0          -0.060296  7.300000e-06
81   20/10/2022 09:55:56         945.0          -0.064242  3.290000e-06
..                   ...           ...                ...           ...
802  20/10/2022 12:16:03        9352.0          -0.063577  5.040000e-09
803  20/10/2022 12:16:15        9364.0          -0.063798  5.030000e-09
804  20/10/2022 12:16:27        9376.0          -0.063354  5.020000e-09
805  20/10/2022 12:16:38        9387.0          -0.063059  5.020000e-09
806  20/10/2022 12:16:50        9399.0          -0.063848  5.010000e-09

         Barion_1  DUAL experiment  DUAL insulation  injection 1mbar
83   9.190000e-07     3.804000e-06         0.000003         1.018400
84   1.610000e-06     7.085000e-06         0.000003         1.006500
82   8.770000e-07     3.687000e-06         0.000003         1.026300
85   1.630000e-06     7.102000e-06         0.000003         0.994580
81   7.390000e-07     3.021000e-06         0.000003         1.032900
..            ...              ...              ...              ...
802  1.520000e-09     4.996000e-09         0.000003         0.000294
803  1.510000e-09     4.996000e-09         0.000003         0.000274
804  1.510000e-09     4.996000e-09         0.000003         0.000293
805  1.510000e-09     4.996000e-09         0.000003         0.000290
806  1.510000e-09     4.996000e-09         0.000003         0.000293

[807 rows x 8 columns]
Value of Elapsed time at the last relevant datapoint 968.4000000000001
                    Time  Elapsed time  injection 100mbar      Barion_2  \
591  20/10/2022 11:35:03        6892.0          -0.059953  1.500000e-08
590  20/10/2022 11:34:51        6880.0          -0.063404  1.510000e-08
592  20/10/2022 11:35:15        6904.0          -0.063652  1.480000e-08
589  20/10/2022 11:34:40        6869.0          -0.063404  1.520000e-08
593  20/10/2022 11:35:26        6915.0          -0.063601  1.470000e-08
..                   ...           ...                ...           ...
4    20/10/2022 09:40:58          47.0          -0.061581  2.530000e-09
3    20/10/2022 09:40:46          35.0          -0.062492  2.530000e-09
2    20/10/2022 09:40:35          24.0          -0.063652  2.530000e-09
1    20/10/2022 09:40:23          12.0          -0.059286  2.530000e-09
0    20/10/2022 09:40:11           0.0          -0.064045  2.530000e-09

         Barion_1  DUAL experiment  DUAL insulation  injection 1mbar
591  3.760000e-09     8.710000e-09         0.000003         0.001317
590  3.790000e-09     8.826000e-09         0.000003         0.001314
592  3.730000e-09     8.773000e-09         0.000003         0.001301
589  3.830000e-09     8.868000e-09         0.000003         0.001344
593  3.690000e-09     8.504000e-09         0.000003         0.001278
..            ...              ...              ...              ...
4    8.500000e-10     4.996000e-09         0.000003         0.000157
3    8.480000e-10     4.996000e-09         0.000003         0.000183
2    8.480000e-10     4.996000e-09         0.000003         0.000195
1    8.480000e-10     4.996000e-09         0.000003         0.000196
0    8.500000e-10     4.996000e-09         0.000003         0.000168

[807 rows x 8 columns]
Value of Elapsed time at the first relevant datapoint 968.4000000000001
                    Time  Elapsed time  injection 100mbar      Barion_2  \
83   20/10/2022 09:56:19         968.0          -0.061679  4.140000e-06
84   20/10/2022 09:56:31         980.0          -0.063798  7.210000e-06
82   20/10/2022 09:56:07         956.0          -0.064415  3.940000e-06
85   20/10/2022 09:56:42         991.0          -0.060296  7.300000e-06
81   20/10/2022 09:55:56         945.0          -0.064242  3.290000e-06
..                   ...           ...                ...           ...
802  20/10/2022 12:16:03        9352.0          -0.063577  5.040000e-09
803  20/10/2022 12:16:15        9364.0          -0.063798  5.030000e-09
804  20/10/2022 12:16:27        9376.0          -0.063354  5.020000e-09
805  20/10/2022 12:16:38        9387.0          -0.063059  5.020000e-09
806  20/10/2022 12:16:50        9399.0          -0.063848  5.010000e-09

         Barion_1  DUAL experiment  DUAL insulation  injection 1mbar
83   9.190000e-07     3.804000e-06         0.000003         1.018400
84   1.610000e-06     7.085000e-06         0.000003         1.006500
82   8.770000e-07     3.687000e-06         0.000003         1.026300
85   1.630000e-06     7.102000e-06         0.000003         0.994580
81   7.390000e-07     3.021000e-06         0.000003         1.032900
..            ...              ...              ...              ...
802  1.520000e-09     4.996000e-09         0.000003         0.000294
803  1.510000e-09     4.996000e-09         0.000003         0.000274
804  1.510000e-09     4.996000e-09         0.000003         0.000293
805  1.510000e-09     4.996000e-09         0.000003         0.000290
806  1.510000e-09     4.996000e-09         0.000003         0.000293

[807 rows x 8 columns]
Value of Elapsed time at the last relevant datapoint 968.4000000000001
                    Time  Elapsed time  injection 100mbar      Barion_2  \
591  20/10/2022 11:35:03        6892.0          -0.059953  1.500000e-08
590  20/10/2022 11:34:51        6880.0          -0.063404  1.510000e-08
592  20/10/2022 11:35:15        6904.0          -0.063652  1.480000e-08
589  20/10/2022 11:34:40        6869.0          -0.063404  1.520000e-08
593  20/10/2022 11:35:26        6915.0          -0.063601  1.470000e-08
..                   ...           ...                ...           ...
4    20/10/2022 09:40:58          47.0          -0.061581  2.530000e-09
3    20/10/2022 09:40:46          35.0          -0.062492  2.530000e-09
2    20/10/2022 09:40:35          24.0          -0.063652  2.530000e-09
1    20/10/2022 09:40:23          12.0          -0.059286  2.530000e-09
0    20/10/2022 09:40:11           0.0          -0.064045  2.530000e-09

         Barion_1  DUAL experiment  DUAL insulation  injection 1mbar
591  3.760000e-09     8.710000e-09         0.000003         0.001317
590  3.790000e-09     8.826000e-09         0.000003         0.001314
592  3.730000e-09     8.773000e-09         0.000003         0.001301
589  3.830000e-09     8.868000e-09         0.000003         0.001344
593  3.690000e-09     8.504000e-09         0.000003         0.001278
..            ...              ...              ...              ...
4    8.500000e-10     4.996000e-09         0.000003         0.000157
3    8.480000e-10     4.996000e-09         0.000003         0.000183
2    8.480000e-10     4.996000e-09         0.000003         0.000195
1    8.480000e-10     4.996000e-09         0.000003         0.000196
0    8.500000e-10     4.996000e-09         0.000003         0.000168

[807 rows x 8 columns]

In [7]:
#New sub-dataset with relevant data
inj = df.iloc[84:592]
inj.tail()

,Time,Elapsed time,injection 100mbar,Barion_2,Barion_1,DUAL experiment,DUAL insulation,injection 1mbar
587,20/10/2022 11:34:16,6845.0,-0.063723,1.560000e-08,3.890000e-09,9.106000e-09,0.000003,0.001400
588,20/10/2022 11:34:28,6857.0,-0.061530,1.540000e-08,3.860000e-09,9.041000e-09,0.000003,0.001362
589,20/10/2022 11:34:40,6869.0,-0.063404,1.520000e-08,3.830000e-09,8.868000e-09,0.000003,0.001344
590,20/10/2022 11:34:51,6880.0,-0.063404,1.510000e-08,3.790000e-09,8.826000e-09,0.000003,0.001314
591,20/10/2022 11:35:03,6892.0,-0.059953,1.500000e-08,3.760000e-09,8.710000e-09,0.000003,0.001317

,Time,Elapsed time,injection 100mbar,Barion_2,Barion_1,DUAL experiment,DUAL insulation,injection 1mbar
587,20/10/2022 11:34:16,6845.0,-0.063723,1.560000e-08,3.890000e-09,9.106000e-09,0.000003,0.001400
588,20/10/2022 11:34:28,6857.0,-0.061530,1.540000e-08,3.860000e-09,9.041000e-09,0.000003,0.001362
589,20/10/2022 11:34:40,6869.0,-0.063404,1.520000e-08,3.830000e-09,8.868000e-09,0.000003,0.001344
590,20/10/2022 11:34:51,6880.0,-0.063404,1.510000e-08,3.790000e-09,8.826000e-09,0.000003,0.001314
591,20/10/2022 11:35:03,6892.0,-0.059953,1.500000e-08,3.760000e-09,8.710000e-09,0.000003,0.001317

In [8]:
#New graph
plt.figure()
plt.plot((inj["Elapsed time"]/3600),inj['Barion_1'],marker=".", markersize=5,label='BA1')
plt.plot((inj["Elapsed time"]/3600),inj['Barion_2'],marker=".", markersize=5,label='BA2')
plt.plot((inj["Elapsed time"]/3600),inj['injection 1mbar'],marker=".", markersize=5,label='1.1 F-R')
plt.xlabel('Elapsed time (h)')
plt.ylabel('Pressure (mbar)')
plt.legend()
plt.title("Pressure evolution during injection")
plt.yscale('log')

## Procedure for the calculation
#### Assumptions
1) Barion gauges' manufacturer made calibrations are valid <br/>
2) The EGA support bearing has minimal conductivity <br/>
3) The distribution of gas molecules in the vessel in homogeneous <br/>
4) Conductance of the calibrated orifice is the limiting factor for achieving pressure equilibrium between the injection volume and experimental chamber <br/>
4) Use Barion_1 gauge as the closest to the turbo and orifice

In [9]:
# Conductance (N2) for the calibrated orifice [l/s]
c_orif=10.13
#Bolzman constant [m2 kg s^-2 K^-1] 
k_B=1.38e-23
#Temperature [K]
T=273+21
#Time amount for achieving equilibrium + pressure delta

In [10]:
#hand calculated example
V=10.13*3.92e-5/(0.05/9)
print(V)

0.07147727999999999
0.07147727999999999

### Formula for calculating injection volume
$$V[l]\cdot \frac{dp}{dt}[\frac{mbar}{s}]=C_{orif}[\frac{l}{s}]\cdot \Delta(Ba_2-Ba_1)[mbar]$$

In [11]:
#V*dp/dt=C(delta(Ba2-Ba1))
#algorithm: for every two consecutive datapoints, take the delta for I-injection and the two relative timestamps
#and the difference of Ba2-Ba1
inj["Time diff"]=inj["Elapsed time"].diff()
inj["p-dif fr"]=abs(inj["injection 1mbar"].diff())
inj["p-dif baryon"]=inj["Barion_2"]-inj["Barion_1"]

C:\Users\etiirine\AppData\Local\Temp\ipykernel_13960\1100470889.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inj["Time diff"]=inj["Elapsed time"].diff()
C:\Users\etiirine\AppData\Local\Temp\ipykernel_13960\1100470889.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inj["p-dif fr"]=abs(inj["injection 1mbar"].diff())
C:\Users\etiirine\AppData\Local\Temp\ipykernel_13960\1100470889.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inj["p-dif baryon"]=inj["Barion_2"]-inj["Barion_1"]
C:\Users\etiirine\AppData\Local\Temp\ipykernel_13960\1100470889.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inj["Time diff"]=inj["Elapsed time"].diff()
C:\Users\etiirine\AppData\Local\Temp\ipykernel_13960\1100470889.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inj["p-dif fr"]=abs(inj["injection 1mbar"].diff())
C:\Users\etiirine\AppData\Local\Temp\ipykernel_13960\1100470889.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inj["p-dif baryon"]=inj["Barion_2"]-inj["Barion_1"]

In [12]:
#subtracting background signal
bck=df["Barion_2"].nsmallest(10).mean()-df["Barion_1"].nsmallest(10).mean()
inj.insert(11,"p-dif bar - Background",inj["p-dif baryon"]-bck)

In [13]:
inj.head()

,Time,Elapsed time,injection 100mbar,Barion_2,Barion_1,DUAL experiment,DUAL insulation,injection 1mbar,Time diff,p-dif fr,p-dif baryon,p-dif bar - Background
84,20/10/2022 09:56:31,980.0,-0.063798,0.000007,0.000002,0.000007,0.000003,1.00650,NaN,NaN,0.000006,0.000006
85,20/10/2022 09:56:42,991.0,-0.060296,0.000007,0.000002,0.000007,0.000003,0.99458,11.0,0.01192,0.000006,0.000006
86,20/10/2022 09:56:54,1003.0,-0.060296,0.000007,0.000002,0.000007,0.000003,0.98282,12.0,0.01176,0.000006,0.000006
87,20/10/2022 09:57:06,1015.0,-0.063133,0.000007,0.000002,0.000007,0.000003,0.97119,12.0,0.01163,0.000006,0.000006
88,20/10/2022 09:57:17,1026.0,-0.064635,0.000007,0.000002,0.000007,0.000003,0.95969,11.0,0.01150,0.000006,0.000006

,Time,Elapsed time,injection 100mbar,Barion_2,Barion_1,DUAL experiment,DUAL insulation,injection 1mbar,Time diff,p-dif fr,p-dif baryon,p-dif bar - Background
84,20/10/2022 09:56:31,980.0,-0.063798,0.000007,0.000002,0.000007,0.000003,1.00650,NaN,NaN,0.000006,0.000006
85,20/10/2022 09:56:42,991.0,-0.060296,0.000007,0.000002,0.000007,0.000003,0.99458,11.0,0.01192,0.000006,0.000006
86,20/10/2022 09:56:54,1003.0,-0.060296,0.000007,0.000002,0.000007,0.000003,0.98282,12.0,0.01176,0.000006,0.000006
87,20/10/2022 09:57:06,1015.0,-0.063133,0.000007,0.000002,0.000007,0.000003,0.97119,12.0,0.01163,0.000006,0.000006
88,20/10/2022 09:57:17,1026.0,-0.064635,0.000007,0.000002,0.000007,0.000003,0.95969,11.0,0.01150,0.000006,0.000006

In [14]:
inj["Inj_V"]=10.13*inj["p-dif bar - Background"]/(inj["p-dif fr"]/inj["Time diff"])

C:\Users\etiirine\AppData\Local\Temp\ipykernel_13960\3911160995.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inj["Inj_V"]=10.13*inj["p-dif bar - Background"]/(inj["p-dif fr"]/inj["Time diff"])
C:\Users\etiirine\AppData\Local\Temp\ipykernel_13960\3911160995.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inj["Inj_V"]=10.13*inj["p-dif bar - Background"]/(inj["p-dif fr"]/inj["Time diff"])

In [15]:
inj.head()

,Time,Elapsed time,injection 100mbar,Barion_2,Barion_1,DUAL experiment,DUAL insulation,injection 1mbar,Time diff,p-dif fr,p-dif baryon,p-dif bar - Background,Inj_V
84,20/10/2022 09:56:31,980.0,-0.063798,0.000007,0.000002,0.000007,0.000003,1.00650,NaN,NaN,0.000006,0.000006,NaN
85,20/10/2022 09:56:42,991.0,-0.060296,0.000007,0.000002,0.000007,0.000003,0.99458,11.0,0.01192,0.000006,0.000006,0.052988
86,20/10/2022 09:56:54,1003.0,-0.060296,0.000007,0.000002,0.000007,0.000003,0.98282,12.0,0.01176,0.000006,0.000006,0.058695
87,20/10/2022 09:57:06,1015.0,-0.063133,0.000007,0.000002,0.000007,0.000003,0.97119,12.0,0.01163,0.000006,0.000006,0.059038
88,20/10/2022 09:57:17,1026.0,-0.064635,0.000007,0.000002,0.000007,0.000003,0.95969,11.0,0.01150,0.000006,0.000006,0.054245

,Time,Elapsed time,injection 100mbar,Barion_2,Barion_1,DUAL experiment,DUAL insulation,injection 1mbar,Time diff,p-dif fr,p-dif baryon,p-dif bar - Background,Inj_V
84,20/10/2022 09:56:31,980.0,-0.063798,0.000007,0.000002,0.000007,0.000003,1.00650,NaN,NaN,0.000006,0.000006,NaN
85,20/10/2022 09:56:42,991.0,-0.060296,0.000007,0.000002,0.000007,0.000003,0.99458,11.0,0.01192,0.000006,0.000006,0.052988
86,20/10/2022 09:56:54,1003.0,-0.060296,0.000007,0.000002,0.000007,0.000003,0.98282,12.0,0.01176,0.000006,0.000006,0.058695
87,20/10/2022 09:57:06,1015.0,-0.063133,0.000007,0.000002,0.000007,0.000003,0.97119,12.0,0.01163,0.000006,0.000006,0.059038
88,20/10/2022 09:57:17,1026.0,-0.064635,0.000007,0.000002,0.000007,0.000003,0.95969,11.0,0.01150,0.000006,0.000006,0.054245

In [16]:
is_inf=inj["Inj_V"].iloc[:] == np.inf
ar=np.asarray(inj["Inj_V"].iloc[:], dtype=np.float)
ar=ar[np.isfinite(ar)]
print(ar)
avg=ar.mean()

print("Average inj volume with valve 2 open and not accounting for residual signal",avg,"l")

[0.05298834 0.05869529 0.05903782 0.05424529 0.05937094 0.05930313
 0.05464311 0.05970868 0.05931416 0.05507267 0.05984683 0.05994857
 0.05489263 0.05987239 0.060158   0.05469951 0.06002265 0.06019921
 0.0551201  0.06018707 0.06037119 0.05515988 0.06023167 0.060424
 0.05538504 0.05974316 0.06034338 0.05530925 0.06019495 0.0600461
 0.05523016 0.06031825 0.06031265 0.05548526 0.06015295 0.06044892
 0.05547824 0.06028629 0.06020169 0.05554331 0.06003041 0.05986011
 0.05538498 0.05959612 0.06092206 0.05483167 0.06069839 0.06036463
 0.05534607 0.06093074 0.06002717 0.05587356 0.06048856 0.05983657
 0.05526929 0.06019269 0.06049403 0.06017751 0.05508357 0.06038328
 0.06047959 0.05521282 0.06043162 0.05501031 0.06010558 0.06093976
 0.06026322 0.05513606 0.06065238 0.05518214 0.06037374 0.06055502
 0.06004085 0.05541786 0.06028516 0.06011107 0.05540644 0.06061361
 0.05565293 0.06063526 0.06019837 0.05536398 0.06008104 0.06068126
 0.05542579 0.06067881 0.05961413 0.05585256 0.06084606 0.06076038
 0.05524595 0.06000226 0.06061078 0.05550319 0.06039467 0.06122636
 0.05586819 0.0594565  0.06028105 0.05644547 0.06014207 0.06065813
 0.05609742 0.06018468 0.05987409 0.05524898 0.06064998 0.06015526
 0.05612727 0.05999333 0.05966341 0.05589912 0.06004165 0.05558525
 0.05949659 0.05951487 0.05580006 0.06007537 0.05966585 0.05468345
 0.06070984 0.06113614 0.05464405 0.06154286 0.06022756 0.05460951
 0.05994519 0.06038484 0.05534865 0.0598704  0.06079522 0.05316348
 0.06249687 0.05945531 0.05536572 0.06135338 0.05930741 0.05596728
 0.06180559 0.06016803 0.05533968 0.05849134 0.06135025 0.05619361
 0.06012873 0.06034378 0.05526094 0.06074029 0.05923564 0.05584238
 0.060497   0.05865392 0.05672022 0.06182969 0.05918735 0.05383795
 0.06054081 0.05911957 0.05744473 0.05914063 0.05972111 0.05522601
 0.05976032 0.06066061 0.05717251 0.05861174 0.05991954 0.05546191
 0.0599036  0.06049511 0.05426574 0.06128547 0.05863687 0.05581375
 0.06047778 0.05965643 0.05512484 0.05732125 0.06196193 0.05486499
 0.05751481 0.06135768 0.05426645 0.06076333 0.05206956 0.06038401
 0.06260544 0.05538647 0.05964237 0.06116734 0.05528047 0.05949983
 0.05874091 0.054837   0.05965504 0.05637728 0.05475198 0.05907517
 0.06003371 0.05487029 0.0570093  0.05927001 0.05553224 0.06027945
 0.06118937 0.05299361 0.06075739 0.06334397 0.05605114 0.06108528
 0.05858867 0.05437117 0.05890849 0.05837532 0.05518517 0.06234402
 0.05874761 0.05509864 0.05876402 0.05640391 0.05193861 0.06338357
 0.05830132 0.05554926 0.05968221 0.06321128 0.05590861 0.05902648
 0.06540358 0.0541409  0.06108693 0.05791451 0.05632404 0.05872655
 0.05843729 0.05813569 0.06031477 0.06264528 0.05462599 0.0598889
 0.06411593 0.05786595 0.06288144 0.0656641  0.05504065 0.06130285
 0.05571892 0.04902247 0.05121713 0.06065488 0.05847332 0.07692783
 0.05711421 0.05353899 0.06059917 0.05900241 0.06027189 0.06595759
 0.06008273 0.05699924 0.05466144 0.06189983 0.05295632 0.0680796
 0.05744792 0.06982619 0.06631425 0.05699138 0.05960834 0.05644397
 0.06404387 0.05658602 0.05652417 0.0658624  0.05267183 0.06115656
 0.05883519 0.0546488  0.06222451 0.06339422 0.05177309 0.06218305
 0.05439146 0.05485467 0.0660352  0.05009141 0.05832158 0.05968543
 0.05151941 0.06123791 0.061865   0.06189626 0.05564843 0.06371413
 0.0719198  0.0495835  0.05880831 0.05729248 0.08834205 0.05385771
 0.05244309 0.06542506 0.0581535  0.05366108 0.06783891 0.06792902
 0.05075754 0.06535543 0.06227257 0.05663396 0.07048215 0.04879439
 0.06370823 0.06120807 0.05817826 0.04718049 0.06438714 0.06090074
 0.06567211 0.06699476 0.05306816 0.05266347 0.07323147 0.05445239
 0.08249804 0.04873208 0.0568181  0.06799011 0.06351709 0.06417051
 0.05853709 0.05465463 0.06508691 0.05979182 0.06388769 0.05890291
 0.0626944  0.05029649 0.06100829 0.05935617 0.06766054 0.05251663
 0.07601855 0.04857494 0.05459396 0.07472068 0.05766111 0.05274862
 0.07437497 0.0452705  0.04743767 0.07143727 0.06311013 0.05298948
 0.06004559 0.07067642 0.04812584 0.09320627 0.04017777 0.05975115
 0.09356148 0.04622022 0.07040672 0.07635153 0.06044313 0.05013532
 0.04423343 0.07794777 0.05775374 0.06052753 0.06717396 0.08020043
 0.07741295 0.0489397  0.08144125 0.05631486 0.06157582 0.04804239
 0.06900721 0.04862634 0.06679532 0.07334407 0.04284097 0.07069547
 0.07057487 0.05928731 0.06780701 0.06611343 0.03051592 0.12279469
 0.06103183 0.04413896 0.0495635  0.11226732 0.05469507 0.05846461
 0.05712944 0.11004936 0.04325758 0.05976646 0.07216517 0.0531302
 0.03559167 0.07880764 0.06327025 0.09999625 0.0497337  0.04669651
 0.09954766 0.09663358 0.04644883 0.04810748 0.08000494 0.06458111
 0.07145014 0.09028992 0.04173301 0.08753072 0.04912903 0.03796974
 0.0790744  0.07739087 0.08924367 0.0629428  0.0596394  0.05010878
 0.08918    0.06881394 0.0743175  0.03961154 0.0857189  0.27959373
 0.03265321 0.06458861 0.07828097 0.06213364 0.06736106 0.07035712
 0.88708229 0.05582223 0.05582598 0.0489116  0.03000728 0.08853691
 0.1120882  0.06712391 0.05768509 0.06215126 0.05752225 0.07766311
 0.05613028 0.11426944 0.06326738 0.05900154 0.78451785 0.05203613
 0.04687603 0.05030413 0.04881567 0.06801872 0.13824441 0.03130839
 0.13514538 0.04710865 0.06378051 0.04415879 0.2257997  0.04508865
 0.07035696 0.13666751 1.18322452 0.03602087 0.04365766 0.12447127
 0.02383548 0.04117696 0.08616588 0.08609082 0.06180697 0.09381929
 0.07482842 0.11123174 0.04338665 0.0882307  0.04419242 0.98872852
 0.03574823 0.80232977 0.03762426 0.26312262 0.03930383 0.16623696
 0.0367361  0.04008377 0.17458174 0.40420599 0.03714314 0.09440295
 0.07000285 0.0700915  0.55884931 0.03137807 0.06437034 0.03601096
 0.36317949]
Average inj volume with valve 2 open and not accounting for residual signal 0.07312294876942818 l

C:\Users\etiirine\AppData\Local\Temp\ipykernel_13960\339711741.py:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  ar=np.asarray(inj["Inj_V"].iloc[:], dtype=np.float)

[0.05298834 0.05869529 0.05903782 0.05424529 0.05937094 0.05930313
 0.05464311 0.05970868 0.05931416 0.05507267 0.05984683 0.05994857
 0.05489263 0.05987239 0.060158   0.05469951 0.06002265 0.06019921
 0.0551201  0.06018707 0.06037119 0.05515988 0.06023167 0.060424
 0.05538504 0.05974316 0.06034338 0.05530925 0.06019495 0.0600461
 0.05523016 0.06031825 0.06031265 0.05548526 0.06015295 0.06044892
 0.05547824 0.06028629 0.06020169 0.05554331 0.06003041 0.05986011
 0.05538498 0.05959612 0.06092206 0.05483167 0.06069839 0.06036463
 0.05534607 0.06093074 0.06002717 0.05587356 0.06048856 0.05983657
 0.05526929 0.06019269 0.06049403 0.06017751 0.05508357 0.06038328
 0.06047959 0.05521282 0.06043162 0.05501031 0.06010558 0.06093976
 0.06026322 0.05513606 0.06065238 0.05518214 0.06037374 0.06055502
 0.06004085 0.05541786 0.06028516 0.06011107 0.05540644 0.06061361
 0.05565293 0.06063526 0.06019837 0.05536398 0.06008104 0.06068126
 0.05542579 0.06067881 0.05961413 0.05585256 0.06084606 0.06076038
 0.05524595 0.06000226 0.06061078 0.05550319 0.06039467 0.06122636
 0.05586819 0.0594565  0.06028105 0.05644547 0.06014207 0.06065813
 0.05609742 0.06018468 0.05987409 0.05524898 0.06064998 0.06015526
 0.05612727 0.05999333 0.05966341 0.05589912 0.06004165 0.05558525
 0.05949659 0.05951487 0.05580006 0.06007537 0.05966585 0.05468345
 0.06070984 0.06113614 0.05464405 0.06154286 0.06022756 0.05460951
 0.05994519 0.06038484 0.05534865 0.0598704  0.06079522 0.05316348
 0.06249687 0.05945531 0.05536572 0.06135338 0.05930741 0.05596728
 0.06180559 0.06016803 0.05533968 0.05849134 0.06135025 0.05619361
 0.06012873 0.06034378 0.05526094 0.06074029 0.05923564 0.05584238
 0.060497   0.05865392 0.05672022 0.06182969 0.05918735 0.05383795
 0.06054081 0.05911957 0.05744473 0.05914063 0.05972111 0.05522601
 0.05976032 0.06066061 0.05717251 0.05861174 0.05991954 0.05546191
 0.0599036  0.06049511 0.05426574 0.06128547 0.05863687 0.05581375
 0.06047778 0.05965643 0.05512484 0.05732125 0.06196193 0.05486499
 0.05751481 0.06135768 0.05426645 0.06076333 0.05206956 0.06038401
 0.06260544 0.05538647 0.05964237 0.06116734 0.05528047 0.05949983
 0.05874091 0.054837   0.05965504 0.05637728 0.05475198 0.05907517
 0.06003371 0.05487029 0.0570093  0.05927001 0.05553224 0.06027945
 0.06118937 0.05299361 0.06075739 0.06334397 0.05605114 0.06108528
 0.05858867 0.05437117 0.05890849 0.05837532 0.05518517 0.06234402
 0.05874761 0.05509864 0.05876402 0.05640391 0.05193861 0.06338357
 0.05830132 0.05554926 0.05968221 0.06321128 0.05590861 0.05902648
 0.06540358 0.0541409  0.06108693 0.05791451 0.05632404 0.05872655
 0.05843729 0.05813569 0.06031477 0.06264528 0.05462599 0.0598889
 0.06411593 0.05786595 0.06288144 0.0656641  0.05504065 0.06130285
 0.05571892 0.04902247 0.05121713 0.06065488 0.05847332 0.07692783
 0.05711421 0.05353899 0.06059917 0.05900241 0.06027189 0.06595759
 0.06008273 0.05699924 0.05466144 0.06189983 0.05295632 0.0680796
 0.05744792 0.06982619 0.06631425 0.05699138 0.05960834 0.05644397
 0.06404387 0.05658602 0.05652417 0.0658624  0.05267183 0.06115656
 0.05883519 0.0546488  0.06222451 0.06339422 0.05177309 0.06218305
 0.05439146 0.05485467 0.0660352  0.05009141 0.05832158 0.05968543
 0.05151941 0.06123791 0.061865   0.06189626 0.05564843 0.06371413
 0.0719198  0.0495835  0.05880831 0.05729248 0.08834205 0.05385771
 0.05244309 0.06542506 0.0581535  0.05366108 0.06783891 0.06792902
 0.05075754 0.06535543 0.06227257 0.05663396 0.07048215 0.04879439
 0.06370823 0.06120807 0.05817826 0.04718049 0.06438714 0.06090074
 0.06567211 0.06699476 0.05306816 0.05266347 0.07323147 0.05445239
 0.08249804 0.04873208 0.0568181  0.06799011 0.06351709 0.06417051
 0.05853709 0.05465463 0.06508691 0.05979182 0.06388769 0.05890291
 0.0626944  0.05029649 0.06100829 0.05935617 0.06766054 0.05251663
 0.07601855 0.04857494 0.05459396 0.07472068 0.05766111 0.05274862
 0.07437497 0.0452705  0.04743767 0.07143727 0.06311013 0.05298948
 0.06004559 0.07067642 0.04812584 0.09320627 0.04017777 0.05975115
 0.09356148 0.04622022 0.07040672 0.07635153 0.06044313 0.05013532
 0.04423343 0.07794777 0.05775374 0.06052753 0.06717396 0.08020043
 0.07741295 0.0489397  0.08144125 0.05631486 0.06157582 0.04804239
 0.06900721 0.04862634 0.06679532 0.07334407 0.04284097 0.07069547
 0.07057487 0.05928731 0.06780701 0.06611343 0.03051592 0.12279469
 0.06103183 0.04413896 0.0495635  0.11226732 0.05469507 0.05846461
 0.05712944 0.11004936 0.04325758 0.05976646 0.07216517 0.0531302
 0.03559167 0.07880764 0.06327025 0.09999625 0.0497337  0.04669651
 0.09954766 0.09663358 0.04644883 0.04810748 0.08000494 0.06458111
 0.07145014 0.09028992 0.04173301 0.08753072 0.04912903 0.03796974
 0.0790744  0.07739087 0.08924367 0.0629428  0.0596394  0.05010878
 0.08918    0.06881394 0.0743175  0.03961154 0.0857189  0.27959373
 0.03265321 0.06458861 0.07828097 0.06213364 0.06736106 0.07035712
 0.88708229 0.05582223 0.05582598 0.0489116  0.03000728 0.08853691
 0.1120882  0.06712391 0.05768509 0.06215126 0.05752225 0.07766311
 0.05613028 0.11426944 0.06326738 0.05900154 0.78451785 0.05203613
 0.04687603 0.05030413 0.04881567 0.06801872 0.13824441 0.03130839
 0.13514538 0.04710865 0.06378051 0.04415879 0.2257997  0.04508865
 0.07035696 0.13666751 1.18322452 0.03602087 0.04365766 0.12447127
 0.02383548 0.04117696 0.08616588 0.08609082 0.06180697 0.09381929
 0.07482842 0.11123174 0.04338665 0.0882307  0.04419242 0.98872852
 0.03574823 0.80232977 0.03762426 0.26312262 0.03930383 0.16623696
 0.0367361  0.04008377 0.17458174 0.40420599 0.03714314 0.09440295
 0.07000285 0.0700915  0.55884931 0.03137807 0.06437034 0.03601096
 0.36317949]
Average inj volume with valve 2 open and not accounting for residual signal 0.07312294876942818 l

C:\Users\etiirine\AppData\Local\Temp\ipykernel_13960\339711741.py:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  ar=np.asarray(inj["Inj_V"].iloc[:], dtype=np.float)

In [17]:
#plotting inj volume
plt.figure()
plt.plot((inj["Elapsed time"]/3600),inj['Inj_V'],marker=".", markersize=5,label='inj volume')
plt.xlabel('Elapsed time (h)')
plt.ylabel('inj volume (l)')
plt.legend()
plt.title("inj volume change during injection")
plt.yscale('linear')
plt.yticks([0,0.2, 0.4, 0.6, 0.8])
plt.show()
print(np.arange(0, 1, step=0.2))

[0.  0.2 0.4 0.6 0.8]
[0.  0.2 0.4 0.6 0.8]

In [18]:
#removing all values after 1hour
print(inj.iloc[(inj['Elapsed time'] - 3600).abs().argsort(),:])
inj2=inj.iloc[84:309]
inj2.describe()

                    Time  Elapsed time  injection 100mbar      Barion_2  \
309  20/10/2022 10:40:15        3604.0          -0.061235  5.040000e-07
308  20/10/2022 10:40:03        3592.0          -0.059411  5.100000e-07
310  20/10/2022 10:40:27        3616.0          -0.063059  4.970000e-07
307  20/10/2022 10:39:52        3581.0          -0.059313  5.080000e-07
311  20/10/2022 10:40:38        3627.0          -0.063699  4.920000e-07
..                   ...           ...                ...           ...
587  20/10/2022 11:34:16        6845.0          -0.063723  1.560000e-08
588  20/10/2022 11:34:28        6857.0          -0.061530  1.540000e-08
589  20/10/2022 11:34:40        6869.0          -0.063404  1.520000e-08
590  20/10/2022 11:34:51        6880.0          -0.063404  1.510000e-08
591  20/10/2022 11:35:03        6892.0          -0.059953  1.500000e-08

         Barion_1  DUAL experiment  DUAL insulation  injection 1mbar  \
309  1.120000e-07     4.238000e-07         0.000003         0.057382
308  1.130000e-07     4.289000e-07         0.000003         0.058177
310  1.100000e-07     4.198000e-07         0.000003         0.056641
307  1.140000e-07     4.336000e-07         0.000003         0.058970
311  1.090000e-07     4.128000e-07         0.000003         0.055881
..            ...              ...              ...              ...
587  3.890000e-09     9.106000e-09         0.000003         0.001400
588  3.860000e-09     9.041000e-09         0.000003         0.001362
589  3.830000e-09     8.868000e-09         0.000003         0.001344
590  3.790000e-09     8.826000e-09         0.000003         0.001314
591  3.760000e-09     8.710000e-09         0.000003         0.001317

     Time diff  p-dif fr  p-dif baryon  p-dif bar - Background     Inj_V
309       12.0  0.000795  3.920000e-07            3.903205e-07  0.059682
308       11.0  0.000793  3.970000e-07            3.953205e-07  0.055549
310       12.0  0.000741  3.870000e-07            3.853205e-07  0.063211
307       12.0  0.000818  3.940000e-07            3.923205e-07  0.058301
311       11.0  0.000760  3.830000e-07            3.813205e-07  0.055909
..         ...       ...           ...                     ...       ...
587       11.0  0.000002  1.171000e-08            1.003050e-08  0.558849
588       12.0  0.000038  1.154000e-08            9.860500e-09  0.031378
589       12.0  0.000018  1.137000e-08            9.690500e-09  0.064370
590       11.0  0.000030  1.131000e-08            9.630500e-09  0.036011
591       12.0  0.000003  1.124000e-08            9.560500e-09  0.363179

[508 rows x 13 columns]
                    Time  Elapsed time  injection 100mbar      Barion_2  \
309  20/10/2022 10:40:15        3604.0          -0.061235  5.040000e-07
308  20/10/2022 10:40:03        3592.0          -0.059411  5.100000e-07
310  20/10/2022 10:40:27        3616.0          -0.063059  4.970000e-07
307  20/10/2022 10:39:52        3581.0          -0.059313  5.080000e-07
311  20/10/2022 10:40:38        3627.0          -0.063699  4.920000e-07
..                   ...           ...                ...           ...
587  20/10/2022 11:34:16        6845.0          -0.063723  1.560000e-08
588  20/10/2022 11:34:28        6857.0          -0.061530  1.540000e-08
589  20/10/2022 11:34:40        6869.0          -0.063404  1.520000e-08
590  20/10/2022 11:34:51        6880.0          -0.063404  1.510000e-08
591  20/10/2022 11:35:03        6892.0          -0.059953  1.500000e-08

         Barion_1  DUAL experiment  DUAL insulation  injection 1mbar  \
309  1.120000e-07     4.238000e-07         0.000003         0.057382
308  1.130000e-07     4.289000e-07         0.000003         0.058177
310  1.100000e-07     4.198000e-07         0.000003         0.056641
307  1.140000e-07     4.336000e-07         0.000003         0.058970
311  1.090000e-07     4.128000e-07         0.000003         0.055881
..            ...              ...              ...              ...
587  3.890000e-09     9.106000e-09         0.000003         0.001400
588  3.860000e-09     9.041000e-09         0.000003         0.001362
589  3.830000e-09     8.868000e-09         0.000003         0.001344
590  3.790000e-09     8.826000e-09         0.000003         0.001314
591  3.760000e-09     8.710000e-09         0.000003         0.001317

     Time diff  p-dif fr  p-dif baryon  p-dif bar - Background     Inj_V
309       12.0  0.000795  3.920000e-07            3.903205e-07  0.059682
308       11.0  0.000793  3.970000e-07            3.953205e-07  0.055549
310       12.0  0.000741  3.870000e-07            3.853205e-07  0.063211
307       12.0  0.000818  3.940000e-07            3.923205e-07  0.058301
311       11.0  0.000760  3.830000e-07            3.813205e-07  0.055909
..         ...       ...           ...                     ...       ...
587       11.0  0.000002  1.171000e-08            1.003050e-08  0.558849
588       12.0  0.000038  1.154000e-08            9.860500e-09  0.031378
589       12.0  0.000018  1.137000e-08            9.690500e-09  0.064370
590       11.0  0.000030  1.131000e-08            9.630500e-09  0.036011
591       12.0  0.000003  1.124000e-08            9.560500e-09  0.363179

[508 rows x 13 columns]

,Elapsed time,injection 100mbar,Barion_2,Barion_1,DUAL experiment,DUAL insulation,injection 1mbar,Time diff,p-dif fr,p-dif baryon,p-dif bar - Background,Inj_V
count,225.000000,225.000000,2.250000e+02,2.250000e+02,2.250000e+02,2.250000e+02,225.000000,225.000000,225.000000,2.250000e+02,2.250000e+02,225.000000
mean,3265.817778,-0.061322,9.885378e-07,2.198098e-07,8.526827e-07,2.681396e-06,0.118336,11.662222,0.001546,7.687280e-07,7.670485e-07,0.058877
std,759.184906,0.001830,7.614645e-07,1.680101e-07,6.730632e-07,1.702543e-08,0.094771,0.474007,0.001195,5.934671e-07,5.934671e-07,0.004336
min,1960.000000,-0.064364,1.670000e-07,3.790000e-08,1.388000e-07,2.663000e-06,0.018465,11.000000,0.000199,1.291000e-07,1.274205e-07,0.049022
25%,2613.000000,-0.063306,3.520000e-07,7.820000e-08,2.949000e-07,2.673000e-06,0.039730,11.000000,0.000552,2.738000e-07,2.721205e-07,0.055814
50%,3266.000000,-0.060445,7.230000e-07,1.620000e-07,6.171000e-07,2.679000e-06,0.084690,12.000000,0.001154,5.610000e-07,5.593205e-07,0.059236
75%,3919.000000,-0.059655,1.480000e-06,3.300000e-07,1.272000e-06,2.686000e-06,0.177240,12.000000,0.002320,1.150000e-06,1.148320e-06,0.060681
max,4572.000000,-0.058991,2.900000e-06,6.370000e-07,2.572000e-06,2.814000e-06,0.361840,12.000000,0.004530,2.263000e-06,2.261321e-06,0.088342

,Elapsed time,injection 100mbar,Barion_2,Barion_1,DUAL experiment,DUAL insulation,injection 1mbar,Time diff,p-dif fr,p-dif baryon,p-dif bar - Background,Inj_V
count,225.000000,225.000000,2.250000e+02,2.250000e+02,2.250000e+02,2.250000e+02,225.000000,225.000000,225.000000,2.250000e+02,2.250000e+02,225.000000
mean,3265.817778,-0.061322,9.885378e-07,2.198098e-07,8.526827e-07,2.681396e-06,0.118336,11.662222,0.001546,7.687280e-07,7.670485e-07,0.058877
std,759.184906,0.001830,7.614645e-07,1.680101e-07,6.730632e-07,1.702543e-08,0.094771,0.474007,0.001195,5.934671e-07,5.934671e-07,0.004336
min,1960.000000,-0.064364,1.670000e-07,3.790000e-08,1.388000e-07,2.663000e-06,0.018465,11.000000,0.000199,1.291000e-07,1.274205e-07,0.049022
25%,2613.000000,-0.063306,3.520000e-07,7.820000e-08,2.949000e-07,2.673000e-06,0.039730,11.000000,0.000552,2.738000e-07,2.721205e-07,0.055814
50%,3266.000000,-0.060445,7.230000e-07,1.620000e-07,6.171000e-07,2.679000e-06,0.084690,12.000000,0.001154,5.610000e-07,5.593205e-07,0.059236
75%,3919.000000,-0.059655,1.480000e-06,3.300000e-07,1.272000e-06,2.686000e-06,0.177240,12.000000,0.002320,1.150000e-06,1.148320e-06,0.060681
max,4572.000000,-0.058991,2.900000e-06,6.370000e-07,2.572000e-06,2.814000e-06,0.361840,12.000000,0.004530,2.263000e-06,2.261321e-06,0.088342

In [19]:
#calculate the average again
print("Average injection volume from valve 1 to valve 2 (closed):",inj2["Inj_V"].mean())

Average injection volume from valve 1 to valve 2 (closed): 0.05887744161962795
Average injection volume from valve 1 to valve 2 (closed): 0.05887744161962795