In [69]:
import pandas as pd
import scipy.constants
from scipy.optimize import curve_fit
from scipy.integrate import quad
from sklearn.metrics import r2_score
import numpy as np
import math
import matplotlib.pyplot as plt
import matplotlib.dates as md
import matplotlib.transforms as transforms
from matplotlib.ticker import LogFormatter
import os
import fnmatch
%matplotlib qt
# %matplotlib inline
import datetime as dt
pd.set_option('display.max_rows', 100)

## Reading in the data and preparing DataFrames

#### MID

In [70]:
#read in the data
mid = pd.read_csv("MID ega middle pos.tsv", sep="\t", skiprows=lambda x: x <=11,  on_bad_lines="skip")
mid.drop([0,1], inplace=True)
print(mid.describe())
#bring the time data into a new df
time = pd.DataFrame(mid.iloc[:,0::2]) #- get every second column
print(time.describe())
#add elapsed time columns
def elapsed_time(df):
    itr = 0
    counter = len(df.columns)
    masses = [2,4,5.5,12,15,16,18,28,32,40,44]
    for i in df:
        timestamp = pd.to_datetime(df[i], format="%Y/%m/%d %H:%M:%S.%f")
        runtime = (timestamp-timestamp[2]).dt.total_seconds()
        colname = "Elapsed time, mass {}".format(masses[itr]) 
        df.insert(counter, colname, runtime)
        itr += 1
        counter += 1
    return(df)
elapsed_time(time)

time_sliced = time.iloc[:,11:].fillna(0)

#convert elapsed times in time-dataframe back to a timestamp
def h2_time(df1,df2):
    startdate = pd.to_datetime(df1.iloc[2,0],format="%Y/%m/%d %H:%M:%S.%f")
    dic= {}
    itr = 0
    masses = [2,4,12,15,16,18,28,32,40,44]
    key = "Timestamp, mass {}".format(masses[itr])
    for label,content in df2.items():
        key = "Timestamp, mass {}".format(masses[itr])
        #.strftime('%d-%m-%Y %H:%M:%S') not used
        for row in content:
            dic.setdefault(key,[]).append((startdate+dt.timedelta(milliseconds=row*1000)))
        itr += 1
    new_df = pd.DataFrame.from_dict(dic)
    return(new_df)

new_df = h2_time(time,time_sliced)
new_df

       mass 2.0_value  mass 4.0_value  mass 12.0_value  mass 16.0_value  \
count    1.342000e+03    1.342000e+03     1.342000e+03     1.342000e+03
mean     4.673327e-11    1.652835e-12     6.387419e-13     1.216852e-12
std      8.472184e-12    9.141274e-13     1.142658e-13     3.653593e-13
min      2.111490e-11    4.500000e-15     2.477000e-13     4.910000e-13
25%      4.137730e-11    1.026875e-12     5.802250e-13     1.105525e-12
50%      4.625055e-11    2.045950e-12     6.326000e-13     1.200500e-12
75%      5.173925e-11    2.302475e-12     7.035500e-13     1.323600e-12
max      1.074910e-10    5.395300e-12     1.251600e-12     1.061040e-11

       mass 18.0_value  mass 28.0_value  mass 32.0_value  mass 40.0_value  \
count     1.342000e+03     1.342000e+03     1.342000e+03     1.342000e+03
mean      2.471230e-12     4.428383e-12     4.599836e-14     1.006524e-12
std       6.172663e-13     9.175029e-13     9.938932e-15     1.226430e-12
min       1.176400e-12     4.930000e-14     3.700000e-15     0.000000e+00
25%       1.988900e-12     3.805050e-12     4.030000e-14     2.200000e-15
50%       2.505250e-12     4.497650e-12     4.680000e-14     5.600000e-15
75%       2.923125e-12     5.057600e-12     5.230000e-14     2.286000e-12
max       4.809000e-12     9.281700e-12     1.070000e-13     4.174900e-12

       mass 44.0_value
count     7.760000e+02
mean      2.567439e-12
std       6.027874e-13
min       6.998000e-13
25%       2.219175e-12
50%       2.526850e-12
75%       2.893275e-12
max       6.212200e-12
                  mass 2.0_time            mass 4.0_time  \
count                      1342                     1342
unique                     1342                     1342
top     2022/11/25 10:03:04.399  2022/11/25 10:03:04.649
freq                          1                        1

                 mass 12.0_time           mass 16.0_time  \
count                      1342                     1342
unique                     1342                     1342
top     2022/11/25 10:03:04.899  2022/11/25 10:03:05.149
freq                          1                        1

                 mass 18.0_time           mass 28.0_time  \
count                      1342                     1342
unique                     1342                     1342
top     2022/11/25 10:03:05.399  2022/11/25 10:03:05.649
freq                          1                        1

                 mass 32.0_time           mass 40.0_time  \
count                      1342                     1342
unique                     1342                     1342
top     2022/11/25 10:03:05.900  2022/11/25 10:03:06.400
freq                          1                        1

                 mass 44.0_time
count                       776
unique                      776
top     2022/11/25 10:03:08.723
freq                          1

,"Timestamp, mass 2","Timestamp, mass 4","Timestamp, mass 12","Timestamp, mass 15","Timestamp, mass 16","Timestamp, mass 18","Timestamp, mass 28"
0,2022-11-25 10:03:09.044,2022-11-25 10:03:09.044,2022-11-25 10:03:09.044,2022-11-25 10:03:09.044,2022-11-25 10:03:09.044,2022-11-25 10:03:09.044,2022-11-25 10:03:09.044
1,2022-11-25 10:03:11.366,2022-11-25 10:03:11.367,2022-11-25 10:03:11.367,2022-11-25 10:03:11.367,2022-11-25 10:03:11.366,2022-11-25 10:03:11.116,2022-11-25 10:03:09.044
2,2022-11-25 10:03:13.689,2022-11-25 10:03:13.689,2022-11-25 10:03:13.689,2022-11-25 10:03:13.690,2022-11-25 10:03:13.689,2022-11-25 10:03:13.439,2022-11-25 10:03:09.044
3,2022-11-25 10:03:16.012,2022-11-25 10:03:16.012,2022-11-25 10:03:16.012,2022-11-25 10:03:16.012,2022-11-25 10:03:16.011,2022-11-25 10:03:15.762,2022-11-25 10:03:09.044
4,2022-11-25 10:03:18.334,2022-11-25 10:03:18.334,2022-11-25 10:03:18.334,2022-11-25 10:03:18.335,2022-11-25 10:03:18.334,2022-11-25 10:03:18.334,2022-11-25 10:03:09.044
...,...,...,...,...,...,...,...
1337,2022-11-25 10:55:01.237,2022-11-25 10:55:01.237,2022-11-25 10:55:01.237,2022-11-25 10:55:01.237,2022-11-25 10:55:01.236,2022-11-25 10:55:00.987,2022-11-25 10:03:09.044
1338,2022-11-25 10:55:03.559,2022-11-25 10:55:03.559,2022-11-25 10:55:03.559,2022-11-25 10:55:03.560,2022-11-25 10:55:03.559,2022-11-25 10:55:03.309,2022-11-25 10:03:09.044
1339,2022-11-25 10:55:05.882,2022-11-25 10:55:05.882,2022-11-25 10:55:05.882,2022-11-25 10:55:05.882,2022-11-25 10:55:05.881,2022-11-25 10:55:05.882,2022-11-25 10:03:09.044
1340,2022-11-25 10:55:08.204,2022-11-25 10:55:08.204,2022-11-25 10:55:08.204,2022-11-25 10:55:08.205,2022-11-25 10:55:08.204,2022-11-25 10:55:08.204,2022-11-25 10:03:09.044
1341,2022-11-25 10:55:10.527,2022-11-25 10:55:10.527,2022-11-25 10:55:10.527,2022-11-25 10:55:10.527,2022-11-25 10:55:10.526,2022-11-25 10:55:10.277,2022-11-25 10:03:09.044

#### Vaclogger

In [71]:
#reading the Emission current, pressures
vaclog=pd.read_csv("vaclog", sep="\t")
vaclog.head()
#adding an elapsed time column
#making the column into a datetime object
vac_timestamps=pd.to_datetime(vaclog["Time"],format="%d/%m/%Y %H:%M:%S")
runtime=(vac_timestamps-vac_timestamps[0]).dt.total_seconds()    
vaclog.insert(2,"Elapsed time",runtime)
#drop index column (not necessary)
# vaclog.drop(index=vaclog.index[0], 
#         axis=0, 
#         inplace=True)
vaclog["Time"] = vac_timestamps.dt.strftime('%d-%m-%Y %H:%M:%S')
vaclog["Time"] = pd.to_datetime(vaclog["Time"],format='%d-%m-%Y %H:%M:%S')

vaclog.head()

,Live comments,Time,Elapsed time,injection 100mbar,Barion_2,Barion_1,DUAL experiment,DUAL insulation,injection 1mbar,helium,T-platinum,T-CERNOX,I_emission,I_grid
0,NaN,2022-11-25 10:02:34,0.0,-0.065205,2.530000e-09,7.720000e-10,4.996000e-09,0.000002,0.000545,0.0,-112.345,55.219,NaN,NaN
1,NaN,2022-11-25 10:02:41,7.0,-0.065079,2.500000e-09,7.630000e-10,4.996000e-09,0.000002,0.000580,0.0,-112.345,54.882,NaN,NaN
2,NaN,2022-11-25 10:02:48,14.0,-0.065967,2.470000e-09,7.490000e-10,4.996000e-09,0.000002,0.000581,0.0,-112.121,54.994,NaN,NaN
3,NaN,2022-11-25 10:02:56,22.0,-0.065055,2.450000e-09,7.520000e-10,4.996000e-09,0.000002,0.000579,0.0,-112.121,55.106,NaN,NaN
4,NaN,2022-11-25 10:03:03,29.0,-0.064906,2.430000e-09,7.490000e-10,4.996000e-09,0.000002,0.000577,0.0,-112.345,55.219,NaN,NaN

#### HiVolta log

In [72]:
#Reading in the HiVolta measurement file 
hv = pd.read_csv("hv log", sep=",")
#hv.drop(columns=["Vmon1","Vmon2","Vmon3","Vmon4","Vmon5","Vmon6","Vmon7","Vmon8","Imon3","Imon4","Imon5","Imon6","Imon7","Imon8","Comments1"], inplace=True)
hv["hv_grid"]=[element * 1e-6 for element in hv["IMon1"]]
hv["em"]=[element * 1e-6 for element in hv["IMon2"]]
hv.drop(hv.columns[hv.columns.str.contains('Unnamed',case = False)],axis = 1, inplace = True)
hv["em"]=abs(hv["em"])
hv["hv_grid"]=abs(hv["hv_grid"])

#adding a datetime column
datetime = pd.to_datetime(hv['Date'] + ' ' + hv['Time'],format="%d/%m/%Y %H:%M:%S.%f")
datetime = datetime.dt.strftime('%d-%m-%Y %H:%M:%S')
datetime = pd.to_datetime(datetime, format='%d-%m-%Y %H:%M:%S')
hv.insert(0,"datetime",datetime)
    
#making the column into a datetime object
hv_timestamps=pd.to_datetime(hv["Time"],format="%H:%M:%S.%f")
runtime=(hv_timestamps-hv_timestamps[0]).dt.total_seconds()    
hv.insert(2,"Elapsed time",runtime)

hv.head()

,datetime,Date,Elapsed time,Time,VMon1,VMon2,VMon3,VMon4,VMon5,VMon6,...,IMon2,IMon3,IMon4,IMon5,IMon6,IMon7,IMon8,Comment,hv_grid,em
0,2022-11-25 10:01:47,25/11/2022,0.000,10:01:47.365,0.06,100.08,999.72,999.74,999.78,0.0,...,0.4838,37.2699,37.2765,37.2760,-0.0248,-0.0312,-0.0215,NaN,6.080000e-08,4.838000e-07
1,2022-11-25 10:02:56,25/11/2022,68.897,10:02:56.262,0.02,0.10,0.06,0.14,0.06,0.0,...,-0.0062,0.0423,0.0504,-0.0038,-0.0243,-0.0321,-0.0212,NaN,3.950000e-08,6.200000e-09
2,2022-11-25 10:02:57,25/11/2022,70.089,10:02:57.454,0.02,0.10,0.06,0.14,0.10,0.0,...,-0.0060,0.0430,0.0512,-0.0033,-0.0243,-0.0321,-0.0212,NaN,3.950000e-08,6.000000e-09
3,2022-11-25 10:02:58,25/11/2022,71.268,10:02:58.633,0.02,0.10,0.06,0.14,0.08,0.0,...,-0.0060,0.0430,0.0513,-0.0071,-0.0243,-0.0321,-0.0212,NaN,3.950000e-08,6.000000e-09
4,2022-11-25 10:03:05,25/11/2022,77.968,10:03:05.333,0.02,0.10,0.06,0.14,0.06,0.0,...,0.0006,0.0030,0.0028,0.0385,-0.0243,-0.0321,-0.0218,NaN,4.030000e-08,6.000000e-10

## Data processing

In [73]:
#print vaclog comments
print(pd.unique(vaclog["Live comments"]))

[nan]

In [74]:
#print hv comments
print(pd.unique(hv["Comment"]))
hv_comm = hv.loc[:,["datetime","Comment"]]
hv_comm.dropna(inplace=True)
print(hv_comm)
hv_comm.index

[nan 'emission on' 'grid repelling ' 'grid transparent' 'grid repelling'
 'ega turned']
                datetime           Comment
96   2022-11-25 10:04:57       emission on
97   2022-11-25 10:04:58       emission on
98   2022-11-25 10:04:59       emission on
99   2022-11-25 10:05:00       emission on
906  2022-11-25 10:21:01   grid repelling
907  2022-11-25 10:21:02   grid repelling
908  2022-11-25 10:21:04   grid repelling
909  2022-11-25 10:21:05   grid repelling
1195 2022-11-25 10:26:47  grid transparent
1196 2022-11-25 10:26:48  grid transparent
1197 2022-11-25 10:26:49  grid transparent
1198 2022-11-25 10:26:50  grid transparent
1803 2022-11-25 10:38:51    grid repelling
1804 2022-11-25 10:38:52    grid repelling
1805 2022-11-25 10:38:53    grid repelling
1806 2022-11-25 10:38:54    grid repelling
1807 2022-11-25 10:38:56    grid repelling
1996 2022-11-25 10:42:41        ega turned
1997 2022-11-25 10:42:42        ega turned
1998 2022-11-25 10:42:43        ega turned
1999 2022-11-25 10:42:44        ega turned
2000 2022-11-25 10:42:46        ega turned

Int64Index([  96,   97,   98,   99,  906,  907,  908,  909, 1195, 1196, 1197,
            1198, 1803, 1804, 1805, 1806, 1807, 1996, 1997, 1998, 1999, 2000],
           dtype='int64')

#### CernOx temperature R-T conversion

In [75]:
#Temperature curve for CERNOX - for temp stability
A=[230.317302,-6170.1513,71837.9529,-477946.76,2.003668910085786e+6,-5.488690193047771e+6,9.830475663897528e+6,-1.111226817786569e+7,7.202477878914065e+6,-2.04194551328507e+6]

#specify fit parameters A, data (Resistance values)
def polyfit(params,data):
    total=[]
    for j in data: 
        exp=0
        for i in range(len(params)):
            exp += (params[i]/(math.log10(j))**i)
        total.append(10**exp)
    return(total)

## Checking injection volume pressure drop linearity

In [76]:
#defining a function for the straight line
def fit(x,a,b):
    return a*x + b
#curve fit for the data
y_val = vaclog["injection 1mbar"].values
x_val = (vaclog["Elapsed time"]/3600).values
params, cov = curve_fit(fit,x_val,y_val)
#straight line parameters
a, b = params
print(f"Fitted line: y = {a:.2f}*x+{b:.2f}")

Fitted line: y = -0.00*x+0.00

#### Data preparation for calculating max desorption yield (w/o recycling)

In [77]:
#Filtering background signal

#Find the timestamp where emission was turned on and off
#print("Result 1:",hv.loc[hv["Comment"]=="grid transparent"])
#print("Result 2:", hv.loc[hv["Comment"]=="grid repelling"])
#print("Result 3:", hv.loc[hv["Comment"]=="electron activity grid repelling"])

x=pd.Timestamp(2023, 1, 12, 17 ,23, 58)
y=pd.Timestamp(2023, 1, 12, 17, 28, 43)
z=pd.Timestamp(2023, 1, 12, 17, 20, 13)

#then find the time value closest to it in the MID scan file 
#print("\n","Result 4:",mid.iloc[(pd.to_datetime(mid['mass 2.0_time'],format="%Y/%m/%d %H:%M:%S") - x).abs().argsort(),:])
#print("\n","Result 5:",mid.iloc[(pd.to_datetime(mid['mass 2.0_time'],format="%Y/%m/%d %H:%M:%S") - y).abs().argsort(),:])
#print("\n","Result 6:",mid.iloc[(pd.to_datetime(mid['mass 2.0_time'],format="%Y/%m/%d %H:%M:%S") - z).abs().argsort(),:])

#take a mass with a signal known to be in the electronics background
elec_bck = 0

#apply elec background correction to h2 data
mid["mass 2, corr"] = mid["mass 2.0_value"] - elec_bck

##apply base pressure correction to mass 2.0 data
#dyn_bck = np.mean(mid["mass 2, corr"][12:56])
#print("dyn_ bck",f"{dyn_bck}")

#subtracting dyn bck like this deletes useful data
#mid["mass 2, corr"] = mid["mass 2, corr"] - dyn_bck

#remove values below 0:
#mid["mass 2, corr"].clip(0, inplace=True) 

#From the signal, get the partial pressures 
h2_sens = 2.13e-2 #A/mbar
h2_equiv = 2.49 #H2 equivalent pressures from N2 reading

#account for the thermal transpiration factor
T2 = 294
T1 = 4.2
T_coef = np.sqrt(T2/T1)

#apply correction factors 
#p_h2 = (mid["mass 2, corr"][91:136]*h2_equiv)/(h2_sens*T_coef) 
#mid.insert(22,"p_h2",p_h2)
#print(p_h2)

#baseline and emission pp for partial pressure delta
#em_h2 = mid["p_h2"][91:136] #hardcoded values for "esd on"
#base_h2 = mid["p_h2"][12:56] #hardcoded values for "esd off"
#print(base_h2)

In [78]:
#NOT USED!

# #non hard coded values for "esd on/off"
# #find the local maxima
# print(mid.p_h2.values)
# mid['ESD max'] = mid.iloc[argrelextrema(mid.p_h2.values, np.greater_equal, order=5)[0]]['p_h2']
# mid['ESD min'] = mid.iloc[argrelextrema(mid.p_h2.values, np.less_equal, order=5)[0]]['p_h2']

# print(mid["ESD max"])
# print(mid["ESD min"])
# #take the 10 next values from max - define as "em on"


# #take the 10 next values from min - define as "em off"

# Apparent desorption yield calculation for H2
### Formula for the cryo setup

$$
\eta_{app}=\frac{C_{comb}\cdot (p_{n,EM} - \overline{p}_{base}) \cdot q_e}{k_B\cdot T \cdot I_{n}}
$$

T here is @RT and therefore thermal transpiration compensation should be applied afterwards to $\Delta p$.

$C_{comb}$ takes into account the conductance from the sample via the copper tube for H2 and the pumping speed for turbo pump

In [79]:
#calculation of delta_p-s
#dp1 = (np.mean(p_h2)-np.mean(base_h2))*100
#print(dp1)

#Constants
k_B = scipy.constants.value("Boltzmann constant")
T = 4.2
q_e = scipy.constants.value("elementary charge")
c_h2 = 37.91/1000
s_h2 = 42/1000
x_h2 = 1/((1/c_h2)+(1/s_h2))
print(x_h2)

#Emission current
I_em = np.nanmean(hv["em"].nlargest(30))
print(I_em)

0.01992516581153798
1.463576666666667e-06

In [80]:
#Desorption yield
#eta_h2 = (x_h2*dp1*q_e)/(k_B*T*I_em)
#eta_co = (c_co*(dp1-dp2)*q_e)/(k_B*T*I_em)
#print("The desorption yield for H2 [mol/el]:",eta_h2,"\n",)#""The desorption yield for CO2 [mol/el]:",eta_co2)

#### Data manipulation for point-by-point ESD

In [81]:
#make a sub-df from mid that includes only mass 2 data
h2 = mid.loc[:, ["mass 2.0_time", "mass 2.0_value"]]
#rename columns
h2 = h2.rename(columns={"mass 2.0_time": "datetime","mass 2.0_value": "Ion current"}).reset_index(drop=True)

print(h2)

                     datetime   Ion current
0     2022/11/25 10:03:04.399  2.197440e-11
1     2022/11/25 10:03:06.721  2.195880e-11
2     2022/11/25 10:03:09.044  2.186260e-11
3     2022/11/25 10:03:11.366  2.177490e-11
4     2022/11/25 10:03:13.689  2.178840e-11
...                       ...           ...
1337  2022/11/25 10:54:56.591  3.414180e-11
1338  2022/11/25 10:54:58.914  3.398860e-11
1339  2022/11/25 10:55:01.236  3.403050e-11
1340  2022/11/25 10:55:03.559  3.374400e-11
1341  2022/11/25 10:55:05.881  3.368490e-11

[1342 rows x 2 columns]

In [82]:
# Convert the 'time' column to datetime index for both dataframes
hv.index = (pd.to_datetime(hv['datetime']).dt.round(freq="S"))
h2.index = (pd.to_datetime(h2['datetime']).dt.round(freq="S"))
print(hv)

# Reindex df1 to match the datetime index of df2
hv = hv.reindex(h2.index, method='nearest', limit=1)

#Drop the "datetime" columns
hv.drop('datetime', axis=1, inplace=True)
h2.drop('datetime', axis=1, inplace=True)

# Now df1 and df2 have the same datetime index and can be joined or aligned
# by joining on the index
hv_aligned = hv.merge(h2,left_index=True, right_index=True, how="inner")

print("aligned",hv_aligned)
print(hv_aligned.describe())

                               datetime        Date  Elapsed time  \
datetime
2022-11-25 10:01:47 2022-11-25 10:01:47  25/11/2022         0.000
2022-11-25 10:02:56 2022-11-25 10:02:56  25/11/2022        68.897
2022-11-25 10:02:57 2022-11-25 10:02:57  25/11/2022        70.089
2022-11-25 10:02:58 2022-11-25 10:02:58  25/11/2022        71.268
2022-11-25 10:03:05 2022-11-25 10:03:05  25/11/2022        77.968
...                                 ...         ...           ...
2022-11-25 10:53:45 2022-11-25 10:53:45  25/11/2022      3118.558
2022-11-25 10:53:47 2022-11-25 10:53:47  25/11/2022      3119.751
2022-11-25 10:53:48 2022-11-25 10:53:48  25/11/2022      3120.937
2022-11-25 10:53:49 2022-11-25 10:53:49  25/11/2022      3122.128
2022-11-25 10:53:50 2022-11-25 10:53:50  25/11/2022      3123.318

                             Time  VMon1   VMon2   VMon3   VMon4    VMon5  \
datetime
2022-11-25 10:01:47  10:01:47.365   0.06  100.08  999.72  999.74   999.78
2022-11-25 10:02:56  10:02:56.262   0.02    0.10    0.06    0.14     0.06
2022-11-25 10:02:57  10:02:57.454   0.02    0.10    0.06    0.14     0.10
2022-11-25 10:02:58  10:02:58.633   0.02    0.10    0.06    0.14     0.08
2022-11-25 10:03:05  10:03:05.333   0.02    0.10    0.06    0.14     0.06
...                           ...    ...     ...     ...     ...      ...
2022-11-25 10:53:45  10:53:45.923   0.10  100.08  999.84  999.96  1000.00
2022-11-25 10:53:47  10:53:47.116   0.10  100.08  999.84  999.96  1000.00
2022-11-25 10:53:48  10:53:48.302   0.10  100.08  999.84  999.96  1000.00
2022-11-25 10:53:49  10:53:49.493   0.10  100.08  999.84  999.96  1000.00
2022-11-25 10:53:50  10:53:50.683   0.10  100.08  999.84  999.96  1000.00

                     VMon6  ...   IMon2    IMon3    IMon4    IMon5   IMon6  \
datetime                    ...
2022-11-25 10:01:47    0.0  ...  0.4838  37.2699  37.2765  37.2760 -0.0248
2022-11-25 10:02:56    0.0  ... -0.0062   0.0423   0.0504  -0.0038 -0.0243
2022-11-25 10:02:57    0.0  ... -0.0060   0.0430   0.0512  -0.0033 -0.0243
2022-11-25 10:02:58    0.0  ... -0.0060   0.0430   0.0513  -0.0071 -0.0243
2022-11-25 10:03:05    0.0  ...  0.0006   0.0030   0.0028   0.0385 -0.0243
...                    ...  ...     ...      ...      ...      ...     ...
2022-11-25 10:53:45    0.0  ...  0.9199  40.7761  40.7887  40.8279 -0.0182
2022-11-25 10:53:47    0.0  ...  0.9166  40.7732  40.7847  40.8260 -0.0182
2022-11-25 10:53:48    0.0  ...  0.9154  40.7733  40.7847  40.8262 -0.0182
2022-11-25 10:53:49    0.0  ...  0.9149  40.7733  40.7880  40.8277 -0.0182
2022-11-25 10:53:50    0.0  ...  0.9158  40.7733  40.7880  40.8279 -0.0182

                      IMon7   IMon8  Comment       hv_grid            em
datetime
2022-11-25 10:01:47 -0.0312 -0.0215      NaN  6.080000e-08  4.838000e-07
2022-11-25 10:02:56 -0.0321 -0.0212      NaN  3.950000e-08  6.200000e-09
2022-11-25 10:02:57 -0.0321 -0.0212      NaN  3.950000e-08  6.000000e-09
2022-11-25 10:02:58 -0.0321 -0.0212      NaN  3.950000e-08  6.000000e-09
2022-11-25 10:03:05 -0.0321 -0.0218      NaN  4.030000e-08  6.000000e-10
...                     ...     ...      ...           ...           ...
2022-11-25 10:53:45 -0.0272 -0.0202      NaN  1.495000e-07  9.199000e-07
2022-11-25 10:53:47 -0.0272 -0.0202      NaN  1.471000e-07  9.166000e-07
2022-11-25 10:53:48 -0.0272 -0.0202      NaN  1.492000e-07  9.154000e-07
2022-11-25 10:53:49 -0.0272 -0.0202      NaN  1.468000e-07  9.149000e-07
2022-11-25 10:53:50 -0.0272 -0.0202      NaN  1.480000e-07  9.158000e-07

[2558 rows x 23 columns]
aligned                            Date  Elapsed time          Time  VMon1  VMon2  \
datetime
2022-11-25 10:03:04  25/11/2022        77.968  10:03:05.333   0.02   0.10
2022-11-25 10:03:07  25/11/2022        80.334  10:03:07.699   0.02   0.10
2022-11-25 10:03:09  25/11/2022        83.310  10:03:10.675   0.02   0.10
2022-11-25 10:03:11  25/11/2022        84.494  10:03:11.859   0.02   0.08
2022-11-25 10:03:14  25/11/2022        86.855  10:03:14.220   0.02   0.08
...                         ...           ...           ...    ...    ...
2022-11-25 10:54:57         NaN           NaN           NaN    NaN    NaN
2022-11-25 10:54:59         NaN           NaN           NaN    NaN    NaN
2022-11-25 10:55:01         NaN           NaN           NaN    NaN    NaN
2022-11-25 10:55:04         NaN           NaN           NaN    NaN    NaN
2022-11-25 10:55:06         NaN           NaN           NaN    NaN    NaN

                     VMon3  VMon4  VMon5  VMon6  VMon7  ...   IMon3   IMon4  \
datetime                                                ...
2022-11-25 10:03:04   0.06   0.14   0.06    0.0    0.0  ...  0.0030  0.0028
2022-11-25 10:03:07   0.04   0.14   0.08    0.0    0.0  ...  0.0114  0.0025
2022-11-25 10:03:09   0.16   0.14   0.06    0.0    0.0  ... -0.0673  0.0117
2022-11-25 10:03:11   0.12   0.20   0.04    0.0    0.0  ...  0.0066 -0.0443
2022-11-25 10:03:14   0.22   0.22   0.04    0.0    0.0  ...  0.0067  0.0216
...                    ...    ...    ...    ...    ...  ...     ...     ...
2022-11-25 10:54:57    NaN    NaN    NaN    NaN    NaN  ...     NaN     NaN
2022-11-25 10:54:59    NaN    NaN    NaN    NaN    NaN  ...     NaN     NaN
2022-11-25 10:55:01    NaN    NaN    NaN    NaN    NaN  ...     NaN     NaN
2022-11-25 10:55:04    NaN    NaN    NaN    NaN    NaN  ...     NaN     NaN
2022-11-25 10:55:06    NaN    NaN    NaN    NaN    NaN  ...     NaN     NaN

                      IMon5   IMon6   IMon7   IMon8  Comment       hv_grid  \
datetime
2022-11-25 10:03:04  0.0385 -0.0243 -0.0321 -0.0218      NaN  4.030000e-08
2022-11-25 10:03:07  0.0063 -0.0243 -0.0321 -0.0218      NaN  4.030000e-08
2022-11-25 10:03:09  0.0111 -0.0237 -0.0321 -0.0225      NaN  3.000000e-10
2022-11-25 10:03:11  0.0339 -0.0237 -0.0321 -0.0225      NaN  0.000000e+00
2022-11-25 10:03:14  0.0408 -0.0237 -0.0321 -0.0227      NaN  0.000000e+00
...                     ...     ...     ...     ...      ...           ...
2022-11-25 10:54:57     NaN     NaN     NaN     NaN      NaN           NaN
2022-11-25 10:54:59     NaN     NaN     NaN     NaN      NaN           NaN
2022-11-25 10:55:01     NaN     NaN     NaN     NaN      NaN           NaN
2022-11-25 10:55:04     NaN     NaN     NaN     NaN      NaN           NaN
2022-11-25 10:55:06     NaN     NaN     NaN     NaN      NaN           NaN

                               em   Ion current
datetime
2022-11-25 10:03:04  6.000000e-10  2.197440e-11
2022-11-25 10:03:07  6.000000e-10  2.195880e-11
2022-11-25 10:03:09  6.000000e-10  2.186260e-11
2022-11-25 10:03:11  8.500000e-09  2.177490e-11
2022-11-25 10:03:14  8.500000e-09  2.178840e-11
...                           ...           ...
2022-11-25 10:54:57           NaN  3.414180e-11
2022-11-25 10:54:59           NaN  3.398860e-11
2022-11-25 10:55:01           NaN  3.403050e-11
2022-11-25 10:55:04           NaN  3.374400e-11
2022-11-25 10:55:06           NaN  3.368490e-11

[1342 rows x 23 columns]
       Elapsed time        VMon1        VMon2        VMon3        VMon4  \
count   1310.000000  1310.000000  1310.000000  1310.000000  1310.000000
mean    1599.236918   178.364137    97.107679   966.887176   965.657206
std      880.686681   238.858813    16.993579   176.961523   180.289340
min       77.968000     0.020000     0.080000     0.000000     0.000000
25%      837.875500     0.080000   100.080000   999.820000   999.900000
50%     1597.643500     0.100000   100.080000   999.820000   999.920000
75%     2358.036500   499.860000   100.080000   999.840000   999.940000
max     3123.318000   499.900000   100.160000   999.860000   999.960000

             VMon5   VMon6   VMon7   VMon8        IMon1        IMon2  \
count  1310.000000  1310.0  1310.0  1310.0  1310.000000  1310.000000
mean    964.843679     0.0     0.0     0.0    -0.046632     0.409554
std     182.550517     0.0     0.0     0.0     0.067792     0.350048
min       0.000000     0.0     0.0     0.0    -0.509900     0.000600
25%     999.960000     0.0     0.0     0.0    -0.084300     0.023100
50%     999.980000     0.0     0.0     0.0    -0.062600     0.487700
75%     999.980000     0.0     0.0     0.0     0.017400     0.659000
max    1000.000000     0.0     0.0     0.0     0.545800     3.256500

             IMon3        IMon4        IMon5        IMon6        IMon7  \
count  1310.000000  1310.000000  1310.000000  1310.000000  1310.000000
mean     38.516727    38.526478    38.563331    -0.019190    -0.029880
std       7.193261     7.204244     7.215906     0.001279     0.001586
min      -0.067300    -0.057100    -0.012400    -0.024300    -0.032400
25%      39.551600    39.564850    39.606025    -0.019800    -0.031100
50%      40.047700    40.062950    40.099850    -0.019100    -0.030300
75%      40.402900    40.417775    40.458375    -0.018200    -0.029100
max      40.788900    40.799300    40.836900    -0.017400    -0.026900

             IMon8       hv_grid            em   Ion current
count  1310.000000  1.310000e+03  1.310000e+03  1.342000e+03
mean     -0.021189  6.271099e-08  4.095544e-07  4.673327e-11
std       0.001467  5.325719e-08  3.500484e-07  8.472184e-12
min      -0.023500  0.000000e+00  6.000000e-10  2.111490e-11
25%      -0.022700  1.790000e-08  2.310000e-08  4.137730e-11
50%      -0.021200  6.305000e-08  4.877000e-07  4.625055e-11
75%      -0.019900  8.465000e-08  6.590000e-07  5.173925e-11
max      -0.018100  5.458000e-07  3.256500e-06  1.074910e-10

In [83]:
#Filtering background signal for interpolated datasets


#From the signal, get the partial pressures 
h2_sens = 2.13e-2 #A/mbar
p_h2_ip = hv_aligned["Ion current"]/(h2_sens) 


#insert partial pressures into the dataframe
hv_aligned.insert(19,"hydrogen pp",p_h2_ip)

In [84]:
hv_aligned.fillna(0,inplace=True)
#hv_aligned["hydrogen pp"].mask(hv_aligned["hydrogen pp"].ge(5.0464e-9), inplace=True)# remove spike
print(hv_aligned["hydrogen pp"].describe())
hv_aligned["Elapsed time"].describe()

count    1.342000e+03
mean     2.194050e-09
std      3.977551e-10
min      9.913099e-10
25%      1.942596e-09
50%      2.171387e-09
75%      2.429073e-09
max      5.046526e-09
Name: hydrogen pp, dtype: float64

count    1342.000000
mean     1561.103101
std       903.701304
min         0.000000
25%       782.077750
50%      1560.184000
75%      2339.862750
max      3123.318000
Name: Elapsed time, dtype: float64

#### Using polynomial regression, remove the pressure decrease from pumping

In [85]:
""" # Load the data
t = time["Elapsed time, mass 2"]
print(t.describe())
I_ion = mid["Ion current"]
print(I_ion.describe())
#The function for the ion current-time relationship is not known. 
#numpy method for creating a polynomial model    
model = np.poly1d(np.polyfit(t, I_ion, 8))
print(model(t))

rsquared = r2_score(I_ion,model(t))
print(rsquared)

# Print the original function
plt.figure(figsize=(12,6))
plt.plot(t, I_ion)

# Add labels and title
plt.xlabel('time (s)')
plt.ylabel('Ion current')
plt.title('Ion current vs time')

plt.yscale("log")
plt.show()
 """

' # Load the data\nt = time["Elapsed time, mass 2"]\nprint(t.describe())\nI_ion = mid["Ion current"]\nprint(I_ion.describe())\n#The function for the ion current-time relationship is not known. \n#numpy method for creating a polynomial model    \nmodel = np.poly1d(np.polyfit(t, I_ion, 8))\nprint(model(t))\n\nrsquared = r2_score(I_ion,model(t))\nprint(rsquared)\n\n# Print the original function\nplt.figure(figsize=(12,6))\nplt.plot(t, I_ion)\n\n# Add labels and title\nplt.xlabel(\'time (s)\')\nplt.ylabel(\'Ion current\')\nplt.title(\'Ion current vs time\')\n\nplt.yscale("log")\nplt.show()\n '

In [86]:
""" #normalise measured data to fit
x = np.linspace(5095.951000, 19700, 3095)
I_norm = I_ion/model(x)

# Plot the normalised ion current
plt.figure(figsize=(12,6))
plt.plot(t, I_norm)

# Add labels and title
plt.xlabel('time (s)')
plt.ylabel('normalised ion current (a.u.)')
plt.title('Ion current vs time')

plt.yscale("linear")
plt.show()

#now we have  """

' #normalise measured data to fit\nx = np.linspace(5095.951000, 19700, 3095)\nI_norm = I_ion/model(x)\n\n# Plot the normalised ion current\nplt.figure(figsize=(12,6))\nplt.plot(t, I_norm)\n\n# Add labels and title\nplt.xlabel(\'time (s)\')\nplt.ylabel(\'normalised ion current (a.u.)\')\nplt.title(\'Ion current vs time\')\n\nplt.yscale("linear")\nplt.show()\n\n#now we have  '

#### Checking injection volume pressure drop linearity

In [87]:
#defining a function for the straight line
def fit(x,a,b):
    return a*x + b
#curve fit for the data
y_val = vaclog["injection 1mbar"].values
x_val = (vaclog["Elapsed time"]/3600).values
params, cov = curve_fit(fit,x_val,y_val)
#straight line parameters
a, b = params
print(f"Fitted line: y = {a:.2f}*x+{b:.2f}")

Fitted line: y = -0.00*x+0.00

## Desorption yield point-by-point

$$
\eta_{app}=\frac{C_{comb}\cdot (p_{n,EM} - \overline{p}_{base}) \cdot q_e}{k_B\cdot T \cdot I_{n}}
$$

In [88]:
""" #partial pressure delta
#wrong methodology
p_delta = 
p_delta = p_delta.clip(lower=0)
print(p_delta)
#hv_shifted = hv_aligned.shift(periods=1)
#print(hv_shifted)
#p_delta = hv_aligned["hydrogen pp"] - hv_shifted["hydrogen pp"]
#print(hv_aligned["hydrogen pp"].describe())
#print(hv_shifted["hydrogen pp"].describe())
print(p_delta.describe()) """

' #partial pressure delta\n#wrong methodology\np_delta = \np_delta = p_delta.clip(lower=0)\nprint(p_delta)\n#hv_shifted = hv_aligned.shift(periods=1)\n#print(hv_shifted)\n#p_delta = hv_aligned["hydrogen pp"] - hv_shifted["hydrogen pp"]\n#print(hv_aligned["hydrogen pp"].describe())\n#print(hv_shifted["hydrogen pp"].describe())\nprint(p_delta.describe()) '

In [89]:
""" #constants are already defined
#emission current and H2 partial pressures are now available at the same sampling rates
print(hv_aligned.describe())
I_n = hv_aligned["em"].replace(0, np.nan).dropna()

I_n.where(hv_aligned["em"] >= 5e-7, np.nan, inplace=True)
#pd.df.where(cond= "Where cond is True, keep the original value. Otherwise, replace with NaN")
print(I_n.describe())

eta = ((x_h2*p_delta*q_e)/(k_B*T*I_n)).dropna()
eta = eta.loc[eta.index[1]:]
print("desorption yields point-by-point:","\n", eta) """

' #constants are already defined\n#emission current and H2 partial pressures are now available at the same sampling rates\nprint(hv_aligned.describe())\nI_n = hv_aligned["em"].replace(0, np.nan).dropna()\n\nI_n.where(hv_aligned["em"] >= 5e-7, np.nan, inplace=True)\n#pd.df.where(cond= "Where cond is True, keep the original value. Otherwise, replace with NaN")\nprint(I_n.describe())\n\neta = ((x_h2*p_delta*q_e)/(k_B*T*I_n)).dropna()\neta = eta.loc[eta.index[1]:]\nprint("desorption yields point-by-point:","\n", eta) '

In [90]:
""" #slicing eta to match hv_aligned["Elapsed time"]:
# Slice x using the index of y
hv_downsampled = hv_aligned.loc[eta.index, :] """

' #slicing eta to match hv_aligned["Elapsed time"]:\n# Slice x using the index of y\nhv_downsampled = hv_aligned.loc[eta.index, :] '

## Electron dose

Find:

$$
Q = \int_{t_1}^{t_2} I \,dt
$$

Where $t_2$ and $t_1$ are the timestamps at which an emission current reading was taken

In [91]:
""" #Integrating the emission current
def integrand(t, i):
    return i*t

i = I_n.dropna().reset_index() 

#for testing:
#t2_2 = (hv_aligned["Elapsed time"].diff(periods=1).fillna(0))

#adding an elapsed time column
timestamp3=[]
for j in hv["Time"]:
    timestamp3.append(j)
    
#making the column into a datetime object
timestamps3=pd.to_datetime(i["datetime"],format="%H:%M:%S")
runtime3=(timestamps3-timestamps3[0]).dt.total_seconds()    
i.insert(2,"Elapsed time",runtime3)

#define the n, n-1 difference in a variable "t2"
t2 = (i["Elapsed time"].diff(periods=1).fillna(0))

#replace all values from t2 that are further away than 50% of the median of the sampling rate (.. > 9) with the median value
t2.where(t2 <= 12,6,inplace=True)
print(t2)

#integration
ar = []
for x in t2:
    itr = 0
    I = quad(integrand, 0, x, args=(i["em"][itr]))
    ar.append(I[0])
    itr += 1
    #if previous value was not NaN, replace the value with the median of elapsed time
    #if 
     """

' #Integrating the emission current\ndef integrand(t, i):\n    return i*t\n\ni = I_n.dropna().reset_index() \n\n#for testing:\n#t2_2 = (hv_aligned["Elapsed time"].diff(periods=1).fillna(0))\n\n#adding an elapsed time column\ntimestamp3=[]\nfor j in hv["Time"]:\n    timestamp3.append(j)\n    \n#making the column into a datetime object\ntimestamps3=pd.to_datetime(i["datetime"],format="%H:%M:%S")\nruntime3=(timestamps3-timestamps3[0]).dt.total_seconds()    \ni.insert(2,"Elapsed time",runtime3)\n\n#define the n, n-1 difference in a variable "t2"\nt2 = (i["Elapsed time"].diff(periods=1).fillna(0))\n\n#replace all values from t2 that are further away than 50% of the median of the sampling rate (.. > 9) with the median value\nt2.where(t2 <= 12,6,inplace=True)\nprint(t2)\n\n#integration\nar = []\nfor x in t2:\n    itr = 0\n    I = quad(integrand, 0, x, args=(i["em"][itr]))\n    ar.append(I[0])\n    itr += 1\n    #if previous value was not NaN, replace the value with the median of elapsed time\n    #if \n     '

In [92]:
""" #calculate the cumulative charge
Q_cumul = np.cumsum(ar)
Q_sum = sum(ar)
print("Total charge emitted from EGA during ~5000 seconds:", f"{Q_sum:.4E}", "C")

#cumulative nr of electrons emitted
N_e = Q_sum/q_e
Ne_cumul = Q_cumul/q_e
print("Total number of electron emitted during ~5000 seconds:", f"{N_e:.4E}", "e")
      
#To get the electron dose, divide n of electrons by sample surface area of 276 cm2, multiply by grid transmittance of 0.9
tot_dose = (N_e/276)*0.9
cumul_dose = (Ne_cumul/276)*0.9
print("Total electron dose on the sample ~5000 seconds:", f"{tot_dose:.4E}", "e-/cm^2")
      
#add these to the "i" dataframe:
i.insert(3,"Cumulative charge", Q_cumul)
i.insert(4,"Cumulative n. of electrons emitted from EGA", Ne_cumul)
i.insert(5,"Cumulative electron dose on the HL sample", cumul_dose)
i.set_index("datetime", drop=True, inplace=True)

#Ignore the first value, also, match the shape of eta
i = i.loc[i.index[1]:]
print(i)
 """

' #calculate the cumulative charge\nQ_cumul = np.cumsum(ar)\nQ_sum = sum(ar)\nprint("Total charge emitted from EGA during ~5000 seconds:", f"{Q_sum:.4E}", "C")\n\n#cumulative nr of electrons emitted\nN_e = Q_sum/q_e\nNe_cumul = Q_cumul/q_e\nprint("Total number of electron emitted during ~5000 seconds:", f"{N_e:.4E}", "e")\n      \n#To get the electron dose, divide n of electrons by sample surface area of 276 cm2, multiply by grid transmittance of 0.9\ntot_dose = (N_e/276)*0.9\ncumul_dose = (Ne_cumul/276)*0.9\nprint("Total electron dose on the sample ~5000 seconds:", f"{tot_dose:.4E}", "e-/cm^2")\n      \n#add these to the "i" dataframe:\ni.insert(3,"Cumulative charge", Q_cumul)\ni.insert(4,"Cumulative n. of electrons emitted from EGA", Ne_cumul)\ni.insert(5,"Cumulative electron dose on the HL sample", cumul_dose)\ni.set_index("datetime", drop=True, inplace=True)\n\n#Ignore the first value, also, match the shape of eta\ni = i.loc[i.index[1]:]\nprint(i)\n '

# Plotting

In [93]:
#define parameters for plotting
#annotation params
font = dict(size = "x-small", color ="green", style ="italic",rotation="vertical")

plt.rcParams["figure.figsize"] = [8,5]
plt.rcParams["axes.edgecolor"] = "black"
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.color"] = "black"
plt.rcParams["grid.linewidth"] = 0.35

formatter = md.DateFormatter('%H:%M')

# Create the "graphs" folder path
graphs_folder = os.path.join(os.getcwd(), 'graphs')

# Ensure the "graphs" folder exists, if not create it
if not os.path.exists(graphs_folder):
    os.makedirs(graphs_folder)

In [94]:
#plot the aligned dataframe results
plt.figure(figsize=(12,6))
plt.plot(hv_aligned["Elapsed time"],hv_aligned["Ion current"],linestyle="-",marker=".", markersize=4,label='H2 ion current')
plt.plot(hv_aligned["Elapsed time"],hv_aligned["em"],linestyle="-",marker=".", markersize=4,label='Emission current')
plt.xlabel('Elapsed time (s)')
plt.ylabel('Current (A)')
plt.yscale('log')

plt.legend(loc="upper right")
plt.title("Current evolution 1 ML tech. surface pre-injection, EGA fully in, dynamic vacuum")


plt.yscale('log')

In [95]:
#plot the h2 mid 
#seems to be too little rows?
plt.figure(figsize=(12,6))
plt.plot(hv_aligned["Elapsed time"],hv_aligned["Ion current"],linestyle="-",marker=".", markersize=4,label='H2 ion current')
plt.xlabel('Elapsed time (s)')
plt.ylabel('Ion current (A)')
plt.legend(loc="upper right")
plt.title("Ion current evolution of H2, 1 ML tech. surface pre-injection, EGA fully in, dynamic vacuum")


plt.yscale('linear')

In [102]:
#plot the aligned dataframe results
fig, ax = plt.subplots()
y_fit = fit(x_val,a,b)
ax.plot(hv_aligned["Elapsed time"],hv_aligned["em"],linestyle="-",marker=".",c="r", markersize=4,label='I_EM')
ax.set_xlim(left=10,right=3030)

ax.set_xlabel('Elapsed time (s)')
ax.set_ylabel('Current (A)')
ax.set_yscale('log')
ax.legend(loc="upper right")
ax.axes.grid(visible=None,axis="y")
ax2 = ax.twinx()
ax2.plot(hv_aligned["Elapsed time"],hv_aligned["hydrogen pp"],linestyle="-",marker=".", c="b",markersize=4,label='H2 partial pressure')
ax2.set_ylabel('Pressure (mbar)')
ax2.set_yscale('linear')
ax2.legend(loc="upper left")

plt.title("S2 HiLumi ESD at RT_EGA middle")

Text(0.5, 1.0, 'S2 HiLumi ESD at RT_EGA middle')

In [97]:
#Plotting the all the relevant MID spectrums
plt.figure(figsize=(14,8))

plt.plot(new_df["Timestamp, mass 2"],mid["mass 2.0_value"]/2.13e-2,marker=".", markersize=4,label='H2')# MBAR
# plt.plot(new_df["Timestamp, mass 44"],mid["mass 44.0_value"],marker=".", markersize=4,label='M44')

plt.xlabel('Timestamp')
plt.ylabel('Pressure (mbar)')
plt.legend(loc="upper right")
plt.title("S2 pressure from MID scan")
plt.tick_params(axis="y", which='minor')
plt.grid(which='minor', axis='y')
plt.yscale('log')

ax = plt.gca()
ax.xaxis.set_major_formatter(md.DateFormatter('%H:%M'))
ax.xaxis.set_major_locator(plt.MaxNLocator(14))
for label in ax.get_xticklabels(which='major'):
    label.set(rotation=30, horizontalalignment='right')

#write comments
trans  = transforms.blended_transform_factory(
    ax.transData, ax.transAxes)
for i in hv_comm.index:
    plt.text(hv_comm["datetime"][i],0.95,str(hv_comm["Comment"][i]),fontdict=font, transform=trans)


plt.savefig(r'./graphs/pressure from mid.png')
plt.show()

In [98]:
#plotting HiVolta log
plt.figure(figsize=(12,6))
plt.plot(hv["Elapsed time"],hv["hv_grid"],marker=".", markersize=4,label='Grid current')
plt.plot(hv["Elapsed time"],hv["em"],marker=".", markersize=4,label='Emission current')
plt.xlabel('Elapsed time (s)')
plt.ylabel('Current (A)')
plt.legend(loc="upper right")
plt.title("Current evolution 1 ML tech. surface pre-injection, EGA fully in, dynamic vacuum")


plt.yscale('log')

In [99]:
#Plotting BA2, BA1 pressure
plt.figure(figsize=(12,6))
plt.plot(vaclog["Time"],vaclog["Barion_2"],marker=".", markersize=4,label='Barion 2')
plt.plot(vaclog["Time"],vaclog["Barion_1"],marker=".", markersize=4,label='Barion 1')
plt.xlabel('Timestamp')
plt.ylabel('Pressure (mbar)')
plt.legend()
plt.title("S1 Total pressure evolution")
plt.tick_params(axis="y", which='minor')
plt.grid(which='minor', axis='y')
plt.yscale('log')

ax = plt.gca()
ax.xaxis.set_major_formatter(md.DateFormatter('%H:%M'))
ax.xaxis.set_major_locator(plt.MaxNLocator(10))
for label in ax.get_xticklabels(which='major'):
    label.set(rotation=30, horizontalalignment='right')    
       
plt.savefig(r'./graphs/Barions.png')
plt.show()

In [100]:
## Plotting the temp evolution
plt.figure(figsize=(10,6))
plt.plot((vaclog["Time"]),polyfit(A,vaclog["T-CERNOX"]),marker=".", markersize=5,label='T-CERNOX')          
plt.xlabel('Timestamp')
plt.ylabel('Temperature (K)')
plt.legend()
plt.title("S1 Temperature evolution")
plt.yscale('linear')
plt.tick_params(axis="y", which='minor')
plt.grid(which='minor', axis='y')

ax = plt.gca()
ax.xaxis.set_major_formatter(md.DateFormatter('%H:%M'))
ax.xaxis.set_major_locator(plt.MaxNLocator(10))
for label in ax.get_xticklabels(which='major'):
    label.set(rotation=30, horizontalalignment='right')
    
plt.savefig(r'./graphs/Temp.png')
plt.show()

In [101]:
#checking inj pressure linearity, graph
fig, ax = plt.subplots()
y_fit = fit(x_val,a,b)
ax.plot((vaclog["Elapsed time"]/3600),vaclog["injection 1mbar"],marker=".", markersize=5,label='inj volume pressure')
ax.plot((vaclog["Elapsed time"]/3600),y_fit, "--",color="red", label="Y= -ax + b fit") 
ax.legend(loc="upper right")

ax.set_xlabel('Elapsed time (h)')
ax.set_ylabel('Pressure (mbar)')
ax.set_yscale('linear')
plt.title("Injection pressure evolution 1mbar conductance gauge")

Text(0.5, 1.0, 'Injection pressure evolution 1mbar conductance gauge')