In [1]:
import pandas as pd
from scipy.optimize import curve_fit
import seaborn
seaborn.set(style='whitegrid')
import numpy as np
import math
import matplotlib.pyplot as plt
from matplotlib.ticker import LogFormatter
%matplotlib qt
# %matplotlib inline
from datetime import datetime, date

C:\Users\etiirine\Anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

## Reading in the data

In [2]:
#read in the data
mid = pd.read_csv("experiment MID.tsv", sep="\t", skiprows=lambda x: x <=11,  on_bad_lines="skip")
mid.drop([0,1], inplace=True)
print(mid.describe())
#bring the time data into a new df
time = pd.DataFrame(mid.iloc[:,0::2]) #- get every second column
print(time.describe())
#add elapsed time columns
def elapsed_time(df):
    itr = 0
    counter = len(df.columns)
    masses = [2,4,5.5,12,15,16,18,28,32,40,44]
    for i in df:
        timestamp = pd.to_datetime(df[i], format="%Y/%m/%d %H:%M:%S.%f")
        runtime = (timestamp-timestamp[2]).dt.total_seconds()
        colname = "Elapsed time, mass {}".format(masses[itr]) 
        df.insert(counter, colname, runtime)
        itr += 1
        counter += 1
    return(df)
elapsed_time(time)

#time["Elapsed time, mass 40"].describe()

       mass 2.0_value  mass 4.0_value  mass 5.5_value  mass 12.0_value  \
count    2.349000e+03    2.349000e+03    2.349000e+03     2.349000e+03
mean     2.620820e-11    8.305234e-13    1.778689e-14     2.530263e-13
std      6.053045e-12    4.745305e-13    5.342895e-15     5.084379e-14
min      2.246530e-11    5.100000e-13    6.300000e-15     1.317000e-13
25%      2.369670e-11    5.876000e-13    1.470000e-14     2.258000e-13
50%      2.439550e-11    5.983000e-13    1.730000e-14     2.406000e-13
75%      2.565810e-11    6.234000e-13    2.010000e-14     2.579000e-13
max      8.010900e-11    3.863000e-12    1.144000e-13     5.491000e-13

       mass 15.0_value  mass 16.0_value  mass 18.0_value  mass 28.0_value  \
count     2.349000e+03     2.349000e+03     2.349000e+03     2.349000e+03
mean      5.220085e-14     5.669347e-13     9.225058e-13     1.512949e-12
std       5.133547e-14     1.516972e-13     3.648962e-13     5.225907e-13
min       1.250000e-14     2.664000e-13     4.620000e-13     1.096000e-12
25%       2.910000e-14     5.072000e-13     7.617000e-13     1.244600e-12
50%       3.580000e-14     5.334000e-13     8.133000e-13     1.297800e-12
75%       4.390000e-14     5.583000e-13     8.868000e-13     1.431100e-12
max       3.402000e-13     1.375400e-12     2.640200e-12     3.845800e-12

       mass 32.0_value  mass 40.0_value  mass 44.0_value
count     2.349000e+03     2.349000e+03     1.262000e+03
mean      7.216105e-14     1.766181e-14     2.797998e-13
std       5.870429e-14     4.995068e-15     2.495986e-13
min       1.510000e-14     6.100000e-15     0.000000e+00
25%       3.020000e-14     1.470000e-14     1.075000e-13
50%       3.830000e-14     1.720000e-14     2.150000e-13
75%       1.227000e-13     2.000000e-14     4.300000e-13
max       2.983000e-13     1.021000e-13     1.451200e-12
                  mass 2.0_time            mass 4.0_time  \
count                      2349                     2349
unique                     2349                     2349
top     2022/12/13 12:30:19.001  2022/12/13 12:30:19.251
freq                          1                        1

                  mass 5.5_time           mass 12.0_time  \
count                      2349                     2349
unique                     2349                     2349
top     2022/12/13 12:30:19.501  2022/12/13 12:30:19.752
freq                          1                        1

                 mass 15.0_time           mass 16.0_time  \
count                      2349                     2349
unique                     2349                     2349
top     2022/12/13 12:30:20.002  2022/12/13 12:30:20.252
freq                          1                        1

                 mass 18.0_time           mass 28.0_time  \
count                      2349                     2349
unique                     2349                     2349
top     2022/12/13 12:30:20.502  2022/12/13 12:30:20.752
freq                          1                        1

                 mass 32.0_time           mass 40.0_time  \
count                      2349                     2349
unique                     2349                     2349
top     2022/12/13 12:30:21.002  2022/12/13 12:30:21.253
freq                          1                        1

                 mass 44.0_time
count                      1262
unique                     1262
top     2022/12/13 12:30:22.004
freq                          1

,mass 2.0_time,mass 4.0_time,mass 5.5_time,mass 12.0_time,mass 15.0_time,mass 16.0_time,mass 18.0_time,mass 28.0_time,mass 32.0_time,mass 40.0_time,...,"Elapsed time, mass 4","Elapsed time, mass 5.5","Elapsed time, mass 12","Elapsed time, mass 15","Elapsed time, mass 16","Elapsed time, mass 18","Elapsed time, mass 28","Elapsed time, mass 32","Elapsed time, mass 40","Elapsed time, mass 44"
2,2022/12/13 12:30:19.001,2022/12/13 12:30:19.251,2022/12/13 12:30:19.501,2022/12/13 12:30:19.752,2022/12/13 12:30:20.002,2022/12/13 12:30:20.252,2022/12/13 12:30:20.502,2022/12/13 12:30:20.752,2022/12/13 12:30:21.002,2022/12/13 12:30:21.253,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
3,2022/12/13 12:30:25.326,2022/12/13 12:30:25.576,2022/12/13 12:30:25.826,2022/12/13 12:30:26.077,2022/12/13 12:30:26.327,2022/12/13 12:30:26.577,2022/12/13 12:30:26.827,2022/12/13 12:30:27.077,2022/12/13 12:30:27.328,2022/12/13 12:30:27.578,...,6.325,6.325,6.325,6.325,6.325,6.325,6.325,6.326,6.325,6.325
4,2022/12/13 12:30:31.651,2022/12/13 12:30:31.901,2022/12/13 12:30:32.152,2022/12/13 12:30:32.402,2022/12/13 12:30:32.652,2022/12/13 12:30:32.902,2022/12/13 12:30:33.152,2022/12/13 12:30:33.402,2022/12/13 12:30:33.653,2022/12/13 12:30:33.903,...,12.650,12.651,12.650,12.650,12.650,12.650,12.650,12.651,12.650,12.651
5,2022/12/13 12:30:37.977,2022/12/13 12:30:38.227,2022/12/13 12:30:38.477,2022/12/13 12:30:38.727,2022/12/13 12:30:38.977,2022/12/13 12:30:39.228,2022/12/13 12:30:39.478,2022/12/13 12:30:39.728,2022/12/13 12:30:39.979,2022/12/13 12:30:40.229,...,18.976,18.976,18.975,18.975,18.976,18.976,18.976,18.977,18.976,18.976
6,2022/12/13 12:30:44.302,2022/12/13 12:30:44.552,2022/12/13 12:30:44.802,2022/12/13 12:30:45.052,2022/12/13 12:30:45.302,2022/12/13 12:30:45.553,2022/12/13 12:30:45.803,2022/12/13 12:30:46.053,2022/12/13 12:30:46.304,2022/12/13 12:30:46.554,...,25.301,25.301,25.300,25.300,25.301,25.301,25.301,25.302,25.301,25.301
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2346,2022/12/13 16:37:24.802,2022/12/13 16:37:25.052,2022/12/13 16:37:25.302,2022/12/13 16:37:25.552,2022/12/13 16:37:25.802,2022/12/13 16:37:26.053,2022/12/13 16:37:26.303,2022/12/13 16:37:26.554,2022/12/13 16:37:26.804,2022/12/13 16:37:27.054,...,14825.801,14825.801,14825.800,14825.800,14825.801,14825.801,14825.802,14825.802,14825.801,14825.801
2347,2022/12/13 16:37:31.127,2022/12/13 16:37:31.377,2022/12/13 16:37:31.627,2022/12/13 16:37:31.877,2022/12/13 16:37:32.127,2022/12/13 16:37:32.378,2022/12/13 16:37:32.628,2022/12/13 16:37:32.879,2022/12/13 16:37:33.129,2022/12/13 16:37:33.379,...,14832.126,14832.126,14832.125,14832.125,14832.126,14832.126,14832.127,14832.127,14832.126,14832.126
2348,2022/12/13 16:37:37.452,2022/12/13 16:37:37.702,2022/12/13 16:37:37.952,2022/12/13 16:37:38.202,2022/12/13 16:37:38.452,2022/12/13 16:37:38.703,2022/12/13 16:37:38.953,2022/12/13 16:37:39.204,2022/12/13 16:37:39.454,2022/12/13 16:37:39.704,...,14838.451,14838.451,14838.450,14838.450,14838.451,14838.451,14838.452,14838.452,14838.451,14838.451
2349,2022/12/13 16:37:43.777,2022/12/13 16:37:44.027,2022/12/13 16:37:44.277,2022/12/13 16:37:44.527,2022/12/13 16:37:44.777,2022/12/13 16:37:45.028,2022/12/13 16:37:45.278,2022/12/13 16:37:45.528,2022/12/13 16:37:45.779,2022/12/13 16:37:46.029,...,14844.776,14844.776,14844.775,14844.775,14844.776,14844.776,14844.776,14844.777,14844.776,NaN
2350,2022/12/13 16:37:50.102,2022/12/13 16:37:50.352,2022/12/13 16:37:50.602,2022/12/13 16:37:50.852,2022/12/13 16:37:51.102,2022/12/13 16:37:51.353,2022/12/13 16:37:51.603,2022/12/13 16:37:51.854,2022/12/13 16:37:52.104,2022/12/13 16:37:52.354,...,14851.101,14851.101,14851.100,14851.100,14851.101,14851.101,14851.102,14851.102,14851.101,14851.101

In [3]:
#reading the Emission current, pressures
vaclog=pd.read_csv("vaclog", sep="\t")
vaclog.head()
#adding an elapsed time column
timestamp=[]
for i in vaclog["Time"]:
    timestamp.append(i)
#making the column into a datetime object
timestamps=pd.to_datetime(vaclog["Time"],format="%d/%m/%Y %H:%M:%S")
runtime=(timestamps-timestamps[0]).dt.total_seconds()    
vaclog.insert(2,"Elapsed time",runtime)
vaclog.drop(index=vaclog.index[0], 
        axis=0, 
        inplace=True)

vaclog.head()

,Live comments,Time,Elapsed time,injection 100mbar,Barion_2,Barion_1,DUAL experiment,DUAL insulation,injection 1mbar,helium,T-platinum,T-CERNOX,I_emission,I_grid
1,NaN,13/12/2022 10:16:52,7.0,-0.047109,1.610000e-09,1.700000e-09,4.996000e-09,3.883000e-07,0.79667,264.0,-5.163,4270.802,NaN,NaN
2,NaN,13/12/2022 10:16:59,14.0,-0.049523,1.610000e-09,1.710000e-09,4.996000e-09,3.887000e-07,0.79667,264.0,-5.387,4271.251,NaN,NaN
3,NaN,13/12/2022 10:17:06,21.0,-0.050807,1.620000e-09,1.720000e-09,4.996000e-09,3.887000e-07,0.79667,265.0,-5.163,4271.700,NaN,NaN
4,NaN,13/12/2022 10:17:14,29.0,-0.046664,1.620000e-09,1.730000e-09,4.996000e-09,3.887000e-07,0.79667,264.0,-5.050,4272.261,NaN,NaN
5,NaN,13/12/2022 10:17:21,36.0,-0.046688,1.620000e-09,1.730000e-09,4.996000e-09,3.892000e-07,0.79667,265.0,-5.050,4271.139,NaN,NaN

In [4]:
#Reading in the HiVolta measurement file 
hv = pd.read_csv("hv log", sep=",")
#hv.drop(columns=["Vmon1","Vmon2","Vmon3","Vmon4","Vmon5","Vmon6","Vmon7","Vmon8","Imon3","Imon4","Imon5","Imon6","Imon7","Imon8","Comments1"], inplace=True)
hv["hv_grid"]=[element * 1e-6 for element in hv["IMon1"]]
hv["em"]=[element * 1e-6 for element in hv["IMon2"]]
hv.drop(hv.columns[hv.columns.str.contains('Unnamed',case = False)],axis = 1, inplace = True)
hv["em"]=abs(hv["em"])
hv["hv_grid"]=abs(hv["hv_grid"])

#adding an elapsed time column
timestamp=[]
for i in hv["Time"]:
    timestamp.append(i)
    
#making the column into a datetime object
timestamps=pd.to_datetime(hv["Time"],format="%H:%M:%S.%f")
runtime=(timestamps-timestamps[0]).dt.total_seconds()    
hv.insert(2,"Elapsed time",runtime)
hv.drop(index=hv.index[0], 
        axis=0, 
        inplace=True)

hv.describe()

,Elapsed time,VMon1,VMon2,VMon3,VMon4,VMon5,VMon6,VMon7,VMon8,IMon1,IMon2,IMon3,IMon4,IMon5,IMon6,IMon7,IMon8,hv_grid,em
count,17990.000000,17990.000000,17990.000000,17990.000000,17990.000000,17990.000000,17990.0,17990.0,17990.000000,17990.000000,17990.000000,17990.000000,17990.000000,17990.000000,17990.000000,17990.000000,17990.000000,1.799000e+04,1.799000e+04
mean,10736.791928,148.642030,72.602601,723.543123,723.567679,723.454823,0.0,0.0,0.010310,-0.170448,0.631303,23.885902,23.903297,23.900375,-0.012947,-0.028290,-0.011917,1.833553e-07,6.376525e-07
std,6218.629470,228.322833,44.641961,447.191660,447.260362,447.348303,0.0,0.0,0.009995,0.211052,0.731377,14.795187,14.808843,14.803129,0.002747,0.001214,0.001854,1.999397e-07,7.258474e-07
min,1.185000,0.000000,0.080000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,-0.593300,-3.616800,-1.335800,-0.948500,-0.585400,-0.018700,-0.031400,-0.016800,0.000000e+00,9.000000e-10
25%,5331.956250,0.060000,0.080000,0.080000,0.120000,0.000000,0.0,0.0,0.000000,-0.407500,0.011000,0.006200,0.002700,0.008700,-0.015500,-0.029400,-0.012700,4.500000e-09,1.100000e-08
50%,10725.534500,0.140000,100.080000,1000.040000,1000.160000,1000.160000,0.0,0.0,0.020000,-0.003900,0.028700,32.656100,32.684800,32.673100,-0.012200,-0.028300,-0.011700,2.110000e-08,2.870000e-08
75%,16126.438250,499.960000,100.080000,1000.060000,1000.180000,1000.180000,0.0,0.0,0.020000,0.020000,1.418400,33.671900,33.698425,33.689800,-0.011100,-0.027300,-0.010800,4.076000e-07,1.419700e-06
max,21520.028000,499.980000,100.160000,1000.080000,1000.200000,1000.180000,0.0,0.0,0.020000,0.525300,3.293600,34.384600,34.409100,34.406300,-0.008000,-0.025000,-0.007700,5.933000e-07,3.616800e-06

### Data processing

In [5]:
#Temperature curve for CERNOX - for temp stability
A=[230.317302,-6170.1513,71837.9529,-477946.76,2.003668910085786e+6,-5.488690193047771e+6,9.830475663897528e+6,-1.111226817786569e+7,7.202477878914065e+6,-2.04194551328507e+6]
#specify fit parameters A, data (Resistance values)
def polyfit(params,data):
    total=[]
    for j in data: 
        exp=0
        for i in range(len(params)):
            exp += (params[i]/(math.log10(j))**i)
        total.append(10**exp)
    return(total)

In [27]:
#Filtering background signal

#Find the timestamp where emission was turned on and off
print("Result 1:",hv.loc[hv["Comment"]=="grid transparent again"])
print("Result 2:", hv.loc[hv["Comment"]=="grid repelling again"])
x=pd.Timestamp(2022, 12, 13, 14,7,8)
y=pd.Timestamp(2022, 12, 13, 12,54, 58)

#then find the time value closest to it in the MID scan file 
print("\n","Result 3:",mid.iloc[(pd.to_datetime(mid['mass 2.0_time'],format="%Y/%m/%d %H:%M:%S") - x).abs().argsort(),:])
print("\n","Result 4:",mid.iloc[(pd.to_datetime(mid['mass 2.0_time'],format="%Y/%m/%d %H:%M:%S") - y).abs().argsort(),:])

#take a mass with a signal known to be in the background
bck=np.mean(mid["mass 40.0_value"])

#apply background correction to the rest of the mass spectrum
mid["mass 2, corr"]=mid["mass 2.0_value"]-bck


#From the signal, get the partial pressures 
h2_sens=2.13e-2
p_h2=mid["mass 2, corr"][920:]/h2_sens
print(p_h2.describe())

#baseline for partial pressure delta
base_h2=mid["mass 2, corr"][236:250]/h2_sens
base_h2.describe()

Result 1:              Date          Time  Elapsed time  VMon1   VMon2    VMon3  \
10444  13/12/2022  14:07:08.510     12465.971   0.08  100.06  1000.04
10445  13/12/2022  14:07:09.711     12467.172   0.06  100.06  1000.04
10446  13/12/2022  14:07:10.914     12468.375   0.06  100.06  1000.04
10447  13/12/2022  14:07:12.112     12469.573   0.06  100.06  1000.04

         VMon4    VMon5  VMon6  VMon7  ...   IMon2    IMon3    IMon4    IMon5  \
10444  1000.18  1000.18    0.0    0.0  ...  1.4491  33.0223  33.0522  33.0445
10445  1000.18  1000.18    0.0    0.0  ...  1.4458  33.0235  33.0509  33.0445
10446  1000.18  1000.18    0.0    0.0  ...  1.4526  33.0257  33.0509  33.0475
10447  1000.18  1000.18    0.0    0.0  ...  1.4550  33.0261  33.0509  33.0497

        IMon6   IMon7   IMon8                 Comment       hv_grid        em
10444 -0.0087 -0.0277 -0.0124  grid transparent again  3.893000e-07  0.000001
10445 -0.0087 -0.0277 -0.0124  grid transparent again  3.893000e-07  0.000001
10446 -0.0087 -0.0277 -0.0124  grid transparent again  3.901000e-07  0.000001
10447 -0.0087 -0.0274 -0.0124  grid transparent again  3.937000e-07  0.000001

[4 rows x 22 columns]
Result 2:             Date          Time  Elapsed time   VMon1   VMon2    VMon3  \
6839  13/12/2022  12:54:58.006      8135.467  160.60  100.14  1000.04
6840  13/12/2022  12:54:59.199      8136.660  291.22  100.12  1000.04
6841  13/12/2022  12:55:00.401      8137.862  431.38  100.14  1000.04
6842  13/12/2022  12:55:01.603      8139.064  499.26  100.14  1000.04

        VMon4    VMon5  VMon6  VMon7  ...   IMon2    IMon3    IMon4    IMon5  \
6839  1000.16  1000.18    0.0    0.0  ...  0.3928  31.8576  31.8685  31.7653
6840  1000.16  1000.18    0.0    0.0  ...  0.0719  31.8538  31.8398  31.7653
6841  1000.16  1000.18    0.0    0.0  ...  0.0642  31.8530  31.8237  31.7653
6842  1000.16  1000.18    0.0    0.0  ...  0.0486  31.8526  31.8110  31.7653

       IMon6   IMon7   IMon8               Comment       hv_grid            em
6839 -0.0111 -0.0289 -0.0090  grid repelling again  4.767000e-07  3.928000e-07
6840 -0.0111 -0.0289 -0.0090  grid repelling again  5.045000e-07  7.190000e-08
6841 -0.0111 -0.0289 -0.0092  grid repelling again  5.229000e-07  6.420000e-08
6842 -0.0111 -0.0289 -0.0092  grid repelling again  1.008000e-07  4.860000e-08

[4 rows x 22 columns]

 Result 3:                 mass 2.0_time  mass 2.0_value            mass 4.0_time  \
920   2022/12/13 14:07:05.352    2.698410e-11  2022/12/13 14:07:05.602
921   2022/12/13 14:07:11.677    2.711420e-11  2022/12/13 14:07:11.927
919   2022/12/13 14:06:59.027    2.726630e-11  2022/12/13 14:06:59.277
922   2022/12/13 14:07:18.002    2.684330e-11  2022/12/13 14:07:18.252
918   2022/12/13 14:06:52.702    2.348600e-11  2022/12/13 14:06:52.952
...                       ...             ...                      ...
2346  2022/12/13 16:37:24.802    2.352630e-11  2022/12/13 16:37:25.052
2347  2022/12/13 16:37:31.127    2.349300e-11  2022/12/13 16:37:31.377
2348  2022/12/13 16:37:37.452    2.348820e-11  2022/12/13 16:37:37.702
2349  2022/12/13 16:37:43.777    2.362090e-11  2022/12/13 16:37:44.027
2350  2022/12/13 16:37:50.102    2.355700e-11  2022/12/13 16:37:50.352

      mass 4.0_value            mass 5.5_time  mass 5.5_value  \
920     6.137000e-13  2022/12/13 14:07:05.852    1.700000e-14
921     6.051000e-13  2022/12/13 14:07:12.177    1.380000e-14
919     6.098000e-13  2022/12/13 14:06:59.527    2.310000e-14
922     6.094000e-13  2022/12/13 14:07:18.502    1.380000e-14
918     5.897000e-13  2022/12/13 14:06:53.202    1.960000e-14
...              ...                      ...             ...
2346    5.759000e-13  2022/12/13 16:37:25.302    2.350000e-14
2347    5.958000e-13  2022/12/13 16:37:31.627    1.680000e-14
2348    5.757000e-13  2022/12/13 16:37:37.952    1.280000e-14
2349    5.917000e-13  2022/12/13 16:37:44.277    1.790000e-14
2350    5.944000e-13  2022/12/13 16:37:50.602    1.700000e-14

               mass 12.0_time  mass 12.0_value           mass 15.0_time  \
920   2022/12/13 14:07:06.102     2.183000e-13  2022/12/13 14:07:06.352
921   2022/12/13 14:07:12.427     2.727000e-13  2022/12/13 14:07:12.677
919   2022/12/13 14:06:59.777     2.349000e-13  2022/12/13 14:07:00.027
922   2022/12/13 14:07:18.752     2.528000e-13  2022/12/13 14:07:19.002
918   2022/12/13 14:06:53.452     2.165000e-13  2022/12/13 14:06:53.702
...                       ...              ...                      ...
2346  2022/12/13 16:37:25.552     2.520000e-13  2022/12/13 16:37:25.802
2347  2022/12/13 16:37:31.877     2.311000e-13  2022/12/13 16:37:32.127
2348  2022/12/13 16:37:38.202     2.260000e-13  2022/12/13 16:37:38.452
2349  2022/12/13 16:37:44.527     2.110000e-13  2022/12/13 16:37:44.777
2350  2022/12/13 16:37:50.852     2.603000e-13  2022/12/13 16:37:51.102

      mass 15.0_value  ... mass 18.0_value           mass 28.0_time  \
920      4.940000e-14  ...    7.096000e-13  2022/12/13 14:07:07.103
921      3.470000e-14  ...    7.717000e-13  2022/12/13 14:07:13.428
919      1.940000e-14  ...    7.538000e-13  2022/12/13 14:07:00.779
922      2.390000e-14  ...    7.216000e-13  2022/12/13 14:07:19.753
918      1.870000e-14  ...    7.005000e-13  2022/12/13 14:06:54.454
...               ...  ...             ...                      ...
2346     4.210000e-14  ...    9.112000e-13  2022/12/13 16:37:26.554
2347     3.470000e-14  ...    8.659000e-13  2022/12/13 16:37:32.879
2348     2.930000e-14  ...    9.075000e-13  2022/12/13 16:37:39.204
2349     3.120000e-14  ...    9.278000e-13  2022/12/13 16:37:45.528
2350     3.740000e-14  ...    8.813000e-13  2022/12/13 16:37:51.854

     mass 28.0_value           mass 32.0_time mass 32.0_value  \
920     1.323500e-12  2022/12/13 14:07:07.354    3.560000e-14
921     1.306900e-12  2022/12/13 14:07:13.679    2.610000e-14
919     1.319800e-12  2022/12/13 14:07:01.029    4.060000e-14
922     1.310300e-12  2022/12/13 14:07:20.004    2.710000e-14
918     1.206300e-12  2022/12/13 14:06:54.704    2.660000e-14
...              ...                      ...             ...
2346    1.281500e-12  2022/12/13 16:37:26.804    2.380000e-14
2347    1.245000e-12  2022/12/13 16:37:33.129    2.210000e-14
2348    1.243200e-12  2022/12/13 16:37:39.454    3.860000e-14
2349    1.198800e-12  2022/12/13 16:37:45.779    2.680000e-14
2350    1.219400e-12  2022/12/13 16:37:52.104    2.480000e-14

               mass 40.0_time mass 40.0_value           mass 44.0_time  \
920   2022/12/13 14:07:07.604    1.580000e-14  2022/12/13 14:07:08.355
921   2022/12/13 14:07:13.929    1.630000e-14  2022/12/13 14:07:14.680
919   2022/12/13 14:07:01.279    1.600000e-14                      NaN
922   2022/12/13 14:07:20.254    1.640000e-14                      NaN
918   2022/12/13 14:06:54.954    2.550000e-14  2022/12/13 14:06:55.705
...                       ...             ...                      ...
2346  2022/12/13 16:37:27.054    2.020000e-14  2022/12/13 16:37:27.805
2347  2022/12/13 16:37:33.379    2.030000e-14  2022/12/13 16:37:34.130
2348  2022/12/13 16:37:39.704    2.220000e-14  2022/12/13 16:37:40.455
2349  2022/12/13 16:37:46.029    1.880000e-14                      NaN
2350  2022/12/13 16:37:52.354    2.000000e-14  2022/12/13 16:37:53.105

     mass 44.0_value  mass 2, corr
920     5.370000e-14  2.696644e-11
921     5.370000e-14  2.709654e-11
919              NaN  2.724864e-11
922              NaN  2.682564e-11
918     1.075000e-13  2.346834e-11
...              ...           ...
2346    5.370000e-14  2.350864e-11
2347    3.225000e-13  2.347534e-11
2348    3.762000e-13  2.347054e-11
2349             NaN  2.360324e-11
2350    5.370000e-14  2.353934e-11

[2349 rows x 23 columns]

 Result 4:                 mass 2.0_time  mass 2.0_value            mass 4.0_time  \
236   2022/12/13 12:54:59.052    2.956840e-11  2022/12/13 12:54:59.302
235   2022/12/13 12:54:52.727    3.239720e-11  2022/12/13 12:54:52.977
237   2022/12/13 12:55:05.377    2.919800e-11  2022/12/13 12:55:05.627
234   2022/12/13 12:54:46.402    3.294550e-11  2022/12/13 12:54:46.652
238   2022/12/13 12:55:11.702    2.922810e-11  2022/12/13 12:55:11.952
...                       ...             ...                      ...
2346  2022/12/13 16:37:24.802    2.352630e-11  2022/12/13 16:37:25.052
2347  2022/12/13 16:37:31.127    2.349300e-11  2022/12/13 16:37:31.377
2348  2022/12/13 16:37:37.452    2.348820e-11  2022/12/13 16:37:37.702
2349  2022/12/13 16:37:43.777    2.362090e-11  2022/12/13 16:37:44.027
2350  2022/12/13 16:37:50.102    2.355700e-11  2022/12/13 16:37:50.352

      mass 4.0_value            mass 5.5_time  mass 5.5_value  \
236     1.406700e-12  2022/12/13 12:54:59.552    1.580000e-14
235     1.561500e-12  2022/12/13 12:54:53.227    1.280000e-14
237     1.429500e-12  2022/12/13 12:55:05.877    1.410000e-14
234     1.577600e-12  2022/12/13 12:54:46.902    1.290000e-14
238     1.417300e-12  2022/12/13 12:55:12.202    1.260000e-14
...              ...                      ...             ...
2346    5.759000e-13  2022/12/13 16:37:25.302    2.350000e-14
2347    5.958000e-13  2022/12/13 16:37:31.627    1.680000e-14
2348    5.757000e-13  2022/12/13 16:37:37.952    1.280000e-14
2349    5.917000e-13  2022/12/13 16:37:44.277    1.790000e-14
2350    5.944000e-13  2022/12/13 16:37:50.602    1.700000e-14

               mass 12.0_time  mass 12.0_value           mass 15.0_time  \
236   2022/12/13 12:54:59.802     3.469000e-13  2022/12/13 12:55:00.052
235   2022/12/13 12:54:53.477     1.828000e-13  2022/12/13 12:54:53.727
237   2022/12/13 12:55:06.127     3.598000e-13  2022/12/13 12:55:06.377
234   2022/12/13 12:54:47.152     3.653000e-13  2022/12/13 12:54:47.402
238   2022/12/13 12:55:12.452     3.349000e-13  2022/12/13 12:55:12.702
...                       ...              ...                      ...
2346  2022/12/13 16:37:25.552     2.520000e-13  2022/12/13 16:37:25.802
2347  2022/12/13 16:37:31.877     2.311000e-13  2022/12/13 16:37:32.127
2348  2022/12/13 16:37:38.202     2.260000e-13  2022/12/13 16:37:38.452
2349  2022/12/13 16:37:44.527     2.110000e-13  2022/12/13 16:37:44.777
2350  2022/12/13 16:37:50.852     2.603000e-13  2022/12/13 16:37:51.102

      mass 15.0_value  ... mass 18.0_value           mass 28.0_time  \
236      1.365000e-13  ...    1.198300e-12  2022/12/13 12:55:00.803
235      1.320000e-13  ...    1.277200e-12  2022/12/13 12:54:54.478
237      1.571000e-13  ...    1.220400e-12  2022/12/13 12:55:07.128
234      1.545000e-13  ...    1.221300e-12  2022/12/13 12:54:48.153
238      1.256000e-13  ...    1.217300e-12  2022/12/13 12:55:13.453
...               ...  ...             ...                      ...
2346     4.210000e-14  ...    9.112000e-13  2022/12/13 16:37:26.554
2347     3.470000e-14  ...    8.659000e-13  2022/12/13 16:37:32.879
2348     2.930000e-14  ...    9.075000e-13  2022/12/13 16:37:39.204
2349     3.120000e-14  ...    9.278000e-13  2022/12/13 16:37:45.528
2350     3.740000e-14  ...    8.813000e-13  2022/12/13 16:37:51.854

     mass 28.0_value           mass 32.0_time mass 32.0_value  \
236     2.426000e-12  2022/12/13 12:55:01.054    1.729000e-13
235     2.491600e-12  2022/12/13 12:54:54.729    1.672000e-13
237     2.435800e-12  2022/12/13 12:55:07.379    2.016000e-13
234     2.518100e-12  2022/12/13 12:54:48.404    1.784000e-13
238     2.412000e-12  2022/12/13 12:55:13.704    1.819000e-13
...              ...                      ...             ...
2346    1.281500e-12  2022/12/13 16:37:26.804    2.380000e-14
2347    1.245000e-12  2022/12/13 16:37:33.129    2.210000e-14
2348    1.243200e-12  2022/12/13 16:37:39.454    3.860000e-14
2349    1.198800e-12  2022/12/13 16:37:45.779    2.680000e-14
2350    1.219400e-12  2022/12/13 16:37:52.104    2.480000e-14

               mass 40.0_time mass 40.0_value           mass 44.0_time  \
236   2022/12/13 12:55:01.304    1.410000e-14  2022/12/13 12:55:02.055
235   2022/12/13 12:54:54.979    1.590000e-14  2022/12/13 12:54:55.730
237   2022/12/13 12:55:07.629    1.480000e-14  2022/12/13 12:55:08.380
234   2022/12/13 12:54:48.654    1.610000e-14  2022/12/13 12:54:49.405
238   2022/12/13 12:55:13.954    1.150000e-14  2022/12/13 12:55:14.705
...                       ...             ...                      ...
2346  2022/12/13 16:37:27.054    2.020000e-14  2022/12/13 16:37:27.805
2347  2022/12/13 16:37:33.379    2.030000e-14  2022/12/13 16:37:34.130
2348  2022/12/13 16:37:39.704    2.220000e-14  2022/12/13 16:37:40.455
2349  2022/12/13 16:37:46.029    1.880000e-14                      NaN
2350  2022/12/13 16:37:52.354    2.000000e-14  2022/12/13 16:37:53.105

     mass 44.0_value  mass 2, corr
236     7.525000e-13  2.955074e-11
235     4.300000e-13  3.237954e-11
237     3.225000e-13  2.918034e-11
234     6.987000e-13  3.292784e-11
238     6.987000e-13  2.921044e-11
...              ...           ...
2346    5.370000e-14  2.350864e-11
2347    3.225000e-13  2.347534e-11
2348    3.762000e-13  2.347054e-11
2349             NaN  2.360324e-11
2350    5.370000e-14  2.353934e-11

[2349 rows x 23 columns]
count    1.429000e+03
mean     1.133486e-09
std      4.507809e-11
min      1.053880e-09
25%      1.104983e-09
50%      1.125523e-09
75%      1.158279e-09
max      1.275114e-09
Name: mass 2, corr, dtype: float64

count    1.400000e+01
mean     1.361414e-09
std      7.841284e-12
min      1.347058e-09
25%      1.354979e-09
50%      1.363145e-09
75%      1.368414e-09
max      1.371410e-09
Name: mass 2, corr, dtype: float64

### Plotting

In [6]:
#Plotting the all the relevant MID spectrums
plt.figure(figsize=(14,8))
plt.plot(time['Elapsed time, mass 2'],mid["mass 2.0_value"],marker=".", markersize=4,label='M2')
plt.plot(time['Elapsed time, mass 4'],mid["mass 4.0_value"],marker=".", markersize=4,label='M4')
plt.plot(time['Elapsed time, mass 12'],mid["mass 12.0_value"],marker=".", markersize=4,label='M14')
plt.plot(time['Elapsed time, mass 16'],mid["mass 16.0_value"],marker=".", markersize=4,label='M16')
plt.plot(time['Elapsed time, mass 18'],mid["mass 18.0_value"],marker=".", markersize=4,label='M18')
plt.plot(time['Elapsed time, mass 28'],mid["mass 28.0_value"],marker=".", markersize=4,label='M28')
plt.plot(time['Elapsed time, mass 32'],mid["mass 32.0_value"],marker=".", markersize=4,label='M32')
plt.plot(time['Elapsed time, mass 40'],mid["mass 40.0_value"],marker=".", markersize=4,label='M40')
plt.plot(time["Elapsed time, mass 44"],mid["mass 44.0_value"],marker=".", markersize=4,label='M44')

plt.xlabel('Elapsed time (s)')
plt.ylabel('Ion current (A)')
plt.legend(title="Mol masses", loc="upper right")
plt.title("MID scan 1 ML tech. surface pre-injection, EGA out, dynamic vacuum")
font = {'family': 'arial',
        'color':  'green',
        'weight': 'normal',
        'size': 12,
        }
plt.text(240, 6.1e-11, 'Base pressure gradient from injection', fontdict = font)
plt.text(2710, 1.7e-11, 'Grid repelling', fontdict = font)
plt.text(5900, 3e-11, 'Grid transparent', fontdict = font)
plt.text(8110, 1.7e-11, 'Grid repelling', fontdict = font)
plt.text(10000, 3e-11, 'Grid transparent', fontdict = font)
plt.yscale('log')

In [7]:
#plotting HiVolta log
plt.figure(figsize=(12,6))
plt.plot(hv["Elapsed time"],hv["hv_grid"],marker=".", markersize=4,label='Grid current')
plt.plot(hv["Elapsed time"],hv["em"],marker=".", markersize=4,label='Emission current')
plt.xlabel('Elapsed time (s)')
plt.ylabel('Current (A)')
plt.legend(loc="upper right")
plt.title("Current evolution with 1ML tech. surface pre-injection,EGA out, dynamic vacuum")


plt.yscale('log')

In [8]:
#Plotting BA2, BA1 pressure
plt.figure(figsize=(10,6))
plt.plot(vaclog["Elapsed time"],vaclog["Barion_2"],marker=".", markersize=4,label='Barion 2')
plt.plot(vaclog["Elapsed time"],vaclog["Barion_1"],marker=".", markersize=4,label='Barion 1')

plt.xlabel('Elapsed time (s)')
plt.ylabel('Pressure (mbar)')
plt.legend()
plt.title("Total pressure evolution with 1ML tech. surface pre-injection,EGA out, dynamic vacuum")
ax = plt.gca()
ax.set_yscale('log')
plt.tick_params(axis="y", which='minor')
plt.grid(visible=None, which='both', axis='both')
plt.show()

In [9]:
#Plotting the temp evolution
plt.figure()
plt.plot((vaclog["Elapsed time"]),polyfit(A,vaclog["T-CERNOX"]),marker=".", markersize=5,label='T-CERNOX')

plt.xlabel('Elapsed time (s)')
plt.ylabel('Temperature (K)')
plt.legend()
plt.title("Temperature evolution with 1ML tech. surface pre-injection,EGA out, dynamic vacuum")
plt.yscale('linear')

# Primary desorption calculation method
### Elena's formula for the cryo setup
$$
\eta=\frac{C_{H2}\cdot (\Delta p_1 - \Delta p_2)q_e}{k_B\cdot T \cdot I_e}
$$

Where $\Delta p_i=p(t)_i - p(t=0)_i$ and $i=1,2$
In the case of the 4K setup, we know the exact conductance of gasses. The formula above applies well.

Due to the EGA being fully retracted, it is safe to assume that the desorption takes place at approximately room temperature

In [32]:
#calculation delta_p-s
#TODO - fix negative value
dp1 = (np.mean(p_h2)-np.mean(base_h2))*100
print(dp1)

#Constants
k_B = 1.38e-23
T = 293
q_e = 1.6e-19
c_h2 = 37.91/1000
s_h2=42/1000
x_h2=1/((1/c_h2)+(1/s_h2))
print(x_h2)
#Emission current
#ignore the inrush current values
hv["em"].where(hv["em"] <= 1.5e-6, np.nan, inplace=True)

I_em = np.nanmean(hv["em"].nlargest(30))
print(I_em)
#Conductance for CO in m3/s
c_co=10.13/1000
c_co2 = 8.08/1000

-2.279285125260535e-08
0.01992516581153798
1.4993266666666665e-06

In [36]:
#Desorption yield
eta_h2 = (x_h2*dp1*q_e)/(k_B*T*I_em)
#eta_co = (c_co*(dp1-dp2)*q_e)/(k_B*T*I_em)
print("The desorption yield for H2 [mol/el]:",eta_h2,"\n",)#""The desorption yield for CO2 [mol/el]:",eta_co2)

The desorption yield for H2 [mol/el]: -0.011986092115735517