In [1]:
import pandas as pd
from scipy.optimize import curve_fit
from scipy.integrate import quad
import seaborn
seaborn.set(style='whitegrid')
import numpy as np
import math
import matplotlib.pyplot as plt
from matplotlib.ticker import LogFormatter
%matplotlib qt
# %matplotlib inline
from datetime import datetime, date

C:\Users\etiirine\Anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

## Reading in the data

In [2]:
#reading the Emission current, pressures
vaclog=pd.read_csv("warmup after power cut", sep="\t")
vaclog.head()

#adding an elapsed time column
timestamp=[]
for i in vaclog["Time"]:
    timestamp.append(i)
    
#making the column into a datetime object
timestamps=pd.to_datetime(vaclog["Time"],format="%d/%m/%Y %H:%M:%S")
runtime=(timestamps-timestamps[0]).dt.total_seconds()    
vaclog.insert(2,"Elapsed time",runtime)
vaclog.drop(index=vaclog.index[0], 
        axis=0, 
        inplace=True)

#creating a new df by dropping the rows where system was warm
cut_vaclog = vaclog.loc[vaclog["Elapsed time"] >= 3310]
cut_vaclog.head()

,Live comments,Time,Elapsed time,injection 100mbar,Barion_2,Barion_1,DUAL experiment,DUAL insulation,injection 1mbar,helium,T-platinum,T-CERNOX,I_emission,I_grid
479,NaN,06/02/2023 18:53:38,3312.0,65.775,2.080000e-07,9.950000e-07,5.486000e-07,7.416000e-07,1.1,0.0,-105.274,58.473,NaN,NaN
480,NaN,06/02/2023 18:53:45,3319.0,65.775,2.080000e-07,9.960000e-07,5.480000e-07,7.416000e-07,1.1,0.0,-105.387,58.698,NaN,NaN
481,NaN,06/02/2023 18:53:52,3326.0,65.775,2.080000e-07,9.960000e-07,5.486000e-07,7.416000e-07,1.1,0.0,-105.162,58.473,NaN,NaN
482,NaN,06/02/2023 18:53:59,3333.0,65.775,2.080000e-07,9.970000e-07,5.480000e-07,7.416000e-07,1.1,0.0,-105.387,58.698,NaN,NaN
483,NaN,06/02/2023 18:54:05,3339.0,65.775,2.080000e-07,9.970000e-07,5.486000e-07,7.416000e-07,1.1,0.0,-105.162,58.698,NaN,NaN

In [8]:
#read in the baseline mass scan

basel = pd.read_csv("post_powercut pumpdown mass scan2.tsv", sep="\t", skiprows=lambda x: x <=19,  on_bad_lines="skip")
basel.rename(columns={"Current": "Ion current"},inplace=True)
#basel.drop([0,1], inplace=True)
print(basel.head())

#bring the time data into a new df
# #add elapsed time columns
# def elapsed_time(df):
#     itr = 0
#     counter = len(df.columns)
#     masses = [2,4,5.5,12,15,16,18,28,32,40,44]
#     for i in df:
#         timestamp = pd.to_datetime(df[i], format="%Y/%m/%d %H:%M:%S.%f")
#         runtime = (timestamp-timestamp[2]).dt.total_seconds()
#         colname = "Elapsed time, mass {}".format(masses[itr]) 
#         df.insert(counter, colname, runtime)
#         itr += 1
#         counter += 1
#     return(df)
# elapsed_time(time1)

# #time["Elapsed time, mass 40"].describe()

        Mass   Ion current
0  99.900002  6.450000e-13
1  99.800003  5.160000e-13
2  99.699997  3.708000e-13
3  99.599998  6.396000e-13
4  99.500000  3.870000e-13

### Temperature conversion

In [4]:
#Temperature curve for CERNOX - for temp stability
A=[230.317302,-6170.1513,71837.9529,-477946.76,2.003668910085786e+6,-5.488690193047771e+6,9.830475663897528e+6,-1.111226817786569e+7,7.202477878914065e+6,-2.04194551328507e+6]
#specify fit parameters A, data (Resistance values)
def polyfit(params,data):
    total=[]
    for j in data: 
        exp=0
        for i in range(len(params)):
            exp += (params[i]/(math.log10(j))**i)
        total.append(10**exp)
    return(total)

### Trendline

In [5]:
#slice the observed data starting from the linear part
print(vaclog["Elapsed time"].shape)
print(vaclog["Barion_2"].shape)
x_slice = vaclog.loc[vaclog["Elapsed time"] >= 40000]
print(x_slice)
y_slice = vaclog["Barion_2"][5766:]
print(y_slice)

#generate new data
x_predict = np.arange(10,1000000,1)
z = np.polyfit(x_slice["Elapsed time"],y_slice,1)
fit = np.poly1d(z)
y_predicted = np.polyval(fit, x_predict)
slope = fit[0]
print(slope)
#plot a y=-x line
x = np.arange(10000,200000,1)
y = -2.5726405582157924e-08*x+1e-8

(83356,)
(83356,)
       Live comments                 Time  Elapsed time  injection 100mbar  \
5767             NaN  07/02/2023 05:05:07       40001.0             65.532
5768             NaN  07/02/2023 05:05:14       40008.0             65.532
5769             NaN  07/02/2023 05:05:21       40015.0             65.532
5770             NaN  07/02/2023 05:05:28       40022.0             65.532
5771             NaN  07/02/2023 05:05:35       40029.0             65.532
...              ...                  ...           ...                ...
83352            NaN  13/02/2023 11:18:25      580799.0             63.819
83353            NaN  13/02/2023 11:18:32      580806.0             63.819
83354            NaN  13/02/2023 11:18:39      580813.0             63.819
83355            NaN  13/02/2023 11:18:46      580820.0             63.819
83356            NaN  13/02/2023 11:18:53      580827.0             63.819

           Barion_2      Barion_1  DUAL experiment  DUAL insulation  \
5767   1.640000e-08  2.840000e-08     1.924000e-08     8.524000e-07
5768   1.640000e-08  2.840000e-08     1.964000e-08     8.534000e-07
5769   1.640000e-08  2.840000e-08     1.947000e-08     8.544000e-07
5770   1.640000e-08  2.840000e-08     1.952000e-08     8.534000e-07
5771   1.640000e-08  2.840000e-08     1.947000e-08     8.524000e-07
...             ...           ...              ...              ...
83352  1.540000e-08  4.410000e-09     8.647000e-09     2.095000e-06
83353  1.540000e-08  4.420000e-09     9.383000e-09     2.092000e-06
83354  1.540000e-08  4.410000e-09     8.986000e-09     2.092000e-06
83355  1.540000e-08  4.410000e-09     8.879000e-09     2.092000e-06
83356  1.540000e-08  4.410000e-09     9.216000e-09     2.092000e-06

       injection 1mbar  helium  T-platinum  T-CERNOX  I_emission  I_grid
5767               1.1     0.0     -87.093    70.033         NaN     NaN
5768               1.1     0.0     -87.317    70.146         NaN     NaN
5769               1.1     0.0     -87.205    70.258         NaN     NaN
5770               1.1     0.0     -87.205    70.146         NaN     NaN
5771               1.1     0.0     -87.429    70.258         NaN     NaN
...                ...     ...         ...       ...         ...     ...
83352              1.1     0.0    -113.804    54.545         NaN     NaN
83353              1.1     0.0    -113.580    54.545         NaN     NaN
83354              1.1     0.0    -113.692    54.433         NaN     NaN
83355              1.1     0.0    -113.467    54.433         NaN     NaN
83356              1.1     0.0    -113.692    54.545         NaN     NaN

[77590 rows x 14 columns]
5767     1.640000e-08
5768     1.640000e-08
5769     1.640000e-08
5770     1.640000e-08
5771     1.640000e-08
             ...
83352    1.540000e-08
83353    1.540000e-08
83354    1.540000e-08
83355    1.540000e-08
83356    1.540000e-08
Name: Barion_2, Length: 77590, dtype: float64
9.631489995724566e-09

### Plotting

In [6]:
#Plotting BA2, BA1 pressure exc time when warm
plt.figure(figsize=(10,6))
plt.plot(vaclog["Elapsed time"],vaclog["Barion_2"],marker=".", markersize=4,label='Barion 2')
plt.plot(vaclog["Elapsed time"],vaclog["Barion_1"],marker=".", markersize=4,label='Barion 1')
plt.plot(x_predict,y_predicted,marker="_", markersize=4,label='Fit')

plt.xlabel('Elapsed time (s)')
plt.ylabel('Pressure (mbar)')
plt.legend()
plt.title("Pumpdown pressure log")
ax = plt.gca()
ax.set_yscale('log')
ax.set_xscale('log')

plt.tick_params(axis="y", which='minor')
plt.grid(visible=None, which='both', axis='both')
plt.ylim(1e-10,1e-6)

plt.show()

In [19]:
#Plotting BA2, BA1 pressure exc time when warm
plt.figure(figsize=(10,6))
plt.plot(basel["Mass"],basel["Ion current"],marker=".", markersize=4)

plt.xlabel('Mass fraction (a.m.u)')
plt.ylabel('Ion current (A)')
plt.legend()
plt.title("Pumpdown mass scan 13.12.2023")
ax = plt.gca()
ax.set_yscale('log')
ax.set_xscale('linear')

plt.tick_params(axis="y", which='minor')
plt.tick_params(axis="x", which='minor')

plt.grid(True,which='both', axis='both')
plt.grid(True,which='minor', axis='x')

plt.show()

No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.

In [12]:
# Plotting the temp evolution exc warm part
plt.figure()
plt.plot((vaclog["Elapsed time"]/3600),polyfit(A,vaclog["T-CERNOX"]),marker=".", markersize=5,label='T-CERNOX')

plt.xlabel('Elapsed time (h)')
plt.ylabel('Temperature (K)')
plt.legend()
plt.title("Pumpdown temp log")
plt.yscale('linear')