In [1]:
import pandas as pd
from scipy.optimize import curve_fit
import seaborn
seaborn.set(style='whitegrid')
import numpy as np
import math
import matplotlib.pyplot as plt
from matplotlib.ticker import LogFormatter
%matplotlib qt
# %matplotlib inline
from datetime import datetime, date

C:\Users\etiirine\Anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

## Reading in the data

In [2]:
#read in the data
mid = pd.read_csv("MID.tsv", sep="\t", skiprows=lambda x: x <=11,  on_bad_lines="skip")
mid.drop([0,1], inplace=True)
print(mid.describe())
#bring the time data into a new df
time = pd.DataFrame(mid.iloc[:,0::2]) #- get every second column
print(time.describe())
#add elapsed time columns
def elapsed_time(df):
    itr = 0
    counter = len(df.columns)
    masses = [2,4,5.5,12,15,16,18,28,32,40,44]
    for i in df:
        timestamp = pd.to_datetime(df[i], format="%Y/%m/%d %H:%M:%S.%f")
        runtime = (timestamp-timestamp[2]).dt.total_seconds()
        colname = "Elapsed time, mass {}".format(masses[itr]) 
        df.insert(counter, colname, runtime)
        itr += 1
        counter += 1
    return(df)
elapsed_time(time)

#time["Elapsed time, mass 40"].describe()

       mass 2.0_value  mass 4.0_value  mass 5.5_value  mass 12.0_value  \
count    3.440000e+02    3.440000e+02    3.440000e+02     3.440000e+02
mean     2.001903e-11    8.151064e-13    1.875756e-14     1.871526e-13
std      9.808227e-13    2.147868e-13    5.398008e-15     5.745776e-14
min      1.875920e-11    5.053000e-13    9.100000e-15     1.409000e-13
25%      1.960000e-11    5.579500e-13    1.560000e-14     1.746750e-13
50%      2.002720e-11    9.553000e-13    1.820000e-14     1.820500e-13
75%      2.037458e-11    9.812250e-13    2.130000e-14     1.923000e-13
max      3.015050e-11    1.441500e-12    6.270000e-14     9.263000e-13

       mass 15.0_value  mass 16.0_value  mass 18.0_value  mass 28.0_value  \
count     3.440000e+02     3.440000e+02     3.440000e+02     3.440000e+02
mean      4.492936e-14     4.502933e-13     8.521137e-13     8.886044e-13
std       6.638411e-14     5.643933e-14     3.725470e-14     4.214157e-14
min       1.530000e-14     3.824000e-13     6.370000e-13     5.755000e-13
25%       2.537500e-14     4.350500e-13     8.353500e-13     8.712750e-13
50%       3.040000e-14     4.448000e-13     8.548000e-13     8.898500e-13
75%       3.687500e-14     4.571250e-13     8.741000e-13     9.107250e-13
max       1.131500e-12     1.131500e-12     1.087900e-12     1.131500e-12

       mass 32.0_value  mass 40.0_value  mass 44.0_value
count     3.440000e+02     3.440000e+02     2.800000e+01
mean      3.103721e-14     1.941017e-14     1.305143e-13
std       1.016889e-14     5.217786e-15     1.319952e-13
min       1.410000e-14     1.070000e-14     0.000000e+00
25%       2.540000e-14     1.620000e-14     4.027500e-14
50%       3.005000e-14     1.880000e-14     1.075000e-13
75%       3.520000e-14     2.180000e-14     1.612000e-13
max       1.137000e-13     6.720000e-14     4.837000e-13
                  mass 2.0_time            mass 4.0_time  \
count                       344                      344
unique                      344                      344
top     2022/12/13 17:34:18.708  2022/12/13 17:34:18.958
freq                          1                        1

                  mass 5.5_time           mass 12.0_time  \
count                       344                      344
unique                      344                      344
top     2022/12/13 17:34:19.208  2022/12/13 17:34:19.458
freq                          1                        1

                 mass 15.0_time           mass 16.0_time  \
count                       344                      344
unique                      344                      344
top     2022/12/13 17:34:19.708  2022/12/13 17:34:19.958
freq                          1                        1

                 mass 18.0_time           mass 28.0_time  \
count                       344                      344
unique                      344                      344
top     2022/12/13 17:34:20.209  2022/12/13 17:34:20.459
freq                          1                        1

                 mass 32.0_time           mass 40.0_time  \
count                       344                      344
unique                      344                      344
top     2022/12/13 17:34:20.709  2022/12/13 17:34:20.960
freq                          1                        1

                 mass 44.0_time
count                        28
unique                       28
top     2022/12/13 17:34:47.011
freq                          1

,mass 2.0_time,mass 4.0_time,mass 5.5_time,mass 12.0_time,mass 15.0_time,mass 16.0_time,mass 18.0_time,mass 28.0_time,mass 32.0_time,mass 40.0_time,...,"Elapsed time, mass 4","Elapsed time, mass 5.5","Elapsed time, mass 12","Elapsed time, mass 15","Elapsed time, mass 16","Elapsed time, mass 18","Elapsed time, mass 28","Elapsed time, mass 32","Elapsed time, mass 40","Elapsed time, mass 44"
2,2022/12/13 17:34:18.708,2022/12/13 17:34:18.958,2022/12/13 17:34:19.208,2022/12/13 17:34:19.458,2022/12/13 17:34:19.708,2022/12/13 17:34:19.958,2022/12/13 17:34:20.209,2022/12/13 17:34:20.459,2022/12/13 17:34:20.709,2022/12/13 17:34:20.960,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,NaN
3,2022/12/13 17:34:25.033,2022/12/13 17:34:25.283,2022/12/13 17:34:25.533,2022/12/13 17:34:25.783,2022/12/13 17:34:26.033,2022/12/13 17:34:26.283,2022/12/13 17:34:26.534,2022/12/13 17:34:26.784,2022/12/13 17:34:27.035,2022/12/13 17:34:27.285,...,6.325,6.325,6.325,6.325,6.325,6.325,6.325,6.326,6.325,NaN
4,2022/12/13 17:34:31.358,2022/12/13 17:34:31.608,2022/12/13 17:34:31.858,2022/12/13 17:34:32.108,2022/12/13 17:34:32.358,2022/12/13 17:34:32.609,2022/12/13 17:34:32.859,2022/12/13 17:34:33.109,2022/12/13 17:34:33.360,2022/12/13 17:34:33.610,...,12.650,12.650,12.650,12.650,12.651,12.650,12.650,12.651,12.650,NaN
5,2022/12/13 17:34:37.683,2022/12/13 17:34:37.933,2022/12/13 17:34:38.183,2022/12/13 17:34:38.433,2022/12/13 17:34:38.683,2022/12/13 17:34:38.934,2022/12/13 17:34:39.184,2022/12/13 17:34:39.434,2022/12/13 17:34:39.685,2022/12/13 17:34:39.935,...,18.975,18.975,18.975,18.975,18.976,18.975,18.975,18.976,18.975,NaN
6,2022/12/13 17:34:44.008,2022/12/13 17:34:44.258,2022/12/13 17:34:44.508,2022/12/13 17:34:44.758,2022/12/13 17:34:45.008,2022/12/13 17:34:45.259,2022/12/13 17:34:45.509,2022/12/13 17:34:45.759,2022/12/13 17:34:46.010,2022/12/13 17:34:46.260,...,25.300,25.300,25.300,25.300,25.301,25.300,25.300,25.301,25.300,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
341,2022/12/13 18:10:02.883,2022/12/13 18:10:03.133,2022/12/13 18:10:03.383,2022/12/13 18:10:03.633,2022/12/13 18:10:03.883,2022/12/13 18:10:04.134,2022/12/13 18:10:04.384,2022/12/13 18:10:04.634,2022/12/13 18:10:04.885,2022/12/13 18:10:05.135,...,2144.175,2144.175,2144.175,2144.175,2144.176,2144.175,2144.175,2144.176,2144.175,NaN
342,2022/12/13 18:10:09.208,2022/12/13 18:10:09.458,2022/12/13 18:10:09.708,2022/12/13 18:10:09.958,2022/12/13 18:10:10.208,2022/12/13 18:10:10.459,2022/12/13 18:10:10.709,2022/12/13 18:10:10.959,2022/12/13 18:10:11.210,2022/12/13 18:10:11.460,...,2150.500,2150.500,2150.500,2150.500,2150.501,2150.500,2150.500,2150.501,2150.500,NaN
343,2022/12/13 18:10:15.533,2022/12/13 18:10:15.783,2022/12/13 18:10:16.033,2022/12/13 18:10:16.283,2022/12/13 18:10:16.533,2022/12/13 18:10:16.784,2022/12/13 18:10:17.034,2022/12/13 18:10:17.284,2022/12/13 18:10:17.535,2022/12/13 18:10:17.785,...,2156.825,2156.825,2156.825,2156.825,2156.826,2156.825,2156.825,2156.826,2156.825,NaN
344,2022/12/13 18:10:21.858,2022/12/13 18:10:22.108,2022/12/13 18:10:22.358,2022/12/13 18:10:22.608,2022/12/13 18:10:22.858,2022/12/13 18:10:23.109,2022/12/13 18:10:23.359,2022/12/13 18:10:23.609,2022/12/13 18:10:23.860,2022/12/13 18:10:24.110,...,2163.150,2163.150,2163.150,2163.150,2163.151,2163.150,2163.150,2163.151,2163.150,NaN
345,2022/12/13 18:10:28.183,2022/12/13 18:10:28.433,2022/12/13 18:10:28.683,2022/12/13 18:10:28.933,2022/12/13 18:10:29.183,2022/12/13 18:10:29.434,2022/12/13 18:10:29.684,2022/12/13 18:10:29.934,2022/12/13 18:10:30.185,2022/12/13 18:10:30.435,...,2169.475,2169.475,2169.475,2169.475,2169.476,2169.475,2169.475,2169.476,2169.475,NaN

In [3]:
#reading the Emission current, pressures
vaclog=pd.read_csv("vaclog", sep="\t")
vaclog.head()
#adding an elapsed time column
timestamp=[]
for i in vaclog["Time"]:
    timestamp.append(i)
#making the column into a datetime object
timestamps=pd.to_datetime(vaclog["Time"],format="%d/%m/%Y %H:%M:%S")
runtime=(timestamps-timestamps[0]).dt.total_seconds()    
vaclog.insert(2,"Elapsed time",runtime)
vaclog.drop(index=vaclog.index[0], 
        axis=0, 
        inplace=True)

vaclog.head()

,Live comments,Time,Elapsed time,injection 100mbar,Barion_2,Barion_1,DUAL experiment,DUAL insulation,injection 1mbar,helium,T-platinum,T-CERNOX,I_emission,I_grid
1,NaN,13/12/2022 17:31:21,7.0,-0.047451,2.900000e-09,1.680000e-09,4.996000e-09,4.919000e-07,0.35245,197.0,-5.275,4288.198,NaN,NaN
2,NaN,13/12/2022 17:31:28,14.0,-0.046614,2.900000e-09,1.640000e-09,4.996000e-09,4.919000e-07,0.35244,197.0,-5.050,4286.403,NaN,NaN
3,NaN,13/12/2022 17:31:35,21.0,-0.050953,2.400000e-09,1.860000e-09,4.996000e-09,4.733000e-07,0.35245,196.0,-5.275,4286.739,NaN,NaN
4,NaN,13/12/2022 17:31:42,28.0,-0.046468,1.140000e-09,6.030000e-10,4.996000e-09,4.688000e-07,0.35244,196.0,-5.163,4286.515,NaN,NaN
5,NaN,13/12/2022 17:31:50,36.0,-0.046122,1.100000e-09,5.530000e-10,4.996000e-09,4.682000e-07,0.35245,196.0,-5.163,4286.178,NaN,NaN

In [4]:
#Reading in the HiVolta measurement file 
hv = pd.read_csv("hv log", sep=",")
#hv.drop(columns=["Vmon1","Vmon2","Vmon3","Vmon4","Vmon5","Vmon6","Vmon7","Vmon8","Imon3","Imon4","Imon5","Imon6","Imon7","Imon8","Comments1"], inplace=True)
hv["hv_grid"]=[element * 1e-6 for element in hv["IMon1"]]
hv["em"]=[element * 1e-6 for element in hv["IMon2"]]
hv.drop(hv.columns[hv.columns.str.contains('Unnamed',case = False)],axis = 1, inplace = True)
hv["em"]=abs(hv["em"])
hv["hv_grid"]=abs(hv["hv_grid"])

#adding an elapsed time column
timestamp=[]
for i in hv["Time"]:
    timestamp.append(i)
    
#making the column into a datetime object
timestamps=pd.to_datetime(hv["Time"],format="%H:%M:%S.%f")
runtime=(timestamps-timestamps[0]).dt.total_seconds()    
hv.insert(2,"Elapsed time",runtime)
hv.drop(index=hv.index[0], 
        axis=0, 
        inplace=True)

hv.describe()

,Elapsed time,VMon1,VMon2,VMon3,VMon4,VMon5,VMon6,VMon7,VMon8,IMon1,IMon2,IMon3,IMon4,IMon5,IMon6,IMon7,IMon8,hv_grid,em
count,1876.000000,1876.000000,1876.000000,1876.000000,1876.000000,1876.000000,1876.0,1876.0,1.876000e+03,1876.000000,1876.000000,1876.000000,1876.000000,1876.000000,1876.000000,1876.000000,1876.000000,1.876000e+03,1.876000e+03
mean,1249.441570,65.732974,62.403443,623.155245,622.758124,624.300181,0.0,0.0,2.000000e-02,-0.021023,0.083723,19.548143,19.555629,19.543000,-0.014207,-0.026659,-0.011533,3.117340e-08,1.106336e-07
std,651.487945,167.850925,48.440119,483.273820,483.345222,482.956009,0.0,0.0,1.422853e-16,0.054618,0.234227,15.108143,15.111161,15.107979,0.000717,0.000799,0.000785,4.952794e-08,2.227760e-07
min,1.178000,0.020000,0.060000,0.000000,0.000000,0.000000,0.0,0.0,2.000000e-02,-0.612000,-2.543700,-0.547300,-0.568800,-0.400800,-0.015600,-0.028300,-0.013200,0.000000e+00,0.000000e+00
25%,686.577250,0.080000,0.100000,0.140000,0.160000,0.000000,0.0,0.0,2.000000e-02,-0.044225,0.004900,0.008900,0.016200,0.008700,-0.014900,-0.027500,-0.012300,9.000000e-10,5.000000e-09
50%,1250.378000,0.080000,100.080000,1000.020000,1000.120000,1000.080000,0.0,0.0,2.000000e-02,-0.000900,0.019500,30.965600,30.996800,30.977000,-0.014200,-0.026300,-0.011400,1.930000e-08,1.167500e-07
75%,1813.010250,0.120000,100.080000,1000.060000,1000.200000,1000.160000,0.0,0.0,2.000000e-02,0.001100,0.155700,31.625250,31.612825,31.642125,-0.013600,-0.026100,-0.010900,4.500000e-08,1.567000e-07
max,2378.651000,499.940000,100.160000,1000.140000,1000.280000,1000.460000,0.0,0.0,2.000000e-02,0.526700,2.758500,31.852800,31.888200,31.824900,-0.013000,-0.024600,-0.009900,6.120000e-07,2.758500e-06

### Data processing

In [5]:
#Temperature curve for CERNOX - for temp stability
A=[230.317302,-6170.1513,71837.9529,-477946.76,2.003668910085786e+6,-5.488690193047771e+6,9.830475663897528e+6,-1.111226817786569e+7,7.202477878914065e+6,-2.04194551328507e+6]
#specify fit parameters A, data (Resistance values)
def polyfit(params,data):
    total=[]
    for j in data: 
        exp=0
        for i in range(len(params)):
            exp += (params[i]/(math.log10(j))**i)
        total.append(10**exp)
    return(total)

In [6]:
#Filtering background signal

#Find the timestamp where emission was turned on and off
print("Result 1:",hv.loc[hv["Comment"]=="emission on"])
print("Result 2:", hv.loc[hv["Comment"]=="grid repelling"])
x=pd.Timestamp(2022, 12, 13, 17,38,53)
y=pd.Timestamp(2022, 12, 13, 17, 45, 21)

#then find the time value closest to it in the MID scan file 
print("\n","Result 3:",mid.iloc[(pd.to_datetime(mid['mass 2.0_time'],format="%Y/%m/%d %H:%M:%S") - x).abs().argsort(),:])
print("\n","Result 4:",mid.iloc[(pd.to_datetime(mid['mass 2.0_time'],format="%Y/%m/%d %H:%M:%S") - y).abs().argsort(),:])

#take a mass with a signal known to be in the background
bck=np.mean(mid["mass 40.0_value"])

#apply background correction to the rest of the mass spectrum
mid["mass 2, corr"]=mid["mass 2.0_value"]-bck

 
#From the signal, get the partial pressures 
h2_sens=2.13e-2
p_h2=mid["mass 2, corr"][45:107]/h2_sens
print(p_h2.describe())

#baseline for partial pressure delta
base_h2=mid["mass 2, corr"][0:45]/h2_sens
base_h2.describe()

Result 1:            Date          Time  Elapsed time  VMon1   VMon2   VMon3   VMon4  \
339  13/12/2022  17:38:53.353       529.855   0.08  100.12  999.66  999.66
340  13/12/2022  17:38:54.536       531.038   0.10  100.12  999.66  999.66
341  13/12/2022  17:38:55.725       532.227   0.16  100.12  999.66  999.64
342  13/12/2022  17:38:56.969       533.471   0.08  100.12  999.68  999.70

      VMon5  VMon6  VMon7  ...   IMon2    IMon3    IMon4    IMon5   IMon6  \
339  641.82    0.0    0.0  ...  0.3700  26.3643  26.3879  26.3281 -0.0149
340  771.98    0.0    0.0  ...  0.3670  27.7330  27.7084  27.6982 -0.0149
341  902.14    0.0    0.0  ...  0.3773  28.6768  28.6777  28.6241 -0.0149
342  998.46    0.0    0.0  ...  0.4532  29.8831  29.8351  29.8594 -0.0149

      IMon7   IMon8      Comment       hv_grid            em
339 -0.0271 -0.0114  emission on  6.000000e-10  3.700000e-07
340 -0.0271 -0.0114  emission on  2.900000e-09  3.670000e-07
341 -0.0271 -0.0114  emission on  7.030000e-08  3.773000e-07
342 -0.0271 -0.0114  emission on  5.420000e-08  4.532000e-07

[4 rows x 22 columns]
Result 2:            Date          Time  Elapsed time   VMon1  VMon2    VMon3    VMon4  \
660  13/12/2022  17:45:18.633       915.135  401.32  100.1  1000.02  1000.14
661  13/12/2022  17:45:19.820       916.322  498.60  100.1  1000.02  1000.14
662  13/12/2022  17:45:21.023       917.525  499.88  100.1  1000.02  1000.14
663  13/12/2022  17:45:22.209       918.711  499.88  100.1  1000.02  1000.14

       VMon5  VMon6  VMon7  ...   IMon2    IMon3    IMon4    IMon5   IMon6  \
660  1000.12    0.0    0.0  ...  0.0375  31.8527  31.8170  31.7556 -0.0141
661  1000.12    0.0    0.0  ...  0.0277  31.8527  31.8172  31.7556 -0.0142
662  1000.12    0.0    0.0  ...  0.0200  31.8527  31.8188  31.7557 -0.0142
663  1000.12    0.0    0.0  ...  0.0195  31.8527  31.8190  31.7558 -0.0142

      IMon7   IMon8         Comment       hv_grid            em
660 -0.0277 -0.0114  grid repelling  5.267000e-07  3.750000e-08
661 -0.0277 -0.0114  grid repelling  2.248000e-07  2.770000e-08
662 -0.0277 -0.0114  grid repelling  2.610000e-08  2.000000e-08
663 -0.0277 -0.0114  grid repelling  2.430000e-08  1.950000e-08

[4 rows x 22 columns]

 Result 3:                mass 2.0_time  mass 2.0_value            mass 4.0_time  \
45   2022/12/13 17:38:50.683    2.048840e-11  2022/12/13 17:38:50.933
46   2022/12/13 17:38:57.008    2.134950e-11  2022/12/13 17:38:57.258
44   2022/12/13 17:38:44.358    2.052920e-11  2022/12/13 17:38:44.608
47   2022/12/13 17:39:03.333    2.101780e-11  2022/12/13 17:39:03.583
43   2022/12/13 17:38:38.033    2.044220e-11  2022/12/13 17:38:38.283
..                       ...             ...                      ...
341  2022/12/13 18:10:02.883    2.048890e-11  2022/12/13 18:10:03.133
342  2022/12/13 18:10:09.208    2.044700e-11  2022/12/13 18:10:09.458
343  2022/12/13 18:10:15.533    2.045180e-11  2022/12/13 18:10:15.783
344  2022/12/13 18:10:21.858    2.051530e-11  2022/12/13 18:10:22.108
345  2022/12/13 18:10:28.183    2.039380e-11  2022/12/13 18:10:28.433

     mass 4.0_value            mass 5.5_time  mass 5.5_value  \
45     1.011300e-12  2022/12/13 17:38:51.183    1.270000e-14
46     1.055900e-12  2022/12/13 17:38:57.508    1.180000e-14
44     9.961000e-13  2022/12/13 17:38:44.858    1.650000e-14
47     1.016700e-12  2022/12/13 17:39:03.833    1.850000e-14
43     9.752000e-13  2022/12/13 17:38:38.533    1.690000e-14
..              ...                      ...             ...
341    5.732000e-13  2022/12/13 18:10:03.383    1.590000e-14
342    5.593000e-13  2022/12/13 18:10:09.708    2.030000e-14
343    5.700000e-13  2022/12/13 18:10:16.033    1.950000e-14
344    5.495000e-13  2022/12/13 18:10:22.358    1.960000e-14
345    5.550000e-13  2022/12/13 18:10:28.683    2.290000e-14

              mass 12.0_time  mass 12.0_value           mass 15.0_time  \
45   2022/12/13 17:38:51.433     1.764000e-13  2022/12/13 17:38:51.683
46   2022/12/13 17:38:57.758     1.923000e-13  2022/12/13 17:38:58.008
44   2022/12/13 17:38:45.108     1.819000e-13  2022/12/13 17:38:45.358
47   2022/12/13 17:39:04.083     1.865000e-13  2022/12/13 17:39:04.333
43   2022/12/13 17:38:38.783     1.923000e-13  2022/12/13 17:38:39.033
..                       ...              ...                      ...
341  2022/12/13 18:10:03.633     1.795000e-13  2022/12/13 18:10:03.883
342  2022/12/13 18:10:09.958     1.635000e-13  2022/12/13 18:10:10.208
343  2022/12/13 18:10:16.283     1.567000e-13  2022/12/13 18:10:16.533
344  2022/12/13 18:10:22.608     1.952000e-13  2022/12/13 18:10:22.858
345  2022/12/13 18:10:28.933     2.028000e-13  2022/12/13 18:10:29.183

     mass 15.0_value  ...           mass 18.0_time  mass 18.0_value  \
45      3.760000e-14  ...  2022/12/13 17:38:52.184     7.932000e-13
46      2.660000e-14  ...  2022/12/13 17:38:58.509     8.610000e-13
44      3.380000e-14  ...  2022/12/13 17:38:45.859     8.397000e-13
47      2.430000e-14  ...  2022/12/13 17:39:04.834     8.555000e-13
43      2.250000e-14  ...  2022/12/13 17:38:39.534     8.691000e-13
..               ...  ...                      ...              ...
341     3.150000e-14  ...  2022/12/13 18:10:04.384     9.007000e-13
342     2.600000e-14  ...  2022/12/13 18:10:10.709     8.688000e-13
343     2.700000e-14  ...  2022/12/13 18:10:17.034     8.501000e-13
344     3.550000e-14  ...  2022/12/13 18:10:23.359     8.845000e-13
345     3.590000e-14  ...  2022/12/13 18:10:29.684     8.759000e-13

              mass 28.0_time  mass 28.0_value           mass 32.0_time  \
45   2022/12/13 17:38:52.434     8.994000e-13  2022/12/13 17:38:52.685
46   2022/12/13 17:38:58.759     8.376000e-13  2022/12/13 17:38:59.010
44   2022/12/13 17:38:46.110     9.263000e-13  2022/12/13 17:38:46.360
47   2022/12/13 17:39:05.084     8.764000e-13  2022/12/13 17:39:05.335
43   2022/12/13 17:38:39.785     9.406000e-13  2022/12/13 17:38:40.035
..                       ...              ...                      ...
341  2022/12/13 18:10:04.634     8.451000e-13  2022/12/13 18:10:04.885
342  2022/12/13 18:10:10.959     8.794000e-13  2022/12/13 18:10:11.210
343  2022/12/13 18:10:17.284     8.661000e-13  2022/12/13 18:10:17.535
344  2022/12/13 18:10:23.609     8.935000e-13  2022/12/13 18:10:23.860
345  2022/12/13 18:10:29.934     8.749000e-13  2022/12/13 18:10:30.185

     mass 32.0_value           mass 40.0_time  mass 40.0_value mass 44.0_time  \
45      2.320000e-14  2022/12/13 17:38:52.935     1.520000e-14            NaN
46      2.270000e-14  2022/12/13 17:38:59.260     2.440000e-14            NaN
44      2.490000e-14  2022/12/13 17:38:46.610     1.650000e-14            NaN
47      4.290000e-14  2022/12/13 17:39:05.585     1.600000e-14            NaN
43      2.680000e-14  2022/12/13 17:38:40.285     2.090000e-14            NaN
..               ...                      ...              ...            ...
341     4.200000e-14  2022/12/13 18:10:05.135     2.300000e-14            NaN
342     3.310000e-14  2022/12/13 18:10:11.460     2.680000e-14            NaN
343     3.780000e-14  2022/12/13 18:10:17.785     1.380000e-14            NaN
344     4.130000e-14  2022/12/13 18:10:24.110     1.790000e-14            NaN
345     2.550000e-14  2022/12/13 18:10:30.435     1.710000e-14            NaN

     mass 44.0_value
45               NaN
46               NaN
44               NaN
47               NaN
43               NaN
..               ...
341              NaN
342              NaN
343              NaN
344              NaN
345              NaN

[344 rows x 22 columns]

 Result 4:                mass 2.0_time  mass 2.0_value            mass 4.0_time  \
107  2022/12/13 17:45:22.833    1.989550e-11  2022/12/13 17:45:23.083
106  2022/12/13 17:45:16.508    1.989180e-11  2022/12/13 17:45:16.758
108  2022/12/13 17:45:29.158    1.982400e-11  2022/12/13 17:45:29.408
105  2022/12/13 17:45:10.183    2.007340e-11  2022/12/13 17:45:10.433
109  2022/12/13 17:45:35.483    2.001970e-11  2022/12/13 17:45:35.733
..                       ...             ...                      ...
341  2022/12/13 18:10:02.883    2.048890e-11  2022/12/13 18:10:03.133
342  2022/12/13 18:10:09.208    2.044700e-11  2022/12/13 18:10:09.458
343  2022/12/13 18:10:15.533    2.045180e-11  2022/12/13 18:10:15.783
344  2022/12/13 18:10:21.858    2.051530e-11  2022/12/13 18:10:22.108
345  2022/12/13 18:10:28.183    2.039380e-11  2022/12/13 18:10:28.433

     mass 4.0_value            mass 5.5_time  mass 5.5_value  \
107    9.841000e-13  2022/12/13 17:45:23.333    1.730000e-14
106    9.604000e-13  2022/12/13 17:45:17.008    2.140000e-14
108    9.396000e-13  2022/12/13 17:45:29.658    2.030000e-14
105    9.642000e-13  2022/12/13 17:45:10.683    1.820000e-14
109    9.669000e-13  2022/12/13 17:45:35.983    1.540000e-14
..              ...                      ...             ...
341    5.732000e-13  2022/12/13 18:10:03.383    1.590000e-14
342    5.593000e-13  2022/12/13 18:10:09.708    2.030000e-14
343    5.700000e-13  2022/12/13 18:10:16.033    1.950000e-14
344    5.495000e-13  2022/12/13 18:10:22.358    1.960000e-14
345    5.550000e-13  2022/12/13 18:10:28.683    2.290000e-14

              mass 12.0_time  mass 12.0_value           mass 15.0_time  \
107  2022/12/13 17:45:23.583     1.927000e-13  2022/12/13 17:45:23.833
106  2022/12/13 17:45:17.258     1.761000e-13  2022/12/13 17:45:17.508
108  2022/12/13 17:45:29.908     1.816000e-13  2022/12/13 17:45:30.158
105  2022/12/13 17:45:10.933     1.774000e-13  2022/12/13 17:45:11.183
109  2022/12/13 17:45:36.233     1.907000e-13  2022/12/13 17:45:36.483
..                       ...              ...                      ...
341  2022/12/13 18:10:03.633     1.795000e-13  2022/12/13 18:10:03.883
342  2022/12/13 18:10:09.958     1.635000e-13  2022/12/13 18:10:10.208
343  2022/12/13 18:10:16.283     1.567000e-13  2022/12/13 18:10:16.533
344  2022/12/13 18:10:22.608     1.952000e-13  2022/12/13 18:10:22.858
345  2022/12/13 18:10:28.933     2.028000e-13  2022/12/13 18:10:29.183

     mass 15.0_value  ...           mass 18.0_time  mass 18.0_value  \
107     2.820000e-14  ...  2022/12/13 17:45:24.334     8.588000e-13
106     2.860000e-14  ...  2022/12/13 17:45:18.009     8.831000e-13
108     2.500000e-14  ...  2022/12/13 17:45:30.659     7.760000e-13
105     3.710000e-14  ...  2022/12/13 17:45:11.684     8.567000e-13
109     3.310000e-14  ...  2022/12/13 17:45:36.984     8.060000e-13
..               ...  ...                      ...              ...
341     3.150000e-14  ...  2022/12/13 18:10:04.384     9.007000e-13
342     2.600000e-14  ...  2022/12/13 18:10:10.709     8.688000e-13
343     2.700000e-14  ...  2022/12/13 18:10:17.034     8.501000e-13
344     3.550000e-14  ...  2022/12/13 18:10:23.359     8.845000e-13
345     3.590000e-14  ...  2022/12/13 18:10:29.684     8.759000e-13

              mass 28.0_time  mass 28.0_value           mass 32.0_time  \
107  2022/12/13 17:45:24.585     9.113000e-13  2022/12/13 17:45:24.835
106  2022/12/13 17:45:18.260     8.844000e-13  2022/12/13 17:45:18.510
108  2022/12/13 17:45:30.910     7.635000e-13  2022/12/13 17:45:31.160
105  2022/12/13 17:45:11.935     9.184000e-13  2022/12/13 17:45:12.185
109  2022/12/13 17:45:37.235     8.687000e-13  2022/12/13 17:45:37.485
..                       ...              ...                      ...
341  2022/12/13 18:10:04.634     8.451000e-13  2022/12/13 18:10:04.885
342  2022/12/13 18:10:10.959     8.794000e-13  2022/12/13 18:10:11.210
343  2022/12/13 18:10:17.284     8.661000e-13  2022/12/13 18:10:17.535
344  2022/12/13 18:10:23.609     8.935000e-13  2022/12/13 18:10:23.860
345  2022/12/13 18:10:29.934     8.749000e-13  2022/12/13 18:10:30.185

     mass 32.0_value           mass 40.0_time  mass 40.0_value  \
107     3.850000e-14  2022/12/13 17:45:25.085     1.880000e-14
106     2.050000e-14  2022/12/13 17:45:18.760     1.560000e-14
108     1.640000e-14  2022/12/13 17:45:31.410     1.380000e-14
105     3.400000e-14  2022/12/13 17:45:12.435     1.360000e-14
109     1.920000e-14  2022/12/13 17:45:37.735     1.720000e-14
..               ...                      ...              ...
341     4.200000e-14  2022/12/13 18:10:05.135     2.300000e-14
342     3.310000e-14  2022/12/13 18:10:11.460     2.680000e-14
343     3.780000e-14  2022/12/13 18:10:17.785     1.380000e-14
344     4.130000e-14  2022/12/13 18:10:24.110     1.790000e-14
345     2.550000e-14  2022/12/13 18:10:30.435     1.710000e-14

              mass 44.0_time  mass 44.0_value
107                      NaN              NaN
106                      NaN              NaN
108                      NaN              NaN
105                      NaN              NaN
109  2022/12/13 17:45:38.486     1.075000e-13
..                       ...              ...
341                      NaN              NaN
342                      NaN              NaN
343                      NaN              NaN
344                      NaN              NaN
345                      NaN              NaN

[344 rows x 22 columns]
count    6.200000e+01
mean     9.541607e-10
std      1.278598e-11
min      9.297929e-10
25%      9.445770e-10
50%      9.536310e-10
75%      9.621967e-10
max      9.858399e-10
Name: mass 2, corr, dtype: float64

count    4.500000e+01
mean     9.510844e-10
std      1.653616e-11
min      9.013563e-10
25%      9.403188e-10
50%      9.560653e-10
75%      9.605300e-10
max      1.001413e-09
Name: mass 2, corr, dtype: float64

### Plotting

In [7]:
#Plotting the all the relevant MID spectrums
plt.figure(figsize=(14,8))
plt.plot(time['Elapsed time, mass 2'],mid["mass 2.0_value"],marker=".", markersize=4,label='M2')
plt.plot(time['Elapsed time, mass 4'],mid["mass 4.0_value"],marker=".", markersize=4,label='M4')
plt.plot(time['Elapsed time, mass 12'],mid["mass 12.0_value"],marker=".", markersize=4,label='M14')
plt.plot(time['Elapsed time, mass 16'],mid["mass 16.0_value"],marker=".", markersize=4,label='M16')
plt.plot(time['Elapsed time, mass 18'],mid["mass 18.0_value"],marker=".", markersize=4,label='M18')
plt.plot(time['Elapsed time, mass 28'],mid["mass 28.0_value"],marker=".", markersize=4,label='M28')
plt.plot(time['Elapsed time, mass 32'],mid["mass 32.0_value"],marker=".", markersize=4,label='M32')
plt.plot(time['Elapsed time, mass 40'],mid["mass 40.0_value"],marker=".", markersize=4,label='M40')
plt.plot(time["Elapsed time, mass 44"],mid["mass 44.0_value"],marker=".", markersize=4,label='M44')

plt.xlabel('Elapsed time (s)')
plt.ylabel('Ion current (A)')
plt.legend(title="Mol masses", loc="upper right")
plt.title("MID scan 1 ML tech. surface pre-injection, EGA in 80mm, dynamic vacuum")
font = {'family': 'arial',
        'color':  'green',
        'weight': 'normal',
        'size': 12,
        }
plt.text(200, 2.5e-11, 'No emission', fontdict = font)
plt.text(525, 2.9e-11, '\u2193 Initial desorption peak', fontdict = font)
plt.text(1100, 2.6e-11, 'Grid transparent', fontdict = font)
plt.text(1670, 1.5e-11, 'Grid repelling', fontdict = font)
plt.text(2005, 4.46e-11, '\u2193 EGA rotated', fontdict = font)
plt.text(2306, 2.6e-11, 'Grid transparent', fontdict = font)
plt.yscale('log')

In [8]:
#plotting HiVolta log
plt.figure(figsize=(12,6))
plt.plot(hv["Elapsed time"],hv["hv_grid"],marker=".", markersize=4,label='Grid current')
plt.plot(hv["Elapsed time"],hv["em"],marker=".", markersize=4,label='Emission current')
plt.xlabel('Elapsed time (s)')
plt.ylabel('Current (A)')
plt.legend(loc="upper right")
plt.title("Current evolution 1 ML tech. surface pre-injection, EGA in 80mm, dynamic vacuum")


plt.yscale('log')

In [9]:
#Plotting BA2, BA1 pressure
plt.figure(figsize=(10,6))
plt.plot(vaclog["Elapsed time"],vaclog["Barion_2"],marker=".", markersize=4,label='Barion 2')
plt.plot(vaclog["Elapsed time"],vaclog["Barion_1"],marker=".", markersize=4,label='Barion 1')

plt.xlabel('Elapsed time (s)')
plt.ylabel('Pressure (mbar)')
plt.legend()
plt.title("Total pressure evolution 1 ML tech. surface pre-injection, EGA in 80mm, dynamic vacuum")
ax = plt.gca()
ax.set_yscale('log')
plt.tick_params(axis="y", which='minor')
plt.grid(visible=None, which='both', axis='both')
plt.show()

In [10]:
## Plotting the temp evolution
plt.figure()
plt.plot((vaclog["Elapsed time"]),polyfit(A,vaclog["T-CERNOX"]),marker=".", markersize=5,label='T-CERNOX')

plt.xlabel('Elapsed time (s)')
plt.ylabel('Temperature (K)')
plt.legend()
plt.title("Temperature evolution 1 ML tech. surface pre-injection, EGA in 80mm, dynamic vacuum")
plt.yscale('linear')

# Primary desorption calculation method
### Elena's formula for the cryo setup
$$
\eta=\frac{C_{H2}\cdot (\Delta p_1 - \Delta p_2)q_e}{k_B\cdot T \cdot I_e}
$$

Where $\Delta p_i=p(t)_i - p(t=0)_i$ and $i=1,2$
In the case of the 4K setup, we know the exact conductance of gasses. The formula above applies well.

Due to the EGA being fully retracted, it is safe to assume that the desorption takes place at approximately room temperature

In [11]:
#calculation delta_p-s
dp1 = (np.mean(p_h2)-np.mean(base_h2))*100
print(dp1)

#Constants
k_B = 1.38e-23
T = 293
print(T)
q_e = 1.6e-19
c_h2 = 37.91/1000
s_h2=42/1000
x_h2=1/((1/c_h2)+(1/s_h2))
print(x_h2)
#Emission current
#ignore the inrush current values
hv["em"].where(hv["em"] <= 1.5e-6, np.nan, inplace=True)

I_em = np.nanmean(hv["em"].nlargest(30))
print(I_em)
#Conductance for CO in m3/s
c_co=10.13/1000
c_co2 = 8.08/1000

3.0762902384438795e-10
293
0.01992516581153798
5.805433333333332e-07

In [12]:
#Desorption yield
eta_h2 = (x_h2*dp1*q_e)/(k_B*T*I_em)
#eta_co = (c_co*(dp1-dp2)*q_e)/(k_B*T*I_em)
print("The desorption yield for H2 [mol/el]:",eta_h2,"\n",)#""The desorption yield for CO2 [mol/el]:",eta_co2)

The desorption yield for H2 [mol/el]: 0.0004177994705124395