In [1]:
import pandas as pd
from scipy.optimize import curve_fit
import seaborn
seaborn.set(style='whitegrid')
import numpy as np
import math
import matplotlib.pyplot as plt
from matplotlib.ticker import LogFormatter
%matplotlib qt
# %matplotlib inline
from datetime import datetime, date

C:\Users\etiirine\Anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

## Reading in the data

In [2]:
#read in the data
mid = pd.read_csv("mid on cu.tsv", sep="\t", skiprows=lambda x: x <=11,  on_bad_lines="skip")
mid.drop([0,1], inplace=True)
print(mid.describe())
#bring the time data into a new df
time = pd.DataFrame(mid.iloc[:,0::2]) #- get every second column
print(time.describe())
#add elapsed time columns
def elapsed_time(df):
    itr = 0
    counter = len(df.columns)
    masses = [2,4,12,16,18,28,32,40,44]
    for i in df:
        timestamp = pd.to_datetime(df[i], format="%Y/%m/%d %H:%M:%S.%f")
        runtime = (timestamp-timestamp[2]).dt.total_seconds()
        colname = "Elapsed time, mass {}".format(masses[itr]) 
        df.insert(counter, colname, runtime)
        itr += 1
        counter += 1
    return(df)
elapsed_time(time)

#time["Elapsed time, mass 40"].describe()

       mass 2.0_value  mass 4.0_value  mass 12.0_value  mass 16.0_value  \
count    3.390000e+02    3.390000e+02     3.390000e+02     3.390000e+02
mean     9.752285e-12    3.712068e-13     2.630059e-13     5.813124e-13
std      2.407824e-12    2.923783e-14     1.541180e-13     3.159315e-13
min      7.740900e-12    2.484000e-13     0.000000e+00     2.375000e-13
25%      9.238300e-12    3.586500e-13     2.432500e-13     5.676000e-13
50%      9.517500e-12    3.735000e-13     3.031000e-13     6.021000e-13
75%      1.027590e-11    3.866500e-13     4.009000e-13     6.215500e-13
max      5.154030e-11    7.127000e-13     4.534000e-13     5.698500e-12

       mass 18.0_value  mass 28.0_value  mass 32.0_value  mass 40.0_value  \
count     3.390000e+02     3.390000e+02     8.600000e+01     5.000000e+00
mean      6.216336e-13     4.352528e-13     4.173116e-13     2.784200e-13
std       5.945869e-14     1.620418e-13     1.381471e-13     2.776703e-13
min       4.599000e-13     2.300000e-15     2.900000e-15     2.400000e-15
25%       5.886500e-13     2.976500e-13     3.967500e-13     2.680000e-14
50%       6.168000e-13     4.387000e-13     4.560000e-13     2.509000e-13
75%       6.601000e-13     5.116000e-13     4.773500e-13     4.722000e-13
max       9.459000e-13     1.114700e-12     1.065100e-12     6.398000e-13

       mass 44.0_value
count     2.000000e+00
mean      2.518000e-13
std       1.838478e-15
min       2.505000e-13
25%       2.511500e-13
50%       2.518000e-13
75%       2.524500e-13
max       2.531000e-13
                  mass 2.0_time            mass 4.0_time  \
count                       339                      339
unique                      339                      339
top     2022/11/15 16:51:46.955  2022/11/15 16:51:47.205
freq                          1                        1

                 mass 12.0_time           mass 16.0_time  \
count                       339                      339
unique                      339                      339
top     2022/11/15 16:51:47.455  2022/11/15 16:51:47.705
freq                          1                        1

                 mass 18.0_time           mass 28.0_time  \
count                       339                      339
unique                      339                      339
top     2022/11/15 16:51:47.955  2022/11/15 16:51:48.205
freq                          1                        1

                 mass 32.0_time           mass 40.0_time  \
count                        86                        5
unique                       86                        5
top     2022/11/15 16:51:48.456  2022/11/15 16:51:48.706
freq                          1                        1

                 mass 44.0_time
count                         2
unique                        2
top     2022/11/15 16:51:48.956
freq                          1

,mass 2.0_time,mass 4.0_time,mass 12.0_time,mass 16.0_time,mass 18.0_time,mass 28.0_time,mass 32.0_time,mass 40.0_time,mass 44.0_time,"Elapsed time, mass 2","Elapsed time, mass 4","Elapsed time, mass 12","Elapsed time, mass 16","Elapsed time, mass 18","Elapsed time, mass 28","Elapsed time, mass 32","Elapsed time, mass 40","Elapsed time, mass 44"
2,2022/11/15 16:51:46.955,2022/11/15 16:51:47.205,2022/11/15 16:51:47.455,2022/11/15 16:51:47.705,2022/11/15 16:51:47.955,2022/11/15 16:51:48.205,2022/11/15 16:51:48.456,2022/11/15 16:51:48.706,2022/11/15 16:51:48.956,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
3,2022/11/15 16:51:49.278,2022/11/15 16:51:49.528,2022/11/15 16:51:49.778,2022/11/15 16:51:50.029,2022/11/15 16:51:50.279,2022/11/15 16:51:50.529,2022/11/15 16:51:50.779,2022/11/15 16:51:51.029,2022/11/15 16:51:51.280,2.323,2.323,2.323,2.324,2.324,2.324,2.323,2.323,2.324
4,2022/11/15 16:51:51.601,2022/11/15 16:51:51.851,2022/11/15 16:51:52.101,2022/11/15 16:51:52.352,2022/11/15 16:51:52.602,2022/11/15 16:51:52.852,2022/11/15 16:51:53.102,2022/11/15 16:51:53.603,NaN,4.646,4.646,4.646,4.647,4.647,4.647,4.646,4.897,NaN
5,2022/11/15 16:51:53.924,2022/11/15 16:51:54.174,2022/11/15 16:51:54.674,2022/11/15 16:51:54.924,2022/11/15 16:51:55.175,2022/11/15 16:51:55.925,NaN,NaN,NaN,6.969,6.969,7.219,7.219,7.220,7.720,NaN,NaN,NaN
6,2022/11/15 16:51:56.246,2022/11/15 16:51:56.496,2022/11/15 16:51:56.997,2022/11/15 16:51:57.247,2022/11/15 16:51:57.497,2022/11/15 16:51:58.248,NaN,NaN,NaN,9.291,9.291,9.542,9.542,9.542,10.043,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336,2022/11/15 17:04:42.671,2022/11/15 17:04:42.921,2022/11/15 17:04:43.422,2022/11/15 17:04:43.672,2022/11/15 17:04:43.922,2022/11/15 17:04:44.673,NaN,NaN,NaN,775.716,775.716,775.967,775.967,775.967,776.468,NaN,NaN,NaN
337,2022/11/15 17:04:44.994,2022/11/15 17:04:45.244,2022/11/15 17:04:45.744,2022/11/15 17:04:45.994,2022/11/15 17:04:46.245,2022/11/15 17:04:46.995,NaN,NaN,NaN,778.039,778.039,778.289,778.289,778.290,778.790,NaN,NaN,NaN
338,2022/11/15 17:04:47.316,2022/11/15 17:04:47.566,2022/11/15 17:04:48.067,2022/11/15 17:04:48.317,2022/11/15 17:04:48.567,2022/11/15 17:04:49.318,NaN,NaN,NaN,780.361,780.361,780.612,780.612,780.612,781.113,NaN,NaN,NaN
339,2022/11/15 17:04:49.639,2022/11/15 17:04:49.889,2022/11/15 17:04:50.139,2022/11/15 17:04:50.389,2022/11/15 17:04:50.639,2022/11/15 17:04:50.890,2022/11/15 17:04:51.640,NaN,NaN,782.684,782.684,782.684,782.684,782.684,782.685,783.184,NaN,NaN
340,2022/11/15 17:04:51.961,2022/11/15 17:04:52.211,2022/11/15 17:04:52.462,2022/11/15 17:04:52.712,2022/11/15 17:04:52.962,2022/11/15 17:04:53.212,2022/11/15 17:04:53.963,NaN,NaN,785.006,785.006,785.007,785.007,785.007,785.007,785.507,NaN,NaN

### Position of the EGA

<div>
<img src="20221117_142845.jpg" width="1000"/>
</div>

In [3]:
#reading the Emission current, pressures
vaclog=pd.read_csv("vaclog", sep="\t")
vaclog.head()
#adding an elapsed time column
timestamp=[]
for i in vaclog["Time"]:
    timestamp.append(i)
#making the column into a datetime object
timestamps=pd.to_datetime(vaclog["Time"],format="%d/%m/%Y %H:%M:%S")
runtime=(timestamps-timestamps[0]).dt.total_seconds()    
vaclog.insert(2,"Elapsed time",runtime)
vaclog.drop(index=vaclog.index[0], 
        axis=0, 
        inplace=True)

vaclog.head()

,Live comments,Time,Elapsed time,injection 100mbar,Barion_2,Barion_1,DUAL experiment,DUAL insulation,injection 1mbar,helium,T-platinum,T-CERNOX,I_emission,I_grid
1,NaN,15/11/2022 16:51:45,7.0,-0.061801,6.480000e-10,3.480000e-10,4.996000e-09,5.356000e-07,0.000490,228.0,-5.275,4306.605,NaN,NaN
2,NaN,15/11/2022 16:51:52,14.0,-0.066462,6.530000e-10,3.470000e-10,4.996000e-09,5.356000e-07,0.000485,228.0,-5.275,4306.605,NaN,NaN
3,NaN,15/11/2022 16:51:59,21.0,-0.066659,6.500000e-10,3.470000e-10,4.996000e-09,5.356000e-07,0.000484,228.0,-5.275,4306.717,NaN,NaN
4,NaN,15/11/2022 16:52:06,28.0,-0.066164,6.510000e-10,3.460000e-10,4.996000e-09,5.363000e-07,0.000496,228.0,-5.275,4306.717,NaN,NaN
5,NaN,15/11/2022 16:52:14,36.0,-0.066116,6.440000e-10,3.470000e-10,4.996000e-09,5.363000e-07,0.000502,228.0,-5.163,4306.941,NaN,NaN

In [4]:
#Reading in the HiVolta measurement file to get the grid current
hv = pd.read_csv("hv log", sep=",")
#hv.drop(columns=["Vmon1","Vmon2","Vmon3","Vmon4","Vmon5","Vmon6","Vmon7","Vmon8","Imon3","Imon4","Imon5","Imon6","Imon7","Imon8","Comments1"], inplace=True)
hv["hv_grid"]=[element * 1e-6 for element in hv["IMon1"]]
hv["em"]=[element * 1e-6 for element in hv["IMon2"]]
hv.drop(hv.columns[hv.columns.str.contains('Unnamed',case = False)],axis = 1, inplace = True)
hv["em"]=abs(hv["em"])
hv["hv_grid"]=abs(hv["hv_grid"])

#adding an elapsed time column
timestamp=[]
for i in hv["Time"]:
    timestamp.append(i)
    
#making the column into a datetime object
timestamps=pd.to_datetime(hv["Time"],format="%H:%M:%S.%f")
runtime=(timestamps-timestamps[0]).dt.total_seconds()    
hv.insert(2,"Elapsed time",runtime)
hv.drop(index=hv.index[0], 
        axis=0, 
        inplace=True)

hv.describe()

,Elapsed time,VMon1,VMon2,VMon3,VMon4,VMon5,VMon6,VMon7,VMon8,IMon1,IMon2,IMon3,IMon4,IMon5,IMon6,IMon7,IMon8,hv_grid,em
count,647.000000,647.000000,647.000000,647.000000,647.000000,647.000000,647.0,647.0,6.470000e+02,647.000000,647.000000,647.000000,647.000000,647.000000,647.000000,647.000000,647.000000,6.470000e+02,6.470000e+02
mean,486.550526,202.437651,93.951561,927.012983,923.529428,919.338733,0.0,0.0,2.000000e-02,-0.184033,0.634996,11.439976,11.442445,11.418432,-0.010329,-0.017727,-0.013836,2.102147e-07,6.349963e-07
std,224.920328,243.341012,23.903505,257.133817,262.478603,268.585441,0.0,0.0,2.881869e-16,0.213841,0.606512,3.201202,3.218060,3.238425,0.000715,0.000184,0.000376,1.881223e-07,6.065119e-07
min,96.117000,0.040000,0.080000,0.000000,0.000000,0.000000,0.0,0.0,2.000000e-02,-0.767900,0.003200,-0.059600,-0.051300,-0.046100,-0.011000,-0.018100,-0.014300,8.000000e-10,3.200000e-09
25%,292.348500,0.100000,100.060000,999.880000,999.940000,999.920000,0.0,0.0,2.000000e-02,-0.387250,0.016500,11.969250,11.975150,11.963650,-0.011000,-0.017700,-0.014200,1.740000e-08,1.650000e-08
50%,486.682000,0.160000,100.080000,999.940000,1000.040000,1000.020000,0.0,0.0,2.000000e-02,-0.330700,1.119800,12.365900,12.378500,12.365600,-0.010400,-0.017700,-0.014000,3.332000e-07,1.119800e-06
75%,680.815000,499.880000,100.080000,999.960000,1000.040000,1000.060000,0.0,0.0,2.000000e-02,0.017400,1.178200,12.670250,12.683300,12.667300,-0.009700,-0.017600,-0.013500,3.892000e-07,1.178200e-06
max,874.674000,499.920000,100.140000,999.960000,1000.060000,1000.080000,0.0,0.0,2.000000e-02,0.534500,2.945800,12.987500,13.004400,12.988400,-0.009000,-0.017400,-0.013100,7.679000e-07,2.945800e-06

### Data processing

In [5]:
#Temperature curve for CERNOX - for temp stability
A=[230.317302,-6170.1513,71837.9529,-477946.76,2.003668910085786e+6,-5.488690193047771e+6,9.830475663897528e+6,-1.111226817786569e+7,7.202477878914065e+6,-2.04194551328507e+6]
#specify fit parameters A, data (Resistance values)
def polyfit(params,data):
    total=[]
    for j in data: 
        exp=0
        for i in range(len(params)):
            exp += (params[i]/(math.log10(j))**i)
        total.append(10**exp)
    return(total)

In [6]:
#Filtering background signal

#Find the timestamp where emission was turned on and off
print("Result 1:",hv.loc[hv["Comment"]=="emission on"])
print("Result 2:", hv.loc[hv["Comment"]=="grid repelling"])
x=pd.Timestamp(2022, 11, 15, 16,53, 7)
y=pd.Timestamp(2022, 11, 15, 16,56, 27)

#then find the time value closest to it in the MID scan file 
print("\n","Result 3:",mid.iloc[(pd.to_datetime(mid['mass 2.0_time'],format="%Y/%m/%d %H:%M:%S") - x).abs().argsort(),:])
print("\n","Result 4:",mid.iloc[(pd.to_datetime(mid['mass 2.0_time'],format="%Y/%m/%d %H:%M:%S") - y).abs().argsort(),:])

#take a mass with a signal known to be in the background
bck=np.mean(mid["mass 40.0_value"])

#apply background correction to the rest of the mass spectrum
mid["mass 2, corr"]=mid["mass 2.0_value"]-bck


#From the signal, get the partial pressures 
h2_sens=2.13e-2
p_h2=mid["mass 2, corr"][37:123]/h2_sens
print(p_h2.describe())

#baseline for partial pressure delta
base_h2=mid["mass 2, corr"][0:37]/h2_sens
base_h2.describe()

Result 1:           Date          Time  Elapsed time  VMon1   VMon2   VMon3   VMon4  \
49  15/11/2022  16:53:02.660       156.593   0.06  100.04  771.94  421.54
50  15/11/2022  16:53:03.879       157.812   0.08  100.04  862.08  511.82
51  15/11/2022  16:53:05.058       158.991   0.08  100.10  993.36  652.40

     VMon5  VMon6  VMon7  ...   IMon2   IMon3   IMon4   IMon5  IMon6   IMon7  \
49   70.46    0.0    0.0  ...  2.8895  7.0358  6.5733  5.5796 -0.011 -0.0177
50  150.50    0.0    0.0  ...  2.9458  8.3780  7.9047  6.9166 -0.011 -0.0177
51  290.68    0.0    0.0  ...  2.0995  9.0782  8.7792  8.1030 -0.011 -0.0177

     IMon8      Comment       hv_grid        em
49 -0.0143  emission on  2.200000e-09  0.000003
50 -0.0143  emission on  6.940000e-08  0.000003
51 -0.0143  emission on  4.000000e-08  0.000002

[3 rows x 22 columns]
Result 2:            Date          Time  Elapsed time   VMon1   VMon2   VMon3    VMon4  \
219  15/11/2022  16:56:26.942       360.875  497.12  100.10  999.90  1000.00
220  15/11/2022  16:56:28.141       362.074  499.82  100.10  999.90  1000.00
221  15/11/2022  16:56:29.337       363.270  499.82  100.10  999.92  1000.00
222  15/11/2022  16:56:30.535       364.468  499.82  100.10  999.92  1000.00
415  15/11/2022  17:00:22.115       596.048    0.14  100.06  999.96  1000.04
416  15/11/2022  17:00:23.314       597.247    0.14  100.06  999.96  1000.04
417  15/11/2022  17:00:24.759       598.692   70.40  100.06  999.96  1000.04
418  15/11/2022  17:00:25.956       599.889  160.60  100.12  999.94  1000.04

       VMon5  VMon6  VMon7  ...   IMon2    IMon3    IMon4    IMon5   IMon6  \
219   999.98    0.0    0.0  ...  0.0290  12.1377  12.1466  12.1204 -0.0110
220   999.98    0.0    0.0  ...  0.0233  12.1377  12.1466  12.1261 -0.0110
221   999.98    0.0    0.0  ...  0.0191  12.1414  12.1508  12.1336 -0.0110
222   999.98    0.0    0.0  ...  0.0184  12.1413  12.1517  12.1343 -0.0110
415  1000.06    0.0    0.0  ...  1.2393  12.5446  12.5596  12.5447 -0.0104
416  1000.06    0.0    0.0  ...  1.2390  12.5475  12.5622  12.5465 -0.0104
417  1000.06    0.0    0.0  ...  1.2347  12.5457  12.5587  12.5425 -0.0104
418  1000.06    0.0    0.0  ...  0.2786  12.6110  12.6214  12.5546 -0.0104

      IMon7   IMon8         Comment       hv_grid            em
219 -0.0176 -0.0142  grid repelling  1.072000e-07  2.900000e-08
220 -0.0176 -0.0142  grid repelling  4.240000e-08  2.330000e-08
221 -0.0176 -0.0142  grid repelling  3.500000e-08  1.910000e-08
222 -0.0176 -0.0142  grid repelling  2.470000e-08  1.840000e-08
415 -0.0181 -0.0140  grid repelling  4.076000e-07  1.239300e-06
416 -0.0181 -0.0140  grid repelling  4.076000e-07  1.239000e-06
417 -0.0181 -0.0140  grid repelling  4.253000e-07  1.234700e-06
418 -0.0181 -0.0140  grid repelling  5.023000e-07  2.786000e-07

[8 rows x 22 columns]

 Result 3:                mass 2.0_time  mass 2.0_value            mass 4.0_time  \
36   2022/11/15 16:53:05.921    7.886000e-12  2022/11/15 16:53:06.171
37   2022/11/15 16:53:08.244    8.134700e-12  2022/11/15 16:53:08.494
35   2022/11/15 16:53:03.599    8.046700e-12  2022/11/15 16:53:03.849
38   2022/11/15 16:53:10.566    9.184000e-12  2022/11/15 16:53:10.816
34   2022/11/15 16:53:01.276    7.785600e-12  2022/11/15 16:53:01.526
..                       ...             ...                      ...
336  2022/11/15 17:04:42.671    1.019530e-11  2022/11/15 17:04:42.921
337  2022/11/15 17:04:44.994    1.028390e-11  2022/11/15 17:04:45.244
338  2022/11/15 17:04:47.316    1.011950e-11  2022/11/15 17:04:47.566
339  2022/11/15 17:04:49.639    1.017000e-11  2022/11/15 17:04:49.889
340  2022/11/15 17:04:51.961    1.019470e-11  2022/11/15 17:04:52.211

     mass 4.0_value           mass 12.0_time  mass 12.0_value  \
36     3.141000e-13  2022/11/15 16:53:06.672     2.611000e-13
37     3.250000e-13  2022/11/15 16:53:08.994     3.119000e-13
35     3.494000e-13  2022/11/15 16:53:04.349     2.938000e-13
38     3.773000e-13  2022/11/15 16:53:11.317     3.562000e-13
34     3.053000e-13  2022/11/15 16:53:02.027     2.692000e-13
..              ...                      ...              ...
336    3.868000e-13  2022/11/15 17:04:43.422     4.135000e-13
337    3.785000e-13  2022/11/15 17:04:45.744     4.085000e-13
338    3.957000e-13  2022/11/15 17:04:48.067     4.318000e-13
339    3.865000e-13  2022/11/15 17:04:50.139     4.000000e-16
340    3.869000e-13  2022/11/15 17:04:52.462     9.100000e-15

              mass 16.0_time  mass 16.0_value           mass 18.0_time  \
36   2022/11/15 16:53:06.922     5.928000e-13  2022/11/15 16:53:07.172
37   2022/11/15 16:53:09.244     5.943000e-13  2022/11/15 16:53:09.495
35   2022/11/15 16:53:04.599     5.901000e-13  2022/11/15 16:53:04.850
38   2022/11/15 16:53:11.567     6.410000e-13  2022/11/15 16:53:11.817
34   2022/11/15 16:53:02.277     5.526000e-13  2022/11/15 16:53:02.527
..                       ...              ...                      ...
336  2022/11/15 17:04:43.672     6.058000e-13  2022/11/15 17:04:43.922
337  2022/11/15 17:04:45.994     6.329000e-13  2022/11/15 17:04:46.245
338  2022/11/15 17:04:48.317     6.389000e-13  2022/11/15 17:04:48.567
339  2022/11/15 17:04:50.389     4.258000e-13  2022/11/15 17:04:50.639
340  2022/11/15 17:04:52.712     4.000000e-13  2022/11/15 17:04:52.962

     mass 18.0_value           mass 28.0_time  mass 28.0_value  \
36      5.177000e-13  2022/11/15 16:53:07.923     2.542000e-13
37      5.335000e-13  2022/11/15 16:53:10.245     2.976000e-13
35      5.191000e-13  2022/11/15 16:53:05.600     2.354000e-13
38      6.101000e-13  2022/11/15 16:53:12.568     4.187000e-13
34      5.537000e-13  2022/11/15 16:53:03.278     2.454000e-13
..               ...                      ...              ...
336     6.993000e-13  2022/11/15 17:04:44.673     5.093000e-13
337     7.392000e-13  2022/11/15 17:04:46.995     5.296000e-13
338     6.995000e-13  2022/11/15 17:04:49.318     5.156000e-13
339     6.267000e-13  2022/11/15 17:04:50.890     6.791000e-13
340     6.181000e-13  2022/11/15 17:04:53.212     6.986000e-13

              mass 32.0_time  mass 32.0_value mass 40.0_time  mass 40.0_value  \
36                       NaN              NaN            NaN              NaN
37                       NaN              NaN            NaN              NaN
35                       NaN              NaN            NaN              NaN
38                       NaN              NaN            NaN              NaN
34                       NaN              NaN            NaN              NaN
..                       ...              ...            ...              ...
336                      NaN              NaN            NaN              NaN
337                      NaN              NaN            NaN              NaN
338                      NaN              NaN            NaN              NaN
339  2022/11/15 17:04:51.640     5.077000e-13            NaN              NaN
340  2022/11/15 17:04:53.963     4.819000e-13            NaN              NaN

    mass 44.0_time  mass 44.0_value
36             NaN              NaN
37             NaN              NaN
35             NaN              NaN
38             NaN              NaN
34             NaN              NaN
..             ...              ...
336            NaN              NaN
337            NaN              NaN
338            NaN              NaN
339            NaN              NaN
340            NaN              NaN

[339 rows x 18 columns]

 Result 4:                mass 2.0_time  mass 2.0_value            mass 4.0_time  \
123  2022/11/15 16:56:27.979    9.128600e-12  2022/11/15 16:56:28.229
122  2022/11/15 16:56:25.656    9.117600e-12  2022/11/15 16:56:25.906
124  2022/11/15 16:56:30.301    8.920600e-12  2022/11/15 16:56:30.551
121  2022/11/15 16:56:23.334    8.988600e-12  2022/11/15 16:56:23.584
125  2022/11/15 16:56:32.624    9.112500e-12  2022/11/15 16:56:32.874
..                       ...             ...                      ...
336  2022/11/15 17:04:42.671    1.019530e-11  2022/11/15 17:04:42.921
337  2022/11/15 17:04:44.994    1.028390e-11  2022/11/15 17:04:45.244
338  2022/11/15 17:04:47.316    1.011950e-11  2022/11/15 17:04:47.566
339  2022/11/15 17:04:49.639    1.017000e-11  2022/11/15 17:04:49.889
340  2022/11/15 17:04:51.961    1.019470e-11  2022/11/15 17:04:52.211

     mass 4.0_value           mass 12.0_time  mass 12.0_value  \
123    3.284000e-13  2022/11/15 16:56:28.729     2.945000e-13
122    3.594000e-13  2022/11/15 16:56:26.407     3.101000e-13
124    3.794000e-13  2022/11/15 16:56:31.052     2.947000e-13
121    3.606000e-13  2022/11/15 16:56:24.084     2.932000e-13
125    3.554000e-13  2022/11/15 16:56:33.374     3.056000e-13
..              ...                      ...              ...
336    3.868000e-13  2022/11/15 17:04:43.422     4.135000e-13
337    3.785000e-13  2022/11/15 17:04:45.744     4.085000e-13
338    3.957000e-13  2022/11/15 17:04:48.067     4.318000e-13
339    3.865000e-13  2022/11/15 17:04:50.139     4.000000e-16
340    3.869000e-13  2022/11/15 17:04:52.462     9.100000e-15

              mass 16.0_time  mass 16.0_value           mass 18.0_time  \
123  2022/11/15 16:56:28.979     6.145000e-13  2022/11/15 16:56:29.230
122  2022/11/15 16:56:26.657     5.676000e-13  2022/11/15 16:56:26.907
124  2022/11/15 16:56:31.302     5.987000e-13  2022/11/15 16:56:31.552
121  2022/11/15 16:56:24.334     5.941000e-13  2022/11/15 16:56:24.585
125  2022/11/15 16:56:33.624     6.077000e-13  2022/11/15 16:56:33.875
..                       ...              ...                      ...
336  2022/11/15 17:04:43.672     6.058000e-13  2022/11/15 17:04:43.922
337  2022/11/15 17:04:45.994     6.329000e-13  2022/11/15 17:04:46.245
338  2022/11/15 17:04:48.317     6.389000e-13  2022/11/15 17:04:48.567
339  2022/11/15 17:04:50.389     4.258000e-13  2022/11/15 17:04:50.639
340  2022/11/15 17:04:52.712     4.000000e-13  2022/11/15 17:04:52.962

     mass 18.0_value           mass 28.0_time  mass 28.0_value  \
123     5.813000e-13  2022/11/15 16:56:29.980     3.409000e-13
122     6.165000e-13  2022/11/15 16:56:27.658     3.644000e-13
124     6.090000e-13  2022/11/15 16:56:32.303     3.148000e-13
121     5.822000e-13  2022/11/15 16:56:25.335     3.110000e-13
125     6.044000e-13  2022/11/15 16:56:34.625     3.001000e-13
..               ...                      ...              ...
336     6.993000e-13  2022/11/15 17:04:44.673     5.093000e-13
337     7.392000e-13  2022/11/15 17:04:46.995     5.296000e-13
338     6.995000e-13  2022/11/15 17:04:49.318     5.156000e-13
339     6.267000e-13  2022/11/15 17:04:50.890     6.791000e-13
340     6.181000e-13  2022/11/15 17:04:53.212     6.986000e-13

              mass 32.0_time  mass 32.0_value mass 40.0_time  mass 40.0_value  \
123                      NaN              NaN            NaN              NaN
122                      NaN              NaN            NaN              NaN
124                      NaN              NaN            NaN              NaN
121                      NaN              NaN            NaN              NaN
125                      NaN              NaN            NaN              NaN
..                       ...              ...            ...              ...
336                      NaN              NaN            NaN              NaN
337                      NaN              NaN            NaN              NaN
338                      NaN              NaN            NaN              NaN
339  2022/11/15 17:04:51.640     5.077000e-13            NaN              NaN
340  2022/11/15 17:04:53.963     4.819000e-13            NaN              NaN

    mass 44.0_time  mass 44.0_value
123            NaN              NaN
122            NaN              NaN
124            NaN              NaN
121            NaN              NaN
125            NaN              NaN
..             ...              ...
336            NaN              NaN
337            NaN              NaN
338            NaN              NaN
339            NaN              NaN
340            NaN              NaN

[339 rows x 18 columns]
count    8.600000e+01
mean     4.661409e-10
std      1.331857e-11
min      4.057362e-10
25%      4.650049e-10
50%      4.681423e-10
75%      4.713441e-10
max      4.930366e-10
Name: mass 2, corr, dtype: float64

count    3.700000e+01
mean     3.573851e-10
std      1.092623e-11
min      3.503512e-10
25%      3.534451e-10
50%      3.548770e-10
75%      3.574920e-10
max      4.181023e-10
Name: mass 2, corr, dtype: float64

### Plotting

In [7]:
#Plotting the all the relevant MID spectrums
plt.figure(figsize=(14,8))
plt.plot(time['Elapsed time, mass 2'],mid["mass 2.0_value"],marker=".", markersize=4,label='M2')
plt.plot(time['Elapsed time, mass 4'],mid["mass 4.0_value"],marker=".", markersize=4,label='M4')
plt.plot(time['Elapsed time, mass 12'],mid["mass 12.0_value"],marker=".", markersize=4,label='M14')
plt.plot(time['Elapsed time, mass 16'],mid["mass 16.0_value"],marker=".", markersize=4,label='M16')
plt.plot(time['Elapsed time, mass 18'],mid["mass 18.0_value"],marker=".", markersize=4,label='M18')
plt.plot(time['Elapsed time, mass 28'],mid["mass 28.0_value"],marker=".", markersize=4,label='M28')
plt.plot(time['Elapsed time, mass 32'],mid["mass 32.0_value"],marker=".", markersize=4,label='M32')
plt.plot(time['Elapsed time, mass 40'],mid["mass 40.0_value"],marker=".", markersize=4,label='M40')
plt.plot(time["Elapsed time, mass 44"],mid["mass 44.0_value"],marker=".", markersize=4,label='M44')

plt.xlabel('Elapsed time (s)')
plt.ylabel('Ion current (A)')
plt.legend(title="Mol masses", loc="upper right")
plt.title("MID scan, EGA out, dynamic vacuum")
font = {'family': 'arial',
        'color':  'green',
        'weight': 'normal',
        'size': 12,
        }
plt.text(2, 1.3e-11, 'No emission', fontdict = font)
plt.text(100, 1.4e-11, 'Emission on, Grid transparent', fontdict = font)
plt.text(280, 5e-12, 'Grid repelling', fontdict = font)
plt.text(414, 1.4e-11, 'Grid transparent', fontdict = font)
plt.text(570, 2.8e-11, '\u2190 peak due to friction', fontdict = font)
plt.yscale('log')

In [8]:
#plotting HiVolta log
plt.figure(figsize=(12,6))
plt.plot(hv["Elapsed time"],hv["hv_grid"],marker=".", markersize=4,label='Grid current')
plt.plot(hv["Elapsed time"],hv["em"],marker=".", markersize=4,label='Emission current')
plt.xlabel('Elapsed time (s)')
plt.ylabel('Current (A)')
plt.legend(loc="upper right")
plt.title("Current evolution, dynamic vacuum")
font = {'family': 'arial',
        'color':  'green',
        'weight': 'normal',
        'size': 14,
        }
plt.text(200, 1.9e-6, 'Emission on', fontdict = font)
plt.text(380, 6e-9, 'Grid repelling', fontdict = font)
plt.text(480, 1.9e-6, 'Grid transparent', fontdict = font)
plt.text(610, 6e-9, 'Grid repelling, EGA turned', fontdict = font)
plt.text(790, 2e-7, 'Grid transparent', fontdict = font)

plt.yscale('log')

In [9]:
#Plotting BA2, BA1 pressure
plt.figure(figsize=(10,6))
plt.plot(vaclog["Elapsed time"],vaclog["Barion_2"],marker=".", markersize=4,label='Barion 2')
plt.plot(vaclog["Elapsed time"],vaclog["Barion_1"],marker=".", markersize=4,label='Barion 1')

plt.xlabel('Elapsed time (s)')
plt.ylabel('Pressure (mbar)')
plt.legend()
plt.title("Total pressure evolution, dynamic vacuum")
ax = plt.gca()
ax.set_yscale('log')
plt.tick_params(axis="y", which='minor')
plt.grid(visible=None, which='both', axis='both')
plt.show()

In [10]:
#Plotting the temp evolution
plt.figure()
plt.plot((vaclog["Elapsed time"]),polyfit(A,vaclog["T-CERNOX"]),marker=".", markersize=5,label='T-CERNOX')

plt.xlabel('Elapsed time (s)')
plt.ylabel('Temperature (K)')
plt.legend()
plt.title("Temperature evolution")
plt.yscale('linear')

# Primary desorption calculation method
### Elena's formula for the cryo setup
$$
\eta=\frac{C_{H2}\cdot (\Delta p_1 - \Delta p_2)q_e}{k_B\cdot T \cdot I_e}
$$

Where $\Delta p_i=p(t)_i - p(t=0)_i$ and $i=1,2$
In the case of the 4K setup, we know the exact conductance of gasses. The formula above applies well.

Due to the EGA being fully retracted, it is safe to assume that the desorption takes place at approximately room temperature

In [11]:
#calculation delta_p-s
dp1 = (np.mean(p_h2)-np.mean(base_h2))*100
print(dp1)

#Constants
k_B = 1.38e-23
T = 298
print(T)
q_e = 1.6e-19
c_h2 = 37.91/1000
s_h2=42/1000
x_h2=1/((1/c_h2)+(1/s_h2))
print(x_h2)
#Emission current
#ignore the inrush current values
hv["em"].where(hv["em"] <= 1.2e-6, np.nan, inplace=True)

I_em = np.nanmean(hv["em"].nlargest(30))
print(I_em)
#Conductance for CO in m3/s
c_co=10.13/1000
c_co2 = 8.08/1000

1.0875583608502072e-08
298
0.01992516581153798
1.1949833333333335e-06

In [12]:
#Desorption yield
eta_h2 = (x_h2*dp1*q_e)/(k_B*T*I_em)
#eta_co = (c_co*(dp1-dp2)*q_e)/(k_B*T*I_em)
print("The desorption yield for H2 [mol/el]:",eta_h2,"\n",)#""The desorption yield for CO2 [mol/el]:",eta_co2)

The desorption yield for H2 [mol/el]: 0.0070553294767953705