In [1]:
import pandas as pd
from scipy.optimize import curve_fit
from scipy.integrate import quad
import seaborn
seaborn.set(style='whitegrid')
import numpy as np
import math
import matplotlib.pyplot as plt
from matplotlib.ticker import LogFormatter
%matplotlib qt
# %matplotlib inline
from datetime import datetime, date

C:\Users\etiirine\Anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
C:\Users\etiirine\Anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

## Reading in the data

In [2]:
#read in the data
mid = pd.read_csv("MID.tsv", sep="\t", skiprows=lambda x: x <=11,  on_bad_lines="skip")
mid.drop([0,1], inplace=True)
print(mid.describe())

#bring the time data into a new df
time = pd.DataFrame(mid.iloc[:,0::2]) #- get every second column
print(time.describe())
#add elapsed time columns
def elapsed_time(df):
    itr = 0
    counter = len(df.columns)
    masses = [2,4,5.5,12,15,16,18,28,32,40,44]
    for i in df:
        timestamp = pd.to_datetime(df[i], format="%Y/%m/%d %H:%M:%S.%f")
        runtime = (timestamp-timestamp[2]).dt.total_seconds()
        colname = "Elapsed time, mass {}".format(masses[itr]) 
        df.insert(counter, colname, runtime)
        itr += 1
        counter += 1
    return(df)
elapsed_time(time)

#time["Elapsed time, mass 40"].describe()

       mass 2.0_value  mass 4.0_value  mass 5.5_value  mass 12.0_value  \
count    8.640000e+02    8.640000e+02    8.640000e+02     8.640000e+02
mean     7.171138e-10    3.559062e-14    3.430174e-14     3.104865e-13
std      2.558800e-09    1.012538e-14    1.136090e-14     2.768158e-14
min      1.017540e-10    6.400000e-15    1.320000e-14     1.118000e-13
25%      1.084107e-10    3.010000e-14    2.850000e-14     2.929000e-13
50%      1.161290e-10    3.510000e-14    3.390000e-14     3.080500e-13
75%      1.211250e-10    4.032500e-14    3.900000e-14     3.224750e-13
max      1.474520e-08    1.300000e-13    2.445000e-13     4.433000e-13

       mass 15.0_value  mass 16.0_value  mass 18.0_value  mass 28.0_value  \
count     8.640000e+02     8.640000e+02     8.640000e+02     8.640000e+02
mean      1.935312e-13     7.326005e-13     3.583548e-12     1.658591e-12
std       8.804527e-14     3.460741e-13     8.286499e-12     9.373318e-13
min       1.369000e-13     5.540000e-13     1.429900e-12     1.010000e-13
25%       1.650000e-13     6.212250e-13     1.541075e-12     1.341650e-12
50%       1.745000e-13     6.521000e-13     1.632150e-12     1.438700e-12
75%       1.836250e-13     6.893000e-13     1.711450e-12     1.563450e-12
max       6.638000e-13     2.385600e-12     4.419430e-11     6.033700e-12

       mass 32.0_value  mass 40.0_value  mass 44.0_value
count     8.640000e+02     8.640000e+02     8.630000e+02
mean      1.846625e-13     6.081377e-14     2.392514e-11
std       4.587825e-14     8.254988e-13     3.098582e-13
min       1.820000e-14     1.180000e-14     2.295120e-11
25%       1.667000e-13     2.717500e-14     2.370370e-11
50%       1.753000e-13     3.175000e-14     2.391870e-11
75%       1.845000e-13     3.660000e-14     2.408000e-11
max       4.266000e-13     2.429500e-11     2.526250e-11
                  mass 2.0_time            mass 4.0_time  \
count                       864                      864
unique                      864                      864
top     2023/01/16 15:29:44.364  2023/01/16 15:29:47.865
freq                          1                        1

                  mass 5.5_time           mass 12.0_time  \
count                       864                      864
unique                      864                      864
top     2023/01/16 15:29:48.115  2023/01/16 15:29:48.365
freq                          1                        1

                 mass 15.0_time           mass 16.0_time  \
count                       864                      864
unique                      864                      864
top     2023/01/16 15:29:48.615  2023/01/16 15:29:48.865
freq                          1                        1

                 mass 18.0_time           mass 28.0_time  \
count                       864                      864
unique                      864                      864
top     2023/01/16 15:29:49.116  2023/01/16 15:29:49.366
freq                          1                        1

                 mass 32.0_time           mass 40.0_time  \
count                       864                      864
unique                      864                      864
top     2023/01/16 15:29:49.616  2023/01/16 15:29:50.367
freq                          1                        1

                 mass 44.0_time
count                       863
unique                      863
top     2023/01/16 15:29:56.692
freq                          1

,mass 2.0_time,mass 4.0_time,mass 5.5_time,mass 12.0_time,mass 15.0_time,mass 16.0_time,mass 18.0_time,mass 28.0_time,mass 32.0_time,mass 40.0_time,...,"Elapsed time, mass 4","Elapsed time, mass 5.5","Elapsed time, mass 12","Elapsed time, mass 15","Elapsed time, mass 16","Elapsed time, mass 18","Elapsed time, mass 28","Elapsed time, mass 32","Elapsed time, mass 40","Elapsed time, mass 44"
2,2023/01/16 15:29:44.364,2023/01/16 15:29:47.865,2023/01/16 15:29:48.115,2023/01/16 15:29:48.365,2023/01/16 15:29:48.615,2023/01/16 15:29:48.865,2023/01/16 15:29:49.116,2023/01/16 15:29:49.366,2023/01/16 15:29:49.616,2023/01/16 15:29:50.367,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,NaN
3,2023/01/16 15:29:50.688,2023/01/16 15:29:53.939,2023/01/16 15:29:54.189,2023/01/16 15:29:54.439,2023/01/16 15:29:54.690,2023/01/16 15:29:54.940,2023/01/16 15:29:55.190,2023/01/16 15:29:55.440,2023/01/16 15:29:55.690,2023/01/16 15:29:55.940,...,6.074,6.074,6.074,6.075,6.075,6.074,6.074,6.074,5.573,NaN
4,2023/01/16 15:29:57.013,2023/01/16 15:30:00.264,2023/01/16 15:30:00.514,2023/01/16 15:30:00.764,2023/01/16 15:30:01.015,2023/01/16 15:30:01.265,2023/01/16 15:30:01.515,2023/01/16 15:30:01.765,2023/01/16 15:30:02.015,2023/01/16 15:30:02.266,...,12.399,12.399,12.399,12.400,12.400,12.399,12.399,12.399,11.899,NaN
5,2023/01/16 15:30:03.338,2023/01/16 15:30:06.589,2023/01/16 15:30:06.839,2023/01/16 15:30:07.089,2023/01/16 15:30:07.340,2023/01/16 15:30:07.590,2023/01/16 15:30:07.840,2023/01/16 15:30:08.090,2023/01/16 15:30:08.340,2023/01/16 15:30:08.591,...,18.724,18.724,18.724,18.725,18.725,18.724,18.724,18.724,18.224,NaN
6,2023/01/16 15:30:09.663,2023/01/16 15:30:12.914,2023/01/16 15:30:13.164,2023/01/16 15:30:13.414,2023/01/16 15:30:13.665,2023/01/16 15:30:13.915,2023/01/16 15:30:14.165,2023/01/16 15:30:14.415,2023/01/16 15:30:14.665,2023/01/16 15:30:14.916,...,25.049,25.049,25.049,25.050,25.050,25.049,25.049,25.049,24.549,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
861,2023/01/16 17:00:17.538,2023/01/16 17:00:20.789,2023/01/16 17:00:21.039,2023/01/16 17:00:21.289,2023/01/16 17:00:21.540,2023/01/16 17:00:21.790,2023/01/16 17:00:22.040,2023/01/16 17:00:22.290,2023/01/16 17:00:22.540,2023/01/16 17:00:22.791,...,5432.924,5432.924,5432.924,5432.925,5432.925,5432.924,5432.924,5432.924,5432.424,NaN
862,2023/01/16 17:00:23.863,2023/01/16 17:00:27.114,2023/01/16 17:00:27.364,2023/01/16 17:00:27.614,2023/01/16 17:00:27.865,2023/01/16 17:00:28.115,2023/01/16 17:00:28.365,2023/01/16 17:00:28.615,2023/01/16 17:00:28.865,2023/01/16 17:00:29.116,...,5439.249,5439.249,5439.249,5439.250,5439.250,5439.249,5439.249,5439.249,5438.749,NaN
863,2023/01/16 17:00:30.188,2023/01/16 17:00:33.439,2023/01/16 17:00:33.689,2023/01/16 17:00:33.939,2023/01/16 17:00:34.190,2023/01/16 17:00:34.440,2023/01/16 17:00:34.690,2023/01/16 17:00:34.940,2023/01/16 17:00:35.191,2023/01/16 17:00:35.441,...,5445.574,5445.574,5445.574,5445.575,5445.575,5445.574,5445.574,5445.575,5445.074,NaN
864,2023/01/16 17:00:36.513,2023/01/16 17:00:39.764,2023/01/16 17:00:40.014,2023/01/16 17:00:40.264,2023/01/16 17:00:40.515,2023/01/16 17:00:40.765,2023/01/16 17:00:41.015,2023/01/16 17:00:41.265,2023/01/16 17:00:41.515,2023/01/16 17:00:41.766,...,5451.899,5451.899,5451.899,5451.900,5451.900,5451.899,5451.899,5451.899,5451.399,NaN
865,2023/01/16 17:00:42.838,2023/01/16 17:00:46.089,2023/01/16 17:00:46.339,2023/01/16 17:00:46.589,2023/01/16 17:00:46.840,2023/01/16 17:00:47.090,2023/01/16 17:00:47.340,2023/01/16 17:00:47.590,2023/01/16 17:00:47.840,2023/01/16 17:00:48.091,...,5458.224,5458.224,5458.224,5458.225,5458.225,5458.224,5458.224,5458.224,5457.724,NaN

       mass 2.0_value  mass 4.0_value  mass 5.5_value  mass 12.0_value  \
count    8.640000e+02    8.640000e+02    8.640000e+02     8.640000e+02
mean     7.171138e-10    3.559062e-14    3.430174e-14     3.104865e-13
std      2.558800e-09    1.012538e-14    1.136090e-14     2.768158e-14
min      1.017540e-10    6.400000e-15    1.320000e-14     1.118000e-13
25%      1.084107e-10    3.010000e-14    2.850000e-14     2.929000e-13
50%      1.161290e-10    3.510000e-14    3.390000e-14     3.080500e-13
75%      1.211250e-10    4.032500e-14    3.900000e-14     3.224750e-13
max      1.474520e-08    1.300000e-13    2.445000e-13     4.433000e-13

       mass 15.0_value  mass 16.0_value  mass 18.0_value  mass 28.0_value  \
count     8.640000e+02     8.640000e+02     8.640000e+02     8.640000e+02
mean      1.935312e-13     7.326005e-13     3.583548e-12     1.658591e-12
std       8.804527e-14     3.460741e-13     8.286499e-12     9.373318e-13
min       1.369000e-13     5.540000e-13     1.429900e-12     1.010000e-13
25%       1.650000e-13     6.212250e-13     1.541075e-12     1.341650e-12
50%       1.745000e-13     6.521000e-13     1.632150e-12     1.438700e-12
75%       1.836250e-13     6.893000e-13     1.711450e-12     1.563450e-12
max       6.638000e-13     2.385600e-12     4.419430e-11     6.033700e-12

       mass 32.0_value  mass 40.0_value  mass 44.0_value
count     8.640000e+02     8.640000e+02     8.630000e+02
mean      1.846625e-13     6.081377e-14     2.392514e-11
std       4.587825e-14     8.254988e-13     3.098582e-13
min       1.820000e-14     1.180000e-14     2.295120e-11
25%       1.667000e-13     2.717500e-14     2.370370e-11
50%       1.753000e-13     3.175000e-14     2.391870e-11
75%       1.845000e-13     3.660000e-14     2.408000e-11
max       4.266000e-13     2.429500e-11     2.526250e-11
                  mass 2.0_time            mass 4.0_time  \
count                       864                      864
unique                      864                      864
top     2023/01/16 15:29:44.364  2023/01/16 15:29:47.865
freq                          1                        1

                  mass 5.5_time           mass 12.0_time  \
count                       864                      864
unique                      864                      864
top     2023/01/16 15:29:48.115  2023/01/16 15:29:48.365
freq                          1                        1

                 mass 15.0_time           mass 16.0_time  \
count                       864                      864
unique                      864                      864
top     2023/01/16 15:29:48.615  2023/01/16 15:29:48.865
freq                          1                        1

                 mass 18.0_time           mass 28.0_time  \
count                       864                      864
unique                      864                      864
top     2023/01/16 15:29:49.116  2023/01/16 15:29:49.366
freq                          1                        1

                 mass 32.0_time           mass 40.0_time  \
count                       864                      864
unique                      864                      864
top     2023/01/16 15:29:49.616  2023/01/16 15:29:50.367
freq                          1                        1

                 mass 44.0_time
count                       863
unique                      863
top     2023/01/16 15:29:56.692
freq                          1

,mass 2.0_time,mass 4.0_time,mass 5.5_time,mass 12.0_time,mass 15.0_time,mass 16.0_time,mass 18.0_time,mass 28.0_time,mass 32.0_time,mass 40.0_time,...,"Elapsed time, mass 4","Elapsed time, mass 5.5","Elapsed time, mass 12","Elapsed time, mass 15","Elapsed time, mass 16","Elapsed time, mass 18","Elapsed time, mass 28","Elapsed time, mass 32","Elapsed time, mass 40","Elapsed time, mass 44"
2,2023/01/16 15:29:44.364,2023/01/16 15:29:47.865,2023/01/16 15:29:48.115,2023/01/16 15:29:48.365,2023/01/16 15:29:48.615,2023/01/16 15:29:48.865,2023/01/16 15:29:49.116,2023/01/16 15:29:49.366,2023/01/16 15:29:49.616,2023/01/16 15:29:50.367,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,NaN
3,2023/01/16 15:29:50.688,2023/01/16 15:29:53.939,2023/01/16 15:29:54.189,2023/01/16 15:29:54.439,2023/01/16 15:29:54.690,2023/01/16 15:29:54.940,2023/01/16 15:29:55.190,2023/01/16 15:29:55.440,2023/01/16 15:29:55.690,2023/01/16 15:29:55.940,...,6.074,6.074,6.074,6.075,6.075,6.074,6.074,6.074,5.573,NaN
4,2023/01/16 15:29:57.013,2023/01/16 15:30:00.264,2023/01/16 15:30:00.514,2023/01/16 15:30:00.764,2023/01/16 15:30:01.015,2023/01/16 15:30:01.265,2023/01/16 15:30:01.515,2023/01/16 15:30:01.765,2023/01/16 15:30:02.015,2023/01/16 15:30:02.266,...,12.399,12.399,12.399,12.400,12.400,12.399,12.399,12.399,11.899,NaN
5,2023/01/16 15:30:03.338,2023/01/16 15:30:06.589,2023/01/16 15:30:06.839,2023/01/16 15:30:07.089,2023/01/16 15:30:07.340,2023/01/16 15:30:07.590,2023/01/16 15:30:07.840,2023/01/16 15:30:08.090,2023/01/16 15:30:08.340,2023/01/16 15:30:08.591,...,18.724,18.724,18.724,18.725,18.725,18.724,18.724,18.724,18.224,NaN
6,2023/01/16 15:30:09.663,2023/01/16 15:30:12.914,2023/01/16 15:30:13.164,2023/01/16 15:30:13.414,2023/01/16 15:30:13.665,2023/01/16 15:30:13.915,2023/01/16 15:30:14.165,2023/01/16 15:30:14.415,2023/01/16 15:30:14.665,2023/01/16 15:30:14.916,...,25.049,25.049,25.049,25.050,25.050,25.049,25.049,25.049,24.549,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
861,2023/01/16 17:00:17.538,2023/01/16 17:00:20.789,2023/01/16 17:00:21.039,2023/01/16 17:00:21.289,2023/01/16 17:00:21.540,2023/01/16 17:00:21.790,2023/01/16 17:00:22.040,2023/01/16 17:00:22.290,2023/01/16 17:00:22.540,2023/01/16 17:00:22.791,...,5432.924,5432.924,5432.924,5432.925,5432.925,5432.924,5432.924,5432.924,5432.424,NaN
862,2023/01/16 17:00:23.863,2023/01/16 17:00:27.114,2023/01/16 17:00:27.364,2023/01/16 17:00:27.614,2023/01/16 17:00:27.865,2023/01/16 17:00:28.115,2023/01/16 17:00:28.365,2023/01/16 17:00:28.615,2023/01/16 17:00:28.865,2023/01/16 17:00:29.116,...,5439.249,5439.249,5439.249,5439.250,5439.250,5439.249,5439.249,5439.249,5438.749,NaN
863,2023/01/16 17:00:30.188,2023/01/16 17:00:33.439,2023/01/16 17:00:33.689,2023/01/16 17:00:33.939,2023/01/16 17:00:34.190,2023/01/16 17:00:34.440,2023/01/16 17:00:34.690,2023/01/16 17:00:34.940,2023/01/16 17:00:35.191,2023/01/16 17:00:35.441,...,5445.574,5445.574,5445.574,5445.575,5445.575,5445.574,5445.574,5445.575,5445.074,NaN
864,2023/01/16 17:00:36.513,2023/01/16 17:00:39.764,2023/01/16 17:00:40.014,2023/01/16 17:00:40.264,2023/01/16 17:00:40.515,2023/01/16 17:00:40.765,2023/01/16 17:00:41.015,2023/01/16 17:00:41.265,2023/01/16 17:00:41.515,2023/01/16 17:00:41.766,...,5451.899,5451.899,5451.899,5451.900,5451.900,5451.899,5451.899,5451.899,5451.399,NaN
865,2023/01/16 17:00:42.838,2023/01/16 17:00:46.089,2023/01/16 17:00:46.339,2023/01/16 17:00:46.589,2023/01/16 17:00:46.840,2023/01/16 17:00:47.090,2023/01/16 17:00:47.340,2023/01/16 17:00:47.590,2023/01/16 17:00:47.840,2023/01/16 17:00:48.091,...,5458.224,5458.224,5458.224,5458.225,5458.225,5458.224,5458.224,5458.224,5457.724,NaN

In [3]:
#read in the baseline MID

basel = pd.read_csv("baseline MID.tsv", sep="\t", skiprows=lambda x: x <=11,  on_bad_lines="skip")
basel.drop([0,1], inplace=True)
print(basel.describe())
#bring the time data into a new df
time1 = pd.DataFrame(basel.iloc[:,0::2]) #- get every second column
print(time.describe())

#add elapsed time columns
def elapsed_time(df):
    itr = 0
    counter = len(df.columns)
    masses = [2,4,5.5,12,15,16,18,28,32,40,44]
    for i in df:
        timestamp = pd.to_datetime(df[i], format="%Y/%m/%d %H:%M:%S.%f")
        runtime = (timestamp-timestamp[2]).dt.total_seconds()
        colname = "Elapsed time, mass {}".format(masses[itr]) 
        df.insert(counter, colname, runtime)
        itr += 1
        counter += 1
    return(df)
elapsed_time(time1)

#time["Elapsed time, mass 40"].describe()

       mass 2.0_value  mass 4.0_value  mass 5.5_value  mass 12.0_value  \
count    4.660000e+02    4.660000e+02    4.660000e+02     4.660000e+02
mean     7.146685e-11    2.264273e-13    5.358240e-14     4.066794e-13
std      2.799245e-11    2.475024e-13    4.287381e-14     8.985203e-14
min      2.915020e-11    2.200000e-14    1.300000e-15     1.900000e-15
25%      4.948198e-11    9.412500e-14    3.352500e-14     3.339250e-13
50%      9.245270e-11    1.220000e-13    3.900000e-14     4.188500e-13
75%      9.552720e-11    1.501000e-13    4.500000e-14     4.809000e-13
max      9.836250e-11    7.760000e-13    2.484000e-13     6.532000e-13

       mass 15.0_value  mass 16.0_value  mass 18.0_value  mass 28.0_value  \
count     4.660000e+02     4.660000e+02     4.660000e+02     4.660000e+02
mean      1.737571e-13     8.296103e-13     1.740183e-12     2.116008e-12
std       7.719386e-14     1.523530e-13     2.531133e-13     5.228452e-13
min       6.400000e-15     1.089000e-13     1.354200e-12     4.800000e-15
25%       7.557500e-14     7.030250e-13     1.551175e-12     1.552475e-12
50%       1.828500e-13     7.943500e-13     1.616250e-12     2.184450e-12
75%       2.341250e-13     9.801750e-13     1.982450e-12     2.591925e-12
max       4.706000e-13     1.482600e-12     2.293300e-12     2.934600e-12

       mass 32.0_value  mass 40.0_value  mass 44.0_value
count     4.660000e+02     4.650000e+02     4.630000e+02
mean      1.621122e-13     1.748477e-13     2.431633e-11
std       1.119392e-12     1.587795e-12     3.846591e-13
min       5.000000e-15     3.200000e-15     2.332750e-11
25%       5.562500e-14     3.670000e-14     2.408000e-11
50%       6.325000e-14     4.320000e-14     2.429500e-11
75%       7.670000e-14     1.249000e-13     2.456370e-11
max       2.418750e-11     2.451000e-11     2.547750e-11
       Elapsed time, mass 2  Elapsed time, mass 4  Elapsed time, mass 5.5  \
count            864.000000            864.000000              864.000000
mean            2729.236501           2728.986791             2728.986791
std             1578.464545           1578.464044             1578.464044
min                0.000000              0.000000                0.000000
25%             1364.617750           1364.367750             1364.367750
50%             2729.236500           2728.986500             2728.986500
75%             4093.855250           4093.605250             4093.605250
max             5458.474000           5458.224000             5458.224000

       Elapsed time, mass 12  Elapsed time, mass 15  Elapsed time, mass 16  \
count             864.000000             864.000000             864.000000
mean             2728.986795            2728.987789            2728.987789
std              1578.464041            1578.464046            1578.464046
min                 0.000000               0.000000               0.000000
25%              1364.367750            1364.368750            1364.368750
50%              2728.986500            2728.987500            2728.987500
75%              4093.605250            4093.606250            4093.606250
max              5458.224000            5458.225000            5458.225000

       Elapsed time, mass 18  Elapsed time, mass 28  Elapsed time, mass 32  \
count             864.000000             864.000000             864.000000
mean             2728.986791            2728.986791            2728.986803
std              1578.464044            1578.464044            1578.464064
min                 0.000000               0.000000               0.000000
25%              1364.367750            1364.367750            1364.367750
50%              2728.986500            2728.986500            2728.986500
75%              4093.605250            4093.605250            4093.605250
max              5458.224000            5458.224000            5458.224000

       Elapsed time, mass 40  Elapsed time, mass 44
count             864.000000                    0.0
mean             2728.487368                    NaN
std              1578.463044                    NaN
min                 0.000000                    NaN
25%              1363.867750                    NaN
50%              2728.486500                    NaN
75%              4093.105250                    NaN
max              5457.724000                    NaN
       mass 2.0_value  mass 4.0_value  mass 5.5_value  mass 12.0_value  \
count    4.660000e+02    4.660000e+02    4.660000e+02     4.660000e+02
mean     7.146685e-11    2.264273e-13    5.358240e-14     4.066794e-13
std      2.799245e-11    2.475024e-13    4.287381e-14     8.985203e-14
min      2.915020e-11    2.200000e-14    1.300000e-15     1.900000e-15
25%      4.948198e-11    9.412500e-14    3.352500e-14     3.339250e-13
50%      9.245270e-11    1.220000e-13    3.900000e-14     4.188500e-13
75%      9.552720e-11    1.501000e-13    4.500000e-14     4.809000e-13
max      9.836250e-11    7.760000e-13    2.484000e-13     6.532000e-13

       mass 15.0_value  mass 16.0_value  mass 18.0_value  mass 28.0_value  \
count     4.660000e+02     4.660000e+02     4.660000e+02     4.660000e+02
mean      1.737571e-13     8.296103e-13     1.740183e-12     2.116008e-12
std       7.719386e-14     1.523530e-13     2.531133e-13     5.228452e-13
min       6.400000e-15     1.089000e-13     1.354200e-12     4.800000e-15
25%       7.557500e-14     7.030250e-13     1.551175e-12     1.552475e-12
50%       1.828500e-13     7.943500e-13     1.616250e-12     2.184450e-12
75%       2.341250e-13     9.801750e-13     1.982450e-12     2.591925e-12
max       4.706000e-13     1.482600e-12     2.293300e-12     2.934600e-12

       mass 32.0_value  mass 40.0_value  mass 44.0_value
count     4.660000e+02     4.650000e+02     4.630000e+02
mean      1.621122e-13     1.748477e-13     2.431633e-11
std       1.119392e-12     1.587795e-12     3.846591e-13
min       5.000000e-15     3.200000e-15     2.332750e-11
25%       5.562500e-14     3.670000e-14     2.408000e-11
50%       6.325000e-14     4.320000e-14     2.429500e-11
75%       7.670000e-14     1.249000e-13     2.456370e-11
max       2.418750e-11     2.451000e-11     2.547750e-11
       Elapsed time, mass 2  Elapsed time, mass 4  Elapsed time, mass 5.5  \
count            864.000000            864.000000              864.000000
mean            2729.236501           2728.986791             2728.986791
std             1578.464545           1578.464044             1578.464044
min                0.000000              0.000000                0.000000
25%             1364.617750           1364.367750             1364.367750
50%             2729.236500           2728.986500             2728.986500
75%             4093.855250           4093.605250             4093.605250
max             5458.474000           5458.224000             5458.224000

       Elapsed time, mass 12  Elapsed time, mass 15  Elapsed time, mass 16  \
count             864.000000             864.000000             864.000000
mean             2728.986795            2728.987789            2728.987789
std              1578.464041            1578.464046            1578.464046
min                 0.000000               0.000000               0.000000
25%              1364.367750            1364.368750            1364.368750
50%              2728.986500            2728.987500            2728.987500
75%              4093.605250            4093.606250            4093.606250
max              5458.224000            5458.225000            5458.225000

       Elapsed time, mass 18  Elapsed time, mass 28  Elapsed time, mass 32  \
count             864.000000             864.000000             864.000000
mean             2728.986791            2728.986791            2728.986803
std              1578.464044            1578.464044            1578.464064
min                 0.000000               0.000000               0.000000
25%              1364.367750            1364.367750            1364.367750
50%              2728.986500            2728.986500            2728.986500
75%              4093.605250            4093.605250            4093.605250
max              5458.224000            5458.224000            5458.224000

       Elapsed time, mass 40  Elapsed time, mass 44
count             864.000000                    0.0
mean             2728.487368                    NaN
std              1578.463044                    NaN
min                 0.000000                    NaN
25%              1363.867750                    NaN
50%              2728.486500                    NaN
75%              4093.105250                    NaN
max              5457.724000                    NaN

,mass 2.0_time,mass 4.0_time,mass 5.5_time,mass 12.0_time,mass 15.0_time,mass 16.0_time,mass 18.0_time,mass 28.0_time,mass 32.0_time,mass 40.0_time,...,"Elapsed time, mass 4","Elapsed time, mass 5.5","Elapsed time, mass 12","Elapsed time, mass 15","Elapsed time, mass 16","Elapsed time, mass 18","Elapsed time, mass 28","Elapsed time, mass 32","Elapsed time, mass 40","Elapsed time, mass 44"
2,2023/01/16 13:30:13.729,2023/01/16 13:30:16.980,2023/01/16 13:30:17.230,2023/01/16 13:30:17.480,2023/01/16 13:30:17.730,2023/01/16 13:30:17.980,2023/01/16 13:30:18.230,2023/01/16 13:30:18.481,2023/01/16 13:30:18.731,2023/01/16 13:30:18.981,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
3,2023/01/16 13:30:20.125,2023/01/16 13:30:23.376,2023/01/16 13:30:23.626,2023/01/16 13:30:23.876,2023/01/16 13:30:24.127,2023/01/16 13:30:24.377,2023/01/16 13:30:24.627,2023/01/16 13:30:24.877,2023/01/16 13:30:25.127,2023/01/16 13:30:25.377,...,6.396,6.396,6.396,6.397,6.397,6.397,6.396,6.396,6.396,6.396
4,2023/01/16 13:30:26.521,2023/01/16 13:30:29.772,2023/01/16 13:30:30.022,2023/01/16 13:30:30.272,2023/01/16 13:30:30.522,2023/01/16 13:30:30.772,2023/01/16 13:30:31.022,2023/01/16 13:30:31.273,2023/01/16 13:30:31.523,2023/01/16 13:30:31.773,...,12.792,12.792,12.792,12.792,12.792,12.792,12.792,12.792,12.792,12.791
5,2023/01/16 13:30:32.916,2023/01/16 13:30:36.167,2023/01/16 13:30:36.417,2023/01/16 13:30:36.667,2023/01/16 13:30:36.917,2023/01/16 13:30:37.167,2023/01/16 13:30:37.417,2023/01/16 13:30:37.668,2023/01/16 13:30:37.918,2023/01/16 13:30:38.168,...,19.187,19.187,19.187,19.187,19.187,19.187,19.187,19.187,19.187,19.186
6,2023/01/16 13:30:39.311,2023/01/16 13:30:42.562,2023/01/16 13:30:42.812,2023/01/16 13:30:43.062,2023/01/16 13:30:43.312,2023/01/16 13:30:43.562,2023/01/16 13:30:43.812,2023/01/16 13:30:44.063,2023/01/16 13:30:44.313,2023/01/16 13:30:44.563,...,25.582,25.582,25.582,25.582,25.582,25.582,25.582,25.582,25.582,25.581
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
463,2023/01/16 14:19:25.018,2023/01/16 14:19:25.268,2023/01/16 14:19:25.518,2023/01/16 14:19:25.768,2023/01/16 14:19:26.018,2023/01/16 14:19:26.269,2023/01/16 14:19:26.519,2023/01/16 14:19:26.770,2023/01/16 14:19:27.020,2023/01/16 14:19:27.270,...,2948.288,2948.288,2948.288,2948.288,2948.289,2948.289,2948.289,2948.289,2948.289,2948.288
464,2023/01/16 14:19:31.414,2023/01/16 14:19:31.664,2023/01/16 14:19:31.915,2023/01/16 14:19:32.165,2023/01/16 14:19:32.415,2023/01/16 14:19:32.665,2023/01/16 14:19:32.915,2023/01/16 14:19:33.166,2023/01/16 14:19:33.416,2023/01/16 14:19:33.666,...,2954.684,2954.685,2954.685,2954.685,2954.685,2954.685,2954.685,2954.685,2954.685,2954.685
465,2023/01/16 14:19:37.811,2023/01/16 14:19:38.061,2023/01/16 14:19:38.311,2023/01/16 14:19:38.562,2023/01/16 14:19:38.812,2023/01/16 14:19:39.062,2023/01/16 14:19:39.312,2023/01/16 14:19:39.562,2023/01/16 14:19:39.813,2023/01/16 14:19:40.063,...,2961.081,2961.081,2961.082,2961.082,2961.082,2961.082,2961.081,2961.082,2961.082,2961.081
466,2023/01/16 14:19:44.207,2023/01/16 14:19:44.457,2023/01/16 14:19:44.707,2023/01/16 14:19:44.957,2023/01/16 14:19:45.207,2023/01/16 14:19:45.458,2023/01/16 14:19:45.708,2023/01/16 14:19:45.958,2023/01/16 14:19:46.208,2023/01/16 14:19:46.458,...,2967.477,2967.477,2967.477,2967.477,2967.478,2967.478,2967.477,2967.477,2967.477,2967.477
467,2023/01/16 14:19:50.603,2023/01/16 14:19:50.853,2023/01/16 14:19:51.103,2023/01/16 14:19:51.353,2023/01/16 14:19:51.603,2023/01/16 14:19:51.854,2023/01/16 14:19:52.104,2023/01/16 14:19:52.355,2023/01/16 14:19:52.605,2023/01/16 14:19:52.855,...,2973.873,2973.873,2973.873,2973.873,2973.874,2973.874,2973.874,2973.874,2973.874,2973.873

,mass 2.0_time,mass 4.0_time,mass 5.5_time,mass 12.0_time,mass 15.0_time,mass 16.0_time,mass 18.0_time,mass 28.0_time,mass 32.0_time,mass 40.0_time,...,"Elapsed time, mass 4","Elapsed time, mass 5.5","Elapsed time, mass 12","Elapsed time, mass 15","Elapsed time, mass 16","Elapsed time, mass 18","Elapsed time, mass 28","Elapsed time, mass 32","Elapsed time, mass 40","Elapsed time, mass 44"
2,2023/01/16 13:30:13.729,2023/01/16 13:30:16.980,2023/01/16 13:30:17.230,2023/01/16 13:30:17.480,2023/01/16 13:30:17.730,2023/01/16 13:30:17.980,2023/01/16 13:30:18.230,2023/01/16 13:30:18.481,2023/01/16 13:30:18.731,2023/01/16 13:30:18.981,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
3,2023/01/16 13:30:20.125,2023/01/16 13:30:23.376,2023/01/16 13:30:23.626,2023/01/16 13:30:23.876,2023/01/16 13:30:24.127,2023/01/16 13:30:24.377,2023/01/16 13:30:24.627,2023/01/16 13:30:24.877,2023/01/16 13:30:25.127,2023/01/16 13:30:25.377,...,6.396,6.396,6.396,6.397,6.397,6.397,6.396,6.396,6.396,6.396
4,2023/01/16 13:30:26.521,2023/01/16 13:30:29.772,2023/01/16 13:30:30.022,2023/01/16 13:30:30.272,2023/01/16 13:30:30.522,2023/01/16 13:30:30.772,2023/01/16 13:30:31.022,2023/01/16 13:30:31.273,2023/01/16 13:30:31.523,2023/01/16 13:30:31.773,...,12.792,12.792,12.792,12.792,12.792,12.792,12.792,12.792,12.792,12.791
5,2023/01/16 13:30:32.916,2023/01/16 13:30:36.167,2023/01/16 13:30:36.417,2023/01/16 13:30:36.667,2023/01/16 13:30:36.917,2023/01/16 13:30:37.167,2023/01/16 13:30:37.417,2023/01/16 13:30:37.668,2023/01/16 13:30:37.918,2023/01/16 13:30:38.168,...,19.187,19.187,19.187,19.187,19.187,19.187,19.187,19.187,19.187,19.186
6,2023/01/16 13:30:39.311,2023/01/16 13:30:42.562,2023/01/16 13:30:42.812,2023/01/16 13:30:43.062,2023/01/16 13:30:43.312,2023/01/16 13:30:43.562,2023/01/16 13:30:43.812,2023/01/16 13:30:44.063,2023/01/16 13:30:44.313,2023/01/16 13:30:44.563,...,25.582,25.582,25.582,25.582,25.582,25.582,25.582,25.582,25.582,25.581
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
463,2023/01/16 14:19:25.018,2023/01/16 14:19:25.268,2023/01/16 14:19:25.518,2023/01/16 14:19:25.768,2023/01/16 14:19:26.018,2023/01/16 14:19:26.269,2023/01/16 14:19:26.519,2023/01/16 14:19:26.770,2023/01/16 14:19:27.020,2023/01/16 14:19:27.270,...,2948.288,2948.288,2948.288,2948.288,2948.289,2948.289,2948.289,2948.289,2948.289,2948.288
464,2023/01/16 14:19:31.414,2023/01/16 14:19:31.664,2023/01/16 14:19:31.915,2023/01/16 14:19:32.165,2023/01/16 14:19:32.415,2023/01/16 14:19:32.665,2023/01/16 14:19:32.915,2023/01/16 14:19:33.166,2023/01/16 14:19:33.416,2023/01/16 14:19:33.666,...,2954.684,2954.685,2954.685,2954.685,2954.685,2954.685,2954.685,2954.685,2954.685,2954.685
465,2023/01/16 14:19:37.811,2023/01/16 14:19:38.061,2023/01/16 14:19:38.311,2023/01/16 14:19:38.562,2023/01/16 14:19:38.812,2023/01/16 14:19:39.062,2023/01/16 14:19:39.312,2023/01/16 14:19:39.562,2023/01/16 14:19:39.813,2023/01/16 14:19:40.063,...,2961.081,2961.081,2961.082,2961.082,2961.082,2961.082,2961.081,2961.082,2961.082,2961.081
466,2023/01/16 14:19:44.207,2023/01/16 14:19:44.457,2023/01/16 14:19:44.707,2023/01/16 14:19:44.957,2023/01/16 14:19:45.207,2023/01/16 14:19:45.458,2023/01/16 14:19:45.708,2023/01/16 14:19:45.958,2023/01/16 14:19:46.208,2023/01/16 14:19:46.458,...,2967.477,2967.477,2967.477,2967.477,2967.478,2967.478,2967.477,2967.477,2967.477,2967.477
467,2023/01/16 14:19:50.603,2023/01/16 14:19:50.853,2023/01/16 14:19:51.103,2023/01/16 14:19:51.353,2023/01/16 14:19:51.603,2023/01/16 14:19:51.854,2023/01/16 14:19:52.104,2023/01/16 14:19:52.355,2023/01/16 14:19:52.605,2023/01/16 14:19:52.855,...,2973.873,2973.873,2973.873,2973.873,2973.874,2973.874,2973.874,2973.874,2973.874,2973.873

In [4]:
#reading the Emission current, pressures
vaclog=pd.read_csv("vaclog", sep="\t")
vaclog.head()

#adding an elapsed time column
timestamp=[]
for i in vaclog["Time"]:
    timestamp.append(i)
#making the column into a datetime object
timestamps=pd.to_datetime(vaclog["Time"],format="%d/%m/%Y %H:%M:%S")
runtime=(timestamps-timestamps[0]).dt.total_seconds()    
vaclog.insert(2,"Elapsed time",runtime)
vaclog.drop(index=vaclog.index[0], 
        axis=0, 
        inplace=True)

vaclog.head()

,Live comments,Time,Elapsed time,injection 100mbar,Barion_2,Barion_1,DUAL experiment,DUAL insulation,injection 1mbar,helium,T-platinum,T-CERNOX,I_emission,I_grid
1,NaN,16/01/2023 14:21:24,7.0,68.018,2.520000e-09,2.780000e-09,4.996000e-09,4.015000e-07,1.1,238.0,-5.163,4296.952,NaN,NaN
2,NaN,16/01/2023 14:21:31,14.0,68.018,2.460000e-09,2.730000e-09,4.996000e-09,4.015000e-07,1.1,237.0,-5.163,4296.728,NaN,NaN
3,NaN,16/01/2023 14:21:38,21.0,68.018,2.430000e-09,2.700000e-09,4.996000e-09,4.015000e-07,1.1,237.0,-5.163,4296.952,NaN,NaN
4,NaN,16/01/2023 14:21:46,29.0,68.015,2.400000e-09,2.680000e-09,4.996000e-09,4.015000e-07,1.1,237.0,-5.163,4297.177,NaN,NaN
5,NaN,16/01/2023 14:21:53,36.0,68.015,2.390000e-09,2.660000e-09,4.996000e-09,4.015000e-07,1.1,237.0,-5.163,4297.177,NaN,NaN

,Live comments,Time,Elapsed time,injection 100mbar,Barion_2,Barion_1,DUAL experiment,DUAL insulation,injection 1mbar,helium,T-platinum,T-CERNOX,I_emission,I_grid
1,NaN,16/01/2023 14:21:24,7.0,68.018,2.520000e-09,2.780000e-09,4.996000e-09,4.015000e-07,1.1,238.0,-5.163,4296.952,NaN,NaN
2,NaN,16/01/2023 14:21:31,14.0,68.018,2.460000e-09,2.730000e-09,4.996000e-09,4.015000e-07,1.1,237.0,-5.163,4296.728,NaN,NaN
3,NaN,16/01/2023 14:21:38,21.0,68.018,2.430000e-09,2.700000e-09,4.996000e-09,4.015000e-07,1.1,237.0,-5.163,4296.952,NaN,NaN
4,NaN,16/01/2023 14:21:46,29.0,68.015,2.400000e-09,2.680000e-09,4.996000e-09,4.015000e-07,1.1,237.0,-5.163,4297.177,NaN,NaN
5,NaN,16/01/2023 14:21:53,36.0,68.015,2.390000e-09,2.660000e-09,4.996000e-09,4.015000e-07,1.1,237.0,-5.163,4297.177,NaN,NaN

In [5]:
#Reading in the HiVolta measurement file 
hv = pd.read_csv("hv log", sep=",")
#hv.drop(columns=["Vmon1","Vmon2","Vmon3","Vmon4","Vmon5","Vmon6","Vmon7","Vmon8","Imon3","Imon4","Imon5","Imon6","Imon7","Imon8","Comments1"], inplace=True)
hv["hv_grid"]=[element * 1e-6 for element in hv["IMon1"]]
hv["I_em"]=[element * 1e-6 for element in hv["IMon2"]]
hv.drop(hv.columns[hv.columns.str.contains('Unnamed',case = False)],axis = 1, inplace = True)
#hv["I_em"]=abs(hv["I_em"])
#hv["hv_grid"]=abs(hv["hv_grid"])
hv["datetime"] = pd.to_datetime(hv['Date'] + ' ' + hv['Time'],format="%d/%m/%Y %H:%M:%S.%f")
hv['datetime'] = hv['datetime'].dt.strftime('%Y-%m-%d %H:%M:%S.%f')
#hv.insert(0,"datetime",hv["Date"]+" "+hv["Time"])

#adding an elapsed time column
timestamp=[]
for i in hv["Time"]:
    timestamp.append(i)
    
#making the column into a datetime object
timestamps=pd.to_datetime(hv["Time"],format="%H:%M:%S.%f")
runtime=(timestamps-timestamps[0]).dt.total_seconds()    
hv.insert(2,"Elapsed time",runtime)


hv

,Date,Time,Elapsed time,VMon1,VMon2,VMon3,VMon4,VMon5,VMon6,VMon7,...,IMon3,IMon4,IMon5,IMon6,IMon7,IMon8,Comment,hv_grid,I_em,datetime
0,16/01/2023,15:29:37.693,0.000,0.04,0.06,0.04,0.08,0.02,0.0,0.0,...,0.0090,0.0107,0.0006,0.0370,-0.0225,-0.0087,NaN,2.400000e-09,8.100000e-09,2023-01-16 15:29:37.693000
1,16/01/2023,15:29:38.875,1.182,0.04,0.06,0.04,0.08,0.02,0.0,0.0,...,0.0090,0.0107,0.0006,0.0370,-0.0225,-0.0087,NaN,2.400000e-09,8.100000e-09,2023-01-16 15:29:38.875000
2,16/01/2023,15:29:40.053,2.360,0.04,0.06,0.04,0.08,0.02,0.0,0.0,...,0.0090,0.0107,0.0006,0.0370,-0.0225,-0.0082,NaN,2.400000e-09,8.100000e-09,2023-01-16 15:29:40.053000
3,16/01/2023,15:29:41.235,3.542,0.04,0.06,0.04,0.08,0.02,0.0,0.0,...,0.0090,0.0107,0.0006,0.0370,-0.0225,-0.0082,NaN,2.400000e-09,8.100000e-09,2023-01-16 15:29:41.235000
4,16/01/2023,15:29:42.419,4.726,0.04,0.06,0.04,0.08,0.02,0.0,0.0,...,0.0090,0.0107,0.0006,0.0370,-0.0225,-0.0082,NaN,2.400000e-09,8.100000e-09,2023-01-16 15:29:42.419000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4528,16/01/2023,17:00:36.820,5459.127,0.06,0.06,0.04,0.08,0.00,0.0,0.0,...,0.0705,0.0117,0.0799,0.0204,-0.0209,-0.0079,NaN,9.500000e-09,9.910000e-08,2023-01-16 17:00:36.820000
4529,16/01/2023,17:00:38.007,5460.314,0.06,0.06,0.04,0.08,0.00,0.0,0.0,...,0.0705,0.0127,0.0799,0.0204,-0.0209,-0.0079,NaN,9.500000e-09,9.910000e-08,2023-01-16 17:00:38.007000
4530,16/01/2023,17:00:39.201,5461.508,0.06,0.06,0.04,0.08,0.00,0.0,0.0,...,0.0705,0.0132,0.0799,0.0204,-0.0209,-0.0079,NaN,9.500000e-09,9.910000e-08,2023-01-16 17:00:39.201000
4531,16/01/2023,17:00:40.389,5462.696,0.06,0.06,0.04,0.08,0.00,0.0,0.0,...,0.0705,0.0132,0.0799,0.0204,-0.0209,-0.0079,NaN,9.500000e-09,9.910000e-08,2023-01-16 17:00:40.389000
4532,16/01/2023,17:00:41.573,5463.880,0.06,0.06,0.04,0.08,0.00,0.0,0.0,...,0.0705,0.0132,0.0799,0.0204,-0.0209,-0.0079,NaN,9.500000e-09,9.900000e-08,2023-01-16 17:00:41.573000

,Date,Time,Elapsed time,VMon1,VMon2,VMon3,VMon4,VMon5,VMon6,VMon7,...,IMon3,IMon4,IMon5,IMon6,IMon7,IMon8,Comment,hv_grid,I_em,datetime
0,16/01/2023,15:29:37.693,0.000,0.04,0.06,0.04,0.08,0.02,0.0,0.0,...,0.0090,0.0107,0.0006,0.0370,-0.0225,-0.0087,NaN,2.400000e-09,8.100000e-09,2023-01-16 15:29:37.693000
1,16/01/2023,15:29:38.875,1.182,0.04,0.06,0.04,0.08,0.02,0.0,0.0,...,0.0090,0.0107,0.0006,0.0370,-0.0225,-0.0087,NaN,2.400000e-09,8.100000e-09,2023-01-16 15:29:38.875000
2,16/01/2023,15:29:40.053,2.360,0.04,0.06,0.04,0.08,0.02,0.0,0.0,...,0.0090,0.0107,0.0006,0.0370,-0.0225,-0.0082,NaN,2.400000e-09,8.100000e-09,2023-01-16 15:29:40.053000
3,16/01/2023,15:29:41.235,3.542,0.04,0.06,0.04,0.08,0.02,0.0,0.0,...,0.0090,0.0107,0.0006,0.0370,-0.0225,-0.0082,NaN,2.400000e-09,8.100000e-09,2023-01-16 15:29:41.235000
4,16/01/2023,15:29:42.419,4.726,0.04,0.06,0.04,0.08,0.02,0.0,0.0,...,0.0090,0.0107,0.0006,0.0370,-0.0225,-0.0082,NaN,2.400000e-09,8.100000e-09,2023-01-16 15:29:42.419000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4528,16/01/2023,17:00:36.820,5459.127,0.06,0.06,0.04,0.08,0.00,0.0,0.0,...,0.0705,0.0117,0.0799,0.0204,-0.0209,-0.0079,NaN,9.500000e-09,9.910000e-08,2023-01-16 17:00:36.820000
4529,16/01/2023,17:00:38.007,5460.314,0.06,0.06,0.04,0.08,0.00,0.0,0.0,...,0.0705,0.0127,0.0799,0.0204,-0.0209,-0.0079,NaN,9.500000e-09,9.910000e-08,2023-01-16 17:00:38.007000
4530,16/01/2023,17:00:39.201,5461.508,0.06,0.06,0.04,0.08,0.00,0.0,0.0,...,0.0705,0.0132,0.0799,0.0204,-0.0209,-0.0079,NaN,9.500000e-09,9.910000e-08,2023-01-16 17:00:39.201000
4531,16/01/2023,17:00:40.389,5462.696,0.06,0.06,0.04,0.08,0.00,0.0,0.0,...,0.0705,0.0132,0.0799,0.0204,-0.0209,-0.0079,NaN,9.500000e-09,9.910000e-08,2023-01-16 17:00:40.389000
4532,16/01/2023,17:00:41.573,5463.880,0.06,0.06,0.04,0.08,0.00,0.0,0.0,...,0.0705,0.0132,0.0799,0.0204,-0.0209,-0.0079,NaN,9.500000e-09,9.900000e-08,2023-01-16 17:00:41.573000

### Data processing - single point desorption

In [6]:
#Temperature curve for CERNOX - for temp stability
A=[230.317302,-6170.1513,71837.9529,-477946.76,2.003668910085786e+6,-5.488690193047771e+6,9.830475663897528e+6,-1.111226817786569e+7,7.202477878914065e+6,-2.04194551328507e+6]
#specify fit parameters A, data (Resistance values)
def polyfit(params,data):
    total=[]
    for j in data: 
        exp=0
        for i in range(len(params)):
            exp += (params[i]/(math.log10(j))**i)
        total.append(10**exp)
    return(total)

In [7]:
#Filtering background signal

#Find the timestamp where emission was turned on and off
print("Result 1:",hv.loc[hv["Comment"]=="grid transparent"])
print("Result 2:", hv.loc[hv["Comment"]=="grid repelling"])
print("Result 3:", hv.loc[hv["Comment"]=="electron activity grid repelling"])

x=pd.Timestamp(2023, 1, 12, 17 ,23, 58)
y=pd.Timestamp(2023, 1, 12, 17, 28, 43)
z=pd.Timestamp(2023, 1, 12, 17, 20, 13)

#then find the time value closest to it in the MID scan file 
print("\n","Result 4:",mid.iloc[(pd.to_datetime(mid['mass 2.0_time'],format="%Y/%m/%d %H:%M:%S") - x).abs().argsort(),:])
print("\n","Result 5:",mid.iloc[(pd.to_datetime(mid['mass 2.0_time'],format="%Y/%m/%d %H:%M:%S") - y).abs().argsort(),:])
print("\n","Result 6:",mid.iloc[(pd.to_datetime(mid['mass 2.0_time'],format="%Y/%m/%d %H:%M:%S") - z).abs().argsort(),:])

#take a mass with a signal known to be in the background
bck=np.mean(mid["mass 40.0_value"])

#apply background correction to the rest of the mass spectrum
mid["mass 2, corr"]=mid["mass 2.0_value"]-bck

#From the signal, get the partial pressures 
h2_sens=2.13e-2
p_h2=mid["mass 2, corr"][91:136]/h2_sens
print(p_h2.describe())

#baseline for partial pressure delta
base_h2=mid["mass 2, corr"][56:91]/h2_sens
base_h2.describe()

Result 1:            Date          Time  Elapsed time   VMon1   VMon2    VMon3    VMon4  \
501  16/01/2023  15:39:46.998       609.305  449.40  100.08  1000.02  1000.14
502  16/01/2023  15:39:48.204       610.511  309.40  100.08  1000.02  1000.14
503  16/01/2023  15:39:49.406       611.713  178.92  100.06  1000.04  1000.14
504  16/01/2023  15:39:50.609       612.916   90.00   99.98  1000.06  1000.16
505  16/01/2023  15:39:51.804       614.111    1.04   99.90  1000.04  1000.14

       VMon5   VMon6  VMon7  ...    IMon3    IMon4    IMon5    IMon6   IMon7  \
501  1000.12  499.98    0.0  ...  21.8108  21.8398  21.8108  21.8081 -0.0192
502  1000.12  499.98    0.0  ...  21.8169  21.8462  21.8172  21.8152 -0.0192
503  1000.12  499.98    0.0  ...  21.8208  21.8502  21.8236  21.8238 -0.0192
504  1000.14  499.98    0.0  ...  21.3355  21.5411  21.6138  21.7407 -0.0192
505  1000.12  499.98    0.0  ...  21.7729  21.8035  21.7545  21.7587 -0.0192

      IMon8           Comment       hv_grid          I_em  \
501 -0.0071  grid transparent -4.318000e-07  2.250000e-08
502 -0.0068  grid transparent -4.431000e-07  2.650000e-08
503 -0.0068  grid transparent -4.651000e-07  1.678000e-07
504 -0.0068  grid transparent -3.469000e-07  2.209400e-06
505 -0.0068  grid transparent -6.057000e-07  4.345600e-06

                       datetime
501  2023-01-16 15:39:46.998000
502  2023-01-16 15:39:48.204000
503  2023-01-16 15:39:49.406000
504  2023-01-16 15:39:50.609000
505  2023-01-16 15:39:51.804000

[5 rows x 23 columns]
Result 2:            Date          Time  Elapsed time   VMon1  VMon2   VMon3   VMon4  \
203  16/01/2023  15:33:48.017       250.324  499.94  100.1  999.90  999.96
204  16/01/2023  15:33:49.214       251.521  499.94  100.1  999.90  999.96
205  16/01/2023  15:33:50.416       252.723  499.94  100.1  999.90  999.96
206  16/01/2023  15:33:51.616       253.923  499.94  100.1  999.88  999.96

      VMon5   VMon6  VMon7  ...    IMon3    IMon4    IMon5    IMon6   IMon7  \
203  999.88  499.90    0.0  ...  19.6942  19.7059  19.6839  19.6832 -0.0225
204  999.88  499.90    0.0  ...  19.7017  19.7163  19.6948  19.6940 -0.0225
205  999.88  499.90    0.0  ...  19.7114  19.7262  19.7054  19.7050 -0.0225
206  999.88  499.88    0.0  ...  19.7836  19.7982  19.7707  19.7711 -0.0225

      IMon8         Comment       hv_grid          I_em  \
203 -0.0066  grid repelling  2.180000e-08  2.030000e-08
204 -0.0066  grid repelling  2.180000e-08  2.030000e-08
205 -0.0066  grid repelling  2.180000e-08  1.960000e-08
206 -0.0066  grid repelling  2.170000e-08  1.960000e-08

                       datetime
203  2023-01-16 15:33:48.017000
204  2023-01-16 15:33:49.214000
205  2023-01-16 15:33:50.416000
206  2023-01-16 15:33:51.616000

[4 rows x 23 columns]
Result 3: Empty DataFrame
Columns: [Date, Time, Elapsed time, VMon1, VMon2, VMon3, VMon4, VMon5, VMon6, VMon7, VMon8, IMon1, IMon2, IMon3, IMon4, IMon5, IMon6, IMon7, IMon8, Comment, hv_grid, I_em, datetime]
Index: []

[0 rows x 23 columns]

 Result 4:                mass 2.0_time  mass 2.0_value            mass 4.0_time  \
2    2023/01/16 15:29:44.364    1.153420e-10  2023/01/16 15:29:47.865
3    2023/01/16 15:29:50.688    1.150680e-10  2023/01/16 15:29:53.939
4    2023/01/16 15:29:57.013    1.141700e-10  2023/01/16 15:30:00.264
5    2023/01/16 15:30:03.338    1.135410e-10  2023/01/16 15:30:06.589
6    2023/01/16 15:30:09.663    1.133800e-10  2023/01/16 15:30:12.914
..                       ...             ...                      ...
861  2023/01/16 17:00:17.538    1.335360e-08  2023/01/16 17:00:20.789
862  2023/01/16 17:00:23.863    1.454360e-08  2023/01/16 17:00:27.114
863  2023/01/16 17:00:30.188    1.365570e-08  2023/01/16 17:00:33.439
864  2023/01/16 17:00:36.513    1.474520e-08  2023/01/16 17:00:39.764
865  2023/01/16 17:00:42.838    1.286880e-08  2023/01/16 17:00:46.089

     mass 4.0_value            mass 5.5_time  mass 5.5_value  \
2      6.400000e-15  2023/01/16 15:29:48.115    2.445000e-13
3      1.079000e-13  2023/01/16 15:29:54.189    9.780000e-14
4      1.021000e-13  2023/01/16 15:30:00.514    1.100000e-13
5      1.300000e-13  2023/01/16 15:30:06.839    1.061000e-13
6      1.048000e-13  2023/01/16 15:30:13.164    1.199000e-13
..              ...                      ...             ...
861    3.650000e-14  2023/01/16 17:00:21.039    3.930000e-14
862    4.990000e-14  2023/01/16 17:00:27.364    2.880000e-14
863    4.510000e-14  2023/01/16 17:00:33.689    2.880000e-14
864    4.530000e-14  2023/01/16 17:00:40.014    2.820000e-14
865    4.840000e-14  2023/01/16 17:00:46.339    2.570000e-14

              mass 12.0_time  mass 12.0_value           mass 15.0_time  \
2    2023/01/16 15:29:48.365     1.118000e-13  2023/01/16 15:29:48.615
3    2023/01/16 15:29:54.439     3.220000e-13  2023/01/16 15:29:54.690
4    2023/01/16 15:30:00.764     3.300000e-13  2023/01/16 15:30:01.015
5    2023/01/16 15:30:07.089     3.329000e-13  2023/01/16 15:30:07.340
6    2023/01/16 15:30:13.414     3.187000e-13  2023/01/16 15:30:13.665
..                       ...              ...                      ...
861  2023/01/16 17:00:21.289     4.384000e-13  2023/01/16 17:00:21.540
862  2023/01/16 17:00:27.614     4.154000e-13  2023/01/16 17:00:27.865
863  2023/01/16 17:00:33.939     3.996000e-13  2023/01/16 17:00:34.190
864  2023/01/16 17:00:40.264     4.433000e-13  2023/01/16 17:00:40.515
865  2023/01/16 17:00:46.589     4.135000e-13  2023/01/16 17:00:46.840

     mass 15.0_value  ...           mass 18.0_time  mass 18.0_value  \
2       6.261000e-13  ...  2023/01/16 15:29:49.116     1.572700e-12
3       1.782000e-13  ...  2023/01/16 15:29:55.190     1.845300e-12
4       2.024000e-13  ...  2023/01/16 15:30:01.515     1.773900e-12
5       1.897000e-13  ...  2023/01/16 15:30:07.840     1.702600e-12
6       1.770000e-13  ...  2023/01/16 15:30:14.165     1.721400e-12
..               ...  ...                      ...              ...
861     6.328000e-13  ...  2023/01/16 17:00:22.040     3.792760e-11
862     6.184000e-13  ...  2023/01/16 17:00:28.365     3.826350e-11
863     6.263000e-13  ...  2023/01/16 17:00:34.690     3.705090e-11
864     6.540000e-13  ...  2023/01/16 17:00:41.015     3.795120e-11
865     6.403000e-13  ...  2023/01/16 17:00:47.340     3.736320e-11

              mass 28.0_time  mass 28.0_value           mass 32.0_time  \
2    2023/01/16 15:29:49.366     1.010000e-13  2023/01/16 15:29:49.616
3    2023/01/16 15:29:55.440     1.665800e-12  2023/01/16 15:29:55.690
4    2023/01/16 15:30:01.765     1.661000e-12  2023/01/16 15:30:02.015
5    2023/01/16 15:30:08.090     1.700100e-12  2023/01/16 15:30:08.340
6    2023/01/16 15:30:14.415     1.680800e-12  2023/01/16 15:30:14.665
..                       ...              ...                      ...
861  2023/01/16 17:00:22.290     5.991300e-12  2023/01/16 17:00:22.540
862  2023/01/16 17:00:28.615     6.028400e-12  2023/01/16 17:00:28.865
863  2023/01/16 17:00:34.940     5.898000e-12  2023/01/16 17:00:35.191
864  2023/01/16 17:00:41.265     5.990000e-12  2023/01/16 17:00:41.515
865  2023/01/16 17:00:47.590     6.022400e-12  2023/01/16 17:00:47.840

     mass 32.0_value           mass 40.0_time  mass 40.0_value  \
2       1.820000e-14  2023/01/16 15:29:50.367     2.429500e-11
3       1.975000e-13  2023/01/16 15:29:55.940     8.540000e-14
4       1.641000e-13  2023/01/16 15:30:02.266     1.130000e-13
5       1.787000e-13  2023/01/16 15:30:08.591     1.061000e-13
6       1.851000e-13  2023/01/16 15:30:14.916     1.008000e-13
..               ...                      ...              ...
861     3.932000e-13  2023/01/16 17:00:22.791     3.360000e-14
862     3.718000e-13  2023/01/16 17:00:29.116     3.970000e-14
863     4.266000e-13  2023/01/16 17:00:35.441     3.100000e-14
864     4.126000e-13  2023/01/16 17:00:41.766     3.610000e-14
865     4.172000e-13  2023/01/16 17:00:48.091     3.220000e-14

              mass 44.0_time  mass 44.0_value
2                        NaN              NaN
3    2023/01/16 15:29:56.692     2.370370e-11
4    2023/01/16 15:30:03.017     2.386500e-11
5    2023/01/16 15:30:09.342     2.386500e-11
6    2023/01/16 15:30:15.667     2.381120e-11
..                       ...              ...
861  2023/01/16 17:00:23.542     2.445620e-11
862  2023/01/16 17:00:29.867     2.451000e-11
863  2023/01/16 17:00:36.192     2.445620e-11
864  2023/01/16 17:00:42.517     2.461750e-11
865  2023/01/16 17:00:48.842     2.483250e-11

[864 rows x 22 columns]

 Result 5:                mass 2.0_time  mass 2.0_value            mass 4.0_time  \
2    2023/01/16 15:29:44.364    1.153420e-10  2023/01/16 15:29:47.865
3    2023/01/16 15:29:50.688    1.150680e-10  2023/01/16 15:29:53.939
4    2023/01/16 15:29:57.013    1.141700e-10  2023/01/16 15:30:00.264
5    2023/01/16 15:30:03.338    1.135410e-10  2023/01/16 15:30:06.589
6    2023/01/16 15:30:09.663    1.133800e-10  2023/01/16 15:30:12.914
..                       ...             ...                      ...
861  2023/01/16 17:00:17.538    1.335360e-08  2023/01/16 17:00:20.789
862  2023/01/16 17:00:23.863    1.454360e-08  2023/01/16 17:00:27.114
863  2023/01/16 17:00:30.188    1.365570e-08  2023/01/16 17:00:33.439
864  2023/01/16 17:00:36.513    1.474520e-08  2023/01/16 17:00:39.764
865  2023/01/16 17:00:42.838    1.286880e-08  2023/01/16 17:00:46.089

     mass 4.0_value            mass 5.5_time  mass 5.5_value  \
2      6.400000e-15  2023/01/16 15:29:48.115    2.445000e-13
3      1.079000e-13  2023/01/16 15:29:54.189    9.780000e-14
4      1.021000e-13  2023/01/16 15:30:00.514    1.100000e-13
5      1.300000e-13  2023/01/16 15:30:06.839    1.061000e-13
6      1.048000e-13  2023/01/16 15:30:13.164    1.199000e-13
..              ...                      ...             ...
861    3.650000e-14  2023/01/16 17:00:21.039    3.930000e-14
862    4.990000e-14  2023/01/16 17:00:27.364    2.880000e-14
863    4.510000e-14  2023/01/16 17:00:33.689    2.880000e-14
864    4.530000e-14  2023/01/16 17:00:40.014    2.820000e-14
865    4.840000e-14  2023/01/16 17:00:46.339    2.570000e-14

              mass 12.0_time  mass 12.0_value           mass 15.0_time  \
2    2023/01/16 15:29:48.365     1.118000e-13  2023/01/16 15:29:48.615
3    2023/01/16 15:29:54.439     3.220000e-13  2023/01/16 15:29:54.690
4    2023/01/16 15:30:00.764     3.300000e-13  2023/01/16 15:30:01.015
5    2023/01/16 15:30:07.089     3.329000e-13  2023/01/16 15:30:07.340
6    2023/01/16 15:30:13.414     3.187000e-13  2023/01/16 15:30:13.665
..                       ...              ...                      ...
861  2023/01/16 17:00:21.289     4.384000e-13  2023/01/16 17:00:21.540
862  2023/01/16 17:00:27.614     4.154000e-13  2023/01/16 17:00:27.865
863  2023/01/16 17:00:33.939     3.996000e-13  2023/01/16 17:00:34.190
864  2023/01/16 17:00:40.264     4.433000e-13  2023/01/16 17:00:40.515
865  2023/01/16 17:00:46.589     4.135000e-13  2023/01/16 17:00:46.840

     mass 15.0_value  ...           mass 18.0_time  mass 18.0_value  \
2       6.261000e-13  ...  2023/01/16 15:29:49.116     1.572700e-12
3       1.782000e-13  ...  2023/01/16 15:29:55.190     1.845300e-12
4       2.024000e-13  ...  2023/01/16 15:30:01.515     1.773900e-12
5       1.897000e-13  ...  2023/01/16 15:30:07.840     1.702600e-12
6       1.770000e-13  ...  2023/01/16 15:30:14.165     1.721400e-12
..               ...  ...                      ...              ...
861     6.328000e-13  ...  2023/01/16 17:00:22.040     3.792760e-11
862     6.184000e-13  ...  2023/01/16 17:00:28.365     3.826350e-11
863     6.263000e-13  ...  2023/01/16 17:00:34.690     3.705090e-11
864     6.540000e-13  ...  2023/01/16 17:00:41.015     3.795120e-11
865     6.403000e-13  ...  2023/01/16 17:00:47.340     3.736320e-11

              mass 28.0_time  mass 28.0_value           mass 32.0_time  \
2    2023/01/16 15:29:49.366     1.010000e-13  2023/01/16 15:29:49.616
3    2023/01/16 15:29:55.440     1.665800e-12  2023/01/16 15:29:55.690
4    2023/01/16 15:30:01.765     1.661000e-12  2023/01/16 15:30:02.015
5    2023/01/16 15:30:08.090     1.700100e-12  2023/01/16 15:30:08.340
6    2023/01/16 15:30:14.415     1.680800e-12  2023/01/16 15:30:14.665
..                       ...              ...                      ...
861  2023/01/16 17:00:22.290     5.991300e-12  2023/01/16 17:00:22.540
862  2023/01/16 17:00:28.615     6.028400e-12  2023/01/16 17:00:28.865
863  2023/01/16 17:00:34.940     5.898000e-12  2023/01/16 17:00:35.191
864  2023/01/16 17:00:41.265     5.990000e-12  2023/01/16 17:00:41.515
865  2023/01/16 17:00:47.590     6.022400e-12  2023/01/16 17:00:47.840

     mass 32.0_value           mass 40.0_time  mass 40.0_value  \
2       1.820000e-14  2023/01/16 15:29:50.367     2.429500e-11
3       1.975000e-13  2023/01/16 15:29:55.940     8.540000e-14
4       1.641000e-13  2023/01/16 15:30:02.266     1.130000e-13
5       1.787000e-13  2023/01/16 15:30:08.591     1.061000e-13
6       1.851000e-13  2023/01/16 15:30:14.916     1.008000e-13
..               ...                      ...              ...
861     3.932000e-13  2023/01/16 17:00:22.791     3.360000e-14
862     3.718000e-13  2023/01/16 17:00:29.116     3.970000e-14
863     4.266000e-13  2023/01/16 17:00:35.441     3.100000e-14
864     4.126000e-13  2023/01/16 17:00:41.766     3.610000e-14
865     4.172000e-13  2023/01/16 17:00:48.091     3.220000e-14

              mass 44.0_time  mass 44.0_value
2                        NaN              NaN
3    2023/01/16 15:29:56.692     2.370370e-11
4    2023/01/16 15:30:03.017     2.386500e-11
5    2023/01/16 15:30:09.342     2.386500e-11
6    2023/01/16 15:30:15.667     2.381120e-11
..                       ...              ...
861  2023/01/16 17:00:23.542     2.445620e-11
862  2023/01/16 17:00:29.867     2.451000e-11
863  2023/01/16 17:00:36.192     2.445620e-11
864  2023/01/16 17:00:42.517     2.461750e-11
865  2023/01/16 17:00:48.842     2.483250e-11

[864 rows x 22 columns]

 Result 6:                mass 2.0_time  mass 2.0_value            mass 4.0_time  \
2    2023/01/16 15:29:44.364    1.153420e-10  2023/01/16 15:29:47.865
3    2023/01/16 15:29:50.688    1.150680e-10  2023/01/16 15:29:53.939
4    2023/01/16 15:29:57.013    1.141700e-10  2023/01/16 15:30:00.264
5    2023/01/16 15:30:03.338    1.135410e-10  2023/01/16 15:30:06.589
6    2023/01/16 15:30:09.663    1.133800e-10  2023/01/16 15:30:12.914
..                       ...             ...                      ...
861  2023/01/16 17:00:17.538    1.335360e-08  2023/01/16 17:00:20.789
862  2023/01/16 17:00:23.863    1.454360e-08  2023/01/16 17:00:27.114
863  2023/01/16 17:00:30.188    1.365570e-08  2023/01/16 17:00:33.439
864  2023/01/16 17:00:36.513    1.474520e-08  2023/01/16 17:00:39.764
865  2023/01/16 17:00:42.838    1.286880e-08  2023/01/16 17:00:46.089

     mass 4.0_value            mass 5.5_time  mass 5.5_value  \
2      6.400000e-15  2023/01/16 15:29:48.115    2.445000e-13
3      1.079000e-13  2023/01/16 15:29:54.189    9.780000e-14
4      1.021000e-13  2023/01/16 15:30:00.514    1.100000e-13
5      1.300000e-13  2023/01/16 15:30:06.839    1.061000e-13
6      1.048000e-13  2023/01/16 15:30:13.164    1.199000e-13
..              ...                      ...             ...
861    3.650000e-14  2023/01/16 17:00:21.039    3.930000e-14
862    4.990000e-14  2023/01/16 17:00:27.364    2.880000e-14
863    4.510000e-14  2023/01/16 17:00:33.689    2.880000e-14
864    4.530000e-14  2023/01/16 17:00:40.014    2.820000e-14
865    4.840000e-14  2023/01/16 17:00:46.339    2.570000e-14

              mass 12.0_time  mass 12.0_value           mass 15.0_time  \
2    2023/01/16 15:29:48.365     1.118000e-13  2023/01/16 15:29:48.615
3    2023/01/16 15:29:54.439     3.220000e-13  2023/01/16 15:29:54.690
4    2023/01/16 15:30:00.764     3.300000e-13  2023/01/16 15:30:01.015
5    2023/01/16 15:30:07.089     3.329000e-13  2023/01/16 15:30:07.340
6    2023/01/16 15:30:13.414     3.187000e-13  2023/01/16 15:30:13.665
..                       ...              ...                      ...
861  2023/01/16 17:00:21.289     4.384000e-13  2023/01/16 17:00:21.540
862  2023/01/16 17:00:27.614     4.154000e-13  2023/01/16 17:00:27.865
863  2023/01/16 17:00:33.939     3.996000e-13  2023/01/16 17:00:34.190
864  2023/01/16 17:00:40.264     4.433000e-13  2023/01/16 17:00:40.515
865  2023/01/16 17:00:46.589     4.135000e-13  2023/01/16 17:00:46.840

     mass 15.0_value  ...           mass 18.0_time  mass 18.0_value  \
2       6.261000e-13  ...  2023/01/16 15:29:49.116     1.572700e-12
3       1.782000e-13  ...  2023/01/16 15:29:55.190     1.845300e-12
4       2.024000e-13  ...  2023/01/16 15:30:01.515     1.773900e-12
5       1.897000e-13  ...  2023/01/16 15:30:07.840     1.702600e-12
6       1.770000e-13  ...  2023/01/16 15:30:14.165     1.721400e-12
..               ...  ...                      ...              ...
861     6.328000e-13  ...  2023/01/16 17:00:22.040     3.792760e-11
862     6.184000e-13  ...  2023/01/16 17:00:28.365     3.826350e-11
863     6.263000e-13  ...  2023/01/16 17:00:34.690     3.705090e-11
864     6.540000e-13  ...  2023/01/16 17:00:41.015     3.795120e-11
865     6.403000e-13  ...  2023/01/16 17:00:47.340     3.736320e-11

              mass 28.0_time  mass 28.0_value           mass 32.0_time  \
2    2023/01/16 15:29:49.366     1.010000e-13  2023/01/16 15:29:49.616
3    2023/01/16 15:29:55.440     1.665800e-12  2023/01/16 15:29:55.690
4    2023/01/16 15:30:01.765     1.661000e-12  2023/01/16 15:30:02.015
5    2023/01/16 15:30:08.090     1.700100e-12  2023/01/16 15:30:08.340
6    2023/01/16 15:30:14.415     1.680800e-12  2023/01/16 15:30:14.665
..                       ...              ...                      ...
861  2023/01/16 17:00:22.290     5.991300e-12  2023/01/16 17:00:22.540
862  2023/01/16 17:00:28.615     6.028400e-12  2023/01/16 17:00:28.865
863  2023/01/16 17:00:34.940     5.898000e-12  2023/01/16 17:00:35.191
864  2023/01/16 17:00:41.265     5.990000e-12  2023/01/16 17:00:41.515
865  2023/01/16 17:00:47.590     6.022400e-12  2023/01/16 17:00:47.840

     mass 32.0_value           mass 40.0_time  mass 40.0_value  \
2       1.820000e-14  2023/01/16 15:29:50.367     2.429500e-11
3       1.975000e-13  2023/01/16 15:29:55.940     8.540000e-14
4       1.641000e-13  2023/01/16 15:30:02.266     1.130000e-13
5       1.787000e-13  2023/01/16 15:30:08.591     1.061000e-13
6       1.851000e-13  2023/01/16 15:30:14.916     1.008000e-13
..               ...                      ...              ...
861     3.932000e-13  2023/01/16 17:00:22.791     3.360000e-14
862     3.718000e-13  2023/01/16 17:00:29.116     3.970000e-14
863     4.266000e-13  2023/01/16 17:00:35.441     3.100000e-14
864     4.126000e-13  2023/01/16 17:00:41.766     3.610000e-14
865     4.172000e-13  2023/01/16 17:00:48.091     3.220000e-14

              mass 44.0_time  mass 44.0_value
2                        NaN              NaN
3    2023/01/16 15:29:56.692     2.370370e-11
4    2023/01/16 15:30:03.017     2.386500e-11
5    2023/01/16 15:30:09.342     2.386500e-11
6    2023/01/16 15:30:15.667     2.381120e-11
..                       ...              ...
861  2023/01/16 17:00:23.542     2.445620e-11
862  2023/01/16 17:00:29.867     2.451000e-11
863  2023/01/16 17:00:36.192     2.445620e-11
864  2023/01/16 17:00:42.517     2.461750e-11
865  2023/01/16 17:00:48.842     2.483250e-11

[864 rows x 22 columns]
count    4.500000e+01
mean     5.700205e-09
std      2.026895e-10
min      5.184891e-09
25%      5.722403e-09
50%      5.736769e-09
75%      5.758741e-09
max      6.291934e-09
Name: mass 2, corr, dtype: float64

count    3.500000e+01
mean     5.217351e-09
std      1.694661e-11
min      5.178553e-09
25%      5.208084e-09
50%      5.218694e-09
75%      5.228905e-09
max      5.253248e-09
Name: mass 2, corr, dtype: float64

Result 1:            Date          Time  Elapsed time   VMon1   VMon2    VMon3    VMon4  \
501  16/01/2023  15:39:46.998       609.305  449.40  100.08  1000.02  1000.14
502  16/01/2023  15:39:48.204       610.511  309.40  100.08  1000.02  1000.14
503  16/01/2023  15:39:49.406       611.713  178.92  100.06  1000.04  1000.14
504  16/01/2023  15:39:50.609       612.916   90.00   99.98  1000.06  1000.16
505  16/01/2023  15:39:51.804       614.111    1.04   99.90  1000.04  1000.14

       VMon5   VMon6  VMon7  ...    IMon3    IMon4    IMon5    IMon6   IMon7  \
501  1000.12  499.98    0.0  ...  21.8108  21.8398  21.8108  21.8081 -0.0192
502  1000.12  499.98    0.0  ...  21.8169  21.8462  21.8172  21.8152 -0.0192
503  1000.12  499.98    0.0  ...  21.8208  21.8502  21.8236  21.8238 -0.0192
504  1000.14  499.98    0.0  ...  21.3355  21.5411  21.6138  21.7407 -0.0192
505  1000.12  499.98    0.0  ...  21.7729  21.8035  21.7545  21.7587 -0.0192

      IMon8           Comment       hv_grid          I_em  \
501 -0.0071  grid transparent -4.318000e-07  2.250000e-08
502 -0.0068  grid transparent -4.431000e-07  2.650000e-08
503 -0.0068  grid transparent -4.651000e-07  1.678000e-07
504 -0.0068  grid transparent -3.469000e-07  2.209400e-06
505 -0.0068  grid transparent -6.057000e-07  4.345600e-06

                       datetime
501  2023-01-16 15:39:46.998000
502  2023-01-16 15:39:48.204000
503  2023-01-16 15:39:49.406000
504  2023-01-16 15:39:50.609000
505  2023-01-16 15:39:51.804000

[5 rows x 23 columns]
Result 2:            Date          Time  Elapsed time   VMon1  VMon2   VMon3   VMon4  \
203  16/01/2023  15:33:48.017       250.324  499.94  100.1  999.90  999.96
204  16/01/2023  15:33:49.214       251.521  499.94  100.1  999.90  999.96
205  16/01/2023  15:33:50.416       252.723  499.94  100.1  999.90  999.96
206  16/01/2023  15:33:51.616       253.923  499.94  100.1  999.88  999.96

      VMon5   VMon6  VMon7  ...    IMon3    IMon4    IMon5    IMon6   IMon7  \
203  999.88  499.90    0.0  ...  19.6942  19.7059  19.6839  19.6832 -0.0225
204  999.88  499.90    0.0  ...  19.7017  19.7163  19.6948  19.6940 -0.0225
205  999.88  499.90    0.0  ...  19.7114  19.7262  19.7054  19.7050 -0.0225
206  999.88  499.88    0.0  ...  19.7836  19.7982  19.7707  19.7711 -0.0225

      IMon8         Comment       hv_grid          I_em  \
203 -0.0066  grid repelling  2.180000e-08  2.030000e-08
204 -0.0066  grid repelling  2.180000e-08  2.030000e-08
205 -0.0066  grid repelling  2.180000e-08  1.960000e-08
206 -0.0066  grid repelling  2.170000e-08  1.960000e-08

                       datetime
203  2023-01-16 15:33:48.017000
204  2023-01-16 15:33:49.214000
205  2023-01-16 15:33:50.416000
206  2023-01-16 15:33:51.616000

[4 rows x 23 columns]
Result 3: Empty DataFrame
Columns: [Date, Time, Elapsed time, VMon1, VMon2, VMon3, VMon4, VMon5, VMon6, VMon7, VMon8, IMon1, IMon2, IMon3, IMon4, IMon5, IMon6, IMon7, IMon8, Comment, hv_grid, I_em, datetime]
Index: []

[0 rows x 23 columns]

 Result 4:                mass 2.0_time  mass 2.0_value            mass 4.0_time  \
2    2023/01/16 15:29:44.364    1.153420e-10  2023/01/16 15:29:47.865
3    2023/01/16 15:29:50.688    1.150680e-10  2023/01/16 15:29:53.939
4    2023/01/16 15:29:57.013    1.141700e-10  2023/01/16 15:30:00.264
5    2023/01/16 15:30:03.338    1.135410e-10  2023/01/16 15:30:06.589
6    2023/01/16 15:30:09.663    1.133800e-10  2023/01/16 15:30:12.914
..                       ...             ...                      ...
861  2023/01/16 17:00:17.538    1.335360e-08  2023/01/16 17:00:20.789
862  2023/01/16 17:00:23.863    1.454360e-08  2023/01/16 17:00:27.114
863  2023/01/16 17:00:30.188    1.365570e-08  2023/01/16 17:00:33.439
864  2023/01/16 17:00:36.513    1.474520e-08  2023/01/16 17:00:39.764
865  2023/01/16 17:00:42.838    1.286880e-08  2023/01/16 17:00:46.089

     mass 4.0_value            mass 5.5_time  mass 5.5_value  \
2      6.400000e-15  2023/01/16 15:29:48.115    2.445000e-13
3      1.079000e-13  2023/01/16 15:29:54.189    9.780000e-14
4      1.021000e-13  2023/01/16 15:30:00.514    1.100000e-13
5      1.300000e-13  2023/01/16 15:30:06.839    1.061000e-13
6      1.048000e-13  2023/01/16 15:30:13.164    1.199000e-13
..              ...                      ...             ...
861    3.650000e-14  2023/01/16 17:00:21.039    3.930000e-14
862    4.990000e-14  2023/01/16 17:00:27.364    2.880000e-14
863    4.510000e-14  2023/01/16 17:00:33.689    2.880000e-14
864    4.530000e-14  2023/01/16 17:00:40.014    2.820000e-14
865    4.840000e-14  2023/01/16 17:00:46.339    2.570000e-14

              mass 12.0_time  mass 12.0_value           mass 15.0_time  \
2    2023/01/16 15:29:48.365     1.118000e-13  2023/01/16 15:29:48.615
3    2023/01/16 15:29:54.439     3.220000e-13  2023/01/16 15:29:54.690
4    2023/01/16 15:30:00.764     3.300000e-13  2023/01/16 15:30:01.015
5    2023/01/16 15:30:07.089     3.329000e-13  2023/01/16 15:30:07.340
6    2023/01/16 15:30:13.414     3.187000e-13  2023/01/16 15:30:13.665
..                       ...              ...                      ...
861  2023/01/16 17:00:21.289     4.384000e-13  2023/01/16 17:00:21.540
862  2023/01/16 17:00:27.614     4.154000e-13  2023/01/16 17:00:27.865
863  2023/01/16 17:00:33.939     3.996000e-13  2023/01/16 17:00:34.190
864  2023/01/16 17:00:40.264     4.433000e-13  2023/01/16 17:00:40.515
865  2023/01/16 17:00:46.589     4.135000e-13  2023/01/16 17:00:46.840

     mass 15.0_value  ...           mass 18.0_time  mass 18.0_value  \
2       6.261000e-13  ...  2023/01/16 15:29:49.116     1.572700e-12
3       1.782000e-13  ...  2023/01/16 15:29:55.190     1.845300e-12
4       2.024000e-13  ...  2023/01/16 15:30:01.515     1.773900e-12
5       1.897000e-13  ...  2023/01/16 15:30:07.840     1.702600e-12
6       1.770000e-13  ...  2023/01/16 15:30:14.165     1.721400e-12
..               ...  ...                      ...              ...
861     6.328000e-13  ...  2023/01/16 17:00:22.040     3.792760e-11
862     6.184000e-13  ...  2023/01/16 17:00:28.365     3.826350e-11
863     6.263000e-13  ...  2023/01/16 17:00:34.690     3.705090e-11
864     6.540000e-13  ...  2023/01/16 17:00:41.015     3.795120e-11
865     6.403000e-13  ...  2023/01/16 17:00:47.340     3.736320e-11

              mass 28.0_time  mass 28.0_value           mass 32.0_time  \
2    2023/01/16 15:29:49.366     1.010000e-13  2023/01/16 15:29:49.616
3    2023/01/16 15:29:55.440     1.665800e-12  2023/01/16 15:29:55.690
4    2023/01/16 15:30:01.765     1.661000e-12  2023/01/16 15:30:02.015
5    2023/01/16 15:30:08.090     1.700100e-12  2023/01/16 15:30:08.340
6    2023/01/16 15:30:14.415     1.680800e-12  2023/01/16 15:30:14.665
..                       ...              ...                      ...
861  2023/01/16 17:00:22.290     5.991300e-12  2023/01/16 17:00:22.540
862  2023/01/16 17:00:28.615     6.028400e-12  2023/01/16 17:00:28.865
863  2023/01/16 17:00:34.940     5.898000e-12  2023/01/16 17:00:35.191
864  2023/01/16 17:00:41.265     5.990000e-12  2023/01/16 17:00:41.515
865  2023/01/16 17:00:47.590     6.022400e-12  2023/01/16 17:00:47.840

     mass 32.0_value           mass 40.0_time  mass 40.0_value  \
2       1.820000e-14  2023/01/16 15:29:50.367     2.429500e-11
3       1.975000e-13  2023/01/16 15:29:55.940     8.540000e-14
4       1.641000e-13  2023/01/16 15:30:02.266     1.130000e-13
5       1.787000e-13  2023/01/16 15:30:08.591     1.061000e-13
6       1.851000e-13  2023/01/16 15:30:14.916     1.008000e-13
..               ...                      ...              ...
861     3.932000e-13  2023/01/16 17:00:22.791     3.360000e-14
862     3.718000e-13  2023/01/16 17:00:29.116     3.970000e-14
863     4.266000e-13  2023/01/16 17:00:35.441     3.100000e-14
864     4.126000e-13  2023/01/16 17:00:41.766     3.610000e-14
865     4.172000e-13  2023/01/16 17:00:48.091     3.220000e-14

              mass 44.0_time  mass 44.0_value
2                        NaN              NaN
3    2023/01/16 15:29:56.692     2.370370e-11
4    2023/01/16 15:30:03.017     2.386500e-11
5    2023/01/16 15:30:09.342     2.386500e-11
6    2023/01/16 15:30:15.667     2.381120e-11
..                       ...              ...
861  2023/01/16 17:00:23.542     2.445620e-11
862  2023/01/16 17:00:29.867     2.451000e-11
863  2023/01/16 17:00:36.192     2.445620e-11
864  2023/01/16 17:00:42.517     2.461750e-11
865  2023/01/16 17:00:48.842     2.483250e-11

[864 rows x 22 columns]

 Result 5:                mass 2.0_time  mass 2.0_value            mass 4.0_time  \
2    2023/01/16 15:29:44.364    1.153420e-10  2023/01/16 15:29:47.865
3    2023/01/16 15:29:50.688    1.150680e-10  2023/01/16 15:29:53.939
4    2023/01/16 15:29:57.013    1.141700e-10  2023/01/16 15:30:00.264
5    2023/01/16 15:30:03.338    1.135410e-10  2023/01/16 15:30:06.589
6    2023/01/16 15:30:09.663    1.133800e-10  2023/01/16 15:30:12.914
..                       ...             ...                      ...
861  2023/01/16 17:00:17.538    1.335360e-08  2023/01/16 17:00:20.789
862  2023/01/16 17:00:23.863    1.454360e-08  2023/01/16 17:00:27.114
863  2023/01/16 17:00:30.188    1.365570e-08  2023/01/16 17:00:33.439
864  2023/01/16 17:00:36.513    1.474520e-08  2023/01/16 17:00:39.764
865  2023/01/16 17:00:42.838    1.286880e-08  2023/01/16 17:00:46.089

     mass 4.0_value            mass 5.5_time  mass 5.5_value  \
2      6.400000e-15  2023/01/16 15:29:48.115    2.445000e-13
3      1.079000e-13  2023/01/16 15:29:54.189    9.780000e-14
4      1.021000e-13  2023/01/16 15:30:00.514    1.100000e-13
5      1.300000e-13  2023/01/16 15:30:06.839    1.061000e-13
6      1.048000e-13  2023/01/16 15:30:13.164    1.199000e-13
..              ...                      ...             ...
861    3.650000e-14  2023/01/16 17:00:21.039    3.930000e-14
862    4.990000e-14  2023/01/16 17:00:27.364    2.880000e-14
863    4.510000e-14  2023/01/16 17:00:33.689    2.880000e-14
864    4.530000e-14  2023/01/16 17:00:40.014    2.820000e-14
865    4.840000e-14  2023/01/16 17:00:46.339    2.570000e-14

              mass 12.0_time  mass 12.0_value           mass 15.0_time  \
2    2023/01/16 15:29:48.365     1.118000e-13  2023/01/16 15:29:48.615
3    2023/01/16 15:29:54.439     3.220000e-13  2023/01/16 15:29:54.690
4    2023/01/16 15:30:00.764     3.300000e-13  2023/01/16 15:30:01.015
5    2023/01/16 15:30:07.089     3.329000e-13  2023/01/16 15:30:07.340
6    2023/01/16 15:30:13.414     3.187000e-13  2023/01/16 15:30:13.665
..                       ...              ...                      ...
861  2023/01/16 17:00:21.289     4.384000e-13  2023/01/16 17:00:21.540
862  2023/01/16 17:00:27.614     4.154000e-13  2023/01/16 17:00:27.865
863  2023/01/16 17:00:33.939     3.996000e-13  2023/01/16 17:00:34.190
864  2023/01/16 17:00:40.264     4.433000e-13  2023/01/16 17:00:40.515
865  2023/01/16 17:00:46.589     4.135000e-13  2023/01/16 17:00:46.840

     mass 15.0_value  ...           mass 18.0_time  mass 18.0_value  \
2       6.261000e-13  ...  2023/01/16 15:29:49.116     1.572700e-12
3       1.782000e-13  ...  2023/01/16 15:29:55.190     1.845300e-12
4       2.024000e-13  ...  2023/01/16 15:30:01.515     1.773900e-12
5       1.897000e-13  ...  2023/01/16 15:30:07.840     1.702600e-12
6       1.770000e-13  ...  2023/01/16 15:30:14.165     1.721400e-12
..               ...  ...                      ...              ...
861     6.328000e-13  ...  2023/01/16 17:00:22.040     3.792760e-11
862     6.184000e-13  ...  2023/01/16 17:00:28.365     3.826350e-11
863     6.263000e-13  ...  2023/01/16 17:00:34.690     3.705090e-11
864     6.540000e-13  ...  2023/01/16 17:00:41.015     3.795120e-11
865     6.403000e-13  ...  2023/01/16 17:00:47.340     3.736320e-11

              mass 28.0_time  mass 28.0_value           mass 32.0_time  \
2    2023/01/16 15:29:49.366     1.010000e-13  2023/01/16 15:29:49.616
3    2023/01/16 15:29:55.440     1.665800e-12  2023/01/16 15:29:55.690
4    2023/01/16 15:30:01.765     1.661000e-12  2023/01/16 15:30:02.015
5    2023/01/16 15:30:08.090     1.700100e-12  2023/01/16 15:30:08.340
6    2023/01/16 15:30:14.415     1.680800e-12  2023/01/16 15:30:14.665
..                       ...              ...                      ...
861  2023/01/16 17:00:22.290     5.991300e-12  2023/01/16 17:00:22.540
862  2023/01/16 17:00:28.615     6.028400e-12  2023/01/16 17:00:28.865
863  2023/01/16 17:00:34.940     5.898000e-12  2023/01/16 17:00:35.191
864  2023/01/16 17:00:41.265     5.990000e-12  2023/01/16 17:00:41.515
865  2023/01/16 17:00:47.590     6.022400e-12  2023/01/16 17:00:47.840

     mass 32.0_value           mass 40.0_time  mass 40.0_value  \
2       1.820000e-14  2023/01/16 15:29:50.367     2.429500e-11
3       1.975000e-13  2023/01/16 15:29:55.940     8.540000e-14
4       1.641000e-13  2023/01/16 15:30:02.266     1.130000e-13
5       1.787000e-13  2023/01/16 15:30:08.591     1.061000e-13
6       1.851000e-13  2023/01/16 15:30:14.916     1.008000e-13
..               ...                      ...              ...
861     3.932000e-13  2023/01/16 17:00:22.791     3.360000e-14
862     3.718000e-13  2023/01/16 17:00:29.116     3.970000e-14
863     4.266000e-13  2023/01/16 17:00:35.441     3.100000e-14
864     4.126000e-13  2023/01/16 17:00:41.766     3.610000e-14
865     4.172000e-13  2023/01/16 17:00:48.091     3.220000e-14

              mass 44.0_time  mass 44.0_value
2                        NaN              NaN
3    2023/01/16 15:29:56.692     2.370370e-11
4    2023/01/16 15:30:03.017     2.386500e-11
5    2023/01/16 15:30:09.342     2.386500e-11
6    2023/01/16 15:30:15.667     2.381120e-11
..                       ...              ...
861  2023/01/16 17:00:23.542     2.445620e-11
862  2023/01/16 17:00:29.867     2.451000e-11
863  2023/01/16 17:00:36.192     2.445620e-11
864  2023/01/16 17:00:42.517     2.461750e-11
865  2023/01/16 17:00:48.842     2.483250e-11

[864 rows x 22 columns]

 Result 6:                mass 2.0_time  mass 2.0_value            mass 4.0_time  \
2    2023/01/16 15:29:44.364    1.153420e-10  2023/01/16 15:29:47.865
3    2023/01/16 15:29:50.688    1.150680e-10  2023/01/16 15:29:53.939
4    2023/01/16 15:29:57.013    1.141700e-10  2023/01/16 15:30:00.264
5    2023/01/16 15:30:03.338    1.135410e-10  2023/01/16 15:30:06.589
6    2023/01/16 15:30:09.663    1.133800e-10  2023/01/16 15:30:12.914
..                       ...             ...                      ...
861  2023/01/16 17:00:17.538    1.335360e-08  2023/01/16 17:00:20.789
862  2023/01/16 17:00:23.863    1.454360e-08  2023/01/16 17:00:27.114
863  2023/01/16 17:00:30.188    1.365570e-08  2023/01/16 17:00:33.439
864  2023/01/16 17:00:36.513    1.474520e-08  2023/01/16 17:00:39.764
865  2023/01/16 17:00:42.838    1.286880e-08  2023/01/16 17:00:46.089

     mass 4.0_value            mass 5.5_time  mass 5.5_value  \
2      6.400000e-15  2023/01/16 15:29:48.115    2.445000e-13
3      1.079000e-13  2023/01/16 15:29:54.189    9.780000e-14
4      1.021000e-13  2023/01/16 15:30:00.514    1.100000e-13
5      1.300000e-13  2023/01/16 15:30:06.839    1.061000e-13
6      1.048000e-13  2023/01/16 15:30:13.164    1.199000e-13
..              ...                      ...             ...
861    3.650000e-14  2023/01/16 17:00:21.039    3.930000e-14
862    4.990000e-14  2023/01/16 17:00:27.364    2.880000e-14
863    4.510000e-14  2023/01/16 17:00:33.689    2.880000e-14
864    4.530000e-14  2023/01/16 17:00:40.014    2.820000e-14
865    4.840000e-14  2023/01/16 17:00:46.339    2.570000e-14

              mass 12.0_time  mass 12.0_value           mass 15.0_time  \
2    2023/01/16 15:29:48.365     1.118000e-13  2023/01/16 15:29:48.615
3    2023/01/16 15:29:54.439     3.220000e-13  2023/01/16 15:29:54.690
4    2023/01/16 15:30:00.764     3.300000e-13  2023/01/16 15:30:01.015
5    2023/01/16 15:30:07.089     3.329000e-13  2023/01/16 15:30:07.340
6    2023/01/16 15:30:13.414     3.187000e-13  2023/01/16 15:30:13.665
..                       ...              ...                      ...
861  2023/01/16 17:00:21.289     4.384000e-13  2023/01/16 17:00:21.540
862  2023/01/16 17:00:27.614     4.154000e-13  2023/01/16 17:00:27.865
863  2023/01/16 17:00:33.939     3.996000e-13  2023/01/16 17:00:34.190
864  2023/01/16 17:00:40.264     4.433000e-13  2023/01/16 17:00:40.515
865  2023/01/16 17:00:46.589     4.135000e-13  2023/01/16 17:00:46.840

     mass 15.0_value  ...           mass 18.0_time  mass 18.0_value  \
2       6.261000e-13  ...  2023/01/16 15:29:49.116     1.572700e-12
3       1.782000e-13  ...  2023/01/16 15:29:55.190     1.845300e-12
4       2.024000e-13  ...  2023/01/16 15:30:01.515     1.773900e-12
5       1.897000e-13  ...  2023/01/16 15:30:07.840     1.702600e-12
6       1.770000e-13  ...  2023/01/16 15:30:14.165     1.721400e-12
..               ...  ...                      ...              ...
861     6.328000e-13  ...  2023/01/16 17:00:22.040     3.792760e-11
862     6.184000e-13  ...  2023/01/16 17:00:28.365     3.826350e-11
863     6.263000e-13  ...  2023/01/16 17:00:34.690     3.705090e-11
864     6.540000e-13  ...  2023/01/16 17:00:41.015     3.795120e-11
865     6.403000e-13  ...  2023/01/16 17:00:47.340     3.736320e-11

              mass 28.0_time  mass 28.0_value           mass 32.0_time  \
2    2023/01/16 15:29:49.366     1.010000e-13  2023/01/16 15:29:49.616
3    2023/01/16 15:29:55.440     1.665800e-12  2023/01/16 15:29:55.690
4    2023/01/16 15:30:01.765     1.661000e-12  2023/01/16 15:30:02.015
5    2023/01/16 15:30:08.090     1.700100e-12  2023/01/16 15:30:08.340
6    2023/01/16 15:30:14.415     1.680800e-12  2023/01/16 15:30:14.665
..                       ...              ...                      ...
861  2023/01/16 17:00:22.290     5.991300e-12  2023/01/16 17:00:22.540
862  2023/01/16 17:00:28.615     6.028400e-12  2023/01/16 17:00:28.865
863  2023/01/16 17:00:34.940     5.898000e-12  2023/01/16 17:00:35.191
864  2023/01/16 17:00:41.265     5.990000e-12  2023/01/16 17:00:41.515
865  2023/01/16 17:00:47.590     6.022400e-12  2023/01/16 17:00:47.840

     mass 32.0_value           mass 40.0_time  mass 40.0_value  \
2       1.820000e-14  2023/01/16 15:29:50.367     2.429500e-11
3       1.975000e-13  2023/01/16 15:29:55.940     8.540000e-14
4       1.641000e-13  2023/01/16 15:30:02.266     1.130000e-13
5       1.787000e-13  2023/01/16 15:30:08.591     1.061000e-13
6       1.851000e-13  2023/01/16 15:30:14.916     1.008000e-13
..               ...                      ...              ...
861     3.932000e-13  2023/01/16 17:00:22.791     3.360000e-14
862     3.718000e-13  2023/01/16 17:00:29.116     3.970000e-14
863     4.266000e-13  2023/01/16 17:00:35.441     3.100000e-14
864     4.126000e-13  2023/01/16 17:00:41.766     3.610000e-14
865     4.172000e-13  2023/01/16 17:00:48.091     3.220000e-14

              mass 44.0_time  mass 44.0_value
2                        NaN              NaN
3    2023/01/16 15:29:56.692     2.370370e-11
4    2023/01/16 15:30:03.017     2.386500e-11
5    2023/01/16 15:30:09.342     2.386500e-11
6    2023/01/16 15:30:15.667     2.381120e-11
..                       ...              ...
861  2023/01/16 17:00:23.542     2.445620e-11
862  2023/01/16 17:00:29.867     2.451000e-11
863  2023/01/16 17:00:36.192     2.445620e-11
864  2023/01/16 17:00:42.517     2.461750e-11
865  2023/01/16 17:00:48.842     2.483250e-11

[864 rows x 22 columns]
count    4.500000e+01
mean     5.700205e-09
std      2.026895e-10
min      5.184891e-09
25%      5.722403e-09
50%      5.736769e-09
75%      5.758741e-09
max      6.291934e-09
Name: mass 2, corr, dtype: float64

count    3.500000e+01
mean     5.217351e-09
std      1.694661e-11
min      5.178553e-09
25%      5.208084e-09
50%      5.218694e-09
75%      5.228905e-09
max      5.253248e-09
Name: mass 2, corr, dtype: float64

## Point-by-point desorption

In [8]:
#make a sub-df from mid that includes only mass 2 data
h2 = mid.loc[:, ["mass 2.0_time", "mass 2.0_value"]]

#rename columns
h2 = h2.rename(columns={"mass 2.0_time": "datetime","mass 2.0_value": "Ion current"}).reset_index(drop=True)

print(h2)

                    datetime   Ion current
0    2023/01/16 15:29:44.364  1.153420e-10
1    2023/01/16 15:29:50.688  1.150680e-10
2    2023/01/16 15:29:57.013  1.141700e-10
3    2023/01/16 15:30:03.338  1.135410e-10
4    2023/01/16 15:30:09.663  1.133800e-10
..                       ...           ...
859  2023/01/16 17:00:17.538  1.335360e-08
860  2023/01/16 17:00:23.863  1.454360e-08
861  2023/01/16 17:00:30.188  1.365570e-08
862  2023/01/16 17:00:36.513  1.474520e-08
863  2023/01/16 17:00:42.838  1.286880e-08

[864 rows x 2 columns]
                    datetime   Ion current
0    2023/01/16 15:29:44.364  1.153420e-10
1    2023/01/16 15:29:50.688  1.150680e-10
2    2023/01/16 15:29:57.013  1.141700e-10
3    2023/01/16 15:30:03.338  1.135410e-10
4    2023/01/16 15:30:09.663  1.133800e-10
..                       ...           ...
859  2023/01/16 17:00:17.538  1.335360e-08
860  2023/01/16 17:00:23.863  1.454360e-08
861  2023/01/16 17:00:30.188  1.365570e-08
862  2023/01/16 17:00:36.513  1.474520e-08
863  2023/01/16 17:00:42.838  1.286880e-08

[864 rows x 2 columns]

In [9]:
# Convert the 'time' column to datetime index for both dataframes
hv.index = (pd.to_datetime(hv['datetime']).dt.round(freq="S"))
h2.index = (pd.to_datetime(h2['datetime']).dt.round(freq="S"))
print(hv)

# Reindex df1 to match the datetime index of df2
hv = hv.reindex(h2.index, method='nearest', limit=1)

#Drop the "datetime" columns
hv.drop('datetime', axis=1, inplace=True)
h2.drop('datetime', axis=1, inplace=True)

# Now df1 and df2 have the same datetime index and can be joined or aligned
# by joining on the index
hv_aligned = hv.merge(h2,left_index=True, right_index=True, how="inner")

print("aligned",hv_aligned)
print(hv_aligned.describe())

                           Date          Time  Elapsed time  VMon1  VMon2  \
datetime
2023-01-16 15:29:38  16/01/2023  15:29:37.693         0.000   0.04   0.06
2023-01-16 15:29:39  16/01/2023  15:29:38.875         1.182   0.04   0.06
2023-01-16 15:29:40  16/01/2023  15:29:40.053         2.360   0.04   0.06
2023-01-16 15:29:41  16/01/2023  15:29:41.235         3.542   0.04   0.06
2023-01-16 15:29:42  16/01/2023  15:29:42.419         4.726   0.04   0.06
...                         ...           ...           ...    ...    ...
2023-01-16 17:00:37  16/01/2023  17:00:36.820      5459.127   0.06   0.06
2023-01-16 17:00:38  16/01/2023  17:00:38.007      5460.314   0.06   0.06
2023-01-16 17:00:39  16/01/2023  17:00:39.201      5461.508   0.06   0.06
2023-01-16 17:00:40  16/01/2023  17:00:40.389      5462.696   0.06   0.06
2023-01-16 17:00:42  16/01/2023  17:00:41.573      5463.880   0.06   0.06

                     VMon3  VMon4  VMon5  VMon6  VMon7  ...   IMon3   IMon4  \
datetime                                                ...
2023-01-16 15:29:38   0.04   0.08   0.02    0.0    0.0  ...  0.0090  0.0107
2023-01-16 15:29:39   0.04   0.08   0.02    0.0    0.0  ...  0.0090  0.0107
2023-01-16 15:29:40   0.04   0.08   0.02    0.0    0.0  ...  0.0090  0.0107
2023-01-16 15:29:41   0.04   0.08   0.02    0.0    0.0  ...  0.0090  0.0107
2023-01-16 15:29:42   0.04   0.08   0.02    0.0    0.0  ...  0.0090  0.0107
...                    ...    ...    ...    ...    ...  ...     ...     ...
2023-01-16 17:00:37   0.04   0.08   0.00    0.0    0.0  ...  0.0705  0.0117
2023-01-16 17:00:38   0.04   0.08   0.00    0.0    0.0  ...  0.0705  0.0127
2023-01-16 17:00:39   0.04   0.08   0.00    0.0    0.0  ...  0.0705  0.0132
2023-01-16 17:00:40   0.04   0.08   0.00    0.0    0.0  ...  0.0705  0.0132
2023-01-16 17:00:42   0.04   0.08   0.00    0.0    0.0  ...  0.0705  0.0132

                      IMon5   IMon6   IMon7   IMon8  Comment       hv_grid  \
datetime
2023-01-16 15:29:38  0.0006  0.0370 -0.0225 -0.0087      NaN  2.400000e-09
2023-01-16 15:29:39  0.0006  0.0370 -0.0225 -0.0087      NaN  2.400000e-09
2023-01-16 15:29:40  0.0006  0.0370 -0.0225 -0.0082      NaN  2.400000e-09
2023-01-16 15:29:41  0.0006  0.0370 -0.0225 -0.0082      NaN  2.400000e-09
2023-01-16 15:29:42  0.0006  0.0370 -0.0225 -0.0082      NaN  2.400000e-09
...                     ...     ...     ...     ...      ...           ...
2023-01-16 17:00:37  0.0799  0.0204 -0.0209 -0.0079      NaN  9.500000e-09
2023-01-16 17:00:38  0.0799  0.0204 -0.0209 -0.0079      NaN  9.500000e-09
2023-01-16 17:00:39  0.0799  0.0204 -0.0209 -0.0079      NaN  9.500000e-09
2023-01-16 17:00:40  0.0799  0.0204 -0.0209 -0.0079      NaN  9.500000e-09
2023-01-16 17:00:42  0.0799  0.0204 -0.0209 -0.0079      NaN  9.500000e-09

                             I_em                    datetime
datetime
2023-01-16 15:29:38  8.100000e-09  2023-01-16 15:29:37.693000
2023-01-16 15:29:39  8.100000e-09  2023-01-16 15:29:38.875000
2023-01-16 15:29:40  8.100000e-09  2023-01-16 15:29:40.053000
2023-01-16 15:29:41  8.100000e-09  2023-01-16 15:29:41.235000
2023-01-16 15:29:42  8.100000e-09  2023-01-16 15:29:42.419000
...                           ...                         ...
2023-01-16 17:00:37  9.910000e-08  2023-01-16 17:00:36.820000
2023-01-16 17:00:38  9.910000e-08  2023-01-16 17:00:38.007000
2023-01-16 17:00:39  9.910000e-08  2023-01-16 17:00:39.201000
2023-01-16 17:00:40  9.910000e-08  2023-01-16 17:00:40.389000
2023-01-16 17:00:42  9.900000e-08  2023-01-16 17:00:41.573000

[4533 rows x 23 columns]
aligned                            Date          Time  Elapsed time  VMon1  VMon2  \
datetime
2023-01-16 15:29:44  16/01/2023  15:29:43.602         5.909   0.04   0.06
2023-01-16 15:29:51  16/01/2023  15:29:50.698        13.005   0.04   0.06
2023-01-16 15:29:57  16/01/2023  15:29:56.522        18.829   0.04   0.06
2023-01-16 15:30:03  16/01/2023  15:30:03.610        25.917   0.04   0.06
2023-01-16 15:30:10  16/01/2023  15:30:09.518        31.825   0.04   0.06
...                         ...           ...           ...    ...    ...
2023-01-16 17:00:18  16/01/2023  17:00:17.887      5440.194   0.06   0.06
2023-01-16 17:00:24  16/01/2023  17:00:23.801      5446.108   0.06   0.06
2023-01-16 17:00:30  16/01/2023  17:00:29.710      5452.017   0.06   0.06
2023-01-16 17:00:37  16/01/2023  17:00:36.820      5459.127   0.06   0.06
2023-01-16 17:00:43  16/01/2023  17:00:41.573      5463.880   0.06   0.06

                     VMon3  VMon4  VMon5  VMon6  VMon7  ...   IMon3   IMon4  \
datetime                                                ...
2023-01-16 15:29:44   0.04   0.08   0.02    0.0    0.0  ...  0.0090  0.0107
2023-01-16 15:29:51   0.04   0.08   0.02    0.0    0.0  ...  0.0090  0.0107
2023-01-16 15:29:57   0.04   0.08   0.02    0.0    0.0  ...  0.0090  0.0107
2023-01-16 15:30:03   0.04   0.08   0.02    0.0    0.0  ...  0.0090  0.0091
2023-01-16 15:30:10   0.04   0.08   0.02    0.0    0.0  ...  0.0090  0.0091
...                    ...    ...    ...    ...    ...  ...     ...     ...
2023-01-16 17:00:18   0.04   0.08   0.00    0.0    0.0  ...  0.0705  0.0110
2023-01-16 17:00:24   0.04   0.08   0.00    0.0    0.0  ...  0.0705  0.0113
2023-01-16 17:00:30   0.04   0.08   0.00    0.0    0.0  ...  0.0705  0.0113
2023-01-16 17:00:37   0.04   0.08   0.00    0.0    0.0  ...  0.0705  0.0117
2023-01-16 17:00:43   0.04   0.08   0.00    0.0    0.0  ...  0.0705  0.0132

                      IMon5   IMon6   IMon7   IMon8  Comment       hv_grid  \
datetime
2023-01-16 15:29:44  0.0006  0.0370 -0.0225 -0.0082      NaN  2.400000e-09
2023-01-16 15:29:51  0.0006  0.0370 -0.0225 -0.0076      NaN  2.400000e-09
2023-01-16 15:29:57  0.0005  0.0015 -0.0225 -0.0076      NaN  2.400000e-09
2023-01-16 15:30:03  0.0002  0.0093 -0.0225 -0.0076      NaN  2.400000e-09
2023-01-16 15:30:10  0.0002  0.0093 -0.0225 -0.0072      NaN  2.400000e-09
...                     ...     ...     ...     ...      ...           ...
2023-01-16 17:00:18  0.0799  0.0205 -0.0209 -0.0075      NaN  9.500000e-09
2023-01-16 17:00:24  0.0799  0.0205 -0.0209 -0.0079      NaN  9.500000e-09
2023-01-16 17:00:30  0.0799  0.0204 -0.0209 -0.0079      NaN  9.500000e-09
2023-01-16 17:00:37  0.0799  0.0204 -0.0209 -0.0079      NaN  9.500000e-09
2023-01-16 17:00:43  0.0799  0.0204 -0.0209 -0.0079      NaN  9.500000e-09

                             I_em   Ion current
datetime
2023-01-16 15:29:44  7.400000e-09  1.153420e-10
2023-01-16 15:29:51  8.900000e-09  1.150680e-10
2023-01-16 15:29:57  8.900000e-09  1.141700e-10
2023-01-16 15:30:03  8.900000e-09  1.135410e-10
2023-01-16 15:30:10  1.000000e-08  1.133800e-10
...                           ...           ...
2023-01-16 17:00:18  9.930000e-08  1.335360e-08
2023-01-16 17:00:24  9.930000e-08  1.454360e-08
2023-01-16 17:00:30  9.930000e-08  1.365570e-08
2023-01-16 17:00:37  9.910000e-08  1.474520e-08
2023-01-16 17:00:43  9.900000e-08  1.286880e-08

[864 rows x 23 columns]
       Elapsed time       VMon1       VMon2        VMon3        VMon4  \
count    864.000000  864.000000  864.000000   864.000000   864.000000
mean    2736.012839  179.597199   79.120116   789.040440   788.346065
std     1578.464695  239.505913   40.719699   407.448259   407.864894
min        5.909000    0.040000    0.060000     0.000000     0.000000
25%     1371.357250    0.140000  100.060000  1000.000000  1000.095000
50%     2735.939000    0.160000  100.060000  1000.080000  1000.220000
75%     4100.692500  499.960000  100.080000  1000.100000  1000.240000
max     5463.880000  500.000000  100.140000  1000.180000  1000.300000

             VMon5       VMon6  VMon7       VMon8       IMon1       IMon2  \
count   864.000000  864.000000  864.0  864.000000  864.000000  864.000000
mean    789.743519  391.813079    0.0    0.026227   -0.251193    1.909148
std     406.947290  205.593193    0.0    0.009266    0.311526    2.148859
min       0.000000    0.000000    0.0    0.020000   -0.659600   -3.403900
25%    1000.060000  499.940000    0.0    0.020000   -0.605625    0.023300
50%    1000.180000  500.000000    0.0    0.020000    0.008600    0.098800
75%    1000.200000  500.020000    0.0    0.040000    0.023400    4.352925
max    1000.420000  500.040000    0.0    0.040000    0.461700    4.725800

            IMon3       IMon4       IMon5       IMon6       IMon7       IMon8  \
count  864.000000  864.000000  864.000000  864.000000  864.000000  864.000000
mean    17.272565   17.283615   17.270664   17.260089   -0.019119   -0.007312
std      8.922249    8.952505    8.919915    8.935924    0.001329    0.000885
min      0.009000   -0.016200    0.000200   -0.066300   -0.022900   -0.009700
25%     20.577775   20.592475   20.567950   20.566975   -0.019400   -0.008000
50%     21.807150   21.834750   21.804500   21.802000   -0.018800   -0.007300
75%     22.318125   22.346825   22.313225   22.307325   -0.018400   -0.006775
max     22.837100   22.855800   22.823500   22.817900   -0.017300   -0.005100

            hv_grid          I_em   Ion current
count  8.640000e+02  8.640000e+02  8.640000e+02
mean  -2.511929e-07  1.909148e-06  7.171138e-10
std    3.115265e-07  2.148859e-06  2.558800e-09
min   -6.596000e-07 -3.403900e-06  1.017540e-10
25%   -6.056250e-07  2.330000e-08  1.084107e-10
50%    8.600000e-09  9.880000e-08  1.161290e-10
75%    2.340000e-08  4.352925e-06  1.211250e-10
max    4.617000e-07  4.725800e-06  1.474520e-08

                           Date          Time  Elapsed time  VMon1  VMon2  \
datetime
2023-01-16 15:29:38  16/01/2023  15:29:37.693         0.000   0.04   0.06
2023-01-16 15:29:39  16/01/2023  15:29:38.875         1.182   0.04   0.06
2023-01-16 15:29:40  16/01/2023  15:29:40.053         2.360   0.04   0.06
2023-01-16 15:29:41  16/01/2023  15:29:41.235         3.542   0.04   0.06
2023-01-16 15:29:42  16/01/2023  15:29:42.419         4.726   0.04   0.06
...                         ...           ...           ...    ...    ...
2023-01-16 17:00:37  16/01/2023  17:00:36.820      5459.127   0.06   0.06
2023-01-16 17:00:38  16/01/2023  17:00:38.007      5460.314   0.06   0.06
2023-01-16 17:00:39  16/01/2023  17:00:39.201      5461.508   0.06   0.06
2023-01-16 17:00:40  16/01/2023  17:00:40.389      5462.696   0.06   0.06
2023-01-16 17:00:42  16/01/2023  17:00:41.573      5463.880   0.06   0.06

                     VMon3  VMon4  VMon5  VMon6  VMon7  ...   IMon3   IMon4  \
datetime                                                ...
2023-01-16 15:29:38   0.04   0.08   0.02    0.0    0.0  ...  0.0090  0.0107
2023-01-16 15:29:39   0.04   0.08   0.02    0.0    0.0  ...  0.0090  0.0107
2023-01-16 15:29:40   0.04   0.08   0.02    0.0    0.0  ...  0.0090  0.0107
2023-01-16 15:29:41   0.04   0.08   0.02    0.0    0.0  ...  0.0090  0.0107
2023-01-16 15:29:42   0.04   0.08   0.02    0.0    0.0  ...  0.0090  0.0107
...                    ...    ...    ...    ...    ...  ...     ...     ...
2023-01-16 17:00:37   0.04   0.08   0.00    0.0    0.0  ...  0.0705  0.0117
2023-01-16 17:00:38   0.04   0.08   0.00    0.0    0.0  ...  0.0705  0.0127
2023-01-16 17:00:39   0.04   0.08   0.00    0.0    0.0  ...  0.0705  0.0132
2023-01-16 17:00:40   0.04   0.08   0.00    0.0    0.0  ...  0.0705  0.0132
2023-01-16 17:00:42   0.04   0.08   0.00    0.0    0.0  ...  0.0705  0.0132

                      IMon5   IMon6   IMon7   IMon8  Comment       hv_grid  \
datetime
2023-01-16 15:29:38  0.0006  0.0370 -0.0225 -0.0087      NaN  2.400000e-09
2023-01-16 15:29:39  0.0006  0.0370 -0.0225 -0.0087      NaN  2.400000e-09
2023-01-16 15:29:40  0.0006  0.0370 -0.0225 -0.0082      NaN  2.400000e-09
2023-01-16 15:29:41  0.0006  0.0370 -0.0225 -0.0082      NaN  2.400000e-09
2023-01-16 15:29:42  0.0006  0.0370 -0.0225 -0.0082      NaN  2.400000e-09
...                     ...     ...     ...     ...      ...           ...
2023-01-16 17:00:37  0.0799  0.0204 -0.0209 -0.0079      NaN  9.500000e-09
2023-01-16 17:00:38  0.0799  0.0204 -0.0209 -0.0079      NaN  9.500000e-09
2023-01-16 17:00:39  0.0799  0.0204 -0.0209 -0.0079      NaN  9.500000e-09
2023-01-16 17:00:40  0.0799  0.0204 -0.0209 -0.0079      NaN  9.500000e-09
2023-01-16 17:00:42  0.0799  0.0204 -0.0209 -0.0079      NaN  9.500000e-09

                             I_em                    datetime
datetime
2023-01-16 15:29:38  8.100000e-09  2023-01-16 15:29:37.693000
2023-01-16 15:29:39  8.100000e-09  2023-01-16 15:29:38.875000
2023-01-16 15:29:40  8.100000e-09  2023-01-16 15:29:40.053000
2023-01-16 15:29:41  8.100000e-09  2023-01-16 15:29:41.235000
2023-01-16 15:29:42  8.100000e-09  2023-01-16 15:29:42.419000
...                           ...                         ...
2023-01-16 17:00:37  9.910000e-08  2023-01-16 17:00:36.820000
2023-01-16 17:00:38  9.910000e-08  2023-01-16 17:00:38.007000
2023-01-16 17:00:39  9.910000e-08  2023-01-16 17:00:39.201000
2023-01-16 17:00:40  9.910000e-08  2023-01-16 17:00:40.389000
2023-01-16 17:00:42  9.900000e-08  2023-01-16 17:00:41.573000

[4533 rows x 23 columns]
aligned                            Date          Time  Elapsed time  VMon1  VMon2  \
datetime
2023-01-16 15:29:44  16/01/2023  15:29:43.602         5.909   0.04   0.06
2023-01-16 15:29:51  16/01/2023  15:29:50.698        13.005   0.04   0.06
2023-01-16 15:29:57  16/01/2023  15:29:56.522        18.829   0.04   0.06
2023-01-16 15:30:03  16/01/2023  15:30:03.610        25.917   0.04   0.06
2023-01-16 15:30:10  16/01/2023  15:30:09.518        31.825   0.04   0.06
...                         ...           ...           ...    ...    ...
2023-01-16 17:00:18  16/01/2023  17:00:17.887      5440.194   0.06   0.06
2023-01-16 17:00:24  16/01/2023  17:00:23.801      5446.108   0.06   0.06
2023-01-16 17:00:30  16/01/2023  17:00:29.710      5452.017   0.06   0.06
2023-01-16 17:00:37  16/01/2023  17:00:36.820      5459.127   0.06   0.06
2023-01-16 17:00:43  16/01/2023  17:00:41.573      5463.880   0.06   0.06

                     VMon3  VMon4  VMon5  VMon6  VMon7  ...   IMon3   IMon4  \
datetime                                                ...
2023-01-16 15:29:44   0.04   0.08   0.02    0.0    0.0  ...  0.0090  0.0107
2023-01-16 15:29:51   0.04   0.08   0.02    0.0    0.0  ...  0.0090  0.0107
2023-01-16 15:29:57   0.04   0.08   0.02    0.0    0.0  ...  0.0090  0.0107
2023-01-16 15:30:03   0.04   0.08   0.02    0.0    0.0  ...  0.0090  0.0091
2023-01-16 15:30:10   0.04   0.08   0.02    0.0    0.0  ...  0.0090  0.0091
...                    ...    ...    ...    ...    ...  ...     ...     ...
2023-01-16 17:00:18   0.04   0.08   0.00    0.0    0.0  ...  0.0705  0.0110
2023-01-16 17:00:24   0.04   0.08   0.00    0.0    0.0  ...  0.0705  0.0113
2023-01-16 17:00:30   0.04   0.08   0.00    0.0    0.0  ...  0.0705  0.0113
2023-01-16 17:00:37   0.04   0.08   0.00    0.0    0.0  ...  0.0705  0.0117
2023-01-16 17:00:43   0.04   0.08   0.00    0.0    0.0  ...  0.0705  0.0132

                      IMon5   IMon6   IMon7   IMon8  Comment       hv_grid  \
datetime
2023-01-16 15:29:44  0.0006  0.0370 -0.0225 -0.0082      NaN  2.400000e-09
2023-01-16 15:29:51  0.0006  0.0370 -0.0225 -0.0076      NaN  2.400000e-09
2023-01-16 15:29:57  0.0005  0.0015 -0.0225 -0.0076      NaN  2.400000e-09
2023-01-16 15:30:03  0.0002  0.0093 -0.0225 -0.0076      NaN  2.400000e-09
2023-01-16 15:30:10  0.0002  0.0093 -0.0225 -0.0072      NaN  2.400000e-09
...                     ...     ...     ...     ...      ...           ...
2023-01-16 17:00:18  0.0799  0.0205 -0.0209 -0.0075      NaN  9.500000e-09
2023-01-16 17:00:24  0.0799  0.0205 -0.0209 -0.0079      NaN  9.500000e-09
2023-01-16 17:00:30  0.0799  0.0204 -0.0209 -0.0079      NaN  9.500000e-09
2023-01-16 17:00:37  0.0799  0.0204 -0.0209 -0.0079      NaN  9.500000e-09
2023-01-16 17:00:43  0.0799  0.0204 -0.0209 -0.0079      NaN  9.500000e-09

                             I_em   Ion current
datetime
2023-01-16 15:29:44  7.400000e-09  1.153420e-10
2023-01-16 15:29:51  8.900000e-09  1.150680e-10
2023-01-16 15:29:57  8.900000e-09  1.141700e-10
2023-01-16 15:30:03  8.900000e-09  1.135410e-10
2023-01-16 15:30:10  1.000000e-08  1.133800e-10
...                           ...           ...
2023-01-16 17:00:18  9.930000e-08  1.335360e-08
2023-01-16 17:00:24  9.930000e-08  1.454360e-08
2023-01-16 17:00:30  9.930000e-08  1.365570e-08
2023-01-16 17:00:37  9.910000e-08  1.474520e-08
2023-01-16 17:00:43  9.900000e-08  1.286880e-08

[864 rows x 23 columns]
       Elapsed time       VMon1       VMon2        VMon3        VMon4  \
count    864.000000  864.000000  864.000000   864.000000   864.000000
mean    2736.012839  179.597199   79.120116   789.040440   788.346065
std     1578.464695  239.505913   40.719699   407.448259   407.864894
min        5.909000    0.040000    0.060000     0.000000     0.000000
25%     1371.357250    0.140000  100.060000  1000.000000  1000.095000
50%     2735.939000    0.160000  100.060000  1000.080000  1000.220000
75%     4100.692500  499.960000  100.080000  1000.100000  1000.240000
max     5463.880000  500.000000  100.140000  1000.180000  1000.300000

             VMon5       VMon6  VMon7       VMon8       IMon1       IMon2  \
count   864.000000  864.000000  864.0  864.000000  864.000000  864.000000
mean    789.743519  391.813079    0.0    0.026227   -0.251193    1.909148
std     406.947290  205.593193    0.0    0.009266    0.311526    2.148859
min       0.000000    0.000000    0.0    0.020000   -0.659600   -3.403900
25%    1000.060000  499.940000    0.0    0.020000   -0.605625    0.023300
50%    1000.180000  500.000000    0.0    0.020000    0.008600    0.098800
75%    1000.200000  500.020000    0.0    0.040000    0.023400    4.352925
max    1000.420000  500.040000    0.0    0.040000    0.461700    4.725800

            IMon3       IMon4       IMon5       IMon6       IMon7       IMon8  \
count  864.000000  864.000000  864.000000  864.000000  864.000000  864.000000
mean    17.272565   17.283615   17.270664   17.260089   -0.019119   -0.007312
std      8.922249    8.952505    8.919915    8.935924    0.001329    0.000885
min      0.009000   -0.016200    0.000200   -0.066300   -0.022900   -0.009700
25%     20.577775   20.592475   20.567950   20.566975   -0.019400   -0.008000
50%     21.807150   21.834750   21.804500   21.802000   -0.018800   -0.007300
75%     22.318125   22.346825   22.313225   22.307325   -0.018400   -0.006775
max     22.837100   22.855800   22.823500   22.817900   -0.017300   -0.005100

            hv_grid          I_em   Ion current
count  8.640000e+02  8.640000e+02  8.640000e+02
mean  -2.511929e-07  1.909148e-06  7.171138e-10
std    3.115265e-07  2.148859e-06  2.558800e-09
min   -6.596000e-07 -3.403900e-06  1.017540e-10
25%   -6.056250e-07  2.330000e-08  1.084107e-10
50%    8.600000e-09  9.880000e-08  1.161290e-10
75%    2.340000e-08  4.352925e-06  1.211250e-10
max    4.617000e-07  4.725800e-06  1.474520e-08

### From H2 ion current to partial pressure:

In [10]:
#Filtering background signal for resampled data

#take a mass with a signal known to be in the background as a definition of electronic noise
#Ignored because has negligeable impact (~1%)
#elec_bck = np.mean(mid["mass 5.5_value"])

# take the Ion current of H2 channel before emission start as a reference to base pressure:
#get the rows where elapsed time is <600s
pre_EM = hv_aligned.loc[hv_aligned["Elapsed time"] <= 600]
dyn_bck = np.mean(pre_EM["Ion current"])
print(dyn_bck)

#apply background corrections
hv_aligned["mass 2 corr"] = hv_aligned["Ion current"] - dyn_bck #- elec_bck 
#remove values below 0:
hv_aligned["mass 2 corr"].clip(0, inplace=True)

#From the signal, get the partial pressures 
h2_sens = 2.13e-2 #[A/mbar]
p_h2_ip = hv_aligned["mass 2 corr"]/(h2_sens*0.46) #H2 equivalent pressures

#account for the thermal transpiration factor (electrons thermalising to RT)
T2 = 4.2
T1 = 296.5
T_coef = np.sqrt(T2/T1)
p_h2_ip = p_h2_ip*T_coef 

#insert partial pressures into the dataframe
hv_aligned.insert(22,"hydrogen pp",p_h2_ip)
print(hv_aligned["hydrogen pp"].describe())

1.1177961702127656e-10
count    8.640000e+02
mean     7.378092e-09
std      3.107620e-08
min      0.000000e+00
25%      0.000000e+00
50%      5.283266e-11
75%      1.135199e-10
max      1.777545e-07
Name: hydrogen pp, dtype: float64
1.1177961702127656e-10
count    8.640000e+02
mean     7.378092e-09
std      3.107620e-08
min      0.000000e+00
25%      0.000000e+00
50%      5.283266e-11
75%      1.135199e-10
max      1.777545e-07
Name: hydrogen pp, dtype: float64

In [11]:
hv_aligned.fillna(0,inplace=True)
hv_aligned["hydrogen pp"].describe()

count    8.640000e+02
mean     7.378092e-09
std      3.107620e-08
min      0.000000e+00
25%      0.000000e+00
50%      5.283266e-11
75%      1.135199e-10
max      1.777545e-07
Name: hydrogen pp, dtype: float64

count    8.640000e+02
mean     7.378092e-09
std      3.107620e-08
min      0.000000e+00
25%      0.000000e+00
50%      5.283266e-11
75%      1.135199e-10
max      1.777545e-07
Name: hydrogen pp, dtype: float64

### Cut away the warmup part from datasets

In [12]:
#cut the hv_aligned dataframe

cut_hv = hv_aligned.loc[hv_aligned["Elapsed time"] <= 5000]
#cut the mid and time dataframes

cut_time = time.loc[time['Elapsed time, mass 2'] <= 5000]
#print(cut_time)

#slicing mid to match time ["Elapsed time, mass 2']:
# Slice x using the index of y
cut_mid = mid.loc[cut_time.index, :]

#remove the spike in emission current between elapsed time[1335:1367]
spike = cut_hv[cut_hv["Elapsed time"].between(1335,1367)]
print(cut_hv)
#find indexes that correspond to these values
#cut_hv.drop(cut_hv.loc[spike.index],inplace=True, axis=0)
cut_hv = cut_hv.loc[(cut_hv.index < '2023-1-16 15:51:53') | (cut_hv.index > '2023-01-16 15:52:24')]
print(cut_hv)

                           Date          Time  Elapsed time  VMon1  VMon2  \
datetime
2023-01-16 15:29:44  16/01/2023  15:29:43.602         5.909   0.04   0.06
2023-01-16 15:29:51  16/01/2023  15:29:50.698        13.005   0.04   0.06
2023-01-16 15:29:57  16/01/2023  15:29:56.522        18.829   0.04   0.06
2023-01-16 15:30:03  16/01/2023  15:30:03.610        25.917   0.04   0.06
2023-01-16 15:30:10  16/01/2023  15:30:09.518        31.825   0.04   0.06
...                         ...           ...           ...    ...    ...
2023-01-16 16:52:29  16/01/2023  16:52:29.218      4971.525   0.06   0.06
2023-01-16 16:52:36  16/01/2023  16:52:36.316      4978.623   0.06   0.06
2023-01-16 16:52:42  16/01/2023  16:52:42.231      4984.538   0.06   0.06
2023-01-16 16:52:48  16/01/2023  16:52:48.170      4990.477   0.06   0.06
2023-01-16 16:52:55  16/01/2023  16:52:55.275      4997.582   0.06   0.06

                     VMon3  VMon4  VMon5  VMon6  VMon7  ...   IMon5   IMon6  \
datetime                                                ...
2023-01-16 15:29:44   0.04   0.08   0.02    0.0    0.0  ...  0.0006  0.0370
2023-01-16 15:29:51   0.04   0.08   0.02    0.0    0.0  ...  0.0006  0.0370
2023-01-16 15:29:57   0.04   0.08   0.02    0.0    0.0  ...  0.0005  0.0015
2023-01-16 15:30:03   0.04   0.08   0.02    0.0    0.0  ...  0.0002  0.0093
2023-01-16 15:30:10   0.04   0.08   0.02    0.0    0.0  ...  0.0002  0.0093
...                    ...    ...    ...    ...    ...  ...     ...     ...
2023-01-16 16:52:29   0.04   0.08   0.00    0.0    0.0  ...  0.0765  0.0202
2023-01-16 16:52:36   0.04   0.08   0.00    0.0    0.0  ...  0.0765  0.0202
2023-01-16 16:52:42   0.04   0.08   0.00    0.0    0.0  ...  0.0765  0.0196
2023-01-16 16:52:48   0.04   0.08   0.00    0.0    0.0  ...  0.0765  0.0195
2023-01-16 16:52:55   0.04   0.08   0.00    0.0    0.0  ...  0.0765  0.0190

                      IMon7   IMon8  Comment       hv_grid          I_em  \
datetime
2023-01-16 15:29:44 -0.0225 -0.0082        0  2.400000e-09  7.400000e-09
2023-01-16 15:29:51 -0.0225 -0.0076        0  2.400000e-09  8.900000e-09
2023-01-16 15:29:57 -0.0225 -0.0076        0  2.400000e-09  8.900000e-09
2023-01-16 15:30:03 -0.0225 -0.0076        0  2.400000e-09  8.900000e-09
2023-01-16 15:30:10 -0.0225 -0.0072        0  2.400000e-09  1.000000e-08
...                     ...     ...      ...           ...           ...
2023-01-16 16:52:29 -0.0200 -0.0073        0  9.800000e-09  9.900000e-08
2023-01-16 16:52:36 -0.0200 -0.0073        0  9.800000e-09  9.780000e-08
2023-01-16 16:52:42 -0.0200 -0.0071        0  9.800000e-09  9.770000e-08
2023-01-16 16:52:48 -0.0200 -0.0071        0  9.800000e-09  9.770000e-08
2023-01-16 16:52:55 -0.0200 -0.0066        0  9.800000e-09  9.560000e-08

                      hydrogen pp   Ion current   mass 2 corr
datetime
2023-01-16 15:29:44  4.327285e-11  1.153420e-10  3.562383e-12
2023-01-16 15:29:51  3.994452e-11  1.150680e-10  3.288383e-12
2023-01-16 15:29:57  2.903637e-11  1.141700e-10  2.390383e-12
2023-01-16 15:30:03  2.139581e-11  1.135410e-10  1.761383e-12
2023-01-16 15:30:10  1.944011e-11  1.133800e-10  1.600383e-12
...                           ...           ...           ...
2023-01-16 16:52:29  0.000000e+00  1.041940e-10  0.000000e+00
2023-01-16 16:52:36  0.000000e+00  1.041620e-10  0.000000e+00
2023-01-16 16:52:42  0.000000e+00  1.044520e-10  0.000000e+00
2023-01-16 16:52:48  0.000000e+00  1.045810e-10  0.000000e+00
2023-01-16 16:52:55  0.000000e+00  1.046670e-10  0.000000e+00

[790 rows x 25 columns]
                           Date          Time  Elapsed time  VMon1  VMon2  \
datetime
2023-01-16 15:29:44  16/01/2023  15:29:43.602         5.909   0.04   0.06
2023-01-16 15:29:51  16/01/2023  15:29:50.698        13.005   0.04   0.06
2023-01-16 15:29:57  16/01/2023  15:29:56.522        18.829   0.04   0.06
2023-01-16 15:30:03  16/01/2023  15:30:03.610        25.917   0.04   0.06
2023-01-16 15:30:10  16/01/2023  15:30:09.518        31.825   0.04   0.06
...                         ...           ...           ...    ...    ...
2023-01-16 16:52:29  16/01/2023  16:52:29.218      4971.525   0.06   0.06
2023-01-16 16:52:36  16/01/2023  16:52:36.316      4978.623   0.06   0.06
2023-01-16 16:52:42  16/01/2023  16:52:42.231      4984.538   0.06   0.06
2023-01-16 16:52:48  16/01/2023  16:52:48.170      4990.477   0.06   0.06
2023-01-16 16:52:55  16/01/2023  16:52:55.275      4997.582   0.06   0.06

                     VMon3  VMon4  VMon5  VMon6  VMon7  ...   IMon5   IMon6  \
datetime                                                ...
2023-01-16 15:29:44   0.04   0.08   0.02    0.0    0.0  ...  0.0006  0.0370
2023-01-16 15:29:51   0.04   0.08   0.02    0.0    0.0  ...  0.0006  0.0370
2023-01-16 15:29:57   0.04   0.08   0.02    0.0    0.0  ...  0.0005  0.0015
2023-01-16 15:30:03   0.04   0.08   0.02    0.0    0.0  ...  0.0002  0.0093
2023-01-16 15:30:10   0.04   0.08   0.02    0.0    0.0  ...  0.0002  0.0093
...                    ...    ...    ...    ...    ...  ...     ...     ...
2023-01-16 16:52:29   0.04   0.08   0.00    0.0    0.0  ...  0.0765  0.0202
2023-01-16 16:52:36   0.04   0.08   0.00    0.0    0.0  ...  0.0765  0.0202
2023-01-16 16:52:42   0.04   0.08   0.00    0.0    0.0  ...  0.0765  0.0196
2023-01-16 16:52:48   0.04   0.08   0.00    0.0    0.0  ...  0.0765  0.0195
2023-01-16 16:52:55   0.04   0.08   0.00    0.0    0.0  ...  0.0765  0.0190

                      IMon7   IMon8  Comment       hv_grid          I_em  \
datetime
2023-01-16 15:29:44 -0.0225 -0.0082        0  2.400000e-09  7.400000e-09
2023-01-16 15:29:51 -0.0225 -0.0076        0  2.400000e-09  8.900000e-09
2023-01-16 15:29:57 -0.0225 -0.0076        0  2.400000e-09  8.900000e-09
2023-01-16 15:30:03 -0.0225 -0.0076        0  2.400000e-09  8.900000e-09
2023-01-16 15:30:10 -0.0225 -0.0072        0  2.400000e-09  1.000000e-08
...                     ...     ...      ...           ...           ...
2023-01-16 16:52:29 -0.0200 -0.0073        0  9.800000e-09  9.900000e-08
2023-01-16 16:52:36 -0.0200 -0.0073        0  9.800000e-09  9.780000e-08
2023-01-16 16:52:42 -0.0200 -0.0071        0  9.800000e-09  9.770000e-08
2023-01-16 16:52:48 -0.0200 -0.0071        0  9.800000e-09  9.770000e-08
2023-01-16 16:52:55 -0.0200 -0.0066        0  9.800000e-09  9.560000e-08

                      hydrogen pp   Ion current   mass 2 corr
datetime
2023-01-16 15:29:44  4.327285e-11  1.153420e-10  3.562383e-12
2023-01-16 15:29:51  3.994452e-11  1.150680e-10  3.288383e-12
2023-01-16 15:29:57  2.903637e-11  1.141700e-10  2.390383e-12
2023-01-16 15:30:03  2.139581e-11  1.135410e-10  1.761383e-12
2023-01-16 15:30:10  1.944011e-11  1.133800e-10  1.600383e-12
...                           ...           ...           ...
2023-01-16 16:52:29  0.000000e+00  1.041940e-10  0.000000e+00
2023-01-16 16:52:36  0.000000e+00  1.041620e-10  0.000000e+00
2023-01-16 16:52:42  0.000000e+00  1.044520e-10  0.000000e+00
2023-01-16 16:52:48  0.000000e+00  1.045810e-10  0.000000e+00
2023-01-16 16:52:55  0.000000e+00  1.046670e-10  0.000000e+00

[784 rows x 25 columns]
                           Date          Time  Elapsed time  VMon1  VMon2  \
datetime
2023-01-16 15:29:44  16/01/2023  15:29:43.602         5.909   0.04   0.06
2023-01-16 15:29:51  16/01/2023  15:29:50.698        13.005   0.04   0.06
2023-01-16 15:29:57  16/01/2023  15:29:56.522        18.829   0.04   0.06
2023-01-16 15:30:03  16/01/2023  15:30:03.610        25.917   0.04   0.06
2023-01-16 15:30:10  16/01/2023  15:30:09.518        31.825   0.04   0.06
...                         ...           ...           ...    ...    ...
2023-01-16 16:52:29  16/01/2023  16:52:29.218      4971.525   0.06   0.06
2023-01-16 16:52:36  16/01/2023  16:52:36.316      4978.623   0.06   0.06
2023-01-16 16:52:42  16/01/2023  16:52:42.231      4984.538   0.06   0.06
2023-01-16 16:52:48  16/01/2023  16:52:48.170      4990.477   0.06   0.06
2023-01-16 16:52:55  16/01/2023  16:52:55.275      4997.582   0.06   0.06

                     VMon3  VMon4  VMon5  VMon6  VMon7  ...   IMon5   IMon6  \
datetime                                                ...
2023-01-16 15:29:44   0.04   0.08   0.02    0.0    0.0  ...  0.0006  0.0370
2023-01-16 15:29:51   0.04   0.08   0.02    0.0    0.0  ...  0.0006  0.0370
2023-01-16 15:29:57   0.04   0.08   0.02    0.0    0.0  ...  0.0005  0.0015
2023-01-16 15:30:03   0.04   0.08   0.02    0.0    0.0  ...  0.0002  0.0093
2023-01-16 15:30:10   0.04   0.08   0.02    0.0    0.0  ...  0.0002  0.0093
...                    ...    ...    ...    ...    ...  ...     ...     ...
2023-01-16 16:52:29   0.04   0.08   0.00    0.0    0.0  ...  0.0765  0.0202
2023-01-16 16:52:36   0.04   0.08   0.00    0.0    0.0  ...  0.0765  0.0202
2023-01-16 16:52:42   0.04   0.08   0.00    0.0    0.0  ...  0.0765  0.0196
2023-01-16 16:52:48   0.04   0.08   0.00    0.0    0.0  ...  0.0765  0.0195
2023-01-16 16:52:55   0.04   0.08   0.00    0.0    0.0  ...  0.0765  0.0190

                      IMon7   IMon8  Comment       hv_grid          I_em  \
datetime
2023-01-16 15:29:44 -0.0225 -0.0082        0  2.400000e-09  7.400000e-09
2023-01-16 15:29:51 -0.0225 -0.0076        0  2.400000e-09  8.900000e-09
2023-01-16 15:29:57 -0.0225 -0.0076        0  2.400000e-09  8.900000e-09
2023-01-16 15:30:03 -0.0225 -0.0076        0  2.400000e-09  8.900000e-09
2023-01-16 15:30:10 -0.0225 -0.0072        0  2.400000e-09  1.000000e-08
...                     ...     ...      ...           ...           ...
2023-01-16 16:52:29 -0.0200 -0.0073        0  9.800000e-09  9.900000e-08
2023-01-16 16:52:36 -0.0200 -0.0073        0  9.800000e-09  9.780000e-08
2023-01-16 16:52:42 -0.0200 -0.0071        0  9.800000e-09  9.770000e-08
2023-01-16 16:52:48 -0.0200 -0.0071        0  9.800000e-09  9.770000e-08
2023-01-16 16:52:55 -0.0200 -0.0066        0  9.800000e-09  9.560000e-08

                      hydrogen pp   Ion current   mass 2 corr
datetime
2023-01-16 15:29:44  4.327285e-11  1.153420e-10  3.562383e-12
2023-01-16 15:29:51  3.994452e-11  1.150680e-10  3.288383e-12
2023-01-16 15:29:57  2.903637e-11  1.141700e-10  2.390383e-12
2023-01-16 15:30:03  2.139581e-11  1.135410e-10  1.761383e-12
2023-01-16 15:30:10  1.944011e-11  1.133800e-10  1.600383e-12
...                           ...           ...           ...
2023-01-16 16:52:29  0.000000e+00  1.041940e-10  0.000000e+00
2023-01-16 16:52:36  0.000000e+00  1.041620e-10  0.000000e+00
2023-01-16 16:52:42  0.000000e+00  1.044520e-10  0.000000e+00
2023-01-16 16:52:48  0.000000e+00  1.045810e-10  0.000000e+00
2023-01-16 16:52:55  0.000000e+00  1.046670e-10  0.000000e+00

[790 rows x 25 columns]
                           Date          Time  Elapsed time  VMon1  VMon2  \
datetime
2023-01-16 15:29:44  16/01/2023  15:29:43.602         5.909   0.04   0.06
2023-01-16 15:29:51  16/01/2023  15:29:50.698        13.005   0.04   0.06
2023-01-16 15:29:57  16/01/2023  15:29:56.522        18.829   0.04   0.06
2023-01-16 15:30:03  16/01/2023  15:30:03.610        25.917   0.04   0.06
2023-01-16 15:30:10  16/01/2023  15:30:09.518        31.825   0.04   0.06
...                         ...           ...           ...    ...    ...
2023-01-16 16:52:29  16/01/2023  16:52:29.218      4971.525   0.06   0.06
2023-01-16 16:52:36  16/01/2023  16:52:36.316      4978.623   0.06   0.06
2023-01-16 16:52:42  16/01/2023  16:52:42.231      4984.538   0.06   0.06
2023-01-16 16:52:48  16/01/2023  16:52:48.170      4990.477   0.06   0.06
2023-01-16 16:52:55  16/01/2023  16:52:55.275      4997.582   0.06   0.06

                     VMon3  VMon4  VMon5  VMon6  VMon7  ...   IMon5   IMon6  \
datetime                                                ...
2023-01-16 15:29:44   0.04   0.08   0.02    0.0    0.0  ...  0.0006  0.0370
2023-01-16 15:29:51   0.04   0.08   0.02    0.0    0.0  ...  0.0006  0.0370
2023-01-16 15:29:57   0.04   0.08   0.02    0.0    0.0  ...  0.0005  0.0015
2023-01-16 15:30:03   0.04   0.08   0.02    0.0    0.0  ...  0.0002  0.0093
2023-01-16 15:30:10   0.04   0.08   0.02    0.0    0.0  ...  0.0002  0.0093
...                    ...    ...    ...    ...    ...  ...     ...     ...
2023-01-16 16:52:29   0.04   0.08   0.00    0.0    0.0  ...  0.0765  0.0202
2023-01-16 16:52:36   0.04   0.08   0.00    0.0    0.0  ...  0.0765  0.0202
2023-01-16 16:52:42   0.04   0.08   0.00    0.0    0.0  ...  0.0765  0.0196
2023-01-16 16:52:48   0.04   0.08   0.00    0.0    0.0  ...  0.0765  0.0195
2023-01-16 16:52:55   0.04   0.08   0.00    0.0    0.0  ...  0.0765  0.0190

                      IMon7   IMon8  Comment       hv_grid          I_em  \
datetime
2023-01-16 15:29:44 -0.0225 -0.0082        0  2.400000e-09  7.400000e-09
2023-01-16 15:29:51 -0.0225 -0.0076        0  2.400000e-09  8.900000e-09
2023-01-16 15:29:57 -0.0225 -0.0076        0  2.400000e-09  8.900000e-09
2023-01-16 15:30:03 -0.0225 -0.0076        0  2.400000e-09  8.900000e-09
2023-01-16 15:30:10 -0.0225 -0.0072        0  2.400000e-09  1.000000e-08
...                     ...     ...      ...           ...           ...
2023-01-16 16:52:29 -0.0200 -0.0073        0  9.800000e-09  9.900000e-08
2023-01-16 16:52:36 -0.0200 -0.0073        0  9.800000e-09  9.780000e-08
2023-01-16 16:52:42 -0.0200 -0.0071        0  9.800000e-09  9.770000e-08
2023-01-16 16:52:48 -0.0200 -0.0071        0  9.800000e-09  9.770000e-08
2023-01-16 16:52:55 -0.0200 -0.0066        0  9.800000e-09  9.560000e-08

                      hydrogen pp   Ion current   mass 2 corr
datetime
2023-01-16 15:29:44  4.327285e-11  1.153420e-10  3.562383e-12
2023-01-16 15:29:51  3.994452e-11  1.150680e-10  3.288383e-12
2023-01-16 15:29:57  2.903637e-11  1.141700e-10  2.390383e-12
2023-01-16 15:30:03  2.139581e-11  1.135410e-10  1.761383e-12
2023-01-16 15:30:10  1.944011e-11  1.133800e-10  1.600383e-12
...                           ...           ...           ...
2023-01-16 16:52:29  0.000000e+00  1.041940e-10  0.000000e+00
2023-01-16 16:52:36  0.000000e+00  1.041620e-10  0.000000e+00
2023-01-16 16:52:42  0.000000e+00  1.044520e-10  0.000000e+00
2023-01-16 16:52:48  0.000000e+00  1.045810e-10  0.000000e+00
2023-01-16 16:52:55  0.000000e+00  1.046670e-10  0.000000e+00

[784 rows x 25 columns]

# Primary desorption calculation method
### Elena's formula for the cryo setup
$$
\eta=\frac{C_{H2}\cdot (\Delta p_1 - \Delta p_2)q_e}{k_B\cdot T \cdot I_e}
$$

Where $\Delta p_i=p(t)_i - p(t=0)_i$ and $i=1,2$
In the case of the 4K setup, we know the exact conductance of gasses. The formula above applies well.

Due to the EGA being fully retracted, it is safe to assume that the desorption takes place at approximately room temperature

In [13]:
#calculation delta_p-s
dp1 = (np.mean(p_h2)-np.mean(base_h2))*100
print(dp1)

#Constants
k_B = 1.38e-23
T = 295.5
q_e = 1.6e-19
c_h2 = 37.91/1000
s_h2=42/1000
x_h2=1/((1/c_h2)+(1/s_h2))
#Conductance for CO in m3/s
c_co=10.13/1000
c_co2 = 8.08/1000
#Emission current
#averaging
I_em = np.nanmean(hv["I_em"].nlargest(30))
print(I_em)

4.828534167970775e-08
4.539523333333333e-06
4.828534167970775e-08
4.539523333333333e-06

In [14]:
#Desorption yield
eta_h2 = (x_h2*dp1*q_e)/(k_B*T*I_em)
#eta_co = (c_co*(dp1-dp2)*q_e)/(k_B*T*I_em)
print("The desorption yield for H2 [mol/el]:",eta_h2,"\n",)#""The desorption yield for CO2 [mol/el]:",eta_co2)

The desorption yield for H2 [mol/el]: 0.008315539127379258

The desorption yield for H2 [mol/el]: 0.008315539127379258

## Desorption yield point-by-point

$$
\eta=\frac{C_{H2}\cdot (p_{n,EM} - \overline{p}_{base}) \cdot q_e}{k_B\cdot T \cdot I_{n}}
$$

In [15]:
#partial pressure delta
#Wrong methodology below. Need to subtract p_duringEM form p_base, noEM
#p_delta = hv_aligned["hydrogen pp"].diff(periods=1).fillna(hv_aligned["hydrogen pp"])*100 #conversion to Pa
#p_delta = p_delta.clip(lower=0)

#Correct methodology
#for the base pressure use the first 600s from cut_hv["Ion current"]
no_EM = cut_hv.loc[cut_hv["Elapsed time"] <= 600]
print(no_EM.describe())
mean_pbase = np.mean(no_EM["hydrogen pp"])

print(mean_pbase)

EM = cut_hv.loc[cut_hv["Elapsed time"] >= 600]
p_delta = (EM["hydrogen pp"] - mean_pbase)*100
p_delta.clip(0, inplace=True)
print(p_delta)

       Elapsed time       VMon1       VMon2        VMon3        VMon4  \
count     94.000000   94.000000   94.000000    94.000000    94.000000
mean     300.909043  379.345106   74.544468   721.924894   712.226383
std      172.449951  213.669192   43.847007   447.645651   450.998751
min        5.909000    0.040000    0.060000     0.040000     0.000000
25%      154.185500  499.900000   25.055000     0.150000     0.080000
50%      300.674500  499.960000  100.080000   999.940000  1000.020000
75%      448.110750  499.960000  100.080000  1000.000000  1000.120000
max      595.067000  499.980000  100.140000  1000.040000  1000.160000

             VMon5       VMon6  VMon7         VMon8      IMon1  ...  \
count    94.000000   94.000000   94.0  9.400000e+01  94.000000  ...
mean    706.622128  350.089149    0.0  2.000000e-02   0.022645  ...
std     454.887006  229.426373    0.0  1.395220e-17   0.046602  ...
min       0.000000    0.000000    0.0  2.000000e-02   0.002400  ...
25%       0.020000    0.000000    0.0  2.000000e-02   0.021700  ...
50%     999.980000  499.920000    0.0  2.000000e-02   0.021800  ...
75%    1000.095000  499.960000    0.0  2.000000e-02   0.022475  ...
max    1000.140000  499.980000    0.0  2.000000e-02   0.461700  ...

           IMon4      IMon5      IMon6      IMon7      IMon8       hv_grid  \
count  94.000000  94.000000  94.000000  94.000000  94.000000  9.400000e+01
mean   14.705203  14.665089  14.643877  -0.021911  -0.007484  2.264468e-08
std     9.278523   9.286302   9.300256   0.001200   0.000513  4.660191e-08
min     0.008900   0.000200   0.001500  -0.022900  -0.008200  2.400000e-09
25%     0.014650   0.004825   0.037000  -0.022600  -0.007900  2.170000e-08
50%    20.135850  20.109550  20.108600  -0.022500  -0.007500  2.180000e-08
75%    21.088400  21.059825  21.059525  -0.021150  -0.007100  2.247500e-08
max    21.793100  21.765200  21.762100  -0.019200  -0.006600  4.617000e-07

               I_em   hydrogen pp   Ion current   mass 2 corr
count  9.400000e+01  9.400000e+01  9.400000e+01  9.400000e+01
mean   9.434894e-08  3.977283e-12  1.117796e-10  3.274249e-13
std    4.480082e-07  8.253279e-12  9.080559e-13  6.794409e-13
min    7.000000e-09  0.000000e+00  1.103640e-10  0.000000e+00
25%    1.182500e-08  0.000000e+00  1.112070e-10  0.000000e+00
50%    1.920000e-08  0.000000e+00  1.116115e-10  0.000000e+00
75%    2.037500e-08  4.122540e-12  1.121190e-10  3.393830e-13
max    3.702400e-06  4.327285e-11  1.153420e-10  3.562383e-12

[8 rows x 22 columns]
3.977283076463187e-12
datetime
2023-01-16 15:39:39    0.000000e+00
2023-01-16 15:39:45    0.000000e+00
2023-01-16 15:39:52    2.668970e-08
2023-01-16 15:39:58    1.788179e-08
2023-01-16 15:40:04    1.539405e-08
                           ...
2023-01-16 16:52:29    0.000000e+00
2023-01-16 16:52:36    0.000000e+00
2023-01-16 16:52:42    0.000000e+00
2023-01-16 16:52:48    0.000000e+00
2023-01-16 16:52:55    0.000000e+00
Name: hydrogen pp, Length: 690, dtype: float64
       Elapsed time       VMon1       VMon2        VMon3        VMon4  \
count     94.000000   94.000000   94.000000    94.000000    94.000000
mean     300.909043  379.345106   74.544468   721.924894   712.226383
std      172.449951  213.669192   43.847007   447.645651   450.998751
min        5.909000    0.040000    0.060000     0.040000     0.000000
25%      154.185500  499.900000   25.055000     0.150000     0.080000
50%      300.674500  499.960000  100.080000   999.940000  1000.020000
75%      448.110750  499.960000  100.080000  1000.000000  1000.120000
max      595.067000  499.980000  100.140000  1000.040000  1000.160000

             VMon5       VMon6  VMon7         VMon8      IMon1  ...  \
count    94.000000   94.000000   94.0  9.400000e+01  94.000000  ...
mean    706.622128  350.089149    0.0  2.000000e-02   0.022645  ...
std     454.887006  229.426373    0.0  1.395220e-17   0.046602  ...
min       0.000000    0.000000    0.0  2.000000e-02   0.002400  ...
25%       0.020000    0.000000    0.0  2.000000e-02   0.021700  ...
50%     999.980000  499.920000    0.0  2.000000e-02   0.021800  ...
75%    1000.095000  499.960000    0.0  2.000000e-02   0.022475  ...
max    1000.140000  499.980000    0.0  2.000000e-02   0.461700  ...

           IMon4      IMon5      IMon6      IMon7      IMon8       hv_grid  \
count  94.000000  94.000000  94.000000  94.000000  94.000000  9.400000e+01
mean   14.705203  14.665089  14.643877  -0.021911  -0.007484  2.264468e-08
std     9.278523   9.286302   9.300256   0.001200   0.000513  4.660191e-08
min     0.008900   0.000200   0.001500  -0.022900  -0.008200  2.400000e-09
25%     0.014650   0.004825   0.037000  -0.022600  -0.007900  2.170000e-08
50%    20.135850  20.109550  20.108600  -0.022500  -0.007500  2.180000e-08
75%    21.088400  21.059825  21.059525  -0.021150  -0.007100  2.247500e-08
max    21.793100  21.765200  21.762100  -0.019200  -0.006600  4.617000e-07

               I_em   hydrogen pp   Ion current   mass 2 corr
count  9.400000e+01  9.400000e+01  9.400000e+01  9.400000e+01
mean   9.434894e-08  3.977283e-12  1.117796e-10  3.274249e-13
std    4.480082e-07  8.253279e-12  9.080559e-13  6.794409e-13
min    7.000000e-09  0.000000e+00  1.103640e-10  0.000000e+00
25%    1.182500e-08  0.000000e+00  1.112070e-10  0.000000e+00
50%    1.920000e-08  0.000000e+00  1.116115e-10  0.000000e+00
75%    2.037500e-08  4.122540e-12  1.121190e-10  3.393830e-13
max    3.702400e-06  4.327285e-11  1.153420e-10  3.562383e-12

[8 rows x 22 columns]
3.977283076463187e-12
datetime
2023-01-16 15:39:39    0.000000e+00
2023-01-16 15:39:45    0.000000e+00
2023-01-16 15:39:52    2.668970e-08
2023-01-16 15:39:58    1.788179e-08
2023-01-16 15:40:04    1.539405e-08
                           ...
2023-01-16 16:52:29    0.000000e+00
2023-01-16 16:52:36    0.000000e+00
2023-01-16 16:52:42    0.000000e+00
2023-01-16 16:52:48    0.000000e+00
2023-01-16 16:52:55    0.000000e+00
Name: hydrogen pp, Length: 690, dtype: float64

In [16]:
#constants are already defined
#emission current and H2 partial pressures are now available at the same sampling rates
I_n = EM["I_em"].replace(0, np.nan)
I_n.where(EM["I_em"] >= 9e-7, np.nan, inplace=True) #--- this will cause minor misalignment if NaNs are thrown away
I_n.dropna(inplace=True)
#pd.df.where(cond= "Where cond is True, keep the original value. Otherwise, replace with NaN")
print(I_n.describe())

eta = ((x_h2*p_delta*q_e)/(k_B*T*I_n)).dropna()
#ignore first row to match "i" dataset
eta = eta.loc[eta.index[1]:]

print(spike)
#eta = eta
print("desorption yields point-by-point:","\n", eta)

count    3.690000e+02
mean     4.370824e-06
std      1.264420e-07
min      2.625200e-06
25%      4.336300e-06
50%      4.369600e-06
75%      4.432400e-06
max      4.725800e-06
Name: I_em, dtype: float64
                           Date          Time  Elapsed time   VMon1   VMon2  \
datetime
2023-01-16 15:51:53  16/01/2023  15:51:53.362      1335.669    0.16  100.06
2023-01-16 15:51:59  16/01/2023  15:51:58.868      1341.175    0.14  100.12
2023-01-16 15:52:05  16/01/2023  15:52:04.865      1347.172    0.14  100.10
2023-01-16 15:52:12  16/01/2023  15:52:12.042      1354.349    0.14  100.08
2023-01-16 15:52:18  16/01/2023  15:52:18.540      1360.847   60.44  100.04
2023-01-16 15:52:24  16/01/2023  15:52:24.548      1366.855  499.88  100.12

                       VMon3    VMon4    VMon5   VMon6  VMon7  ...    IMon5  \
datetime                                                       ...
2023-01-16 15:51:53  1000.06  1000.22  1000.16  500.02    0.0  ...  22.6134
2023-01-16 15:51:59  1000.18  1000.30  1000.26  220.12    0.0  ...  19.8260
2023-01-16 15:52:05  1000.12  1000.26  1000.24    0.00    0.0  ...  18.2792
2023-01-16 15:52:12  1000.10  1000.26  1000.24    0.00    0.0  ...  18.1989
2023-01-16 15:52:18   999.96  1000.12  1000.08  442.92    0.0  ...  22.3928
2023-01-16 15:52:24  1000.04  1000.18  1000.16  500.00    0.0  ...  22.4718

                       IMon6   IMon7   IMon8               Comment  \
datetime
2023-01-16 15:51:53  22.6089 -0.0189 -0.0053                     0
2023-01-16 15:51:59  19.8051 -0.0189 -0.0053  grid repelling again
2023-01-16 15:52:05  18.2733 -0.0189 -0.0053                     0
2023-01-16 15:52:12  18.1898 -0.0189 -0.0053                     0
2023-01-16 15:52:18  22.2534 -0.0189 -0.0053                     0
2023-01-16 15:52:24  22.4572 -0.0190 -0.0053                     0

                          hv_grid          I_em   hydrogen pp   Ion current  \
datetime
2023-01-16 15:51:53 -6.050000e-07  4.346000e-06  1.733325e-10  1.260490e-10
2023-01-16 15:51:59 -4.072000e-07  2.656100e-06  1.540064e-10  1.244580e-10
2023-01-16 15:52:05 -2.679000e-07  1.893500e-06  1.421872e-10  1.234850e-10
2023-01-16 15:52:12 -2.429000e-07  1.766000e-06  1.399643e-10  1.233020e-10
2023-01-16 15:52:18  3.650000e-07  3.170100e-06  1.736605e-10  1.260760e-10
2023-01-16 15:52:24  4.000000e-08  4.240000e-08  1.049076e-10  1.204160e-10

                      mass 2 corr
datetime
2023-01-16 15:51:53  1.426938e-11
2023-01-16 15:51:59  1.267838e-11
2023-01-16 15:52:05  1.170538e-11
2023-01-16 15:52:12  1.152238e-11
2023-01-16 15:52:18  1.429638e-11
2023-01-16 15:52:24  8.636383e-12

[6 rows x 25 columns]
desorption yields point-by-point:
 datetime
2023-01-16 15:39:58    0.003263
2023-01-16 15:40:04    0.002856
2023-01-16 15:40:11    0.002653
2023-01-16 15:40:17    0.002533
2023-01-16 15:40:23    0.002396
                         ...
2023-01-16 16:43:45    0.000000
2023-01-16 16:43:51    0.000000
2023-01-16 16:43:57    0.000000
2023-01-16 16:44:03    0.000000
2023-01-16 16:44:10    0.000000
Length: 368, dtype: float64
count    3.690000e+02
mean     4.370824e-06
std      1.264420e-07
min      2.625200e-06
25%      4.336300e-06
50%      4.369600e-06
75%      4.432400e-06
max      4.725800e-06
Name: I_em, dtype: float64
                           Date          Time  Elapsed time   VMon1   VMon2  \
datetime
2023-01-16 15:51:53  16/01/2023  15:51:53.362      1335.669    0.16  100.06
2023-01-16 15:51:59  16/01/2023  15:51:58.868      1341.175    0.14  100.12
2023-01-16 15:52:05  16/01/2023  15:52:04.865      1347.172    0.14  100.10
2023-01-16 15:52:12  16/01/2023  15:52:12.042      1354.349    0.14  100.08
2023-01-16 15:52:18  16/01/2023  15:52:18.540      1360.847   60.44  100.04
2023-01-16 15:52:24  16/01/2023  15:52:24.548      1366.855  499.88  100.12

                       VMon3    VMon4    VMon5   VMon6  VMon7  ...    IMon5  \
datetime                                                       ...
2023-01-16 15:51:53  1000.06  1000.22  1000.16  500.02    0.0  ...  22.6134
2023-01-16 15:51:59  1000.18  1000.30  1000.26  220.12    0.0  ...  19.8260
2023-01-16 15:52:05  1000.12  1000.26  1000.24    0.00    0.0  ...  18.2792
2023-01-16 15:52:12  1000.10  1000.26  1000.24    0.00    0.0  ...  18.1989
2023-01-16 15:52:18   999.96  1000.12  1000.08  442.92    0.0  ...  22.3928
2023-01-16 15:52:24  1000.04  1000.18  1000.16  500.00    0.0  ...  22.4718

                       IMon6   IMon7   IMon8               Comment  \
datetime
2023-01-16 15:51:53  22.6089 -0.0189 -0.0053                     0
2023-01-16 15:51:59  19.8051 -0.0189 -0.0053  grid repelling again
2023-01-16 15:52:05  18.2733 -0.0189 -0.0053                     0
2023-01-16 15:52:12  18.1898 -0.0189 -0.0053                     0
2023-01-16 15:52:18  22.2534 -0.0189 -0.0053                     0
2023-01-16 15:52:24  22.4572 -0.0190 -0.0053                     0

                          hv_grid          I_em   hydrogen pp   Ion current  \
datetime
2023-01-16 15:51:53 -6.050000e-07  4.346000e-06  1.733325e-10  1.260490e-10
2023-01-16 15:51:59 -4.072000e-07  2.656100e-06  1.540064e-10  1.244580e-10
2023-01-16 15:52:05 -2.679000e-07  1.893500e-06  1.421872e-10  1.234850e-10
2023-01-16 15:52:12 -2.429000e-07  1.766000e-06  1.399643e-10  1.233020e-10
2023-01-16 15:52:18  3.650000e-07  3.170100e-06  1.736605e-10  1.260760e-10
2023-01-16 15:52:24  4.000000e-08  4.240000e-08  1.049076e-10  1.204160e-10

                      mass 2 corr
datetime
2023-01-16 15:51:53  1.426938e-11
2023-01-16 15:51:59  1.267838e-11
2023-01-16 15:52:05  1.170538e-11
2023-01-16 15:52:12  1.152238e-11
2023-01-16 15:52:18  1.429638e-11
2023-01-16 15:52:24  8.636383e-12

[6 rows x 25 columns]
desorption yields point-by-point:
 datetime
2023-01-16 15:39:58    0.003263
2023-01-16 15:40:04    0.002856
2023-01-16 15:40:11    0.002653
2023-01-16 15:40:17    0.002533
2023-01-16 15:40:23    0.002396
                         ...
2023-01-16 16:43:45    0.000000
2023-01-16 16:43:51    0.000000
2023-01-16 16:43:57    0.000000
2023-01-16 16:44:03    0.000000
2023-01-16 16:44:10    0.000000
Length: 368, dtype: float64

In [17]:
#slicing eta to match hv_aligned["Elapsed time"]:
# Slice x using the index of y
hv_downsampled = hv_aligned.loc[eta.index, :]
hv_downsampled.describe()

,Elapsed time,VMon1,VMon2,VMon3,VMon4,VMon5,VMon6,VMon7,VMon8,IMon1,...,IMon4,IMon5,IMon6,IMon7,IMon8,hv_grid,I_em,hydrogen pp,Ion current,mass 2 corr
count,368.000000,368.000000,368.000000,368.000000,368.000000,368.000000,368.000000,368.0,368.000000,368.000000,...,368.000000,368.000000,368.000000,368.00000,368.000000,3.680000e+02,3.680000e+02,3.680000e+02,3.680000e+02,3.680000e+02
mean,2180.602861,0.376630,100.063696,1000.082935,1000.224239,1000.182174,500.002065,0.0,0.022500,-0.608715,...,22.215217,22.184926,22.182510,-0.01856,-0.007202,-6.087152e-07,4.370893e-06,1.050939e-10,1.200776e-10,8.651725e-12
std,1068.688009,4.257161,0.011599,0.025829,0.022812,0.022039,0.013291,0.0,0.006623,0.013764,...,0.406212,0.407245,0.404406,0.00056,0.001083,1.376362e-08,1.266073e-07,4.604385e-11,4.629764e-12,3.790502e-12
min,620.119000,0.060000,99.960000,1000.020000,1000.140000,1000.120000,499.980000,0.0,0.020000,-0.659600,...,20.980700,21.139000,21.170700,-0.01940,-0.009700,-6.596000e-07,2.625200e-06,0.000000e+00,1.080420e-10,0.000000e+00
25%,1200.548750,0.160000,100.060000,1000.060000,1000.220000,1000.160000,500.000000,0.0,0.020000,-0.617525,...,22.092875,22.061100,22.061775,-0.01900,-0.008000,-6.175250e-07,4.336275e-06,9.480111e-11,1.195840e-10,7.804383e-12
50%,2147.449000,0.160000,100.060000,1000.080000,1000.220000,1000.180000,500.000000,0.0,0.020000,-0.608450,...,22.287550,22.257700,22.254150,-0.01880,-0.007300,-6.084500e-07,4.369650e-06,1.098029e-10,1.208190e-10,9.039383e-12
75%,2727.834750,0.160000,100.060000,1000.100000,1000.240000,1000.200000,500.020000,0.0,0.020000,-0.602200,...,22.500750,22.468700,22.464650,-0.01820,-0.006400,-6.022000e-07,4.432400e-06,1.285733e-10,1.223642e-10,1.058463e-11
max,4473.677000,81.820000,100.080000,1000.140000,1000.260000,1000.240000,500.020000,0.0,0.040000,-0.567400,...,22.855800,22.823500,22.817900,-0.01730,-0.005300,-5.674000e-07,4.725800e-06,1.827952e-10,1.268280e-10,1.504838e-11

,Elapsed time,VMon1,VMon2,VMon3,VMon4,VMon5,VMon6,VMon7,VMon8,IMon1,...,IMon4,IMon5,IMon6,IMon7,IMon8,hv_grid,I_em,hydrogen pp,Ion current,mass 2 corr
count,368.000000,368.000000,368.000000,368.000000,368.000000,368.000000,368.000000,368.0,368.000000,368.000000,...,368.000000,368.000000,368.000000,368.00000,368.000000,3.680000e+02,3.680000e+02,3.680000e+02,3.680000e+02,3.680000e+02
mean,2180.602861,0.376630,100.063696,1000.082935,1000.224239,1000.182174,500.002065,0.0,0.022500,-0.608715,...,22.215217,22.184926,22.182510,-0.01856,-0.007202,-6.087152e-07,4.370893e-06,1.050939e-10,1.200776e-10,8.651725e-12
std,1068.688009,4.257161,0.011599,0.025829,0.022812,0.022039,0.013291,0.0,0.006623,0.013764,...,0.406212,0.407245,0.404406,0.00056,0.001083,1.376362e-08,1.266073e-07,4.604385e-11,4.629764e-12,3.790502e-12
min,620.119000,0.060000,99.960000,1000.020000,1000.140000,1000.120000,499.980000,0.0,0.020000,-0.659600,...,20.980700,21.139000,21.170700,-0.01940,-0.009700,-6.596000e-07,2.625200e-06,0.000000e+00,1.080420e-10,0.000000e+00
25%,1200.548750,0.160000,100.060000,1000.060000,1000.220000,1000.160000,500.000000,0.0,0.020000,-0.617525,...,22.092875,22.061100,22.061775,-0.01900,-0.008000,-6.175250e-07,4.336275e-06,9.480111e-11,1.195840e-10,7.804383e-12
50%,2147.449000,0.160000,100.060000,1000.080000,1000.220000,1000.180000,500.000000,0.0,0.020000,-0.608450,...,22.287550,22.257700,22.254150,-0.01880,-0.007300,-6.084500e-07,4.369650e-06,1.098029e-10,1.208190e-10,9.039383e-12
75%,2727.834750,0.160000,100.060000,1000.100000,1000.240000,1000.200000,500.020000,0.0,0.020000,-0.602200,...,22.500750,22.468700,22.464650,-0.01820,-0.006400,-6.022000e-07,4.432400e-06,1.285733e-10,1.223642e-10,1.058463e-11
max,4473.677000,81.820000,100.080000,1000.140000,1000.260000,1000.240000,500.020000,0.0,0.040000,-0.567400,...,22.855800,22.823500,22.817900,-0.01730,-0.005300,-5.674000e-07,4.725800e-06,1.827952e-10,1.268280e-10,1.504838e-11

## Electron dose

Find:

$$
Q = \int_{t_1}^{t_2} I \,dt
$$

Where $t_2$ and $t_1$ are the timestamps at which an emission current reading was taken

In [18]:
#Integrating the emission current

def integrand(t, i):
    return i*t

i = I_n.dropna().reset_index() 

#for testing:
#t2_2 = (hv_aligned["Elapsed time"].diff(periods=1).fillna(0))

#adding an elapsed time column
timestamp3=[]
for j in hv["Time"]:
    timestamp3.append(j)
    
#making the column into a datetime object
timestamps3=pd.to_datetime(i["datetime"],format="%H:%M:%S")
runtime3=(timestamps3-timestamps3[0]).dt.total_seconds()    
i.insert(2,"Elapsed time",runtime3)

#define the n, n-1 difference in a variable "t2"
t2 = (i["Elapsed time"].diff(periods=1).fillna(0))

#replace all values from t2 that are further away than 50% of the median (.. > 9) with the median value
t2.where(t2 <= 12,6,inplace=True)
print(t2)

#integration
ar = []
for x in t2:
    itr = 0
    I = quad(integrand, 0, x, args=(i["I_em"][itr]))
    ar.append(I[0])
    itr += 1
    #if previous value was not NaN, replace the value with the median of elapsed time
    #if

0      0.0
1      6.0
2      6.0
3      7.0
4      6.0
      ...
364    7.0
365    6.0
366    6.0
367    6.0
368    7.0
Name: Elapsed time, Length: 369, dtype: float64
0      0.0
1      6.0
2      6.0
3      7.0
4      6.0
      ...
364    7.0
365    6.0
366    6.0
367    6.0
368    7.0
Name: Elapsed time, Length: 369, dtype: float64

In [19]:
#calculate the cumulative charge
Q_cumul = np.cumsum(ar)
Q_sum = sum(ar)
print("Total charge emitted from EGA during ~5000 seconds:", f"{Q_sum:.4E}", "C")

#cumulative nr of electrons emitted
N_e = Q_sum/1.6e-19
Ne_cumul = Q_cumul/1.6e-19
print("Total number of electron emitted during ~5000 seconds:", f"{N_e:.4E}", "e")
      
#To get the electron dose, divide n of electrons by sample surface area of 276 cm2, multiply by grid transmittance of 0.9
tot_dose = (N_e/276)*0.9
cumul_dose = (Ne_cumul/276)*0.9
print("Total electron dose on the sample ~5000 seconds:", f"{tot_dose:.4E}", "e-/cm^2")
      
#add these to the "i" dataframe:
i.insert(3,"Cumulative charge", Q_cumul)
i.insert(4,"Cumulative n. of electrons emitted from EGA", Ne_cumul)
i.insert(5,"Cumulative electron dose on the HL sample", cumul_dose)
i.set_index("datetime", drop=True, inplace=True)

#Ignore the first value, also, match the shape of eta
i = i.loc[i.index[1]:]
print(i)

Total charge emitted from EGA during ~5000 seconds: 3.2147E-02 C
Total number of electron emitted during ~5000 seconds: 2.0092E+17 e
Total electron dose on the sample ~5000 seconds: 6.5516E+14 e-/cm^2
                         I_em  Elapsed time  Cumulative charge  \
datetime
2023-01-16 15:39:58  0.000004           6.0           0.000078
2023-01-16 15:40:04  0.000004          12.0           0.000156
2023-01-16 15:40:11  0.000004          19.0           0.000263
2023-01-16 15:40:17  0.000004          25.0           0.000341
2023-01-16 15:40:23  0.000004          31.0           0.000419
...                       ...           ...                ...
2023-01-16 16:43:45  0.000004        3833.0           0.031805
2023-01-16 16:43:51  0.000004        3839.0           0.031884
2023-01-16 16:43:57  0.000004        3845.0           0.031962
2023-01-16 16:44:03  0.000004        3851.0           0.032040
2023-01-16 16:44:10  0.000004        3858.0           0.032147

                     Cumulative n. of electrons emitted from EGA  \
datetime
2023-01-16 15:39:58                                 4.888800e+14
2023-01-16 15:40:04                                 9.777600e+14
2023-01-16 15:40:11                                 1.643180e+15
2023-01-16 15:40:17                                 2.132060e+15
2023-01-16 15:40:23                                 2.620940e+15
...                                                          ...
2023-01-16 16:43:45                                 1.987840e+17
2023-01-16 16:43:51                                 1.992729e+17
2023-01-16 16:43:57                                 1.997618e+17
2023-01-16 16:44:03                                 2.002507e+17
2023-01-16 16:44:10                                 2.009161e+17

                     Cumulative electron dose on the HL sample
datetime
2023-01-16 15:39:58                               1.594174e+12
2023-01-16 15:40:04                               3.188348e+12
2023-01-16 15:40:11                               5.358196e+12
2023-01-16 15:40:17                               6.952370e+12
2023-01-16 15:40:23                               8.546543e+12
...                                                        ...
2023-01-16 16:43:45                               6.482088e+14
2023-01-16 16:43:51                               6.498030e+14
2023-01-16 16:43:57                               6.513972e+14
2023-01-16 16:44:03                               6.529913e+14
2023-01-16 16:44:10                               6.551612e+14

[368 rows x 5 columns]
Total charge emitted from EGA during ~5000 seconds: 3.2147E-02 C
Total number of electron emitted during ~5000 seconds: 2.0092E+17 e
Total electron dose on the sample ~5000 seconds: 6.5516E+14 e-/cm^2
                         I_em  Elapsed time  Cumulative charge  \
datetime
2023-01-16 15:39:58  0.000004           6.0           0.000078
2023-01-16 15:40:04  0.000004          12.0           0.000156
2023-01-16 15:40:11  0.000004          19.0           0.000263
2023-01-16 15:40:17  0.000004          25.0           0.000341
2023-01-16 15:40:23  0.000004          31.0           0.000419
...                       ...           ...                ...
2023-01-16 16:43:45  0.000004        3833.0           0.031805
2023-01-16 16:43:51  0.000004        3839.0           0.031884
2023-01-16 16:43:57  0.000004        3845.0           0.031962
2023-01-16 16:44:03  0.000004        3851.0           0.032040
2023-01-16 16:44:10  0.000004        3858.0           0.032147

                     Cumulative n. of electrons emitted from EGA  \
datetime
2023-01-16 15:39:58                                 4.888800e+14
2023-01-16 15:40:04                                 9.777600e+14
2023-01-16 15:40:11                                 1.643180e+15
2023-01-16 15:40:17                                 2.132060e+15
2023-01-16 15:40:23                                 2.620940e+15
...                                                          ...
2023-01-16 16:43:45                                 1.987840e+17
2023-01-16 16:43:51                                 1.992729e+17
2023-01-16 16:43:57                                 1.997618e+17
2023-01-16 16:44:03                                 2.002507e+17
2023-01-16 16:44:10                                 2.009161e+17

                     Cumulative electron dose on the HL sample
datetime
2023-01-16 15:39:58                               1.594174e+12
2023-01-16 15:40:04                               3.188348e+12
2023-01-16 15:40:11                               5.358196e+12
2023-01-16 15:40:17                               6.952370e+12
2023-01-16 15:40:23                               8.546543e+12
...                                                        ...
2023-01-16 16:43:45                               6.482088e+14
2023-01-16 16:43:51                               6.498030e+14
2023-01-16 16:43:57                               6.513972e+14
2023-01-16 16:44:03                               6.529913e+14
2023-01-16 16:44:10                               6.551612e+14

[368 rows x 5 columns]

## Electron energies

In [20]:
#getting electron energies for plotting

# Plotting

In [21]:
#plot the aligned dataframe results

plt.figure(figsize=(12,6))
plt.plot(cut_hv["Elapsed time"],cut_hv["Ion current"],linestyle="-",marker=".", markersize=4,label='H2 ion current')
plt.plot(cut_hv["Elapsed time"],cut_hv["I_em"],linestyle="-",marker=".", markersize=4,label='Emission current')
plt.xlabel('Elapsed time (s)')
plt.ylabel('Current (A)')
plt.legend(loc="upper right")
plt.title("Current evolution 2e18 M pre-injection, EGA fully in, dynamic vacuum")


plt.yscale('log')

In [22]:
#plot the h2 mid 
#seems to be too little rows?

plt.figure(figsize=(12,6))
plt.plot(cut_hv["Elapsed time"],cut_hv["Ion current"],linestyle="-",marker=".", markersize=4,label='H2 ion current')
plt.xlabel('Elapsed time (s)')
plt.ylabel('Ion current (A)')
plt.legend(loc="upper right")
plt.title("Ion current evolution of H2, 2e18 M pre-injection, EGA fully in, dynamic vacuum")


plt.yscale('linear')

In [23]:
#Plotting the all the relevant MID spectrums
plt.figure(figsize=(14,8))
plt.plot(cut_time['Elapsed time, mass 2'],cut_mid["mass 2.0_value"],marker=".", markersize=4,label='M2')
plt.plot(cut_time['Elapsed time, mass 4'],cut_mid["mass 4.0_value"],marker=".", markersize=4,label='M4')
plt.plot(cut_time['Elapsed time, mass 12'],cut_mid["mass 12.0_value"],marker=".", markersize=4,label='M14')
plt.plot(cut_time['Elapsed time, mass 16'],cut_mid["mass 16.0_value"],marker=".", markersize=4,label='M16')
plt.plot(cut_time['Elapsed time, mass 18'],cut_mid["mass 18.0_value"],marker=".", markersize=4,label='M18')
plt.plot(cut_time['Elapsed time, mass 28'],cut_mid["mass 28.0_value"],marker=".", markersize=4,label='M28')
plt.plot(cut_time['Elapsed time, mass 32'],cut_mid["mass 32.0_value"],marker=".", markersize=4,label='M32')
plt.plot(cut_time['Elapsed time, mass 40'],cut_mid["mass 40.0_value"],marker=".", markersize=4,label='M40')
plt.plot(cut_time["Elapsed time, mass 44"],cut_mid["mass 44.0_value"],marker=".", markersize=4,label='M44')

plt.xlabel('Elapsed time (s)')
plt.ylabel('Ion current (A)')
plt.legend(title="Mol masses", loc="upper right")
plt.title("MID scan 2e18 M pre-injection, EGA fully in, dynamic vacuum")

plt.yscale('log')

In [24]:
#Plotting the baseline mid
plt.figure(figsize=(14,8))
plt.plot(time1['Elapsed time, mass 2'],basel["mass 2.0_value"],marker=".", markersize=4,label='M2')
plt.plot(time1['Elapsed time, mass 4'],basel["mass 4.0_value"],marker=".", markersize=4,label='M4')
plt.plot(time1['Elapsed time, mass 12'],basel["mass 12.0_value"],marker=".", markersize=4,label='M14')
plt.plot(time1['Elapsed time, mass 16'],basel["mass 16.0_value"],marker=".", markersize=4,label='M16')
plt.plot(time1['Elapsed time, mass 18'],basel["mass 18.0_value"],marker=".", markersize=4,label='M18')
plt.plot(time1['Elapsed time, mass 28'],basel["mass 28.0_value"],marker=".", markersize=4,label='M28')
plt.plot(time1['Elapsed time, mass 32'],basel["mass 32.0_value"],marker=".", markersize=4,label='M32')
plt.plot(time1['Elapsed time, mass 40'],basel["mass 40.0_value"],marker=".", markersize=4,label='M40')
plt.plot(time1["Elapsed time, mass 44"],basel["mass 44.0_value"],marker=".", markersize=4,label='M44')

plt.xlabel('Elapsed time (s)')
plt.ylabel('Ion current (A)')
plt.legend(title="Mol masses", loc="upper right")
plt.title("MID baseline scan 2e18 M pre-injection, EGA fully in, dynamic vacuum")

plt.yscale('log')

In [25]:
#plotting HiVolta log
plt.figure(figsize=(12,6))
plt.plot(hv["Elapsed time"],hv["hv_grid"],marker=".", markersize=4,label='Grid current')
plt.plot(hv["Elapsed time"],hv["I_em"],marker=".", markersize=4,label='Emission current')
plt.xlabel('Elapsed time (s)')
plt.ylabel('Current (A)')
plt.legend(loc="upper right")
plt.title("Current evolution 2e18 M pre-injection, EGA fully in, dynamic vacuum")


plt.yscale('log')

In [26]:
#Plotting BA2, BA1 pressure
plt.figure(figsize=(10,6))
plt.plot(vaclog["Elapsed time"],vaclog["Barion_2"],marker=".", markersize=4,label='Barion 2')
plt.plot(vaclog["Elapsed time"],vaclog["Barion_1"],marker=".", markersize=4,label='Barion 1')

plt.xlabel('Elapsed time (s)')
plt.ylabel('Pressure (mbar)')
plt.legend()
plt.title("Total pressure evolution 2e18 M pre-injection, EGA fully in, dynamic vacuum")
ax = plt.gca()
ax.set_yscale('log')
plt.tick_params(axis="y", which='minor')
plt.grid(visible=None, which='both', axis='both')
plt.show()

In [27]:
# Plotting the temp evolution
plt.figure()
plt.plot((vaclog["Elapsed time"]),polyfit(A,vaclog["T-CERNOX"]),marker=".", markersize=5,label='T-CERNOX')

plt.xlabel('Elapsed time (s)')
plt.ylabel('Temperature (K)')
plt.legend()
plt.title("Temperature evolution 2e18 M pre-injection, EGA fully in, dynamic vacuum")
plt.yscale('linear')

In [28]:
#plotting point-by-point eta
plt.figure(figsize=(10,6))
plt.plot(hv_downsampled["Elapsed time"],eta,marker=".", markersize=4,label='eta')
#plt.plot(vaclog["Elapsed time"],vaclog["Barion_1"],marker=".", markersize=4,label='Barion 1')

plt.xlabel('Elapsed time (s)')
plt.ylabel('Electon stimulated desorption yield (M/el) 2e18 M pre-injection')
plt.legend()
plt.title("ESD vs time, p_n - p_n-1")
ax = plt.gca()
ax.set_yscale('log')
ax.grid(which="major",axis="x")
plt.tick_params(axis="y", which='minor')
plt.grid(visible=None, which='both', axis='both')
plt.show()

In [29]:
#plotting ESD vs electron dose
plt.figure(figsize=(10,6))
plt.plot(i["Cumulative electron dose on the HL sample"],eta,marker=".", markersize=4,label='eta')
#plt.plot(vaclog["Elapsed time"],vaclog["Barion_1"],marker=".", markersize=4,label='Barion 1')

plt.xlabel('Electron dose (e/cm^2)')
plt.ylabel('ESD yield (M/el)')
plt.legend()
plt.title("Electron stimulated desorption yield vs electron dose")
ax = plt.gca()
ax.set_yscale('linear')
ax.grid(which="major",axis="both")
plt.tick_params(axis="y", which='minor')
plt.grid(visible=None, which='both', axis='both')
plt.show()